import type { Project } from './types';

export const projects: Project[] = [
  // ─── 2019 ──────────────────────────────────────────────────────────────
  {
    id: 'incobrasa-silo-2019',
    slug: 'incobrasa-silo-expansion',
    title: 'Cleaner and Silo Expansion for Soy Beans',
    client: 'Incobrasa',
    displayDate: '2019',
    startYear: 2019,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Rockwell', 'Wonderware InTouch'],
    scope:
      'Automation design for silo-control expansion in a soybean drying process using Rockwell PLC controls and Wonderware InTouch supervision.',
    featured: true,
    source: 'legacy-site',
    sortWeight: 10,
  },
  {
    id: 'incobrasa-oil-2019',
    slug: 'incobrasa-soy-oil-line',
    title: 'Soy Oil Filling Line Automation Changes',
    client: 'Incobrasa',
    displayDate: '2019',
    startYear: 2019,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['Siemens PLC', 'Siemens HMI'],
    scope:
      'Conveyor changes for production and reliability, palletizer changes for new pallet formation, labeler and conveyor signal integration.',
    source: 'legacy-site',
  },
  {
    id: 'ford-schuler-2018',
    slug: 'ford-schuler-stamping-press',
    title: 'Schuler Stamping Press',
    client: 'Ford',
    displayDate: '2018–2019',
    startYear: 2018,
    endYear: 2019,
    industry: 'automotive',
    capabilities: ['commissioning', 'plc-hmi-scada'],
    technologies: [],
    scope:
      'Automation improvement, troubleshooting, commissioning and service for stamping equipment.',
    featured: true,
    source: 'legacy-site',
    sortWeight: 20,
  },
  {
    id: 'chicago-tower-2018',
    slug: 'chicago-tower-body-shop',
    title: 'Chicago Tower Body Shop',
    displayDate: '2018–2019',
    startYear: 2018,
    endYear: 2019,
    industry: 'automotive',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Rockwell'],
    scope: 'Body-shop PLC integration.',
    source: 'legacy-site',
  },

  // ─── 2018 ──────────────────────────────────────────────────────────────
  {
    id: 'bmw-wire-harness-2018',
    slug: 'bmw-wire-harness-oven',
    title: 'Wire Harness Oven',
    client: 'BMW',
    displayDate: '2018',
    startYear: 2018,
    industry: 'automotive',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens STEP 7', 'WinCC Flexible'],
    scope: 'Wire-harness oven extension.',
    source: 'legacy-site',
  },
  {
    id: 'bmw-marriage-2018',
    slug: 'bmw-spartanburg-marriage-line',
    title: 'Marriage Line',
    client: 'BMW',
    location: 'Spartanburg, South Carolina, USA',
    displayDate: '2018',
    startYear: 2018,
    industry: 'automotive',
    capabilities: ['plc-hmi-scada', 'robotics', 'commissioning'],
    technologies: [],
    scope: 'PLC and robot integration across the powertrain/body marriage line.',
    featured: true,
    detailPage: true,
    source: 'legacy-site',
    sortWeight: 100,
  },
  {
    id: 'bmw-hatch-2017',
    slug: 'bmw-hatch-lift-assist',
    title: 'Hatch Lift Assist',
    client: 'BMW Manufacturing Company',
    displayDate: '2017–2018',
    startYear: 2017,
    endYear: 2018,
    industry: 'automotive',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['Simatic S7', 'Festo CPX', 'Profinet', 'PROFIsafe', 'TIA 13'],
    scope: 'Hatch lift-assist controls.',
    source: 'legacy-site',
  },

  // ─── 2017 ──────────────────────────────────────────────────────────────
  {
    id: 'bmw-pokayoke-2017',
    slug: 'bmw-differential-oil-poka-yoke',
    title: 'Differential Oil Filling Poka-Yoke',
    client: 'Dürr / BMW USA',
    displayDate: '2017',
    startYear: 2017,
    industry: 'automotive',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens S7', 'TIA'],
    scope: 'Interlock to prevent incorrect filling-nozzle placement.',
    source: 'legacy-site',
  },
  {
    id: 'bmw-nvld-2017',
    slug: 'bmw-nvld',
    title: 'NVLD',
    client: 'BMW',
    location: 'South Carolina, USA',
    displayDate: '2017',
    startYear: 2017,
    industry: 'automotive',
    capabilities: ['commissioning', 'plc-hmi-scada'],
    technologies: ['Siemens TIA'],
    scope: 'Commissioning, interlock improvements and customer acceptance.',
    source: 'legacy-site',
  },
  {
    id: 'kister-servo-2017',
    slug: 'kister-packer-servo-upgrade',
    title: 'Servo Upgrade for Kister Packer',
    displayDate: '2017',
    startYear: 2017,
    industry: 'food-beverage',
    capabilities: ['motion-process', 'plc-hmi-scada'],
    technologies: [],
    scope: 'Double-servo pack-separation upgrade; HMI/PLC changes.',
    source: 'legacy-site',
  },
  {
    id: 'paresa-conveyor-2017',
    slug: 'paresa-conveyor-changes',
    title: 'Conveyor Changes',
    client: 'Paresa',
    location: 'Paraguay',
    displayDate: '2017',
    startYear: 2017,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens S7'],
    scope: 'Bottle-conveyor speed settings and interlock changes.',
    source: 'legacy-site',
  },
  {
    id: 'heineken-kaizen-2016',
    slug: 'heineken-haiti-kaizen',
    title: 'Bottling-Line Kaizen',
    client: 'Heineken',
    location: 'Haiti',
    displayDate: '2016–2017',
    startYear: 2016,
    endYear: 2017,
    industry: 'food-beverage',
    capabilities: ['commissioning', 'support'],
    technologies: [],
    scope:
      'Production-line audit and cross-functional improvement work involving operations, maintenance and supply planning.',
    outcome: 'The published project record reports a 20-point increase in average efficiency.',
    featured: true,
    detailPage: true,
    source: 'legacy-site',
    sortWeight: 90,
  },

  // ─── 2016 ──────────────────────────────────────────────────────────────
  {
    id: 'p75-vru-2016',
    slug: 'p75-vapor-recovery-unit',
    title: 'Vapor Recovery Unit P-75',
    displayDate: '2016',
    startYear: 2016,
    industry: 'energy-process',
    capabilities: ['electrical-controls', 'plc-hmi-scada', 'commissioning'],
    technologies: [],
    scope:
      'Electrical and automation development for an oil-and-gas vapor recovery unit, including FAT, FMEA and project documentation.',
    featured: true,
    source: 'legacy-site',
    sortWeight: 80,
  },
  {
    id: 'porto-acu-2016',
    slug: 'porto-acu-compressor-control',
    title: 'Air Compressor Control and Interlock',
    location: 'Porto do Açu, Brazil',
    displayDate: '2016',
    startYear: 2016,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['Altus'],
    scope: 'PLC/HMI development and commissioning.',
    source: 'legacy-site',
  },
  {
    id: 'p75-nitrogen-2016',
    slug: 'p75-nitrogen-generator',
    title: 'P75 Petrobras Nitrogen Generator',
    client: 'Petrobras',
    displayDate: '2016',
    startYear: 2016,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada', 'electrical-controls', 'commissioning'],
    technologies: ['Altus PLC', 'Siemens HMI'],
    scope: 'Automation development, documentation, commissioning, FAT/FMEA for Exd environment.',
    source: 'legacy-site',
  },
  {
    id: 'p70-nitrogen-2016',
    slug: 'p70-nitrogen-generator',
    title: 'P70 Petrobras Nitrogen Generator',
    client: 'Petrobras',
    displayDate: '2016',
    startYear: 2016,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada', 'electrical-controls', 'commissioning'],
    technologies: ['Altus PLC', 'Siemens HMI'],
    scope: 'Automation development, documentation, commissioning, FAT/FMEA for Exd environment.',
    source: 'legacy-site',
  },
  {
    id: 'p71-nitrogen-2016',
    slug: 'p71-nitrogen-generator',
    title: 'P71 Petrobras Nitrogen Generator',
    client: 'Petrobras',
    displayDate: '2016',
    startYear: 2016,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada', 'electrical-controls', 'commissioning'],
    technologies: ['Altus PLC', 'Siemens HMI'],
    scope: 'Automation development, documentation, commissioning, FAT/FMEA for Exd environment.',
    source: 'legacy-site',
  },

  // ─── 2015 ──────────────────────────────────────────────────────────────
  {
    id: 'rexam-trimmer-2015',
    slug: 'rexam-trimmer-overhaul',
    title: 'Trimmer Machine Overhaul',
    client: 'Rexam',
    location: 'Winston-Salem, NC',
    displayDate: '2015',
    startYear: 2015,
    industry: 'general-industry',
    capabilities: ['commissioning'],
    technologies: [],
    scope: 'Management of overhaul of five machines, parts and service-technician coordination.',
    source: 'legacy-site',
  },
  {
    id: 'avon-hotfill-2015',
    slug: 'avon-hot-fill-line',
    title: 'Hot-Fill Makeup Line',
    client: 'Avon',
    displayDate: '2015',
    startYear: 2015,
    industry: 'cosmetics-packaging',
    capabilities: ['plc-hmi-scada', 'robotics', 'commissioning'],
    technologies: ['Rockwell'],
    scope:
      'PLC/HMI automation, line integration, commissioning, FAT and SAT across bottle indexing, filling, capping, cooling, pick-and-place and labeling equipment.',
    featured: true,
    detailPage: true,
    source: 'legacy-site',
    sortWeight: 70,
  },
  {
    id: 'avon-filler-2015',
    slug: 'avon-bottle-indexing-filler',
    title: 'Bottle Indexing and Filler',
    client: 'Avon',
    displayDate: '2015',
    startYear: 2015,
    industry: 'cosmetics-packaging',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['Rockwell'],
    scope: 'PLC/HMI automation development, tests, commissioning, FAT/SAT.',
    source: 'legacy-site',
  },

  // ─── 2014 ──────────────────────────────────────────────────────────────
  {
    id: 'aquarex-png-2014',
    slug: 'aquarex-heineken-png',
    title: 'Aquarex Caustic Recovery System',
    client: 'Heineken',
    location: 'Papua New Guinea',
    displayDate: '2014',
    startYear: 2014,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada', 'electrical-controls'],
    technologies: ['Siemens STEP 7'],
    scope: 'Automation and electrical upgrade for Aquarex caustic recovery system.',
    source: 'legacy-site',
  },
  {
    id: 'campari-capper-2014',
    slug: 'campari-zalkin-capper',
    title: 'Cap Feeder for Zalkin Capper',
    client: 'Campari',
    displayDate: '2014',
    startYear: 2014,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'PLC software modification to integrate new capper with Krones filler.',
    source: 'legacy-site',
  },
  {
    id: 'heineken-haiti-2014',
    slug: 'heineken-haiti-filling-line',
    title: '40,000 Bottles/Hour Filling Line',
    client: 'BRANA / Heineken',
    location: 'Haiti',
    displayDate: '2014',
    startYear: 2014,
    industry: 'food-beverage',
    capabilities: ['commissioning', 'support'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Commissioning, ramp-up, efficiency improvement and assisted operation.',
    source: 'legacy-site',
  },

  // ─── 2013 ──────────────────────────────────────────────────────────────
  {
    id: 'femsa-filler-2013',
    slug: 'femsa-filler-camming',
    title: 'Filler Pneumatic Camming Adjustment',
    client: 'FEMSA',
    location: 'Bauru',
    displayDate: '2013',
    startYear: 2013,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: [],
    scope: 'Software changes for pneumatic cams and mixer changes for sparkling-water production.',
    source: 'legacy-site',
  },
  {
    id: 'avon-puck-2013',
    slug: 'avon-puck-conveyor',
    title: 'Puck Conveyor Upgrade',
    client: 'Avon',
    displayDate: '2013',
    startYear: 2013,
    industry: 'cosmetics-packaging',
    capabilities: ['motion-process', 'plc-hmi-scada'],
    technologies: ['Siemens Simotion'],
    scope: 'Conveyor modification to create puck buffer at filler infeed.',
    source: 'legacy-site',
  },
  {
    id: 'boticario-cartoner-2013',
    slug: 'boticario-cartoner',
    title: 'Cartoner CMF 60/min',
    client: 'Grupo Boticário / Optima Group GmbH',
    displayDate: '2013',
    startYear: 2013,
    industry: 'cosmetics-packaging',
    capabilities: ['commissioning', 'motion-process'],
    technologies: ['Simotion'],
    scope: 'Assembly, commissioning, startup, FAT, IQ/OQ and documentation localization.',
    source: 'legacy-site',
  },
  {
    id: 'scjohnson-filler-2013',
    slug: 'sc-johnson-bug-protection-filler',
    title: 'Bug Protection Filler',
    client: 'SC Johnson',
    location: 'Manaus',
    displayDate: '2013',
    startYear: 2013,
    industry: 'cosmetics-packaging',
    capabilities: ['commissioning', 'motion-process'],
    technologies: ['Simotion Motion Control', 'WinCC Flexible'],
    scope: 'Assembly, commissioning, startup and ramp-up.',
    source: 'legacy-site',
  },
  {
    id: 'avon-mexico-2013',
    slug: 'avon-mexico-cap-pick-and-place',
    title: 'Cap Pick-and-Place',
    client: 'Avon',
    location: 'Mexico',
    displayDate: '2013',
    startYear: 2013,
    industry: 'cosmetics-packaging',
    capabilities: ['robotics', 'commissioning'],
    technologies: ['FANUC'],
    scope: 'Robotic cap-feeding system; commissioning and startup.',
    source: 'legacy-site',
  },

  // ─── 2012 ──────────────────────────────────────────────────────────────
  {
    id: 'panco-conveyor-2012',
    slug: 'panco-batch-air-conveyor',
    title: 'Batch Air Conveyor for Flour',
    client: 'Panco',
    displayDate: '2012',
    startYear: 2012,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['CompactLogix', 'FactoryTalk ME'],
    scope: 'Software development, commissioning and production tests.',
    source: 'legacy-site',
  },
  {
    id: 'hyosung-tank-2012',
    slug: 'hyosung-chemical-tank-control',
    title: 'Chemical Tank Control',
    client: 'Hyosung',
    displayDate: '2012',
    startYear: 2012,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada', 'motion-process'],
    technologies: ['CompactLogix', 'FactoryTalk ME'],
    scope: 'Pressure and closed-loop control.',
    source: 'legacy-site',
  },
  {
    id: 'ambev-pet-2012',
    slug: 'ambev-pet-format-changeover',
    title: 'PET 500 ml Format Changeover',
    client: 'Ambev',
    location: 'Fortaleza',
    displayDate: '2012',
    startYear: 2012,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Air-conveyor software change.',
    source: 'legacy-site',
  },
  {
    id: 'soy-oil-overhaul-2012',
    slug: 'soy-oil-line-overhaul',
    title: 'Soy Oil Line Overhaul',
    displayDate: '2012',
    startYear: 2012,
    industry: 'food-beverage',
    capabilities: ['commissioning'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Startup and commissioning after mechanical overhaul.',
    source: 'legacy-site',
  },

  // ─── 2011 ──────────────────────────────────────────────────────────────
  {
    id: 'petropolis-269-2011',
    slug: 'petropolis-269-473-format',
    title: '269/473 ml Format',
    client: 'Cervejaria Petrópolis',
    displayDate: '2011',
    startYear: 2011,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Recipe creation and adaptation for both formats.',
    source: 'legacy-site',
  },
  {
    id: 'petropolis-ice-2011',
    slug: 'petropolis-blue-spirit-ice',
    title: 'Blue Spirit Ice Changeover',
    client: 'Cervejaria Petrópolis',
    displayDate: '2011',
    startYear: 2011,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Recipe and software modification for new bottles.',
    source: 'legacy-site',
  },
  {
    id: 'bombril-soap-2011',
    slug: 'bombril-dish-soap-filling',
    title: 'Dish Soap Filling Line',
    client: 'Bombril',
    displayDate: '2011',
    startYear: 2011,
    industry: 'cosmetics-packaging',
    capabilities: ['commissioning'],
    technologies: ['Siemens'],
    scope: 'Line commissioning, startup and ramp-up.',
    source: 'legacy-site',
  },

  // ─── 2010 ──────────────────────────────────────────────────────────────
  {
    id: 'campari-filling-2010',
    slug: 'campari-filling-line',
    title: 'Filling Line 18,000 Bottles/Hour',
    client: 'Campari',
    displayDate: '2010',
    startYear: 2010,
    industry: 'food-beverage',
    capabilities: ['commissioning'],
    technologies: ['Siemens Simatic STEP 7'],
    scope: 'Assembly, commissioning and production tests.',
    source: 'legacy-site',
  },
  {
    id: 'sabb-hotfill-2010',
    slug: 'sabb-hot-fill-line',
    title: 'Hot-Fill Production Line',
    client: 'SABB',
    location: 'Linhares',
    displayDate: '2010',
    startYear: 2010,
    industry: 'food-beverage',
    capabilities: ['commissioning'],
    technologies: ['Rockwell ControlLogix'],
    scope: 'Commissioning, startup and production testing.',
    source: 'legacy-site',
  },
  {
    id: 'cocacola-labeler-2010',
    slug: 'coca-cola-amapa-labeler',
    title: 'PET Labeler and Infeed Conveyor',
    client: 'Coca-Cola',
    location: 'Amapá',
    displayDate: '2010',
    startYear: 2010,
    industry: 'food-beverage',
    capabilities: ['commissioning'],
    technologies: ['Siemens STEP 7'],
    scope:
      'Assembly, commissioning and production tests; Contiroll 15,000 bottles per hour reference.',
    source: 'legacy-site',
  },

  // ─── 2008 and earlier ─────────────────────────────────────────────────
  {
    id: 'unilever-ades-2008',
    slug: 'unilever-ades-formulation',
    title: 'Continuous Formulation',
    client: 'Ades / Unilever',
    location: 'Pouso Alegre',
    displayDate: '2008',
    startYear: 2008,
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['ControlLogix', 'FactoryTalk'],
    scope: 'Software development, commissioning and production tests.',
    source: 'legacy-site',
  },
  {
    id: 'usiminas-ute-2007',
    slug: 'usiminas-ute-supervisory',
    title: 'UTE Usiminas',
    client: 'Usiminas',
    displayDate: 'Prior experience',
    startYear: 2007,
    industry: 'energy-process',
    capabilities: ['plc-hmi-scada'],
    technologies: ['WinCC Flexible', 'WinCC OS', 'PCS 7'],
    scope: 'HMI and supervisory system development.',
    source: 'legacy-site',
  },

  // ─── Undated historical records ────────────────────────────────────────
  {
    id: 'bmw-hatch-undated',
    slug: 'bmw-hatch-lift-undated',
    title: 'Hatch Lift',
    client: 'BMW',
    location: 'USA',
    displayDate: 'Year not specified',
    industry: 'automotive',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: ['Festo CPMAX'],
    scope:
      'Project design, interlock improvements, Festo CPMAX commissioning, IPS integration and HMI design (V8).',
    source: 'legacy-site',
  },
  {
    id: 'bmw-abs-undated',
    slug: 'bmw-abs-tester-rebuild',
    title: 'ABS Tester Rebuild',
    client: 'BMW',
    location: 'USA',
    displayDate: 'Year not specified',
    industry: 'automotive',
    capabilities: ['commissioning', 'motion-process'],
    technologies: ['Movidrive'],
    scope: 'Movidrive commissioning and system startup.',
    source: 'legacy-site',
  },
  {
    id: 'bmw-console-undated',
    slug: 'bmw-console-conveyor',
    title: 'Console Conveyor',
    client: 'BMW',
    location: 'USA',
    displayDate: 'Year not specified',
    industry: 'automotive',
    capabilities: ['plc-hmi-scada', 'electrical-controls', 'commissioning'],
    technologies: [],
    scope: 'Project design, commissioning and safety design to BMW standard.',
    source: 'legacy-site',
  },
  {
    id: 'bmw-shifter-undated',
    slug: 'bmw-manual-shifter-assembler',
    title: 'Manual Shifter Assembler',
    client: 'BMW',
    location: 'USA',
    displayDate: 'Year not specified',
    industry: 'automotive',
    capabilities: ['commissioning', 'plc-hmi-scada'],
    technologies: [],
    scope: 'Commissioning, interlock improvements and IPS integration.',
    source: 'legacy-site',
  },
  {
    id: 'foaming-station-undated',
    slug: 'foaming-station',
    title: 'Foaming Station',
    displayDate: 'Year not specified',
    industry: 'general-industry',
    capabilities: ['commissioning'],
    technologies: [],
    scope: 'Commissioning and interlock improvements.',
    source: 'legacy-site',
  },
  {
    id: 'cocacola-krones-undated',
    slug: 'coca-cola-krones-filling-rebuild',
    title: 'Krones Filling Line Rebuild',
    client: 'Coca-Cola',
    location: 'Brazil',
    displayDate: 'Year not specified',
    industry: 'food-beverage',
    capabilities: ['commissioning'],
    technologies: [],
    scope: 'Startup after rebuild.',
    source: 'legacy-site',
  },
  {
    id: 'cocacola-khs-undated',
    slug: 'coca-cola-khs-kister-upgrade',
    title: 'KHS Kister Upgrade',
    client: 'Coca-Cola',
    location: 'Brazil',
    displayDate: 'Year not specified',
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada', 'commissioning'],
    technologies: [],
    scope: 'Software changes and commissioning.',
    source: 'legacy-site',
  },
  {
    id: 'cocacola-paraguay-undated',
    slug: 'coca-cola-paraguay-conveyor',
    title: 'Conveyor Format Addition',
    client: 'Coca-Cola',
    location: 'Paraguay',
    displayDate: 'Year not specified',
    industry: 'food-beverage',
    capabilities: ['plc-hmi-scada'],
    technologies: [],
    scope: 'Software integration.',
    source: 'legacy-site',
  },
  {
    id: 'mercedes-bodyshop-undated',
    slug: 'mercedes-benz-body-shop',
    title: 'Body Shop',
    client: 'Mercedes-Benz',
    location: 'Alabama, USA',
    displayDate: 'Year not specified',
    industry: 'automotive',
    capabilities: ['plc-hmi-scada', 'robotics'],
    technologies: [],
    scope: 'Body-shop automation work.',
    source: 'legacy-site',
  },
];

export const featuredProjects = projects
  .filter((p) => p.featured)
  .sort((a, b) => (b.sortWeight ?? 0) - (a.sortWeight ?? 0))
  .slice(0, 6);

export const clientNames = [
  'BMW',
  'Ford',
  'Mercedes-Benz',
  'Coca-Cola',
  'Heineken',
  'Avon',
  'Petrobras',
  'Campari',
  'Unilever',
  'Ambev',
  'SC Johnson',
  'Grupo Boticário',
] as const;
