export const ownerFinanceCopy = {
  en: {
    title: 'Company finances',
    subtitle: 'Collections, commitments and recorded cash at a glance.',
    currency: 'Currency',
    allTime: 'All recorded history · amounts kept in their original currency',
    collected: 'Customer collections',
    receivable: 'Invoices to collect',
    overdue: 'Overdue',
    not_due: 'Not overdue / no due date',
    payable: 'Payments due',
    paid: 'Payments recorded',
    unconfirmed: 'Needs confirmation',
    incoming: 'Cash in',
    outgoing: 'Cash out',
    all: 'All movements',
    trend: 'Cash in & cash out',
    period: 'Last six months · recorded transactions only',
    collections: 'Outstanding invoices',
    payments: 'Worker payments & reimbursements',
    empty: 'No financial movements recorded yet.',
    noData: 'No amounts in this chart',
    view: 'View details',
    billing: 'Invoices',
    expenses: 'Expenses',
    finance: 'Finance overview',
    cash: 'Cash calendar',
    note: 'Cash out includes recorded reimbursements and receipt reversals. Finalized worker compensation without transfer evidence remains unconfirmed. This view is not a bank balance or a complete supplier-bill register.',
    dates: 'Only dated transactions',
    filter: 'Movement type',
  },
  es: {
    title: 'Finanzas de la empresa',
    subtitle: 'Cobros, compromisos y movimientos de caja de un vistazo.',
    currency: 'Moneda',
    allTime: 'Todo el historial registrado · importes en su moneda original',
    collected: 'Cobros de clientes',
    receivable: 'Facturas por cobrar',
    overdue: 'Vencido',
    not_due: 'No vencido / sin vencimiento',
    payable: 'Pagos pendientes',
    paid: 'Pagos registrados',
    unconfirmed: 'Pendiente de confirmación',
    incoming: 'Entradas de caja',
    outgoing: 'Salidas de caja',
    all: 'Todos los movimientos',
    trend: 'Entradas y salidas de caja',
    period: 'Últimos seis meses · solo transacciones registradas',
    collections: 'Facturas pendientes de cobro',
    payments: 'Pagos y reembolsos a trabajadores',
    empty: 'Todavía no hay movimientos financieros registrados.',
    noData: 'No hay importes en este gráfico',
    view: 'Ver detalles',
    billing: 'Facturas',
    expenses: 'Gastos',
    finance: 'Resumen financiero',
    cash: 'Calendario de caja',
    note: 'Las salidas incluyen reembolsos registrados y reversiones de cobros. La compensación finalizada sin evidencia de transferencia sigue pendiente de confirmación. Esta vista no es un saldo bancario ni un registro completo de facturas de proveedores.',
    dates: 'Solo transacciones con fecha',
    filter: 'Tipo de movimiento',
  },
  pt: {
    title: 'Finanças da empresa',
    subtitle: 'Recebimentos, compromissos e caixa em uma visão.',
    currency: 'Moeda',
    allTime: 'Todo o histórico registrado · valores na moeda original',
    collected: 'Recebimentos de clientes',
    receivable: 'Faturas a receber',
    overdue: 'Vencido',
    not_due: 'Não vencido / sem vencimento',
    payable: 'Pagamentos pendentes',
    paid: 'Pagamentos registrados',
    unconfirmed: 'Precisa de confirmação',
    incoming: 'Entradas de caixa',
    outgoing: 'Saídas de caixa',
    all: 'Todos os movimentos',
    trend: 'Entradas e saídas de caixa',
    period: 'Últimos seis meses · apenas transações registradas',
    collections: 'Faturas pendentes de recebimento',
    payments: 'Pagamentos e reembolsos a trabalhadores',
    empty: 'Ainda não há movimentos financeiros registrados.',
    noData: 'Sem valores neste gráfico',
    view: 'Ver detalhes',
    billing: 'Faturas',
    expenses: 'Despesas',
    finance: 'Resumo financeiro',
    cash: 'Calendário de caixa',
    note: 'As saídas incluem reembolsos registrados e reversões de recebimentos. Remuneração finalizada sem comprovante de transferência permanece sem confirmação. Esta visão não é um saldo bancário nem um registro completo de faturas de fornecedores.',
    dates: 'Apenas transações com data',
    filter: 'Tipo de movimento',
  },
};
