import type { OwnerFinanceSummary } from './owner-finance';
import type { ProblemData } from '../problem/contract';
export type PortalRow = Record<string, string | number | boolean | string[] | null>;

export type PortalData = {
  suppliers?: PortalRow[];
  locale?: 'en' | 'es' | 'pt';
  offlineEnabled?: boolean;
  ownerFinance?: OwnerFinanceSummary;
  user: {
    id: string;
    name: string;
    email: string;
    role?: string;
    status?: string;
    mfaEnrolled?: boolean;
    mfaRequired?: boolean;
    workforceProfile?: 'external_technician' | 'supplier_coordinator';
  };
  section: string;
  projects?: PortalRow[];
  clients?: PortalRow[];
  assignments?: PortalRow[];
  assignmentToday?: string;
  timeAssignments?: PortalRow[];
  contacts?: PortalRow[];
  workers?: PortalRow[];
  planningFilterWorkers?: PortalRow[];
  skills?: PortalRow[];
  workerSkills?: PortalRow[];
  allSkills?: PortalRow[];
  availability?: PortalRow[];
  selectedWorkerId?: string;
  records?: PortalRow[];
  milestones?: PortalRow[];
  documents?: PortalRow[];
  technicalChanges?: PortalRow[];
  periodReports?: PortalRow[];
  billingRules?: PortalRow[];
  compensationRules?: PortalRow[];
  clientLaborRates?: PortalRow[];
  internalCostRules?: PortalRow[];
  assignmentExpensePolicies?: PortalRow[];
  projectExpenseReimbursement?: PortalRow | null;
  reimbursementPreferenceAsOf?: string;
  reimbursementPreferenceHistory?: PortalRow[];
  commercialPolicies?: PortalRow[];
  commercialTermsSummary?: PortalRow[];
  commercialAsOf?: string;
  commercialCategory?: string;
  financeExpenses?: PortalRow[];
  invoices?: PortalRow[];
  invoiceEmailDeliveries?: PortalRow[];
  settlements?: PortalRow[];
  compensationPayments?: PortalRow[];
  financeToday?: string;
  payActivities?: PortalRow[];
  payExpenses?: PortalRow[];
  payOutstanding?: Array<{
    currency: string;
    settlementMinor: string;
    reimbursementMinor: string;
  }>;
  reimbursements?: PortalRow[];
  ledger?: Array<Record<string, unknown>>;
  packs?: Array<Record<string, unknown>>;
  audit?: PortalRow[];
  auditView?: 'all' | 'business' | 'service';
  auditHasMore?: boolean;
  auditNextCursor?: { occurredAt: string; id: string } | null;
  auditOlderPage?: boolean;
  legalEntities?: PortalRow[];
  canonicalLegalEntityOptions?: PortalRow[];
  projectLegalEntityAssignments?: PortalRow[];
  canonicalAssignmentCommandToken?: string;
  canonicalRevisionCommandToken?: string;
  canonicalAuthorityAsOf?: string;
  taxProfiles?: PortalRow[];
  selectedProjectId?: string;
  periodStart?: string;
  periodEnd?: string;
  payPeriodProblem?: ProblemData | null;
  weekStart?: string;
  weekEnd?: string;
  calendarRecords?: PortalRow[];
  weekDraftRecords?: PortalRow[];
  timeFilter?: {
    category: string;
    projectId: string;
    workerId: string;
    from: string;
    to: string;
  };
  timesheet?: {
    weekStart: string;
    weekEnd: string;
    days: Array<{
      date: string;
      label: string;
      expectedMinutes: number | null;
      actualMinutes: number;
      differenceMinutes: number | null;
      status: string;
      categories: Record<string, number>;
    }>;
  };
  weeklyPay?: {
    currency: string;
    approvedMinutes: number;
    pendingMinutes: number;
    estimatedApprovedMinor: string;
    estimatedPendingMinor: string;
    currencyBreakdown?: Array<{
      currency: string;
      estimatedApprovedMinor: string;
      estimatedPendingMinor: string;
    }>;
  };
  searchQuery?: string;
  searchSuggestions?: PortalRow[];
  searchResults?: PortalRow[];
  pay?: {
    currency: string;
    projectIds?: string[];
    approvedMinutes: number;
    pendingMinutes: number;
    estimatedApprovedMinor: string;
    estimatedPendingMinor: string;
    approvedReimbursementMinor: string;
    pendingReimbursementMinor: string;
    currencyBreakdown?: Array<{
      currency: string;
      estimatedApprovedMinor: string;
      estimatedPendingMinor: string;
      approvedReimbursementMinor: string;
      pendingReimbursementMinor: string;
    }>;
    guaranteedMinutes?: number;
    percentageBased?: boolean;
    settlementTriggers?: string[];
    missingCompensationRules?: number;
    label?: string;
    projectProgress?: Array<Record<string, unknown>>;
  };
  finance?: {
    currency: string;
    actualMinutes?: number;
    approvedMinutes?: number;
    approvedCostMinor: string;
    revenueCandidateMinor: string;
    contributionMarginMinor: string;
    invoicedMinor: string;
    paidMinor: string;
    receivableMinor: string;
    laborRevenueMinor?: string;
    expenseRevenueMinor?: string;
    directLaborCostMinor?: string;
    travelCostMinor?: string;
    otherDirectCostMinor?: string;
    approvedUnbilledWipMinor?: string;
    unapprovedWipMinor?: string;
    milestoneRevenueMinor?: string;
    budgetMinor?: string | null;
    plannedMinutes?: number | null;
    plannedRemainingMinutes?: number | null;
    estimateToCompleteMinor?: string | null;
    estimateAtCompletionCostMinor?: string | null;
    expectedFinalMarginMinor?: string | null;
    hoursConsumedBps?: string | null;
    travelBudgetConsumedBps?: string | null;
    travelBudgetMinor?: string | null;
    expenseBudgetConsumedBps?: string | null;
    expenseBudgetMinor?: string | null;
    forecastAvailable?: boolean;
    alerts?: string[];
    contributionMarginBps?: string;
    timeEconomics?: Array<Record<string, unknown>>;
    expenseEconomics?: Array<Record<string, unknown>>;
  } | null;
  portfolio?: {
    projects?: Array<Record<string, unknown>>;
    byClient?: Array<Record<string, unknown>>;
    byWorker?: Array<Record<string, unknown>>;
    byMonth?: Array<Record<string, unknown>>;
    byWeek?: Array<Record<string, unknown>>;
  };
  dashboard?: {
    activeProjects: number;
    actualMinutes: number;
    pendingReports: number;
    expenseTotalsByCurrency?: Array<{ currency: string; minor: string }>;
    upcomingInvoices?: number;
    upcomingInvoiceTotalsByCurrency?: Array<{ currency: string; minor: string }>;
  };
};

export type PortalActionResult = {
  success?: boolean;
  message?: string;
  messageKey?: string;
} | null;
