export const closeoutCopy = {
  en: {
    back: 'Project',
    kicker: 'PROJECT CLOSEOUT',
    immutable:
      'Internal and customer packages are immutable after finalization. Customer publication requires confirmation of the exact reviewed snapshot.',
    prepare: 'Prepare a new revision',
    selection:
      'Select only deliberately authorized customer PDFs. Sensitive content is reviewed before publication; selection remains optional.',
    prepareAction: 'Prepare closeout draft',
    draft: 'Draft revision',
    internal: 'Internal audience preview',
    client: 'Customer audience preview',
    project: 'Project',
    reports: 'Technical reports',
    backups: 'System and backup register',
    risks: 'Validation and open risks',
    invoices: 'Invoice register',
    payments: 'Payments and collections',
    expenses: 'Approved expenses',
    documents: 'Document index',
    periods: 'Accepted customer periods',
    noItems: 'No entries',
    rawSnapshot: 'Exact snapshot record',
    revision: 'Revision',
    final: 'Final',
    refresh: 'Refresh draft from current sources',
    replace: 'Replace selected customer documents',
    confirm:
      'I confirm publication of this exact client snapshot after reviewing the selected content.',
    confirmAction: 'Confirm client publication',
    finalize: 'Finalize both packages',
    revisions: 'Revisions',
    ready: 'ready',
    reason: 'Reason',
    reopen: 'Reopen',
    legacy:
      'Legacy closeout evidence exists and is shown separately. It was not converted into a customer package.',
  },
  es: {
    back: 'Proyecto',
    kicker: 'CIERRE DEL PROYECTO',
    immutable:
      'Los paquetes internos y de cliente son inmutables tras la finalización. La publicación al cliente requiere confirmar la instantánea exacta revisada.',
    prepare: 'Preparar una nueva revisión',
    selection:
      'Seleccione solo PDF de cliente autorizados expresamente. El contenido sensible se revisa antes de publicarlo; la selección es opcional.',
    prepareAction: 'Preparar borrador de cierre',
    draft: 'Borrador de revisión',
    internal: 'Vista previa interna',
    client: 'Vista previa para cliente',
    project: 'Proyecto',
    reports: 'Informes técnicos',
    backups: 'Registro de sistemas y copias',
    risks: 'Validación y riesgos abiertos',
    invoices: 'Registro de facturas',
    payments: 'Pagos y cobros',
    expenses: 'Gastos aprobados',
    documents: 'Índice de documentos',
    periods: 'Periodos de cliente aceptados',
    noItems: 'Sin registros',
    rawSnapshot: 'Registro exacto de la instantánea',
    revision: 'Revisión',
    final: 'Final',
    refresh: 'Actualizar borrador desde las fuentes actuales',
    replace: 'Sustituir documentos de cliente seleccionados',
    confirm:
      'Confirmo la publicación de esta instantánea exacta para cliente tras revisar el contenido seleccionado.',
    confirmAction: 'Confirmar publicación al cliente',
    finalize: 'Finalizar ambos paquetes',
    revisions: 'Revisiones',
    ready: 'listo',
    reason: 'Motivo',
    reopen: 'Reabrir',
    legacy:
      'La evidencia histórica de cierre se muestra por separado. No se convirtió en un paquete para cliente.',
  },
  pt: {
    back: 'Projeto',
    kicker: 'ENCERRAMENTO DO PROJETO',
    immutable:
      'Os pacotes internos e de cliente são imutáveis após a finalização. A publicação ao cliente exige confirmação da captura exata revisada.',
    prepare: 'Preparar nova revisão',
    selection:
      'Selecione apenas PDFs de cliente deliberadamente autorizados. O conteúdo sensível é revisado antes da publicação; a seleção é opcional.',
    prepareAction: 'Preparar rascunho de encerramento',
    draft: 'Rascunho da revisão',
    internal: 'Prévia para público interno',
    client: 'Prévia para cliente',
    project: 'Projeto',
    reports: 'Relatórios técnicos',
    backups: 'Registro de sistemas e backups',
    risks: 'Validação e riscos abertos',
    invoices: 'Registro de faturas',
    payments: 'Pagamentos e recebimentos',
    expenses: 'Despesas aprovadas',
    documents: 'Índice de documentos',
    periods: 'Períodos de cliente aceitos',
    noItems: 'Sem registros',
    rawSnapshot: 'Registro exato da captura',
    revision: 'Revisão',
    final: 'Final',
    refresh: 'Atualizar rascunho com as fontes atuais',
    replace: 'Substituir documentos de cliente selecionados',
    confirm:
      'Confirmo a publicação desta captura exata para cliente após revisar o conteúdo selecionado.',
    confirmAction: 'Confirmar publicação ao cliente',
    finalize: 'Finalizar ambos os pacotes',
    revisions: 'Revisões',
    ready: 'pronto',
    reason: 'Motivo',
    reopen: 'Reabrir',
    legacy:
      'A evidência histórica de encerramento é exibida separadamente. Ela não foi convertida em pacote para cliente.',
  },
} as const;
