import { createHash } from 'node:crypto';
import type { DatabaseSync } from 'node:sqlite';
import { newId, type Principal } from '@ja/domain';
import type { Currency } from '@ja/money';
import { assertActiveAccount, assertLiveSession } from '../../core/authorization.ts';
import { recordAuditEvent } from '../../core/audit.ts';
import { runImmediateTransaction } from '../../core/transaction.ts';
import { resolveAssignmentCommercialTerms } from '../commercial/assignment-commercial-terms.ts';
import { V3Repository } from '../../v3-repository.ts';
import {
  AssignmentExpensePolicyRepository,
  type ExpensePayer,
  type WorkerReimbursementMode,
  type ClientRecoveryMode,
} from '../expenses/assignment-expense-policy-repository.ts';
import {
  AccessDeniedError,
  ConflictError,
  ValidationError,
  type PortalRepository,
} from '../../repository.ts';

export type ProjectBillingArrangement = 'combined' | 'separate';
export type ProjectBillingSetupInput = Readonly<{
  projectId: string;
  expectedVersion: number;
  expectedRulesFingerprint: string;
  requestKey: string;
  selectedTemplateId?: string;
  mode: ProjectBillingArrangement;
  effectiveFrom: string;
  legalEntityId: string;
  laborTaxProfileId: string;
  expenseTaxProfileId: string;
  cadenceType: 'weekly' | 'every_14_days' | 'semi_monthly' | 'monthly' | 'manual';
  expenseCadenceType: 'weekly' | 'every_14_days' | 'semi_monthly' | 'monthly' | 'manual';
  anchorDate?: string;
  expenseAnchorDate?: string;
  invoiceLayout: 'default' | 'labor-detailed' | 'labor-summary';
  groupingMode: 'detail' | 'summary' | 'by_worker' | 'by_day' | 'by_category';
  billingContactId?: string;
  recipientEmail?: string;
  paymentTermsDays: number;
  autoGenerateDraft: boolean;
  saveAsTemplate: boolean;
  templateName?: string;
}>;

export type ProjectPersonTermsInput = Readonly<{
  projectId: string;
  projectMemberId: string;
  workerId: string;
  expectedFingerprint: string;
  effectiveFrom: string;
  customerHourlyRate: string;
  workerPayType:
    | 'Hourly'
    | 'Daily'
    | 'FixedPerBillingPeriod'
    | 'FixedProjectAmount'
    | 'PercentageOfEligibleClientLabor';
  workerPayAmount: string;
  percentageBasis:
    | 'CLIENT_LABOR_BEFORE_TAX'
    | 'CLIENT_LABOR_AFTER_APPROVED_DISCOUNT'
    | 'ISSUED_ELIGIBLE_LABOR'
    | 'COLLECTED_ELIGIBLE_LABOR';
  expensePayer: ExpensePayer;
  workerReimbursement: WorkerReimbursementMode;
  clientRecovery: ClientRecoveryMode;
  markupPercent: string;
}>;

function decimalHundredths(value: string, field: string): bigint {
  const normalized = value.trim().replace(',', '.');
  if (!/^\d{1,10}(?:\.\d{1,2})?$/.test(normalized))
    throw new ValidationError(`${field} must be a non-negative amount with at most two decimals`);
  const [whole, fraction = ''] = normalized.split('.');
  return BigInt(whole!) * 100n + BigInt(fraction.padEnd(2, '0'));
}

function decimalFromHundredths(value: string | number | bigint | null | undefined): string {
  if (value == null) return '';
  const amount = BigInt(value);
  return `${amount / 100n}.${(amount % 100n).toString().padStart(2, '0')}`;
}

type RuleRow = Readonly<{
  id: string;
  project_id: string;
  stream_type: 'labor' | 'expense';
  enabled: number;
  effective_from: string;
  effective_to: string | null;
  version: number;
  legal_entity_id: string | null;
  tax_profile_id: string | null;
  currency: string;
  cadence_type: string;
  anchor_date: string | null;
  template_id: string | null;
  grouping_mode: string | null;
  billing_contact_id: string | null;
  recipient_email: string | null;
  payment_terms_days: number | null;
  auto_generate_draft: number;
  include_expenses: number;
}>;

type TemplateRow = Readonly<{
  id: string;
  name: string;
  version: number;
  config_json: string;
}>;

const dayPattern = /^\d{4}-\d{2}-\d{2}$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const previousDay = (date: string): string =>
  new Date(Date.parse(`${date}T12:00:00Z`) - 86_400_000).toISOString().slice(0, 10);
export function projectCalendarDate(timezone: string, instant = new Date()): string {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: timezone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(instant);
  const value = (kind: 'year' | 'month' | 'day') =>
    parts.find((part) => part.type === kind)?.value ?? '';
  return `${value('year')}-${value('month')}-${value('day')}`;
}
const stamp = (): string => new Date().toISOString();

function validate(input: ProjectBillingSetupInput): void {
  if (!uuidPattern.test(input.projectId) || !uuidPattern.test(input.requestKey))
    throw new ValidationError('Project or request reference is invalid');
  if (!Number.isInteger(input.expectedVersion) || input.expectedVersion < 0)
    throw new ValidationError('Billing setup version is invalid');
  if (!/^[0-9a-f]{64}$/.test(input.expectedRulesFingerprint))
    throw new ValidationError('Billing rules revision is invalid');
  if (!['combined', 'separate'].includes(input.mode))
    throw new ValidationError('Choose one or two invoices');
  if (!dayPattern.test(input.effectiveFrom) || Number.isNaN(Date.parse(input.effectiveFrom)))
    throw new ValidationError('Effective date is invalid');
  for (const value of [
    input.legalEntityId,
    input.laborTaxProfileId,
    ...(input.mode === 'separate' ? [input.expenseTaxProfileId] : []),
  ])
    if (!uuidPattern.test(value))
      throw new ValidationError('Select a legal entity and tax profile');
  for (const cadence of [input.cadenceType, input.expenseCadenceType])
    if (!['weekly', 'every_14_days', 'semi_monthly', 'monthly', 'manual'].includes(cadence))
      throw new ValidationError('Unsupported billing cadence');
  if (input.cadenceType === 'every_14_days' && !dayPattern.test(input.anchorDate ?? ''))
    throw new ValidationError('Labor cadence needs an anchor date');
  if (
    input.mode === 'separate' &&
    input.expenseCadenceType === 'every_14_days' &&
    !dayPattern.test(input.expenseAnchorDate ?? '')
  )
    throw new ValidationError('Expense cadence needs an anchor date');
  if (!['default', 'labor-detailed', 'labor-summary'].includes(input.invoiceLayout))
    throw new ValidationError('Unsupported invoice layout');
  if (!['detail', 'summary', 'by_worker', 'by_day', 'by_category'].includes(input.groupingMode))
    throw new ValidationError('Unsupported invoice grouping');
  if (input.billingContactId && !uuidPattern.test(input.billingContactId))
    throw new ValidationError('Billing contact is invalid');
  if (input.recipientEmail && !/^\S+@\S+\.\S+$/.test(input.recipientEmail))
    throw new ValidationError('Recipient email is invalid');
  if (
    !Number.isInteger(input.paymentTermsDays) ||
    input.paymentTermsDays < 0 ||
    input.paymentTermsDays > 365
  )
    throw new ValidationError('Payment terms must be between 0 and 365 days');
  if (
    input.saveAsTemplate &&
    (!input.templateName || input.templateName.trim().length < 2 || input.templateName.length > 100)
  )
    throw new ValidationError('Template name must be between 2 and 100 characters');
}

export class ProjectBillingSetupRepository {
  private readonly sqlite: DatabaseSync;
  private readonly repository: PortalRepository;

  constructor(sqlite: DatabaseSync, repository: PortalRepository) {
    this.sqlite = sqlite;
    this.repository = repository;
  }

  private assertReadable(principal: Principal): void {
    assertActiveAccount(this.sqlite, principal, AccessDeniedError);
    if (!['owner_admin', 'finance_admin', 'auditor_read_only'].includes(principal.role))
      throw new AccessDeniedError('Finance role required');
  }

  private assertWritable(principal: Principal): void {
    this.assertReadable(principal);
    if (principal.role === 'auditor_read_only')
      throw new AccessDeniedError('Finance role required');
    assertLiveSession(this.sqlite, principal, AccessDeniedError);
  }

  listTemplates(
    principal: Principal,
    currency: Currency,
  ): Array<{ id: string; name: string; version: number; config: Record<string, unknown> }> {
    this.assertReadable(principal);
    const rows = this.sqlite
      .prepare(
        `SELECT t.id,t.name,t.version,t.config_json FROM project_billing_setup_template t
       WHERE t.currency=? AND NOT EXISTS(SELECT 1 FROM project_billing_setup_template newer
         WHERE newer.currency=t.currency AND lower(newer.name)=lower(t.name) AND newer.version>t.version)
       ORDER BY t.name COLLATE NOCASE`,
      )
      .all(currency) as TemplateRow[];
    return rows.map((row) => ({
      id: row.id,
      name: row.name,
      version: row.version,
      config: JSON.parse(row.config_json) as Record<string, unknown>,
    }));
  }

  currentVersion(principal: Principal, projectId: string): number {
    this.assertReadable(principal);
    return Number(
      (
        this.sqlite
          .prepare(
            'SELECT MAX(version) version FROM project_billing_setup_revision WHERE project_id=?',
          )
          .get(projectId) as { version: number | null }
      ).version ?? 0,
    );
  }

  rulesFingerprint(principal: Principal, projectId: string): string {
    this.assertReadable(principal);
    const rows = this.sqlite
      .prepare(
        `SELECT id,version,enabled,effective_from,effective_to FROM billing_rule
         WHERE project_id=? AND stream_type IN ('labor','expense') ORDER BY id`,
      )
      .all(projectId);
    return createHash('sha256').update(JSON.stringify(rows)).digest('hex');
  }

  issuingPrerequisites(
    principal: Principal,
    projectId: string,
    onDate: string,
    legalEntityId: string,
    taxProfileIds: readonly string[],
  ): string[] {
    this.assertReadable(principal);
    const issues: string[] = [];
    const identity = this.sqlite
      .prepare('SELECT tenant_id,deployment_id FROM deployment_identity WHERE singleton=1')
      .get() as { tenant_id: string; deployment_id: string } | undefined;
    const canonical =
      identity &&
      this.sqlite
        .prepare(
          `SELECT 1 FROM legal_entity_revision_bridge bridge
         JOIN project_legal_entity_assignment assignment
           ON assignment.legal_entity_revision_id=bridge.canonical_revision_id
          AND assignment.project_id=? AND assignment.tenant_id=? AND assignment.deployment_id=?
          AND assignment.effective_from<=? AND (assignment.effective_to IS NULL OR assignment.effective_to>=?)
         JOIN legal_entity_revision revision ON revision.revision_id=bridge.canonical_revision_id
          AND revision.effective_from<=? AND (revision.effective_to IS NULL OR revision.effective_to>=?)
         WHERE bridge.legacy_legal_entity_id=? AND bridge.tenant_id=? AND bridge.deployment_id=? LIMIT 1`,
        )
        .get(
          projectId,
          identity.tenant_id,
          identity.deployment_id,
          onDate,
          onDate,
          onDate,
          onDate,
          legalEntityId,
          identity.tenant_id,
          identity.deployment_id,
        );
    if (!canonical) issues.push('canonical_legal_entity_revision_required');
    const numberPolicy = this.sqlite
      .prepare(
        `SELECT 1 FROM invoice_number_policy WHERE legal_entity_id=?
        AND accountant_approved_at IS NOT NULL AND effective_from<=?
        AND (effective_to IS NULL OR effective_to>=?) LIMIT 1`,
      )
      .get(legalEntityId, projectCalendarDate('UTC'), projectCalendarDate('UTC'));
    if (!numberPolicy) issues.push('missing_accountant_approved_number_policy');
    for (const taxId of new Set(taxProfileIds)) {
      const tax = this.sqlite
        .prepare(
          `SELECT 1 FROM tax_profile WHERE id=? AND status='active'
          AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) LIMIT 1`,
        )
        .get(taxId, onDate, onDate);
      if (!tax) issues.push('tax_profile_not_effective');
    }
    return issues;
  }

  peopleReview(
    principal: Principal,
    projectId: string,
    onDate: string,
  ): Array<{
    id: string;
    name: string;
    customerRate: string | null;
    customerRateAmount: string;
    payConfigured: boolean;
    payType: string;
    payAmount: string;
    percentageBasis: string;
    expenseConfigured: boolean;
    activeExpensePayers: string[];
    expensePayer: string;
    workerReimbursement: string;
    clientRecovery: string;
    markupPercent: string;
    assignmentId: string;
    termsEffectiveFrom: string;
    termsFingerprint: string;
    needsReview: boolean;
  }> {
    this.assertReadable(principal);
    const rows = this.sqlite
      .prepare(
        `SELECT pm.id,pm.user_id,pm.starts_on,u.name FROM project_member pm JOIN user u ON u.id=pm.user_id
       WHERE pm.project_id=? AND (pm.ends_on IS NULL OR pm.ends_on>=?)
         AND pm.status='active' AND u.status='active'
       ORDER BY u.name,CASE WHEN pm.starts_on<=? THEN 0 ELSE 1 END,pm.starts_on`,
      )
      .all(projectId, onDate, onDate) as Array<{
      id: string;
      user_id: string;
      starts_on: string;
      name: string;
    }>;
    const seen = new Set<string>();
    return rows
      .filter((row) => {
        if (seen.has(row.user_id)) return false;
        seen.add(row.user_id);
        return true;
      })
      .map((row) => {
        const reviewDate = row.starts_on > onDate ? row.starts_on : onDate;
        let terms;
        try {
          terms = resolveAssignmentCommercialTerms(this.sqlite, {
            projectId,
            workerId: row.user_id,
            workDate: reviewDate,
            category: 'regular',
          });
        } catch {
          // Broken or ambiguous legacy assignments must remain visible in the
          // project setup instead of hiding the entire detail page behind a 500.
          return {
            id: row.user_id,
            name: row.name,
            customerRate: null,
            customerRateAmount: '',
            payConfigured: false,
            payType: 'Hourly',
            payAmount: '',
            percentageBasis: 'CLIENT_LABOR_BEFORE_TAX',
            expenseConfigured: false,
            activeExpensePayers: [],
            expensePayer: 'worker',
            workerReimbursement: 'at_cost',
            clientRecovery: 'at_cost',
            markupPercent: '',
            assignmentId: row.id,
            termsEffectiveFrom: reviewDate,
            termsFingerprint: this.personTermsFingerprint(principal, projectId, row.user_id),
            needsReview: true,
          };
        }
        const rate = terms.clientLaborRate?.rule.hourly_rate_minor;
        const policy = this.sqlite
          .prepare(
            `SELECT payer,worker_reimbursement,client_recovery,markup_bps
           FROM assignment_expense_policy WHERE project_member_id=? AND category IS NULL
          AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)
          ORDER BY effective_from DESC,version DESC LIMIT 1`,
          )
          .get(row.id, reviewDate, reviewDate) as
          | {
              payer: string;
              worker_reimbursement: string;
              client_recovery: string;
              markup_bps: number;
            }
          | undefined;
        const pay = terms.workerCompensation?.rule;
        const activeExpensePayers = (
          this.sqlite
            .prepare(
              `SELECT DISTINCT payer FROM assignment_expense_policy WHERE project_member_id=? AND category IS NULL AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY payer`,
            )
            .all(row.id, reviewDate, reviewDate) as Array<{ payer: string }>
        ).map((entry) => entry.payer);
        return {
          id: row.user_id,
          name: row.name,
          customerRate:
            rate == null
              ? null
              : `${terms.clientLaborRate?.rule.currency ?? ''} ${(BigInt(rate) / 100n).toString()}.${(BigInt(rate) % 100n).toString().padStart(2, '0')}/h`,
          customerRateAmount: decimalFromHundredths(rate),
          payConfigured: terms.workerCompensation !== null,
          payType: pay?.rule_type ?? 'Hourly',
          payAmount:
            pay?.rule_type === 'PercentageOfEligibleClientLabor'
              ? decimalFromHundredths(pay.percentage_bps)
              : decimalFromHundredths(pay?.rate_minor),
          percentageBasis: pay?.percentage_basis ?? 'CLIENT_LABOR_BEFORE_TAX',
          expenseConfigured: Boolean(policy),
          activeExpensePayers,
          expensePayer: policy?.payer ?? 'worker',
          workerReimbursement: policy?.worker_reimbursement ?? 'at_cost',
          clientRecovery: policy?.client_recovery ?? 'at_cost',
          markupPercent: decimalFromHundredths(policy?.markup_bps),
          assignmentId: row.id,
          termsEffectiveFrom: reviewDate,
          termsFingerprint: this.personTermsFingerprint(principal, projectId, row.user_id),
          needsReview: terms.issues.length > 0,
        };
      });
  }

  personTermsFingerprint(principal: Principal, projectId: string, workerId: string): string {
    this.assertReadable(principal);
    const member = this.sqlite
      .prepare(
        'SELECT id,version,starts_on,ends_on,status,client_bill_rule_id,worker_compensation_rule_id FROM project_member WHERE project_id=? AND user_id=? ORDER BY starts_on DESC,id DESC',
      )
      .all(projectId, workerId);
    const client = this.sqlite
      .prepare(
        'SELECT id,version,effective_from,effective_to,hourly_rate_minor FROM client_labor_rate WHERE project_id=? AND (worker_id=? OR worker_id IS NULL) ORDER BY id',
      )
      .all(projectId, workerId);
    const pay = this.sqlite
      .prepare(
        'SELECT id,version,effective_from,effective_to,rate_minor,rule_type,percentage_bps FROM compensation_rule WHERE worker_id=? AND (project_id=? OR project_id IS NULL) ORDER BY id',
      )
      .all(workerId, projectId);
    const policies = this.sqlite
      .prepare(
        `SELECT ep.id,ep.version,ep.effective_from,ep.effective_to,ep.payer,ep.worker_reimbursement,ep.client_recovery,ep.markup_bps FROM assignment_expense_policy ep JOIN project_member pm ON pm.id=ep.project_member_id WHERE pm.project_id=? AND pm.user_id=? ORDER BY ep.id`,
      )
      .all(projectId, workerId);
    const overrides = this.sqlite
      .prepare(
        `SELECT o.id,o.version,o.effective_from,o.effective_to,o.client_labor_rate_id,o.compensation_rule_id,o.priority FROM assignment_rate_override o JOIN project_member pm ON pm.id=o.project_member_id WHERE pm.project_id=? AND pm.user_id=? ORDER BY o.id`,
      )
      .all(projectId, workerId);
    return createHash('sha256')
      .update(JSON.stringify({ member, client, pay, policies, overrides }))
      .digest('hex');
  }

  savePersonTerms(principal: Principal, input: ProjectPersonTermsInput): { changed: boolean } {
    this.assertWritable(principal);
    if (
      !uuidPattern.test(input.projectId) ||
      !uuidPattern.test(input.projectMemberId) ||
      !input.workerId ||
      input.workerId.length > 200 ||
      !/^[0-9a-f]{64}$/.test(input.expectedFingerprint)
    )
      throw new ValidationError('Person terms reference is invalid');
    if (!dayPattern.test(input.effectiveFrom) || Number.isNaN(Date.parse(input.effectiveFrom)))
      throw new ValidationError('Person terms effective date is invalid');
    const customerMinor = decimalHundredths(input.customerHourlyRate, 'Customer hourly rate');
    const payHundredths = decimalHundredths(input.workerPayAmount, 'Worker compensation');
    const markupBps = Number(decimalHundredths(input.markupPercent || '0', 'Expense markup'));
    if (input.workerPayType === 'PercentageOfEligibleClientLabor' && payHundredths > 10_000n)
      throw new ValidationError('Worker compensation percentage cannot exceed 100%');
    if (markupBps > 10_000) throw new ValidationError('Expense markup cannot exceed 100%');
    return runImmediateTransaction(this.sqlite, 'project-person-terms', () => {
      if (
        input.expectedFingerprint !==
        this.personTermsFingerprint(principal, input.projectId, input.workerId)
      )
        throw new ConflictError('Person commercial terms changed. Reload before saving.');
      const project = this.sqlite
        .prepare('SELECT currency FROM project WHERE id=?')
        .get(input.projectId) as { currency: Currency } | undefined;
      const member = this.sqlite
        .prepare(
          `SELECT id,starts_on,ends_on,status FROM project_member WHERE id=? AND project_id=? AND user_id=?`,
        )
        .get(input.projectMemberId, input.projectId, input.workerId) as
        | { id: string; starts_on: string; ends_on: string | null; status: string }
        | undefined;
      if (
        !project ||
        !member ||
        member.status !== 'active' ||
        input.effectiveFrom < member.starts_on ||
        (member.ends_on && input.effectiveFrom > member.ends_on)
      )
        throw new ValidationError('Choose an effective date within this active project assignment');
      const billed = this.sqlite
        .prepare(
          "SELECT 1 FROM invoice WHERE project_id=? AND period_end>=? AND state NOT IN ('void','cancelled') LIMIT 1",
        )
        .get(input.projectId, input.effectiveFrom);
      const settled = this.sqlite
        .prepare(
          "SELECT 1 FROM compensation_settlement WHERE project_id=? AND worker_id=? AND period_end>=? AND state IN ('approved','settled') LIMIT 1",
        )
        .get(input.projectId, input.workerId, input.effectiveFrom);
      if (billed || settled)
        throw new ConflictError(
          'Invoice or finalized worker settlement history overlaps these terms. Choose a later effective date.',
        );
      const terms = resolveAssignmentCommercialTerms(this.sqlite, {
        projectId: input.projectId,
        workerId: input.workerId,
        workDate: input.effectiveFrom,
        category: 'regular',
      });
      if (
        terms.assignmentId !== member.id ||
        terms.issues.some((issue) => issue.code === 'ambiguous_assignment')
      )
        throw new ConflictError('Assignment needs review before commercial terms can be edited');
      const selectedClient = terms.clientLaborRate?.rule;
      const selectedPay = terms.workerCompensation?.rule;
      const clientChanged =
        !selectedClient ||
        selectedClient.project_id !== input.projectId ||
        selectedClient.worker_id !== input.workerId ||
        selectedClient.category !== null ||
        BigInt(selectedClient.hourly_rate_minor) !== customerMinor;
      const payChanged =
        !selectedPay ||
        selectedPay.project_id !== input.projectId ||
        selectedPay.rule_type !== input.workerPayType ||
        (input.workerPayType === 'PercentageOfEligibleClientLabor'
          ? Number(selectedPay.percentage_bps) !== Number(payHundredths) ||
            selectedPay.percentage_basis !== input.percentageBasis
          : BigInt(selectedPay.rate_minor) !== payHundredths);
      let clientRuleId: string | undefined;
      let payRuleId: string | undefined;
      if (clientChanged || payChanged) {
        const sameDayOverride = this.sqlite
          .prepare(
            `SELECT 1 FROM assignment_rate_override WHERE project_member_id=? AND effective_from=? AND (client_labor_rate_id IS NOT NULL OR compensation_rule_id IS NOT NULL) LIMIT 1`,
          )
          .get(member.id, input.effectiveFrom);
        if (sameDayOverride)
          throw new ConflictError(
            'An assignment rate already starts on this date. Choose a later effective date.',
          );
        const v3 = new V3Repository(this.sqlite);
        if (clientChanged)
          clientRuleId = v3.createClientLaborRate(principal, {
            projectId: input.projectId,
            workerId: input.workerId,
            currency: project.currency,
            hourlyRateMinor: customerMinor,
            effectiveFrom: input.effectiveFrom,
          }).id;
        if (payChanged)
          payRuleId = v3.createCompensationRule(principal, {
            projectId: input.projectId,
            workerId: input.workerId,
            currency: project.currency,
            ruleType: input.workerPayType,
            ...(input.workerPayType === 'PercentageOfEligibleClientLabor'
              ? { percentageBps: Number(payHundredths), percentageBasis: input.percentageBasis }
              : {
                  rateMinor: payHundredths,
                  ...(input.workerPayType === 'Daily' ? { rateBasis: 'daily' as const } : {}),
                }),
            effectiveFrom: input.effectiveFrom,
          }).id;
        v3.createAssignmentRateOverride(principal, {
          projectMemberId: member.id,
          effectiveFrom: input.effectiveFrom,
          clientLaborRateId: clientRuleId,
          compensationRuleId: payRuleId,
        });
        const resolved = resolveAssignmentCommercialTerms(this.sqlite, {
          projectId: input.projectId,
          workerId: input.workerId,
          workDate: input.effectiveFrom,
          category: 'regular',
        });
        if (
          (clientRuleId && resolved.clientLaborRate?.rule.id !== clientRuleId) ||
          (payRuleId && resolved.workerCompensation?.rule.id !== payRuleId)
        )
          throw new ConflictError(
            'A more specific assignment override controls this person. Review advanced commercial terms.',
          );
      }
      const policy = this.sqlite
        .prepare(
          `SELECT id,effective_from,worker_reimbursement,client_recovery,markup_bps FROM assignment_expense_policy WHERE project_member_id=? AND payer=? AND category IS NULL AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC,version DESC LIMIT 1`,
        )
        .get(member.id, input.expensePayer, input.effectiveFrom, input.effectiveFrom) as
        | {
            id: string;
            effective_from: string;
            worker_reimbursement: string;
            client_recovery: string;
            markup_bps: number;
          }
        | undefined;
      const policyChanged =
        !policy ||
        policy.worker_reimbursement !== input.workerReimbursement ||
        policy.client_recovery !== input.clientRecovery ||
        policy.markup_bps !== markupBps;
      if (policyChanged) {
        if (policy?.effective_from === input.effectiveFrom)
          throw new ConflictError(
            'An expense policy already starts on this date. Choose a later effective date.',
          );
        new AssignmentExpensePolicyRepository(this.sqlite).create(principal, {
          projectMemberId: member.id,
          payer: input.expensePayer,
          effectiveFrom: input.effectiveFrom,
          effectiveTo: member.ends_on,
          workerReimbursement: input.workerReimbursement,
          clientRecovery: input.clientRecovery,
          markupBps,
          reason: 'Project billing setup per-person terms',
        });
      }
      return { changed: clientChanged || payChanged || policyChanged };
    });
  }

  savePeopleTerms(
    principal: Principal,
    inputs: readonly ProjectPersonTermsInput[],
  ): { saved: number } {
    this.assertWritable(principal);
    if (inputs.length < 1 || inputs.length > 50)
      throw new ValidationError('Select between one and fifty people');
    if (new Set(inputs.map((input) => input.workerId)).size !== inputs.length)
      throw new ValidationError('A person may appear only once in a batch');
    if (new Set(inputs.map((input) => input.projectId)).size !== 1)
      throw new ValidationError('All people must belong to the same project');
    return runImmediateTransaction(this.sqlite, 'project-people-terms', () => {
      for (const input of inputs) this.savePersonTerms(principal, input);
      return { saved: inputs.length };
    });
  }

  save(
    principal: Principal,
    input: ProjectBillingSetupInput,
  ): {
    version: number;
    laborRuleId: string;
    expenseRuleId: string | null;
    templateId: string | null;
  } {
    this.assertWritable(principal);
    validate(input);
    const project = this.sqlite
      .prepare('SELECT id,currency,timezone FROM project WHERE id=?')
      .get(input.projectId) as { id: string; currency: Currency; timezone: string } | undefined;
    if (!project) throw new ValidationError('Project not found');
    const config = {
      mode: input.mode,
      legalEntityId: input.legalEntityId,
      laborTaxProfileId: input.laborTaxProfileId,
      expenseTaxProfileId:
        input.mode === 'separate' ? input.expenseTaxProfileId : input.laborTaxProfileId,
      cadenceType: input.cadenceType,
      expenseCadenceType: input.mode === 'separate' ? input.expenseCadenceType : input.cadenceType,
      anchorDate: input.anchorDate ?? '',
      expenseAnchorDate: input.mode === 'separate' ? (input.expenseAnchorDate ?? '') : '',
      invoiceLayout: input.invoiceLayout,
      groupingMode: input.groupingMode,
      paymentTermsDays: input.paymentTermsDays,
      autoGenerateDraft: input.autoGenerateDraft,
    };
    const payload = JSON.stringify({
      ...config,
      projectId: input.projectId,
      effectiveFrom: input.effectiveFrom,
      billingContactId: input.billingContactId ?? '',
      recipientEmail: input.recipientEmail ?? '',
      selectedTemplateId: input.selectedTemplateId ?? '',
      saveAsTemplate: input.saveAsTemplate,
      templateName: input.templateName?.trim() ?? '',
    });
    const payloadHash = createHash('sha256').update(payload).digest('hex');
    return runImmediateTransaction(this.sqlite, 'project-billing-setup', () => {
      const replay = this.sqlite
        .prepare(
          'SELECT payload_hash,version,labor_rule_id,expense_rule_id,template_id FROM project_billing_setup_revision WHERE request_key=?',
        )
        .get(input.requestKey) as
        | {
            payload_hash: string;
            version: number;
            labor_rule_id: string;
            expense_rule_id: string | null;
            template_id: string | null;
          }
        | undefined;
      if (replay) {
        if (replay.payload_hash !== payloadHash)
          throw new ConflictError(
            'Billing setup request key was already used for different settings',
          );
        return {
          version: replay.version,
          laborRuleId: replay.labor_rule_id,
          expenseRuleId: replay.expense_rule_id,
          templateId: replay.template_id,
        };
      }
      const latest = this.sqlite
        .prepare(
          'SELECT MAX(version) version FROM project_billing_setup_revision WHERE project_id=?',
        )
        .get(input.projectId) as { version: number | null };
      const currentVersion = Number(latest.version ?? 0);
      if (input.expectedVersion !== currentVersion)
        throw new ConflictError('Billing setup changed. Reload before saving.');
      if (input.expectedRulesFingerprint !== this.rulesFingerprint(principal, input.projectId))
        throw new ConflictError(
          'Billing rules changed outside this setup. Reload and review before saving.',
        );
      if (input.effectiveFrom < projectCalendarDate(project.timezone)) {
        if (currentVersion > 0)
          throw new ConflictError('Existing billing setup changes must start today or later.');
        const billed = this.sqlite
          .prepare('SELECT 1 FROM invoice WHERE project_id=? AND period_end>=? LIMIT 1')
          .get(input.projectId, input.effectiveFrom);
        const period = this.sqlite
          .prepare(
            'SELECT 1 FROM billing_period bp JOIN billing_rule br ON br.id=bp.billing_rule_id WHERE br.project_id=? AND bp.period_end>=? LIMIT 1',
          )
          .get(input.projectId, input.effectiveFrom);
        if (billed || period)
          throw new ConflictError(
            'Existing invoice or billing period history overlaps the backdated setup.',
          );
      }
      if (
        input.selectedTemplateId &&
        !this.sqlite
          .prepare('SELECT 1 FROM project_billing_setup_template WHERE id=? AND currency=?')
          .get(input.selectedTemplateId, project.currency)
      )
        throw new ValidationError('Saved template no longer exists for this currency');
      if (
        input.billingContactId &&
        !this.sqlite
          .prepare(
            'SELECT 1 FROM client_contact cc JOIN project p ON p.client_id=cc.client_id WHERE cc.id=? AND p.id=?',
          )
          .get(input.billingContactId, input.projectId)
      )
        throw new ValidationError('Billing contact does not belong to this client');
      const commercialIdentity = this.sqlite
        .prepare(
          `SELECT p.currency, c.status client_status, le.currency entity_currency, le.status entity_status
           FROM project p JOIN client c ON c.id=p.client_id
           JOIN legal_entity le ON le.id=? WHERE p.id=?`,
        )
        .get(input.legalEntityId, input.projectId) as
        | {
            currency: string;
            client_status: string;
            entity_currency: string;
            entity_status: string;
          }
        | undefined;
      if (
        !commercialIdentity ||
        commercialIdentity.client_status !== 'active' ||
        commercialIdentity.entity_status !== 'active' ||
        commercialIdentity.currency !== commercialIdentity.entity_currency
      )
        throw new ValidationError(
          'The client and issuing entity must be active and use the project currency',
        );
      for (const taxId of input.mode === 'combined'
        ? [input.laborTaxProfileId]
        : [input.laborTaxProfileId, input.expenseTaxProfileId]) {
        const tax = this.sqlite
          .prepare('SELECT currency,status,legal_entity_id FROM tax_profile WHERE id=?')
          .get(taxId) as
          | { currency: string; status: string; legal_entity_id: string | null }
          | undefined;
        if (
          !tax ||
          tax.status !== 'active' ||
          tax.currency !== project.currency ||
          (tax.legal_entity_id && tax.legal_entity_id !== input.legalEntityId)
        )
          throw new ValidationError(
            'Choose active tax profiles for the issuing entity and project currency',
          );
      }
      const active = this.sqlite
        .prepare(
          `SELECT * FROM billing_rule WHERE project_id=? AND enabled=1 AND stream_type IN ('labor','expense')
          AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)`,
        )
        .all(input.projectId, input.effectiveFrom, input.effectiveFrom) as RuleRow[];
      const labor = active.find((row) => row.stream_type === 'labor');
      const expense = active.find((row) => row.stream_type === 'expense');
      if (
        active.filter((row) => row.stream_type === 'labor').length > 1 ||
        active.filter((row) => row.stream_type === 'expense').length > 1
      )
        throw new ConflictError(
          'Overlapping billing rules need Finance review before saving this setup',
        );
      if (input.mode === 'combined' && expense)
        this.closeExpenseRule(principal, expense, input.effectiveFrom);
      // createBillingRule supersedes an earlier active rule of the same stream
      // in the same transaction, closing its effective range the day before.
      const laborRuleId = this.writeRule(principal, project.currency, input, 'labor', labor);
      let expenseRuleId: string | null = null;
      if (input.mode === 'separate') {
        expenseRuleId = this.writeRule(principal, project.currency, input, 'expense', expense);
      }
      let templateId: string | null = null;
      if (input.saveAsTemplate) {
        const name = input.templateName!.trim();
        const prior = this.sqlite
          .prepare(
            'SELECT MAX(version) version FROM project_billing_setup_template WHERE lower(name)=lower(?)',
          )
          .get(name) as { version: number | null };
        const templateVersion = Number(prior.version ?? 0) + 1;
        templateId = newId();
        this.sqlite
          .prepare(
            'INSERT INTO project_billing_setup_template(id,name,version,currency,config_json,created_by_user_id,created_at) VALUES(?,?,?,?,?,?,?)',
          )
          .run(
            templateId,
            name,
            templateVersion,
            project.currency,
            JSON.stringify(config),
            principal.userId,
            stamp(),
          );
        recordAuditEvent(
          this.sqlite,
          principal,
          'project_billing_template.save',
          'project_billing_setup_template',
          templateId,
          { projectId: input.projectId, name, version: templateVersion },
        );
      }
      const revisionId = newId();
      const version = currentVersion + 1;
      this.sqlite
        .prepare(
          `INSERT INTO project_billing_setup_revision(id,project_id,version,effective_from,mode,config_json,
          labor_rule_id,expense_rule_id,template_id,request_key,payload_hash,created_by_user_id,created_at)
          VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,
        )
        .run(
          revisionId,
          input.projectId,
          version,
          input.effectiveFrom,
          input.mode,
          payload,
          laborRuleId,
          expenseRuleId,
          templateId ?? input.selectedTemplateId ?? null,
          input.requestKey,
          payloadHash,
          principal.userId,
          stamp(),
        );
      recordAuditEvent(
        this.sqlite,
        principal,
        'project_billing_setup.save',
        'project_billing_setup_revision',
        revisionId,
        {
          projectId: input.projectId,
          version,
          mode: input.mode,
          laborRuleId,
          expenseRuleId,
          templateId,
        },
      );
      return { version, laborRuleId, expenseRuleId, templateId };
    });
  }

  private writeRule(
    principal: Principal,
    currency: Currency,
    input: ProjectBillingSetupInput,
    stream: 'labor' | 'expense',
    existing: RuleRow | undefined,
  ): string {
    const labor = stream === 'labor';
    const taxProfileId = labor ? input.laborTaxProfileId : input.expenseTaxProfileId;
    const cadenceType = labor ? input.cadenceType : input.expenseCadenceType;
    const anchorDate = labor ? input.anchorDate : input.expenseAnchorDate;
    const templateId = labor ? input.invoiceLayout : 'expenses-detailed';
    const includeExpenses = labor && input.mode === 'combined';
    const data = {
      legalEntityId: input.legalEntityId,
      taxProfileId,
      cadenceType,
      anchorDate: anchorDate || undefined,
      templateId,
      groupingMode: input.groupingMode,
      billingContactId: input.billingContactId || undefined,
      recipientEmail: input.recipientEmail || undefined,
      paymentTermsDays: input.paymentTermsDays,
      autoGenerateDraft: input.autoGenerateDraft,
      includeExpenses,
    };
    if (existing) this.assertNoBillingHistoryOnOrAfter(existing, input.effectiveFrom);
    if (existing && existing.effective_from === input.effectiveFrom) {
      const used =
        this.sqlite
          .prepare('SELECT 1 FROM invoice WHERE billing_rule_id=? LIMIT 1')
          .get(existing.id) ||
        this.sqlite
          .prepare('SELECT 1 FROM billing_period WHERE billing_rule_id=? LIMIT 1')
          .get(existing.id);
      if (used)
        throw new ConflictError(
          'This billing rule has invoice or period history. Choose a later effective date.',
        );
      this.repository.updateBillingRule(principal, existing.id, data);
      // These reviewed setup fields are immutable in the advanced editor but can be
      // corrected before the first billing period or invoice uses the rule.
      this.sqlite
        .prepare(
          `UPDATE billing_rule SET legal_entity_id=?,tax_profile_id=?,cadence_type=?,anchor_date=?,
           billing_contact_id=?,recipient_email=?,template_id=?,grouping_mode=?,
           payment_terms_days=?,auto_generate_draft=?,include_expenses=?,updated_at=? WHERE id=?`,
        )
        .run(
          input.legalEntityId,
          taxProfileId,
          cadenceType,
          anchorDate || null,
          input.billingContactId || null,
          input.recipientEmail || null,
          templateId,
          input.groupingMode,
          input.paymentTermsDays,
          input.autoGenerateDraft ? 1 : 0,
          includeExpenses ? 1 : 0,
          stamp(),
          existing.id,
        );
      return existing.id;
    }
    const created = this.repository.createBillingRule(principal, {
      projectId: input.projectId,
      legalEntityId: input.legalEntityId,
      streamType: stream,
      cadenceType,
      anchorDate: anchorDate || undefined,
      taxProfileId,
      currency,
      effectiveFrom: input.effectiveFrom,
      templateId,
      recipientEmail: input.recipientEmail || undefined,
      paymentTermsDays: input.paymentTermsDays,
      groupingMode: input.groupingMode,
      autoGenerateDraft: input.autoGenerateDraft,
      billingContactId: input.billingContactId || undefined,
      includeExpenses,
    });
    return created.id;
  }

  private closeExpenseRule(principal: Principal, rule: RuleRow, effectiveFrom: string): void {
    this.assertNoBillingHistoryOnOrAfter(rule, effectiveFrom);
    if (rule.effective_from === effectiveFrom) {
      const used =
        this.sqlite.prepare('SELECT 1 FROM invoice WHERE billing_rule_id=? LIMIT 1').get(rule.id) ||
        this.sqlite
          .prepare('SELECT 1 FROM billing_period WHERE billing_rule_id=? LIMIT 1')
          .get(rule.id);
      if (used)
        throw new ConflictError(
          'Expense rule already has billing history. Choose a later effective date.',
        );
      this.sqlite
        .prepare('UPDATE billing_rule SET enabled=0,updated_at=?,version=version+1 WHERE id=?')
        .run(stamp(), rule.id);
    } else {
      this.sqlite
        .prepare(
          'UPDATE billing_rule SET effective_to=?,updated_at=?,version=version+1 WHERE id=? AND effective_from<?',
        )
        .run(previousDay(effectiveFrom), stamp(), rule.id, effectiveFrom);
    }
    recordAuditEvent(this.sqlite, principal, 'billing_rule.archive', 'billing_rule', rule.id, {
      projectId: rule.project_id,
      effectiveFrom,
      reason: 'Combined project invoice arrangement',
    });
  }

  private assertNoBillingHistoryOnOrAfter(rule: RuleRow, effectiveFrom: string): void {
    const invoice = this.sqlite
      .prepare('SELECT 1 FROM invoice WHERE billing_rule_id=? AND period_end>=? LIMIT 1')
      .get(rule.id, effectiveFrom);
    const period = this.sqlite
      .prepare('SELECT 1 FROM billing_period WHERE billing_rule_id=? AND period_end>=? LIMIT 1')
      .get(rule.id, effectiveFrom);
    if (invoice || period)
      throw new ConflictError(
        'Existing invoice or billing period history overlaps this effective date. Choose a later date.',
      );
  }
}
