BEGIN IMMEDIATE;

CREATE TABLE IF NOT EXISTS schema_migration (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL) STRICT;
INSERT OR IGNORE INTO schema_migration VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));

CREATE TABLE IF NOT EXISTS user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL DEFAULT 0 CHECK(email_verified IN (0,1)), image TEXT, role TEXT NOT NULL DEFAULT 'worker' CHECK(role IN ('owner_admin','finance_admin','project_manager','worker','auditor_read_only')), status TEXT NOT NULL DEFAULT 'invited' CHECK(status IN ('invited','active','suspended','offboarded')), mfa_enrolled INTEGER NOT NULL DEFAULT 0 CHECK(mfa_enrolled IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0)) STRICT;
CREATE TABLE IF NOT EXISTS session (id TEXT PRIMARY KEY, token TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, expires_at TEXT NOT NULL, ip_address TEXT, user_agent TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL) STRICT;
CREATE INDEX IF NOT EXISTS session_user_idx ON session(user_id);
CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, password TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, account_id)) STRICT;
CREATE TABLE IF NOT EXISTS verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS passkey (id TEXT PRIMARY KEY, name TEXT, public_key TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, credential_id TEXT NOT NULL UNIQUE, counter INTEGER NOT NULL, device_type TEXT NOT NULL, backed_up INTEGER NOT NULL CHECK(backed_up IN (0,1)), transports TEXT, created_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS two_factor (id TEXT PRIMARY KEY, secret TEXT NOT NULL, backup_codes TEXT NOT NULL, user_id TEXT NOT NULL UNIQUE REFERENCES user(id) ON DELETE CASCADE) STRICT;
CREATE TABLE IF NOT EXISTS invitation (id TEXT PRIMARY KEY, email TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, role TEXT NOT NULL, invited_by TEXT NOT NULL REFERENCES user(id), expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL) STRICT;

CREATE TABLE IF NOT EXISTS number_sequence (scope TEXT NOT NULL, scope_id TEXT NOT NULL, next_value INTEGER NOT NULL CHECK(next_value > 0), version INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(scope, scope_id)) STRICT;
CREATE TABLE IF NOT EXISTS client (id TEXT PRIMARY KEY, client_number TEXT NOT NULL UNIQUE, legal_name TEXT NOT NULL, display_name TEXT NOT NULL, status TEXT NOT NULL, currency TEXT NOT NULL CHECK(length(currency)=3), timezone TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS project (id TEXT PRIMARY KEY, project_number TEXT NOT NULL UNIQUE, client_id TEXT NOT NULL REFERENCES client(id), name TEXT NOT NULL, timezone TEXT NOT NULL, currency TEXT NOT NULL CHECK(length(currency)=3), status TEXT NOT NULL CHECK(status IN ('draft','planned','active','paused','closing','closed','archived')), billing_model TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE INDEX IF NOT EXISTS project_client_idx ON project(client_id);
CREATE TABLE IF NOT EXISTS project_member (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), user_id TEXT NOT NULL REFERENCES user(id), assignment_role TEXT NOT NULL, starts_on TEXT NOT NULL, ends_on TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, UNIQUE(project_id,user_id,starts_on)) STRICT;
CREATE TABLE IF NOT EXISTS skill (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, created_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS worker_skill (worker_id TEXT NOT NULL REFERENCES user(id), skill_id TEXT NOT NULL REFERENCES skill(id), proficiency INTEGER NOT NULL CHECK(proficiency BETWEEN 1 AND 5), verified_at TEXT, PRIMARY KEY(worker_id,skill_id)) STRICT;
CREATE TABLE IF NOT EXISTS schedule (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), timezone TEXT NOT NULL, monday_minutes INTEGER NOT NULL DEFAULT 600, tuesday_minutes INTEGER NOT NULL DEFAULT 600, wednesday_minutes INTEGER NOT NULL DEFAULT 600, thursday_minutes INTEGER NOT NULL DEFAULT 600, friday_minutes INTEGER NOT NULL DEFAULT 600, saturday_minutes INTEGER NOT NULL DEFAULT 600, sunday_minutes INTEGER NOT NULL DEFAULT 0, effective_from TEXT NOT NULL, effective_to TEXT, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS planning_assignment (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), worker_id TEXT NOT NULL REFERENCES user(id), starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, planned_minutes INTEGER NOT NULL CHECK(planned_minutes >= 0), version INTEGER NOT NULL DEFAULT 1) STRICT;

CREATE TABLE IF NOT EXISTS time_entry (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), worker_id TEXT NOT NULL REFERENCES user(id), work_date TEXT NOT NULL, category TEXT NOT NULL, minutes INTEGER NOT NULL CHECK(minutes BETWEEN 0 AND 1440), approval_state TEXT NOT NULL DEFAULT 'draft', billability_state TEXT NOT NULL DEFAULT 'pending', invoice_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE INDEX IF NOT EXISTS time_project_period_idx ON time_entry(project_id,work_date);
CREATE INDEX IF NOT EXISTS time_worker_period_idx ON time_entry(worker_id,work_date);
CREATE TABLE IF NOT EXISTS daily_report (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), worker_id TEXT NOT NULL REFERENCES user(id), work_date TEXT NOT NULL, summary TEXT NOT NULL, safety_notes TEXT, approval_state TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS technical_report (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), author_id TEXT NOT NULL REFERENCES user(id), system_name TEXT NOT NULL, controller TEXT, change_summary TEXT NOT NULL, safety_related INTEGER NOT NULL DEFAULT 0 CHECK(safety_related IN (0,1)), validation TEXT, rollback_plan TEXT, approval_state TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS expense (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), worker_id TEXT NOT NULL REFERENCES user(id), spent_on TEXT NOT NULL, category TEXT NOT NULL, currency TEXT NOT NULL, amount_minor INTEGER NOT NULL CHECK(amount_minor >= 0), client_treatment TEXT NOT NULL CHECK(client_treatment IN ('all_in','reimbursable','non_billable')), approval_state TEXT NOT NULL DEFAULT 'draft', invoice_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE INDEX IF NOT EXISTS expense_project_period_idx ON expense(project_id,spent_on);
CREATE TABLE IF NOT EXISTS compensation_rule (id TEXT PRIMARY KEY, worker_id TEXT NOT NULL REFERENCES user(id), project_id TEXT REFERENCES project(id), currency TEXT NOT NULL, rate_minor INTEGER NOT NULL CHECK(rate_minor >= 0), rate_basis TEXT NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT, version INTEGER NOT NULL DEFAULT 1) STRICT;

CREATE TABLE IF NOT EXISTS tax_profile (id TEXT PRIMARY KEY, name TEXT NOT NULL, currency TEXT NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS tax_component (id TEXT PRIMARY KEY, tax_profile_id TEXT NOT NULL REFERENCES tax_profile(id), name TEXT NOT NULL, basis_points INTEGER NOT NULL, calculation_order INTEGER NOT NULL, compound INTEGER NOT NULL DEFAULT 0 CHECK(compound IN (0,1))) STRICT;
CREATE TABLE IF NOT EXISTS billing_rule (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), stream_type TEXT NOT NULL CHECK(stream_type IN ('labor','expense','milestone','other')), cadence_type TEXT NOT NULL, anchor_date TEXT, tax_profile_id TEXT REFERENCES tax_profile(id), currency TEXT NOT NULL, auto_generate_draft INTEGER NOT NULL DEFAULT 0, auto_issue INTEGER NOT NULL DEFAULT 0 CHECK(auto_issue=0), auto_send INTEGER NOT NULL DEFAULT 0 CHECK(auto_send=0), effective_from TEXT NOT NULL, effective_to TEXT, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS billing_lock (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), stream_type TEXT NOT NULL, period_start TEXT NOT NULL, period_end TEXT NOT NULL, acquired_at TEXT NOT NULL, UNIQUE(project_id,stream_type,period_start,period_end)) STRICT;
CREATE TABLE IF NOT EXISTS invoice (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), invoice_number TEXT UNIQUE, stream_type TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'draft', currency TEXT NOT NULL, subtotal_minor INTEGER NOT NULL DEFAULT 0, tax_minor INTEGER NOT NULL DEFAULT 0, total_minor INTEGER NOT NULL DEFAULT 0, issued_at TEXT, snapshot_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, CHECK((state NOT IN ('issued','sent','partially_paid','paid','overdue','void','credited')) OR (invoice_number IS NOT NULL AND issued_at IS NOT NULL AND snapshot_json IS NOT NULL))) STRICT;
CREATE TABLE IF NOT EXISTS invoice_line (id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL REFERENCES invoice(id), description TEXT NOT NULL, quantity_numerator INTEGER NOT NULL, quantity_denominator INTEGER NOT NULL CHECK(quantity_denominator > 0), unit_price_minor INTEGER NOT NULL, subtotal_minor INTEGER NOT NULL, source_type TEXT NOT NULL, source_id TEXT NOT NULL, snapshot_json TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS payment (id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL REFERENCES invoice(id), amount_minor INTEGER NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL, received_at TEXT NOT NULL, reference TEXT, created_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS finance_snapshot (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(id), as_of TEXT NOT NULL, cost_minor INTEGER NOT NULL, revenue_minor INTEGER NOT NULL, contribution_margin_minor INTEGER NOT NULL, etc_minor INTEGER NOT NULL, eac_minor INTEGER NOT NULL, input_hash TEXT NOT NULL, created_at TEXT NOT NULL) STRICT;

CREATE TABLE IF NOT EXISTS document (id TEXT PRIMARY KEY, project_id TEXT REFERENCES project(id), owner_id TEXT NOT NULL REFERENCES user(id), sha256 TEXT NOT NULL, media_type TEXT NOT NULL, byte_length INTEGER NOT NULL CHECK(byte_length >= 0), state TEXT NOT NULL CHECK(state IN ('temporary','quarantined','committed','rejected')), storage_key TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, UNIQUE(sha256,byte_length)) STRICT;
CREATE TABLE IF NOT EXISTS approval_event (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, from_state TEXT NOT NULL, to_state TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES user(id), reason TEXT, occurred_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS notification (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES user(id), kind TEXT NOT NULL, subject_id TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL, UNIQUE(user_id,kind,subject_id)) STRICT;
CREATE TABLE IF NOT EXISTS job (id TEXT PRIMARY KEY, kind TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, state TEXT NOT NULL, run_after TEXT NOT NULL, lease_until TEXT, attempts INTEGER NOT NULL DEFAULT 0, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1) STRICT;
CREATE TABLE IF NOT EXISTS job_run (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES job(id), started_at TEXT NOT NULL, finished_at TEXT, outcome TEXT, error_code TEXT) STRICT;
CREATE TABLE IF NOT EXISTS audit_event (id TEXT PRIMARY KEY, actor_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, occurred_at TEXT NOT NULL, details_json TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS public_inquiry (id TEXT PRIMARY KEY, kind TEXT NOT NULL, payload_json TEXT NOT NULL, source_hash TEXT NOT NULL, created_at TEXT NOT NULL, delivered_at TEXT) STRICT;
CREATE TABLE IF NOT EXISTS outbox_event (id TEXT PRIMARY KEY, topic TEXT NOT NULL, aggregate_id TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL, available_at TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, delivered_at TEXT, created_at TEXT NOT NULL) STRICT;

CREATE TRIGGER IF NOT EXISTS issued_invoice_no_update BEFORE UPDATE ON invoice WHEN OLD.state IN ('issued','sent','partially_paid','paid','overdue','void','credited') BEGIN SELECT RAISE(ABORT,'issued invoice is immutable'); END;
CREATE TRIGGER IF NOT EXISTS issued_invoice_no_delete BEFORE DELETE ON invoice WHEN OLD.state IN ('issued','sent','partially_paid','paid','overdue','void','credited') BEGIN SELECT RAISE(ABORT,'issued invoice is immutable'); END;
CREATE TRIGGER IF NOT EXISTS issued_line_no_update BEFORE UPDATE ON invoice_line WHEN EXISTS(SELECT 1 FROM invoice WHERE id=OLD.invoice_id AND state IN ('issued','sent','partially_paid','paid','overdue','void','credited')) BEGIN SELECT RAISE(ABORT,'issued invoice line is immutable'); END;
CREATE TRIGGER IF NOT EXISTS issued_line_no_delete BEFORE DELETE ON invoice_line WHEN EXISTS(SELECT 1 FROM invoice WHERE id=OLD.invoice_id AND state IN ('issued','sent','partially_paid','paid','overdue','void','credited')) BEGIN SELECT RAISE(ABORT,'issued invoice line is immutable'); END;
CREATE TRIGGER IF NOT EXISTS all_in_expense_invoice_guard BEFORE UPDATE OF invoice_id ON expense WHEN OLD.client_treatment='all_in' AND NEW.invoice_id IS NOT NULL BEGIN SELECT RAISE(ABORT,'all-in expense cannot enter customer invoice'); END;

COMMIT;
