from pathlib import Path
import ast, hashlib, html, json, shutil

ROOT = Path(__file__).resolve().parent
DOCS = ROOT.parent.parent / 'docs' / 'manuals'
FIG = DOCS / 'bbs-illustrated-en-v2'
FIG.mkdir(exist_ok=True)
NAME = 'BBS_Project_to_Client_Invoices_Guide_EN'
BASE = 'https://j-aautomation.com/j-aautomation/app'
PROJECT = '01a10c51-a391-7288-aad1-cb38be43f496'
pages, original = [], []

def table(headers, rows):
    return '<table><thead><tr>' + ''.join('<th>'+html.escape(x)+'</th>' for x in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join('<td>'+html.escape(str(x))+'</td>' for x in row)+'</tr>' for row in rows) + '</tbody></table>'
def steps(*items):
    return '<ol>' + ''.join('<li>'+x+'</li>' for x in items) + '</ol>'
def note(text):
    return '<aside>'+text+'</aside>'
def route(text, url=''):
    return '<div class="route"><strong>Go here:</strong> '+text + ('<br><a href="'+html.escape(BASE+url, quote=True)+'">Live company portal · open this workspace</a>' if url else '') + '</div>'
def add(title, body, image=None, caption=''):
    original.append((title, body, image, caption))

# Read the existing guide's chapter content without running its writes/builds.
tree = ast.parse((ROOT/'original-chapters.py').read_text())
env = {'add':add, 'table':table, 'steps':steps, 'note':note}
for node in tree.body:
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name) and node.value.func.id == 'add':
        eval(compile(ast.Expression(node.value), '<existing-guide>', 'eval'), env)

def page(key, title, body, toc=False, wide=False):
    pages.append({'key':key, 'title':title, 'body':body, 'toc':toc, 'wide':wide, 'figure':False})
def fig(key, title, filename, caption, wide=True):
    src = FIG/filename
    assert src.is_file(), filename
    pages.append({'key':key, 'title':title, 'body':'<figure><img src="bbs-illustrated-en-v2/'+filename+'"><figcaption>'+caption+'</figcaption></figure>', 'toc':False, 'wide':wide, 'figure':True})
def pair(key, title, filenames, caption):
    for name in filenames:
        assert (FIG/name).is_file(), name
    pages.append({'key':key,'title':title,'body':'<figure class="pair">'+''.join('<img src="bbs-illustrated-en-v2/'+name+'">' for name in filenames)+'<figcaption>'+caption+'</figcaption></figure>','toc':False,'wide':True,'figure':True})

page('cover','BBS · Project to client invoices', '<p class="lead">An illustrated BBS worked lab and Owner operating reference.</p><p>English instructions · Actual application captures · Downloaded invoice PDFs included.</p><p>Training project: <strong>BBS · Ejemplo de manual</strong><br>Project number: <strong>C-0050-P-20261005</strong></p>'+table(['Example','Approved sources','Final training invoice PDF'],[['Stage 1 · 1–4 October','35 actual hours','USD 2,230 labor'],['Expenses · October','4 expenses; USD 230 spent','USD 182 customer expense recovery'],['Stage 2 · 5–11 October','7.5 actual hours; hour/day/week units','USD 2,260 labor']])+note('This separate BBS project contains fictional training records. Original BBS Mexico and Junkers are outside the exercise. The three final invoices in the annex were genuinely approved and issued by the application in an isolated training database. Their totals and invoice numbers are preserved. Numbering approval and payment evidence in the training database are simulations, never proof of accountant approval or a real transfer. No customer email was sent.')+'<p>Use the contents pages to find a task. Each chapter gives the role, exact navigation path, fields to fill and buttons to click. Important forms have a separate enlarged screenshot page. Saved example names/descriptions are quoted exactly as displayed, including their original record language.</p>')
page('contents-1','Contents · Course tasks (1/4)','')
page('contents-2','Contents · Course tasks (2/4)','')
page('contents-3','Contents · Course tasks (3/4)','')
page('contents-4','Contents · Course tasks (4/4)','')

routes = {
1: ('Owner → Projects; workers/chief → Time, Expenses or Crew; reviewer → Approvals; Owner/Finance → Billing','/projects?lang=en'),
2: ('Owner → Projects → More actions → New Client; then Projects → New Project','/projects?action=new-client&lang=en'),
3: ('Owner → Projects → open BBS · Ejemplo de manual → Billing → Configure project defaults; then Configure this project’s invoices → 3. Review each person',f'/projects/{PROJECT}?tab=billing&billingStep=people&lang=en'),
4: ('Owner/Finance → project → Billing → Configure this project’s invoices → 2. Billing details',f'/projects/{PROJECT}?tab=billing&lang=en'),
5: ('Owner/Finance → project → Billing → 3. Review each person → Person: BBS DEMO - Jefe de crew → Go to person',f'/projects/{PROJECT}?tab=billing&billingStep=people&lang=en'),
6: ('Owner/Finance → project → Billing → 3. Review each person → Person: BBS DEMO - Tecnico 1 → Go to person',f'/projects/{PROJECT}?tab=billing&billingStep=people&lang=en'),
7: ('Owner/Finance → project → Billing → 3. Review each person → Person: BBS DEMO - Tecnico 2 → Go to person',f'/projects/{PROJECT}?tab=billing&billingStep=people&lang=en'),
8: ('Owner/Finance → project → Billing → 3. Review each person; additional policies: Finance → Commercial Configuration',f'/projects/{PROJECT}?tab=billing&billingStep=people&lang=en'),
9: ('Owner → Projects → project → Team for memberships; then Crew → select project → Show project → Assign a crew chief',f'/crew?project={PROJECT}&lang=en'),
10: ('Worker → Time → Log time; crew chief → Crew → Log team hours','/time?lang=en'),
11: ('Owner/reviewer → Approvals → select project; then Finance review. Approved entries: Time → Filter time entries',f'/time?project={PROJECT}&from=2026-10-01&to=2026-10-04&status=approved&category=&worker=&lang=en'),
12: ('Worker → Expenses → Record expense; chief → Crew → shared receipt tools','/expenses?lang=en'),
13: ('Owner/Finance → Approvals → operational approval; Finance → expense classification; Approvals → Finance review',f'/expenses?project={PROJECT}&from=2026-10-01&to=2026-10-04&status=approved&lang=en'),
14: ('Worker → account/workspace navigation → My Pay → choose the period; Time and Expenses show that worker’s own records','/pay?start=2026-10-01&end=2026-10-04&lang=en'),
15: ('Owner/Finance → Billing → Configure billing → New billing stream; alternatively project → Billing → Configure this project’s invoices',f'/billing?view=setup&setup=stream&project={PROJECT}&lang=en'),
16: ('Owner/Finance → Billing → Create invoice → select training project and Labor · Manual','/billing?lang=en'),
17: ('Owner/Finance → Billing → Create invoice → select training project and Expense · Monthly','/billing?lang=en'),
18: ('Owner/Finance → Billing → Create invoice → select training project and Labor · Weekly','/billing?lang=en'),
19: ('Owner → Finance → Commercial Configuration → select project → Project issuing authority',f'/finance?view=commercial&project={PROJECT}&lang=en'),
20: ('Owner/Finance → Billing → Invoices → open the draft → Edit Invoice Details; then Download PDF · Preview','/billing?view=invoices&lang=en'),
21: ('Owner → Billing → Configure billing → Invoice numbering policy; then Billing → Invoices → open reviewed invoice','/billing?view=setup&setup=numbering&lang=en'),
22: ('Owner/Finance → the named workspace and saved source record; use its error-message links','/billing?lang=en'),
}

exec(compile((ROOT/'owner-operating-chapters.py').read_text(), '<owner-operating-chapters>', 'exec'))
build_owner_start()

for i,(title,body,image,caption) in enumerate(original):
    if i==0: continue
    path,url = routes[i]
    if i==2:
        body=steps('Click <strong>Projects</strong>. Click <strong>More actions</strong>, then <strong>New Client</strong>. The panel heading is <strong>Create client</strong>.','Fill the legal name, display name, currency and timezone. Fill billing address and either billing email or the required billing contact name. Set agreed payment terms and the PO/reference. Click <strong>Create client</strong>.','Click <strong>Projects → New Project</strong>. In <strong>1 · Basics</strong>, select the saved client. Fill the project name and cost center. Choose currency. Review the optional description, alias and manager.','Continue through <strong>2 · People</strong> and <strong>3 · Commercial defaults</strong> as explained on the following pages. Fill the start date and timezone, and select the applicable reporting/budget choices.','Click <strong>Create project</strong> once. Reopen the saved project, check its number and team, and use <strong>Edit project</strong> to review/update the PO and remaining project details.')+note('The BBS training project is already saved. The creation-form screenshots illustrate a draft form, not instructions to create a duplicate of it.')
    elif i==3:
        body=steps('Open the saved project and click its <strong>Billing</strong> tab. Expand <strong>Configure project defaults</strong> under <strong>Project defaults for people</strong>. Fill the effective date and default terms, then save.','Under <strong>Configure this project’s invoices</strong>, click the numbered <strong>3. Review each person</strong> step. This is project configuration, not the invoice-creation dialog.','In <strong>Person</strong>, choose the required worker and click <strong>Go to person</strong>. Fill that person’s dated charge, pay and expense agreement.','Click <strong>Save person terms</strong>. Wait for confirmation and reopen/reload to check persistence. Repeat for the other workers.','Use <strong>Copy draft terms from</strong> and the selection boxes only when people intentionally share terms. Review every selected person and effective date before <strong>Save selected people</strong>.')+note('Project defaults start new assignments; saved person agreements remain independent. “Use project defaults in this draft” fills fields but does not save them. Pin matching rates with “Save these rates as explicit person overrides” when they must stay independent of later defaults.')
    elif i==9:
        body=steps('Open <strong>Projects → BBS training project → Team</strong>. Assign the three active worker accounts with assignment dates covering the work. New workforce accounts must exist and be active before they can be chosen.','Click <strong>Crew</strong>. Select the BBS training project and work date, then click <strong>Show project</strong>. Owner sees <strong>Assign a crew chief</strong>.','Select <strong>Chief</strong> and one <strong>Team member</strong>. Fill <strong>Effective from</strong> and optional <strong>Effective until</strong>. Click <strong>Assign chief</strong>. Repeat for the second team member.','The chief signs in to their own worker account and opens <strong>Crew</strong>. Select the project/date. Only delegated, assigned people are available.','Use <strong>Log team hours</strong>, choose members and shared or different hours. Fill category and <strong>Work performed</strong>. Choose draft or <strong>Submit for approval now</strong>, then click the save button showing the member count.')+note('Assignment grants project participation; chief delegation grants entry on behalf of named colleagues. Both must cover the work date. The chief records personal hours in Time and cannot approve their own crew submission simply by submitting it.')
    elif i==10:
        body=steps('As the worker, click <strong>Time</strong>, then the blue <strong>Log time</strong> button.','Choose <strong>Project</strong> and <strong>Date</strong>. Fill <strong>Actual hours</strong> in decimal form: 7.5 means seven hours thirty minutes. Select the actual work category and fill the activity summary.','If actual clocks are known, choose <strong>Add start and end times</strong> and enter the project-local start/end and real break. Keep duration-only work as duration-only when clocks were not recorded.','Click <strong>Save draft</strong>. Open the saved record from the register and click its available <strong>Submit</strong> action. To submit a complete reviewed week, use <strong>Submit all week drafts</strong>.','Check the saved record and calendar. Correct returned work through its permitted correction/edit flow; do not create another source to repeat an existing submission.')+note('Category describes actual work. It does not itself create overtime pay or customer premiums: those come from the dated commercial rules. Expected hours, actual hours, approved hours and billed units remain separate.')
    elif i==11:
        body=table(['Person','2 October','3 October','Actual total','Customer revenue'],[['Chief','8 h commissioning','2 h overtime','10 h','USD 800'],['Technician 1','8 h regular','3 h travel','11 h','USD 660'],['Technician 2','8 h regular','6 h travel','14 h','USD 770'],['Total','24 h','11 h','35 h','USD 2,230']])+steps('After submission, open <strong>Approvals</strong>, choose the training project and apply the filter. Review the operational source facts, then use <strong>Approve</strong> or the available changes/rejection action with a reason.','In the same workspace, scroll to <strong>Finance review</strong>. For approved time choose <strong>Commercial treatment: Billable</strong> or <strong>Non-billable</strong>, then click <strong>Record Finance review</strong>.','For an expense that says <strong>Classify this expense before Finance review</strong>, click <strong>Classify expense in Finance</strong>, save its treatment, return and record Finance review.','To inspect the example hours, open <strong>Time → Filter time entries</strong>, select the training project, dates 1–4 October, Approved, all workers and all categories, then click <strong>Apply filters</strong>.')+note('All six stage-1 records (35 hours) and all four expenses have both operational approval and Finance review saved. The screenshots show the six approved sources and the cleared Finance queue. “Approved” alone is the operational state, not proof that commercial review was completed.')
    elif i==12:
        body=steps('As a worker click <strong>Expenses → Record expense</strong>. Choose the assigned project and actual expense date.','Select the actual <strong>Category</strong>. Enter vendor and factual description; fill amount and currency. Select the actual payer/payment method, and attach a receipt where required.','Choose <strong>Save draft</strong>, inspect the saved entry, then use <strong>Submit</strong>. Where the app pairs an expense with time, follow its notice and submit the pair through the weekly time workflow.','Examples: parking USD 20 paid by the chief; hotel USD 100 paid by technician 1; company-card tools USD 50 for technician 2.','For a shared crew meal, record one USD 60 receipt and two USD 30 allocations linked to the two technicians. Attach its evidence and submit through the supported crew workflow.')+note('One shared purchase remains one financial source. Do not add separate USD 30 expense rows after allocating the USD 60 receipt. Operational evidence and commercial reimbursement/customer recovery are separate steps.')
    elif i==15:
        body=steps('Click <strong>Billing</strong>. Click <strong>Configure billing</strong>, then <strong>New billing stream</strong>. The form appears below the three setup directories; scroll down if it is offscreen.','Select <strong>Project</strong>. Review the prefilled currency, PO, terms and billing recipient/contact rather than typing them from memory.','Choose the stream type and cadence. Fill <strong>Effective from</strong> and any required anchor. Choose issuer, tax and template deliberately.','Review recipient, payment terms, PO override and automation. Click the form’s save/create button once and wait for confirmation.','Open <strong>Billing streams</strong> and review the saved dated rule. The BBS examples use a Manual labor period for 1–4 October, a Weekly labor stream from 5 October and Monthly expenses.')+note('Creating a stream configures how invoices are prepared; it creates no time, expense, invoice, payment or email. Cadence belongs to the project stream. Each worker’s hourly/daily/weekly rate unit is configured separately in person terms.')
    elif i in (16,17,18):
        body=body.replace('Create invoice draft','Create invoice').replace('Prepare and open the draft','Click <strong>Save invoice draft</strong> and open the saved draft').replace('prepare the draft','save the draft').replace('Prepare the draft','Save the draft')
    elif i==20:
        body=steps('Click <strong>Billing → Invoices</strong> and open the saved Draft. Review its preview and calculated totals.','Click an underlined editable presentation field or <strong>Edit Invoice Details</strong>. Fill only the intended date, terms, Purchase No. or text/contact/bank fields.','Click <strong>Save Details</strong> and wait for confirmation. Reload the draft and compare the saved values before downloading.','Click <strong>Download PDF · Preview</strong>. Open the downloaded file and check customer, issuer, PO, period, quantity units, subtotal, tax and total.','Change hours/rates/expenses through their source or commercial correction workflows, review approvals and use the permitted draft refresh/recalculation path. Invoice presentation edits do not replace those financial workflows.')+note('This page teaches the review stage. Preview marks indicate an unissued document. Complete the numbered approval and issue procedure later in this guide to obtain a final invoice. The final application-issued PDF files are appended unchanged at the end.')
    elif i==21:
        body=steps('Before a real issue, Owner clicks <strong>Billing → Configure billing → Invoice numbering policy</strong>. Configure the approved business prefix/sequence and issuer/currency scope; review the real form’s required values. For real issuance obtain actual accountant approval. The later training chapter gives an explicitly synthetic example and a proposed real policy for review.','Open the reviewed draft in <strong>Billing → Invoices</strong>. Resolve the invoice’s readiness messages, including approvals, issuer/tax dates and any customer sign-off. Use the authorized approval action.','Use the available <strong>Issue</strong> action only after those prerequisites are met. Issue assigns the final number and preserves the financial snapshot. Wait for final PDF generation to become ready.','Review billing recipient/contact and the final PDF. Use the permitted invoice sending action or download the final PDF for the company’s approved delivery process. Customer expense invoices follow this same lifecycle.','After an actual receipt, record collection separately and reconcile unpaid/partly paid/paid balances. Sending or downloading is not collection.','Use void/credit/adjustment/replacement procedures for an issued-document correction; never overwrite its historical financial truth.')+note('Continue with the detailed Final invoice issuance chapter for the complete tested training flow, numbering provenance and exact buttons. Final files in the annex come from the isolated environment; do not copy synthetic approval evidence into a real invoice policy.')

    page('chapter-'+str(i), title, route(path,url)+body, toc=True)

    if i==1:
        page('project-prerequisites','Before creating the project',table(['Prerequisite','What the Owner must do'],[['Account','Sign in as Owner; Finance has only its permitted administration scope.'],['Client','Create/select the customer with correct currency, contact/email and billing address.'],['Workforce','Create/activate real worker accounts before assigning them. Example accounts are fictional.'],['Agreement','Know customer charge, worker pay, internal cost, who pays expenses and who reimburses/recovers them.'],['Dates','Choose project start/timezone and assignment/term effective dates covering the work.'],['Billing policy','Know the contract’s invoice cadence, issuer and applicable taxes. These are reviewed again before invoices.']])+note('Start at the first unfinished step for an existing project. Do not create another project merely to edit its billing settings.'))
    elif i==2:
        page('client-fields','Client fields · what to enter',route('Projects → More actions → New Client → Create client','/projects?action=new-client&lang=en')+table(['Field','Meaning / action'],[['Legal name / Display name','Legal invoice customer identity versus the name shown in directories. Fill both as required.'],['Client code (optional)','Optional customer reference; do not reuse an existing code unintentionally.'],['Currency / Timezone','Customer currency and local context; project currency is selected independently when created.'],['Billing contact name / email','Fill a usable billing identity/recipient. The form requires a contact name if no billing email is provided.'],['Billing address','The customer’s billing destination shown on invoices.'],['Payment terms (days)','Agreed number of days from invoice date. Zero is a real value; review any suggested starting default.'],['PO / reference','Client-level purchase reference used when a selected project has no project-specific PO.'],['Notes','Optional internal context; it is not a payment or invoice.']])+steps('After filling the fields, click <strong>Create client</strong>. Select the saved client when creating the project.'))
        fig('project-basics-image','Create project · required and optional basics','29-create-project-basics.png','Projects → New Project → 1 · Basics. Choose the saved client, fill Name and Cost center code, then review Currency and the optional fields.')
        page('project-fields','Project fields · basics and dates',table(['Field','Meaning / action'],[['Client','Select the saved customer; it controls customer references, not a worker’s private compensation.'],['Name / Cost center code','Fill a readable project name and unique cost center ending in digits. The trailing digits determine the project-number suffix.'],['Description / Project alias','Optional context and alternate project label; these do not create work.'],['Currency','Select the contract currency. Rates, invoices and issuer must be compatible with it.'],['Project manager','Optional assigned manager; choose an available authorized manager or leave Unassigned.'],['Site timezone','Actual work/site timezone for date and clock interpretation. The saved BBS example uses America/New_York.'],['Start / Planned end date','Real start date and optional planning end; assignment and legal-authority dates are checked separately.']])+steps('Fill these fields before <strong>Create project</strong>. After saving, use <strong>Edit project</strong> for permitted project details such as the PO.'))
        page('commercial-project','Commercial defaults · models and hours',route('Projects → New Project → 3 · Commercial defaults','/projects?action=new-project&lang=en')+table(['Option','What it changes'],[['Time & materials','Customer work is charged by the configured dated source/person terms. The training example uses this model.'],['T&M · daily minimum','A configured hourly customer minimum can add a commercial top-up; it does not fabricate actual time or change worker pay.'],['Hourly labor with included expenses (all-in)','Eligible labor remains hourly and selected expenses are included in its price. Hour-based included-minute combinations require hourly customer rates.'],['Capped T&M','T&M with the agreed cap/budget constraints. Fill the appropriate contractual cap rather than treating it as a flat rate.'],['Expected hours / day','Planning/reference hours only, never actual or submitted time.'],['Client daily minimum hours','A separate hourly commercial minimum, not the Daily billing-unit rate or the worker’s compensation.']])+note('Customer daily/weekly full-unit agreements are saved per person. They are independent of the project’s planning hours and the invoice cadence.'))
        fig('commercial-image','Project commercial defaults','31-create-commercial.png','Select Billing model deliberately. Review Expected hours / day and the separate Client daily minimum hours field.')
        page('budget-fields','Budgets and reporting · optional controls',table(['Field','Meaning / action'],[['Budget type','No budget, Revenue, Purchase order, Labor, Travel, Expenses or Combined select the planning/contract limits to review.'],['Revenue budget / PO cap','Expected customer revenue or agreed purchase-order ceiling, in project currency.'],['Planned labor hours','Planning allowance; it does not create hours or approved compensation.'],['Expense / Travel budget','Planning cost allowances; they are not recorded expenses.'],['Weekly close required','Requires the configured weekly closure flow; review before submitting/closing periods.'],['Daily / Technical reporting required','Enable when the contract/workflow requires the corresponding reports. Required sign-off can affect final invoice readiness.']])+steps('Enter only the agreed budget amounts/hours. Leave optional budgets empty when they do not apply. Click <strong>Create project</strong> after reviewing all sections.'))
        fig('budget-image','Project budgets and report requirements','95-project-budgets-and-report-switches.png','3 · Commercial defaults: optional budgets and weekly/daily/technical reporting flags.')
        page('creation-people','Optional worker table during creation',route('Projects → New Project → 2 · People → Worker assignments (optional)','/projects?action=new-project&lang=en')+steps('Expand <strong>Project defaults for people (optional)</strong> if new assignments should start from common terms. Select the save-defaults checkbox and fill the dated agreement.','Expand <strong>Worker assignments (optional)</strong>. Click <strong>Add worker assignment</strong>. Select an active Worker; fill <strong>Starts on</strong> and optional <strong>Ends on</strong>.','Select <strong>Terms source: Use project defaults</strong> or <strong>Override for this person</strong>. For an override, fill customer billing unit/rate, internal cost, worker compensation and expense terms.','Add another row for each worker. <strong>Remove</strong> removes that unsaved row, not an existing worker account.','Click <strong>Create project</strong> only after reviewing the complete form. These illustrative screenshots do not save another BBS project.')+note('The illustrated chief has USD 80/h customer charge, USD 45/h internal cost and USD 40/h worker pay. Owner can save different values for the other people.'))
        fig('creation-assignment-image','Optional assignments · worker, dates and terms source','63-create-assignment-header.png','Choose Worker and assignment dates first. Choose Override for this person to reveal the individual fields. The toolbar is excluded from this new capture.')
        fig('creation-terms-image','Optional assignment · individual terms enlarged','59-create-assignment-terms.png','Individual charge, worker compensation and expense treatment in the creation form. Fill each value and review the selected payer; creating the project saves the configured rows.',wide=False)
    elif i==3:
        fig('find-person-image','Where to find Review each person','51-review-person-location.png','Project → Billing → Configure this project’s invoices → 3. Review each person. Use Person and Go to person; each worker has a separate Save person terms button.')
        page('dated-terms','Effective dates, overrides and bulk controls',table(['Control','Meaning / action'],[['Terms effective from','The date on which the new agreement applies. Keep earlier work/rates unchanged by choosing the intended later date.'],['Use project defaults in this draft','Copies current defaults into the draft only. Review and click Save person terms to apply.'],['Save these rates as explicit person overrides','Pins even matching rates as deliberate person agreements. Later project-default changes do not erase those overrides.'],['Select this person for bulk actions','Select only people who should receive the bulk draft.'],['Copy draft terms from / Apply to selected people','Copies draft terms; review every selected person and date before saving.'],['Save selected people','Saves the selected agreements after validation, not every unselected worker.'],['Same-date agreement warning','Existing terms on the same date are immutable; choose a later effective date rather than trying to overwrite them.']])+note('Approved invoices, locked sources or finalized settlements may block conflicting changes. A successful field edit alone is not proof of persistence; wait for save confirmation and reopen the saved context.'))
    elif i==4:
        fig('issuer-setup-image','Project billing · issuer, taxes, cadence and delivery','18-ja-default-issuer.png','2. Billing details. Review issuer/currency, tax, cadence, layout, grouping, recipient and terms before saving.')
        page('issuer-directories','Issuer settings and tax profiles',route('Billing → Configure billing → expand the setup directories','/billing?view=setup&lang=en')+table(['Owner option','Meaning / action'],[['Invoice issuers → New invoice issuer','Create the selling company’s identity/currency, address and identifiers. Select the correct issuer for the project.'],['Invoice issuers → Edit / Archive','Edit permitted identity fields or retire the issuer from active choices while preserving history.'],['Issuer payment and contact settings → Add / Edit','Fill the issuer’s payment instructions, bank and contact fields; save and reopen the directory to verify.'],['Clear payment and contact settings','Clears those fields through a confirmed action; it does not delete the issuer.'],['Tax profiles → New tax profile','Create the applicable currency/issuer, effective date and tax components/rates. Review tax applicability with the business policy.'],['Tax profile Edit / Archive','Rename an existing profile or archive it. A changed rate/date/currency requires a new profile explicitly selected for the relevant stream.']])+note('Issuer payment/contact settings are shared by streams using that issuer and currency. Be deliberate: a change can affect other unissued drafts. Issued invoice snapshots retain their historical values.'))
    elif i in (5,6,7):
        names={5:('52-chief-rates.png','53-chief-expenses.png'),6:('35-worker-daily-rates.png','36-worker-daily-expenses.png'),7:('54-weekly-rates.png','55-weekly-expenses.png')}
        a,b=names[i]
        fig('person-'+str(i)+'-rates','Person terms · customer charge, cost and worker pay',a,'Later agreement form: fill Terms effective from, customer billing unit/rate and independent worker method/rate. Before initial 2 October work, use the earlier agreements listed in Initial data sheet; this later screenshot is not initial-date coverage.')
        fig('person-'+str(i)+'-expenses','Person terms · reimbursement and customer expense recovery',b,'Choose Expense payer, reimbursement source, reimbursement and customer recovery. Save the selected payer’s policy; policies for other payers remain separate.')
    elif i==8:
        page('billing-unit-meaning','Customer unit and worker compensation · two decisions',table(['Customer billing unit','Calculation'],[['Hourly','Eligible approved billable duration × the dated hourly customer rate.'],['Daily','Full configured customer rate once for a person/project/worked day with eligible approved work. A partial day is still a full unit.'],['Weekly','Full configured customer rate once for a person/project/Monday–Sunday worked week with eligible approved work. A partial week is still a full unit.']])+table(['Worker compensation','Meaning'],[['Hourly / Daily','Worker’s own rate and applicable actual/approved-hour or daily rules. These are not the customer charge.'],['Fixed per billing period','Configured amount for the applicable compensation/settlement period; not another amount for each time part.'],['Fixed project amount','Project fixed agreement; review its settlement rather than multiplying it by hours.'],['Percentage of eligible client labor','Fill the percentage and choose the eligible labor basis: before tax, after approved discount, issued or collected eligible labor. Expenses/tax are not automatically part of that basis.']])+note('Customer unit, worker pay method and invoice cadence are independent. Two approved parts in one day/week do not charge the full customer unit twice, including attempts across invoice periods.'))
    elif i==9:
        fig('assign-chief-image','Owner · assigning the crew chief','46-assign-chief.png','Illustrative form: Crew → Show project → Assign a crew chief. The captured draft date is later than the first workday. Saved example delegations actually cover 1–31 October; use dates covering the work, including 2 October.')
        fig('chief-hours-image','Chief · shared or individual team hours','48-chief-team-hours.png','Select delegated members; choose Same hours for each selected member or Different hours for each member. Fill the actual hours and activity, then review draft/submission mode.',wide=False)
        fig('chief-receipt-image','Chief · one shared crew receipt','49-chief-shared-receipt.png','Record one purchase and allocate its total to the selected time records. USD 30 + USD 30 must equal the one USD 60 receipt.')
    elif i==10:
        fig('worker-time-image','Worker · Log time fields','47-worker-log-time.png','Time → Log time. Fill assigned Project, Date, actual duration/category and factual activity; use real clocks only when known.',wide=False)
    elif i==11:
        fig('approved-time-image','Stage 1 · six approved records, 35 hours','60-stage1-approved-35-hours.png','Dates 2–3 October: 8+8+8+2+3+6 = 35 actual hours. All six sources are Approved; their Finance review is also saved.',wide=False)
        fig('finance-complete-image','Finance review · completed queue','62-finance-review-cleared.png','Approvals → selected BBS training project → Finance review. After the saved reviews the app shows Finance queue clear. Commercial review follows operational approval.')
    elif i==12:
        page('expense-entry-fields','Expense-entry fields · amount and evidence',table(['Field','What to fill / why'],[['Project / Worker / Date','The assigned project, entitled worker and actual purchase date; Owner’s on-behalf entry remains scoped.'],['Category / Description / Vendor','Choose what was bought and explain the business reason and supplier.'],['Amount / Currency','Real purchase value and original currency. Foreign currency may need verified conversion before billing.'],['Expense payer / payment method','Identify who actually paid: worker, company card/direct, client or third party. This determines which dated payer policy is resolved.'],['Receipt / Receipt required','Attach the required evidence. Do not claim a receipt exists when it has not been uploaded.'],['Time expense occurred / Related logged hours','Optional occurrence detail or supported link to the related time source.'],['Save draft / Submit','Draft is editable working data; submission starts review. Neither action reimburses a worker or invoices the client.']])+note('The policy can reimburse a worker USD 100 and charge the customer USD 0. At-cost recovery, markup, included expense and worker reimbursement are different controls.'))
        fig('expense-source-image','Record expense · project, date and category','56-expense-source-fields.png','Expenses → Record expense. Start with the assigned project/date and the correct category.',wide=False)
        fig('expense-money-image','Record expense · amount, payer and evidence','57-expense-money-fields.png','Fill the actual amount/currency, payer/payment method and supporting evidence. These source facts are reviewed separately from customer recovery.',wide=False)
    elif i==13:
        fig('approved-expense-image','Stage 1 · the four approved expenses','61-four-approved-expenses.png','Parking, hotel, one shared meal and company-card tools. Their saved Finance classifications/reviews produce USD 182 customer recovery from USD 230 spent.',wide=False)
    elif i==14:
        pair('worker-pay-summary-image','Worker My Pay · amount and project period',['37-worker-pay-summary.png','38-worker-pay-project.png'],'Technician 2’s 1–4 October worker view: 840 approved minutes (14 h), USD 900 approved compensation and no reimbursement. The project row and amount are enlarged instead of shrinking an entire long page.')
        fig('worker-pay-activity-image','Worker My Pay · supporting activities','39-worker-pay-activity.png','The same worker period’s source activities support the fixed-period result. Worker views retain compensation privacy and do not expose customer rates or internal cost.')
    elif i==15:
        page('stream-prerequisites','Prerequisites · creating a billing stream',table(['Before clicking Create','What to verify'],[['Role / project','Owner or authorized Finance role; saved accessible project with compatible currency.'],['Client defaults','Billing identity/address, PO, terms, recipient/contact. Review missing or ambiguous values manually.'],['Issuer','Active compatible invoice issuer selected. Legal authority/dated revision must cover invoices generated later.'],['Tax','Applicable active tax profile(s), currency and effective dates, or an intentionally applicable no-tax/zero-rate arrangement.'],['Commercial agreement','Rates, source eligibility, expense treatment and cadence understood. A stream can be configured before actual work exists.'],['Effective date / anchor','Correct start; a two-week cycle needs its anchor. Review existing dated streams to avoid conflicting starts.'],['Template / automation','Deliberately choose presentation and any draft automation. Saving a stream is not issuing or sending an invoice.']])+note('Approved time/expenses are prerequisites for source-based invoice creation, not for merely saving a stream. Do not add fictitious time just to configure billing.'))
        page('stream-core-fields','New billing stream · project, sources and timing',table(['Field','Meaning / action'],[['Project','Choose the saved project first. The form fills saved currency/PO and available client delivery defaults.'],['Stream type','Labor, Expense, milestone/other sources as offered. Use separate Labor and Expense for this training arrangement.'],['Cadence','How invoice service periods are suggested/scheduled; it does not change a worker’s Hourly/Daily/Weekly rate unit.'],['Effective from','First date of this configuration. Prior dated history stays retained.'],['Anchor date','Defines the two-week/custom alignment when required; review the chosen cadence’s instructions.'],['Currency / Invoice issuer','Project currency and selected compatible selling company. Currency defaults; issuer remains a choice to verify.'],['Tax profile / Template','Applicable taxation and invoice presentation. A template does not create eligible source money.']])+steps('Select the project before reviewing the defaults. Scroll through the complete form; the final save button is below the delivery/automation fields.'))
        fig('stream-cadence-image','New billing stream · source and cadence controls','40-new-stream-cadence.png','Billing → Configure billing → New billing stream. Choose Project, stream, cadence, effective/anchor dates, issuer, tax and template.')
        page('stream-delivery-fields','New billing stream · delivery and defaults',table(['Field','Saved source / meaning'],[['Recipient email','Client billing email, otherwise the uniquely selected billing contact email; review before real sending.'],['Billing contact','Unique primary billing contact, otherwise sole client billing contact. Ambiguous choices remain for you to select.'],['Payment terms (days)','Valid saved client terms, including zero. If absent, the disclosed 30-day starting value is a value to review.'],['PO reference','Project PO, otherwise the client PO/reference. Editing it stores an intentional stream override.'],['Semi-monthly rule','Calendar split used for a semi-monthly period. Review the form’s rule, not an arbitrary 14-day cycle.'],['Automatic draft preparation','Optional job preparation of drafts. It does not automatically issue or email them.'],['Save/create action','Save once, wait for confirmation, then review Billing streams. A rejected form retains values for correction.']])+note('Changing Project deliberately clears incompatible prior values. Do not carry the previous project’s manual PO/contact/tax/issuer into another project by accident.'))
        fig('stream-delivery-image','New billing stream · recipient, PO, terms and automation','41-new-stream-delivery.png','Review Recipient email, Billing contact, Payment terms, PO reference and automatic draft preparation before saving.')
        page('cadence-options','Cadence options · which period do they mean?',table(['Cadence','Meaning / required choice'],[['Weekly','Weekly cycle; the BBS stage-2 example is 5–11 October.'],['Every 14 days','Two-week cycle aligned to the anchor date; different from two calendar halves per month.'],['Semi-monthly','1–15 and 16–month end, according to the selected rule.'],['Monthly','A calendar month; the expense example is 1–31 October.'],['Manual','You deliberately choose the invoice period; used for the initial 1–4 October labor example.'],['Custom / Milestone','Direct-form choices for applicable custom schedules or contractual milestone billing; configure the offered fields and source readiness.']])+note('One combined stream invoices labor and expenses together. Separate streams can use different cadence and taxes. In this app cadence is a project-stream configuration; individual customer rate units stay in person terms.'))
    elif i==16:
        page('invoice-prerequisites','Prerequisites · creating an invoice draft',table(['Requirement','What to check and where'],[['Project / stream','Billing → Billing streams: active dated stream, compatible project/currency and intended period.'],['Assignments / person terms','Project → Team and Billing → Review each person: membership and dated customer/pay/expense terms cover the source dates.'],['Source approval','Time/Expenses → submit; Approvals → operational approval, then Finance review/billability.'],['Expense classification','Finance → review/classify payer, recovery, reimbursement and any required evidence/FX. Only eligible customer charges enter the expense invoice.'],['Issuer authority / tax','Finance → Commercial Configuration → Project issuing authority; compatible issuer revision covers the entire invoice period. Review tax-profile validity.'],['Source availability','Included and Excluded / pending: sources or full day/week units already covered cannot be billed again.'],['Final-issue requirements','Customer sign-off when required and approved numbering/issue readiness can still block issue even when a reviewable draft PDF exists.']])+note('A zero-source/zero-charge warning requires checking the period, approvals, terms and prior invoice reservations. Creating a stream or planning hours never satisfies the source prerequisites.'))
        page('invoice-wizard','Create invoice · every review step',route('Billing → Create invoice','/billing?lang=en')+steps('In <strong>1 Client / project</strong>, choose the project and stream in <strong>Project and billing stream</strong>. Click <strong>Next</strong>; review <strong>2 Billing stream</strong> and <strong>3 Labor / expenses</strong>.','At <strong>4 Period</strong>, fill <strong>Period start</strong> and <strong>Period end</strong>. Click <strong>Check selected period</strong>, then <strong>Next</strong>. Suggested dates come from cadence; a manual change is deliberate.','Review <strong>5 Included records</strong> and <strong>6 Excluded / pending</strong>. Follow links to resolve missing approvals, terms, locked sources or coverage; do not duplicate the sources.','Review <strong>7 Taxes</strong>, <strong>8 Invoice data</strong> and <strong>9 Banking / payment</strong>: identity, PO, dates, terms, recipient and payment instructions.','Review <strong>10 Commercial adjustments</strong> using the approved workflow, then <strong>11 Preview</strong>. Check amounts and unit labels.','At <strong>12 Save / issue</strong>, click <strong>Save invoice draft</strong>. Wait for success and open the saved Draft in <strong>Invoices</strong>.')+note('Use Previous/Next or the numbered stage buttons to revisit a review. Save invoice draft builds the snapshot; it does not issue, number, email or collect it.'))
        fig('invoice-project-image','Create invoice · project/stream and review stages','lab-correct-labor-wizard.png','Corrected capture: the original BBS Labor · Manual stream is selected, matching the initial labor example. The twelve stages identify what to review; this read-only capture did not create another invoice.',wide=False)
        fig('invoice-period-image','Create invoice · service-period dates','43-invoice-period.png','Fill Period start and Period end. Click Check selected period and Next. Service period is separate from invoice date and due date.',wide=False)
        fig('labor-lines-image','Labor draft · six sources, USD 2,230','22-labor-lines.png','Stage 1: 35 hours billed at the dated customer rates. Appendix A contains the later final issued PDF with the same sources and total.')
    elif i==17:
        fig('expense-lines-image','Customer expense draft · USD 182','23-expense-lines.png','Three customer charges from four source expenses: USD 22 parking + USD 100 hotel + USD 60 shared meal. Appendix B contains the later final issued PDF with the same expense lines.')
    elif i==18:
        fig('mixed-lines-image','Labor draft · hours, full day and full week','24-mixed-lines.png','Two hours × USD 80 + one day × USD 600 + one week × USD 1,500 = USD 2,260. Additional covered parts are not another full-unit charge. Appendix C contains the later final issued PDF with the same grouped quantities and total.')
    elif i==20:
        page('invoice-edit-fields','Invoice detail edits · where each value is saved',table(['Edited field','Meaning / save scope'],[['Invoice date / Due date','Date for this draft. An empty explicit due date uses invoice date plus payment terms.'],['Payment terms / past-due notice','Current draft and its underlying stream. Review the effect on future draft defaults.'],['Purchase No. / PO','Existing stream PO override, or project PO when there is no stream override. Check the project/stream after an intended change.'],['Bank / company contact fields','Shared issuer settings for that currency. They can affect other unissued drafts using the issuer.'],['Hours / rates / expenses / tax / totals','Financial source/calculation workflows, not a cosmetic amount override in presentation fields.'],['Save Details / PDF Preview','Save first, wait for confirmation and reload. Download the PDF after verifying the saved preview.']])+note('If a version/source conflict appears, retain entered values, reconcile the latest saved context and use the offered recovery links. Issued invoices keep historical snapshots.'))
        fig('invoice-dates-image','Draft details · saved invoice and due dates','44-edit-draft-dates.png','Open the saved draft, choose the editable detail field or Edit Invoice Details, and Save Details. Date changes belong to this draft.')
        fig('pdf-button-image','Download the actual draft PDF','27-pdf-download.png','Click Download PDF · Preview after reviewing the saved draft. This screenshot illustrates the preview stage. The three FINAL issued application downloads, obtained after approval and issue in isolated training, are appended unmodified and embedded as attachments.')

build_owner_cycle()

exec(compile((ROOT/'worker-and-export-chapters.py').read_text(), '<worker-spreadsheet-additions>', 'exec'))

exec(compile((ROOT/'evidence-chapters.py').read_text(), '<evidence-chapters>', 'exec'))
build_evidence_chapters()

page('appendices','Final issued invoice PDFs · original downloads', '<p>The following six pages reproduce the three original two-page FINAL application downloads. Each has a final invoice number and no preview watermark. The files were produced by the genuine approval/issue workflow in an isolated training database.</p>'+table(['Appendix','Final invoice number / example','Total'],[['A','JA-DEMO--2026-000001 · 1–4 October labor','USD 2,230'],['B','JA-DEMO--2026-000002 · October customer expenses','USD 182'],['C','JA-DEMO--2026-000003 · 5–11 October hour/day/week labor','USD 2,260']])+note('These are confirmed training invoices, not invoices sent to a real customer. The synthetic training approval timestamp is not evidence of an accountant approving a production policy. The original PDFs are appended without altering their invoice state, number, amounts or bank fields. The native double separator reflects the stored JA-DEMO- prefix; the numbering chapter uses neutral illustrative values and requires genuine company approval in live use.')+'<p>Save exact files from the PDF Attachments panel or from the adjacent bbs-example-artifacts directory in the repository. The final pages retain their native pagination and payment instructions. Compare the final number, service period, quantity units and totals with the worked examples.</p>',toc=True)

exec(compile((ROOT/'editorial-chapters.py').read_text(), '<editorial-chapters>', 'exec'))
build_editorial_chapters()
exec(compile((ROOT/'financial-completion-chapters.py').read_text(), '<financial-completion-chapters>', 'exec'))
build_financial_completion()
order_course()
exec(compile((ROOT/'readiness-chapters.py').read_text(), '<readiness-revision>', 'exec'))
apply_readiness_revision()

guide_count = len(pages)
index = {p['key']:n for n,p in enumerate(pages,1)}
entries = [(p['title'],index[p['key']],p['key']) for p in pages if p['toc']]
extra = [('Project, client and budget field reference',index['client-fields'],'client-fields'),('Optional worker table during project creation',index['creation-people'],'creation-people'),('Customer hourly/daily/weekly unit meanings',index['billing-unit-meaning'],'billing-unit-meaning'),('Billing stream prerequisites',index['stream-prerequisites'],'stream-prerequisites'),('Stream field meanings and defaults',index['stream-core-fields'],'stream-core-fields'),('Invoice prerequisites and 12 review stages',index['invoice-prerequisites'],'invoice-prerequisites'),('Invoice edit/save scope',index['invoice-edit-fields'],'invoice-edit-fields')]
entries.extend(extra)
entries.sort(key=lambda x:x[1])
entries.extend([('Appendix A · Actual labor PDF',guide_count+1,'native-a'),('Appendix B · Actual expense PDF',guide_count+3,'native-b'),('Appendix C · Actual hour/day/week PDF',guide_count+5,'native-c')])
chunk=(len(entries)+3)//4
for idx,part in enumerate([entries[:chunk],entries[chunk:2*chunk],entries[2*chunk:3*chunk],entries[3*chunk:]],1):
    p=pages[index['contents-'+str(idx)]-1]
    p['body']='<p>Click a chapter link where supported, or go to its printed page number. Large screenshot pages follow their instructions.</p><div class="toc">'+''.join('<div><a href="#'+key+'">'+html.escape(title)+'</a><strong>'+str(num)+'</strong></div>' for title,num,key in part)+'</div>'

css='''@page{size:A4;margin:16mm 15mm 15mm}@page wide{size:A4 landscape;margin:12mm 14mm}*{box-sizing:border-box}body{font:16px/1.48 Arial,sans-serif;color:#182b40;margin:0}.page{width:180mm;height:260mm;break-after:page;position:relative;padding-bottom:10mm}.page.wide{page:wide;width:269mm;height:182mm}.page:last-child{break-after:avoid}.tag{font-size:11px;letter-spacing:.7px;text-transform:uppercase;color:#516c83;margin:0 0 9px}h1{font-size:27px;line-height:1.18;color:#163e64;margin:0 0 13px;border-bottom:3px solid #287cc1;padding-bottom:9px}p{margin:11px 0}.lead{font-size:23px;line-height:1.3}ol{padding-left:25px;margin:12px 0}li{margin-bottom:10px}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.4;margin:12px 0}td,th{border:1px solid #d6e1eb;padding:8px 9px;text-align:left;vertical-align:top}th{background:#eef5fb;color:#173f63}aside,.route{background:#edf5fc;border-left:4px solid #287cc1;padding:10px 12px;margin:13px 0;font-size:14px;line-height:1.45}.route{background:#f7fafc;border-color:#7296b5}a{color:#145986;text-decoration:none}.content{max-height:237mm}.wide h1{font-size:21px;margin-bottom:8px;padding-bottom:7px}.wide .tag{font-size:10px;margin-bottom:5px}.figure-page figure{margin:8px 0 0;height:222mm;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:10px}.figure-page.wide figure{height:157mm}.figure-page img{display:block;max-width:100%;max-height:207mm;width:auto;height:auto;object-fit:contain;border:1px solid #d9e3ec}.figure-page.wide img{max-height:142mm}.figure-page figcaption{font-size:13px;line-height:1.4;color:#3b5267;width:100%;text-align:left}.pair img{max-height:67mm!important}.toc>div{display:flex;align-items:baseline;justify-content:space-between;gap:18px;border-bottom:1px solid #e1e8ef;padding:6px 0;font-size:14px}.toc a{flex:1}.footer{position:absolute;bottom:0;left:0;right:0;display:flex;justify-content:space-between;border-top:1px solid #d4e0eb;padding-top:5px;font-size:10px;color:#586e81}'''
output='<!doctype html><html lang="en"><head><meta charset="utf-8"><title>BBS · Owner operating reference and final invoice lab</title><style>'+css+'</style></head><body>'
for num,p in enumerate(pages,1):
    classes='page'+(' wide' if p['wide'] else '')+(' figure-page' if p['figure'] else '')
    output+='<section class="'+classes+'" id="'+p['key']+'"><div class="tag">J&amp;A · '+html.escape(p['context'])+'</div><h1>'+html.escape(p['title'])+'</h1><div class="content">'+p['body']+'</div><footer class="footer"><span>Fictional examples · English · 5 October 2026</span><span>'+str(num)+' / '+str(guide_count+6)+'</span></footer></section>'
output+='</body></html>'
(DOCS/(NAME+'.html')).write_text(output)

meta={'guidePages':guide_count,'totalPages':guide_count+6,'contents':entries,'pages':[{k:v for k,v in p.items() if k!='body'} for p in pages]}
(DOCS/'bbs-manual-layout.json').write_text(json.dumps(meta,indent=2)+'\n')
used_figures = sorted({Path(m).name for p in pages for m in __import__('re').findall(r'src="([^"]+)"', p['body'])})
manifest={'capturedOn':'2026-10-05','environments':['Saved fictional BBS operational example and pre-issue production read-only captures','Isolated local training database for issue, payment, reversal, account, correction and reporting browser exercises'],'project':'C-0050-P-20261005','interfaceLanguage':'English','fictionalData':True,'screenshots':'Original browser pixels; cropped at capture to show relevant controls and avoid unrelated private records. Screenshot captions distinguish initial and isolated lifecycle states.','workbookPreviews':'Original pre-issue XLSX values and formats rendered in a read-only browser viewer; not Microsoft Excel. Original files embedded without cell editing. A separate after-lifecycle XLSX snapshot is labeled separately when present.','paymentTest':'Initial production example settlements unpaid; isolated simulated payment/reversal and reimbursement events demonstrate application bookkeeping. No real bank transfer or customer email.','nativePDFs':'Three native FINAL issued training downloads, appended unchanged and embedded as attachments. No preview-watermark removal.','accountantApproval':'Synthetic training timestamp is fixture data; no genuine accountant approval is asserted.','correctedInvoiceWizard':{'project':'C-0050-P-20261005','streamType':'Labor','cadence':'Manual','selectedStreamId':'01a10c63-bd67-746f-bcbe-7d3ddb17cc0b','readOnlyCapture':True,'newInvoiceCreated':False},'figures':[{'name':name,'sha256':hashlib.sha256((FIG/name).read_bytes()).hexdigest()} for name in used_figures]}
manifest.update({
    'environments': [
        'Original BBS pre-issue: historical fictional operational example and production read-only captures',
        'Isolated BBS lifecycle: copied original sources, canonical issued masters and simulated ledgers/private document exercises',
        'Separate onboarding lab: C-0050-P-20261006 entry/report/planning and C-0050-P-050901 supplier/empty-project lifecycle',
        'New Accounting demo: separate all-synthetic portfolio/C-0002-P-002 for financial exceptions and separate August/October Accounting snapshots',
    ],
    'operatorTrainingAccessSupplied': False,
    'livePortalLinks': 'Visibly labelled Live company portal; never enter the isolated simulation',
    'practicePrerequisites': 'Operator-provisioned URL, own training account, visible deployment identity, authorized fictional scope and reset procedure',
    'signoffTest': 'Marked synthetic v2 acceptance, invalidation and replacement v3; genuine customer acceptance not asserted; optional fixture was not_scanned',
    'accountingTest': 'Separate synthetic October native five-format generation/download/review/final pass with zero review counts, cross-month evidence links and void-date cut verified; historical August advisories and original BBS October issuer coverage failure remain distinct',
})
(FIG/'capture-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
(DOCS/(NAME+'.md')).write_text('# BBS · Owner operating reference and final invoice lab\n\n'+str(guide_count+6)+'-page illustrated English guide with numbered contents, explicit role handoffs, setup prerequisites, correction/reporting procedures, final invoice lifecycle, worker settlements, and landscape previews of hours, expenses, costs, revenue and cash workbook ranges.\n\n- [PDF]('+NAME+'.pdf)\n- [Printable HTML]('+NAME+'.html)\n- [Capture provenance](bbs-illustrated-en-v2/capture-manifest.json)\n- [Build and verification](../../scripts/bbs-owner-manual/README.md)\n\nTraining project `C-0050-P-20261005` is separate from original BBS and Junkers. Preserve the worked calculations: Stage 1 is 35 approved hours and USD 2,230 labor; customer expense recovery is USD 182 from USD 230 spent; Stage 2 is 7.5 actual hours billed in hourly/daily/weekly units for USD 2,260. The six final annex pages and embedded originals are genuinely application-issued **training** invoices `JA-DEMO--2026-000001`, `000002`, `000003`, produced in isolation and appended without modifying their state, totals or contents.\n\nProduction financial history is unchanged by isolated issue/payment tests. Synthetic training approval timestamps are not real accountant approval. Payment, collection and reimbursement demonstrations are simulated ledger entries, not bank transfers; no customer email was sent. Three original XLSX files are attached: two pre-issue baseline examples and one separately labeled after-lifecycle snapshot. The guide distinguishes browser-tested workflows from source-checked references and untested external processes; it does not claim universal Owner-function validation.\n')
print(json.dumps({'guidePages':guide_count,'totalPages':guide_count+6,'figures':len(manifest['figures']),'contentsEntries':len(entries)}))
with (DOCS/(NAME+'.md')).open('a') as markdown:
    markdown.write('\n---\n\n## Operating course\n\nThe following chapters mirror the printable HTML. Figure paths point to the original browser captures beside this file.\n\n')
    for p in pages:
        markdown.write('<a id="'+p['key']+'"></a>\n\n## '+p['title']+'\n\n**Context: '+p['context']+'**\n\n'+p['body']+'\n\n')
    markdown.write('## Native final invoice originals\n\n- [Final labor invoice](bbs-example-artifacts/BBS-DEMO-labor-issued-en.pdf)\n- [Final expense invoice](bbs-example-artifacts/BBS-DEMO-expense-issued-en.pdf)\n- [Final mixed-unit invoice](bbs-example-artifacts/BBS-DEMO-mixed-issued-en.pdf)\n')
