"""Course ordering, explicit environments and bounded reference procedures."""
import re

def revise(key, title=None, body=None):
    item = next(p for p in pages if p['key'] == key)
    if title is not None: item['title'] = title
    if body is not None: item['body'] = body
    return item

def build_editorial_chapters():
    revise('owner-first-access')['body']=revise('owner-first-access')['body'].replace('Two environments appear in the evidence. Initial BBS operational records and pre-issue exports were inspected in the saved fictional project. Issue, payment, reversal and onboarding exercises use a separate local training database.', 'The next page names four evidence contexts: the original BBS pre-issue snapshot, its isolated lifecycle, the separate onboarding lab and a new synthetic Accounting portfolio. The live company application is separate from these training exercises.')
    page('before-practising','Before practising · obtain a separate training environment',
        note('<strong>BEFORE PRACTISING:</strong> No shared Owner-accessible training URL or account is supplied by this manual. Every link labelled <strong>Live company portal</strong> opens the company application; it never enters a simulation. Do not enter test payments, signatures, accounts or synthetic approval dates there.')
        +steps('Ask the platform operator for a separately provisioned training URL and your own authorized training account.',
            'Obtain a visible deployment/environment identifier, the permitted fictional project/date scope and the agreed reset or cleanup procedure. Verify these before any write.',
            'If that environment is unavailable, read the isolated demonstrations without repeating their transactions. Inspect live records only within your existing authority; use genuine evidence for live actions.',
            'Do not use another person’s credentials. Training credentials and the operator’s local test address are deliberately not published here.')
        +table(['Page context label','How to read the example'],[
            ['Original BBS pre-issue','Saved fictional original sources and historical pre-issue snapshots. Drafts/unpaid values describe that capture time.'],
            ['Isolated BBS lifecycle','The copied original BBS sources, issued masters and simulated receipt/payment/reimbursement events. Read-only demonstration unless training is provisioned.'],
            ['Separate onboarding lab','Fictional C-0050-P-20261006 for entry/reports/planning; C-0050-P-050901 for supplier/empty-project lifecycle. These are outside original BBS exports.'],
            ['New Accounting demo','Separate synthetic portfolio and C-0002-P-002 financial/weekly examples, including separately preserved August and October Accounting snapshots. They do not replace original BBS outputs.'],
            ['Reference procedure','Inspected controls/source logic or arithmetic; a browser pass is stated only for the explicitly tested action.'],
        ]),toc=True)
    revise('chapter-1',title='Understand the operating cycle')
    revise('collections-procedure')['body']=revise('collections-procedure')['body'].replace('In its collection form enter the <strong>Amount</strong>, <strong>Payment date</strong>, required reference from the actual receipt.', 'In <strong>Record payment</strong>, enter <strong>Amount</strong>, <strong>Received on</strong> and <strong>Reference</strong>; verify readonly <strong>Currency</strong> against the actual receipt.')
    revise('correction-states')['body']=revise('correction-states')['body'].replace('void/credit/adjustment/replacement flow', 'void or linked Credit/Debit/Correction adjustment flow')
    old=revise('chapter-22')
    old['title']='Pre-issue checkpoint and troubleshooting'
    old['body']=old['body'].replace('Completed example:', 'Original BBS pre-issue checkpoint:').replace('No invoice was issued/sent and no payment was recorded.', 'At this captured checkpoint no invoice was issued/sent and no payment was recorded. Later isolated lifecycle pages show the subsequently issued and simulated paid states.')
    revise('overtime-reference','Configure overtime · separate customer, worker and cost rules',
        route('Finance → Commercial Configuration → project → Finance configuration → Commercial policies',f'/finance?view=commercial&project={PROJECT}&lang=en')
        +steps('Inspect the work categories and agreed dated terms. If the contract derives overtime after a threshold, select <strong>Project commercial policy</strong> and review <strong>Derive overtime after the threshold</strong> and <strong>Overtime threshold (minutes)</strong>. Do not invent a threshold to manipulate recorded work.',
            'Select <strong>Client labor rate</strong>: review <strong>Overtime method</strong> and <strong>Overtime multiplier</strong>. Separately select <strong>Worker compensation</strong>: <strong>Worker overtime method</strong> and <strong>Worker overtime multiplier</strong>. Separately select <strong>Internal loaded cost</strong>: its overtime method/multiplier.',
            'Enter approved dated terms. Multiplier fields use human multipliers such as <strong>1.50</strong>. Offered methods include None, Fixed rate and Fixed addition per hour; worker compensation also offers Percentage of eligible overtime.',
            'Review eligible approved Labor source amounts for the same worker/date/category. Confirm actual time, charge, compensation and internal cost independently.')
        +table(['Reference calculation: two eligible overtime hours','Amount'],[
            ['Customer USD 100/h × 1.50 × 2 h','USD 300'],['Worker USD 40/h × 1.25 × 2 h','USD 100'],['Internal cost USD 50/h × 1.20 × 2 h','USD 120'],
        ])+note('Reference arithmetic, not a BBS browser exercise. In original BBS, the chief’s two overtime-category hours still use customer USD 80/h and worker USD 40/h. Selecting Overtime does not itself create a premium.'))
    revise('worker-trigger-limits','Percentage compensation · precise basis and trigger',
        route('Commercial Configuration → project → Finance configuration → Commercial policies: Worker compensation',f'/finance?view=commercial&project={PROJECT}&lang=en')
        +steps('Select <strong>Worker compensation</strong>, the worker and <strong>Rule type: Percentage of eligible client labor</strong>. Fill <strong>Percentage</strong>, <strong>Percentage basis</strong>, <strong>Settlement trigger</strong> and effective dates.',
            'Choose the exact basis: <strong>Client labor before tax</strong>, <strong>Client labor after approved discount</strong>, <strong>Issued eligible labor</strong> or <strong>Collected eligible labor</strong>. Check that the relevant client labor rate is percentage-eligible.',
            'Choose the trigger: <strong>Approved billable labor</strong>, <strong>Invoice issue</strong> or <strong>Client payment</strong>. Inspect actual source eligibility and allocations before finalizing a settlement; a dropdown selection does not prove the trigger has occurred.',
            'Review the finalized basis, reviewed amount, payee and period before registering a real payment.')
        +table(['Reference calculation','Conditional result'],[['25% of USD 1,000 issued eligible labor','USD 250 when the issue/basis conditions are met.'],['25% of USD 400 collected eligible labor','USD 100 when eligible collection allocations support it.']])
        +note('Reference arithmetic/source-checked controls, not a tested BBS percentage transition. Tax, expenses, discounts and noneligible categories are not automatically included. This is a compensation eligibility mechanism, not an automatic payroll cadence.'))
    page('alternative-contracts','Daily minimum, caps and forecast · reference exercises',
        table(['Contract / exact distinction','Configure, verify and recover'],[
            ['Hourly customer daily minimum','Project Client daily minimum hours is separate from Daily full-unit billing. Example: actual 2 h, minimum 8 h, customer USD 100/h → USD 800; worker USD 40 per actual hour → USD 80 unless a separate worker guarantee applies. Keep actual time at 2 h. Review Daily minimum adjustments and grouped sources.'],
            ['Cap / purchase order','Inspect the saved PO cap/revenue budget, currency, Billing readiness and remaining cap. Verify which issued subtotal/period counts. A budget warning is not proof of contractual cap compliance or permission to issue more.'],
            ['All-in price','Customer included expense recovery can be zero while a worker remains reimbursable. Inspect actual payer, compensation and company costs independently.'],
            ['Milestone','The Milestone stream uses approved unbilled project milestone sources. Check source amount, dates, issuer/tax and stream before draft/issue. Empty BBS Milestones is not a successful milestone exercise.'],
            ['Forecast','Compare estimate-to-complete, estimate-at-completion cost and expected final margin to the approved actual basis. A revised forecast creates no actual hours, payroll payment or customer receipt.'],
        ])+note('These representative calculations and procedures are reference material. They are not additional BBS browser transactions.'),toc=True)
    page('foreign-currency-remedy','Foreign-currency expense · supported escalation',
        route('Expenses → expense detail → Project-currency amount → Review expense classification','/expenses?lang=en')
        +steps('Keep the original purchase amount, currency, receipt and actual payer unchanged.',
            'When the detail says <strong>Verified currency conversion needed</strong>, open <strong>Review expense classification</strong> and read the readiness message. The current screen explicitly states that a conversion cannot be entered there.',
            'Use <strong>Help → Contact support</strong> (admin@j-aautomation.com). Supply expense/project ID, original currency/amount, exact warning and genuine rate evidence. Ask for the supported verified conversion/history procedure.',
            'After that supported process completes, reopen the expense and check the project-currency amount and Finance readiness before billing.')
        +note('Source-checked reference. No self-service conversion form is demonstrated. Overwriting original currency/amount or pretending the purchase used project currency would lose the source facts.'),toc=True)
    revise('planning-owner-time','Owner weekly entry · actual hours and layout copy',
        route('Time → Enter a week in a table','/time?lang=en')
        +steps('Select Worker, Assigned project and Week of; click <strong>Open week</strong>. Review existing drafts and dated assignments before entering actual Hours, Category and Activity summary.',
            'Leave unworked days empty. Review the actual entries and click <strong>Save daily drafts</strong> once. Blank days are skipped; inspect the saved register, not only filled input fields.',
            'When ready, use <strong>Submit this week</strong>, select the Worker and click <strong>Submit all week drafts</strong>. Linked corrections require their individual Submit action.',
            'Select the destination <strong>Week of</strong>, then <strong>Copy previous week layout</strong>. Review the displayed <strong>Previous week</strong> and <strong>This week</strong>, then <strong>Add this week’s layout</strong>. Newly added drafts have <strong>zero hours</strong>; fill actual durations before submission. There are no editable Source/Destination date fields in this dialog.',
            'If no rows were added, inspect existing drafts and assignment coverage instead of repeatedly copying.')
        +note('Separate onboarding lab browser: Friday 8 h + Saturday 1.5 h saved/submitted as 9.5 h. Later linked corrections preserve those originals and replace their eligible durations. Layout-copy zero-hour behavior is source-checked reference.'))
    # The former “after” screenshot is still an input form, not a saved register.
    pages[:]=[p for p in pages if p['key']!='lab-week-result-image']
    fig('lab-week-register-image','Saved original time and linked corrections · current register','lab-corrected-saved-time-register.png','Separate onboarding lab, Browser onboarding worker: original 8 h and 1.5 h sources remain Needs changes, linked replacements 6 h and 1 h are Approved. The original submission was 9.5 h; the current approved replacement total is 7 h. Do not add both originals and replacements.',wide=False)
    revise('lab-daily-form-image')['body']='<figure><img src="bbs-illustrated-en-v2/lab-daily-report-top-fields.png"><figcaption>Separate onboarding lab, New technician worker: actual Project, Work date, Worker, Shift summary and Tasks completed controls. This read-only filled form was not saved again; the earlier separate Daily report submission/approval is shown next.</figcaption></figure>'
    revise('lab-issued-ready-image','Issued unpaid labor invoice · final Ready PDF')['body']='<figure><img src="bbs-illustrated-en-v2/lab-issued-unpaid-invoice-heading.png"><figcaption>Isolated original BBS labor invoice, USD 2,230: Issued and unpaid, Invoice · PDF Ready, Open PDF and Download PDF. This is the issuance checkpoint. Later Paid expense and partially paid mixed-labor examples belong to collection, not this step. The final native master is unchanged.</figcaption></figure>'
    revise('signoff-evidence')['body']=revise('signoff-evidence')['body'].replace('Customer acceptance remains pending: no signed copy was supplied and no signature was fabricated.', 'Genuine customer acceptance remains pending. The initial Ready checkpoint supplied no signed copy; the later explicitly synthetic acceptance/invalidation exercise demonstrates the application state changes without claiming a real signature.')
    revise('lab-signoff-ready-image')['body']=revise('lab-signoff-ready-image')['body'].replace('no signed copy or signer was fabricated.', 'at this earlier checkpoint no signed copy or signer had been supplied. The following training lifecycle is separately labelled synthetic.')
    page('signoff-simulated-completion','Training acceptance, invalidation and a replacement version',
        note('<strong>SYNTHETIC TRAINING ONLY:</strong> The uploaded exercise PDF begins SYNTHETIC TRAINING – NOT CUSTOMER SIGNATURE. The signer is TRAINING ONLY Customer Representative, with an example.test identity. No real customer signed or accepted this work.')
        +steps('For actual operation, obtain the genuine complete signed copy of the exact customer-safe report. In the separately authorized training exercise, the operator used a conspicuously marked synthetic file instead. Open the Ready version 2 record, select Signed PDF copy, enter signer/identity/actual date and <strong>Record verified signed-copy evidence</strong>.',
            'The training UI showed <strong>Verified evidence</strong>, fictional signer, server verification time and the exact v2/hash binding. This verifies the application transition; the uploaded fixture was <strong>not_scanned</strong> under optional scan policy, with no scan job or invented clean result.',
            'Expand <strong>Invalidate sign-off</strong>, fill <strong>Reason for invalidation</strong> and <strong>Confirm invalidation</strong>. The lab became <strong>Invalid / superseded</strong>; previous conformity, snapshot/hash and native v2 PDF remained preserved.',
            'Open <strong>Refresh period reports → Open period refresh</strong> for the same scope. Repeating identical Hours and activity summary kept the version. Choosing <strong>Hours, activity and selected technical reports</strong> and the approved simulated bench record produced version 3.',
            'Version 3 initially showed <strong>Needs report</strong>. The Owner clicked <strong>Approve customer report → Generate report</strong>, waited for Queued processing, then downloaded the English Ready PDF. The fresh record became <strong>Ready for signature</strong>, bound to v3/hash. Obtain acceptance for that exact new version; version 2 acceptance does not cover it.')
        +note('V3 retains 12 h from two six-hour sources and one Daily report, adding one Technical report. Its scope differs from the worker’s corrected 7 h weekly register. No v3 signature was added. The current UI shows readable Problem / symptom, Diagnosis / root cause and Change performed fields; its 390 px browser check had no overflow or errors. Future PDF output now maps these details, verified by focused output tests. The already-generated v3 master’s blank Detail cell remains historical; no regeneration or signature was performed. Review selected technical content before delivery and use a supported new reviewed output/version when needed.'),toc=True)
    revise('lab-technical-approval-image', 'Technical report · approval and readable selected details', '<figure class="pair"><img src="bbs-illustrated-en-v2/lab-owner-45-technical-report-approval-before.png"><img src="bbs-illustrated-en-v2/lab-technical-readable-details.png"><figcaption>Separate onboarding lab: Submitted simulated-bench report had Approve report, then Approved was verified. The rebuilt selected-report UI uses readable labels, with no raw JSON and no 390 px overflow. Future PDF detail mapping passed output tests; the stored earlier v3 PDF is preserved, including its historical blank Detail cell. No real PLC change occurred.</figcaption></figure>')
    ux=revise('ux-improvements')
    ux['body']=ux['body'].replace('</table>', '<tr><td>Technical details showed JSON / blank PDF detail</td><td>Current UI uses human labels and wraps at 390 px; future PDF outputs map details. Existing issued/generated masters stay preserved; review a new authorized output before delivery.</td></tr></table>')
    pages[:]=[p for p in pages if p['key']!='lab-signoff-ready-image']
    fig('lab-signoff-completed-image','Synthetic v2 acceptance · exact signer/version binding','lab-synthetic-signoff-accepted.png','Separate onboarding lab: marked synthetic signer and version 2 hash. The UI state transition was tested; no genuine customer signature or acceptance occurred. Invalidation subsequently retained this evidence and the original native v2 PDF.')
    fig('lab-signoff-replacement-image','Replacement v3 · Ready after fresh approval and generation','lab-synthetic-signoff-replacement.png','Separate onboarding lab: after selecting the approved simulated Technical report, v3 moved Needs report → Approve customer report → Generate report → Queued → Ready for signature. English Download succeeded. V2 evidence remains preserved; no v3 signature or real customer acceptance is claimed.')
    page('planning-skills-availability','Planning, skills and availability · tested lab cycle',
        route('Planning → selected fictional project/worker; worker Profile → availability','/planning?lang=en')
        +steps('Select the intended project/worker; inspect the displayed timezone. The tested Planning page uses UTC.',
            'Expand <strong>Manage worker expertise → New expertise</strong>, fill <strong>Code</strong> and <strong>Name</strong>, then <strong>Save expertise</strong>. In <strong>Assign expertise</strong>, select Worker, Expertise and Proficiency, then <strong>Update expertise matrix</strong>. The lab saved Instrumentation QA at 3/5; skills do not grant project access.',
            'Select <strong>Project</strong> and <strong>Workers</strong>; fill <strong>Start (UTC)</strong>, optional <strong>End (UTC)</strong>, <strong>Planned hours</strong>, <strong>Site</strong> and <strong>Required expertise</strong>, then <strong>Publish assignment</strong>. The lab published 6 October 09:00–11:00 UTC, 120 planned minutes.',
            'In <strong>Published assignments</strong>, edit the same row and <strong>Save assignment</strong>. The lab saved 10:00–12:00 UTC and an updated site, then <strong>Cancel assignment</strong>. The day’s event disappeared and schedule count returned to zero.',
            'In Profile, select <strong>Inspect worker → View worker profile</strong>. Use <strong>Add availability</strong>: Starts, Ends, Availability and Note → <strong>Save availability</strong>. The lab saved Tentative 12:00–15:00 UTC, then Edit availability changed the note. Check calendar/table after saving.')
        +note('Isolated browser plus narrow read-only verification: one cancelled plan, one tentative availability window and zero actual time entries for that worker on 6 October. Planning publication/cancellation does not create actual work. Phone agenda was readable after scrolling; no confirmed responsive defect was observed.'),toc=True)
    revise('suppliers-owner','Supplier setup and personnel · exact tested controls',
        route('Suppliers → Setup and access / Authorize installation / Personnel','/suppliers?lang=en')
        +steps('In <strong>Setup and access</strong>, search existing suppliers. Fill <strong>Name</strong> and optional Email, Phone, Address and Notes, then <strong>Add supplier</strong>. Reopen the saved supplier.',
            'Create the external person’s account in Team with its approved role and supplier-linked profile. Provision a <strong>Supplier coordinator</strong> as well: the installation authorization requires an eligible coordinator from that supplier.',
            'In <strong>Authorize installation</strong>, select <strong>Supplier</strong>, <strong>Installation / project</strong> and <strong>Supplier coordinator</strong>; fill <strong>Starts on</strong>, optional <strong>Ends on</strong>, then <strong>Authorize installation</strong>. Verify the Active authorization.',
            'In <strong>Personnel → Assign existing technician</strong>, select the eligible technician/project and dated interval, then save the assignment. The future-dated lab assignment showed Future, not already-worked hours.',
            'Verify project team and supplier authorization independently. Internal crew delegation neither creates the supplier relationship nor grants supplier finance access. Check supplier operational-reporting details in the separate Supplier operations guide.')
        +note('Browser-tested in a separate empty supplier lab C-0050-P-050901: supplier/coordinator saved, Active authorization, future technician assignment. No supplier time submission, invoice or payment was created; those broader behaviors remain reference.'))
    pair('supplier-example-image','Supplier setup, profile and installation authorization', ['lab-supplier-create.png','lab-supplier-profile.png','lab-supplier-authorize.png'],'Separate supplier lab: Add supplier; supplier-linked External technician profile; Authorize installation with coordinator and dates. These are three separate saved permissions, not a single employee setup.')
    page('supplier-access-lifecycle','Team role, external profile and access removal',
        route('Projects → Team access → selected person; Suppliers → authorization row','/projects?view=team&lang=en')
        +steps('Inspect the account’s base <strong>Role</strong> separately from its <strong>Access profile</strong>. In the lab, Worker had External technician plus the supplier link; Worker → Project Manager → Worker saved. The profile editor was unavailable for Project Manager.',
            'For an external Worker, choose <strong>Access profile</strong> and required <strong>Supplier</strong>, then <strong>Save profile</strong>. The lab changed External technician → Supplier coordinator → External technician, preserving that link.',
            'Before ending access, review actual work, future assignments/delegations and financial obligations. Use <strong>Remove Assignment</strong> with the required factual reason. The empty lab’s future assignments were cancelled before start; historical rows remain.',
            'On the supplier authorization use <strong>Revoke access</strong>. The lab retained the authorization row as Revoked.',
            'For the ordinary technician account, use <strong>Remove access</strong> and review <strong>Remove this team member access?</strong> before confirming. It disappeared from the active Team filter; this is not proof of hard deletion of historical records.')
        +note('Separate empty supplier lab only. A future assignment’s impossible end-date range was not bypassed; the supported cancellation control was used. The protected Owner role/account is outside ordinary role/removal controls.'),toc=True)
    revise('owner-close-and-history','Project closure and archive · exact tested empty-project cycle',
        route('Projects → selected row → Actions; project detail → Project closeout','/projects?lang=en')
        +steps('Review actual sources/corrections, schedules and assignments, Daily/Technical reports, acceptance, issued documents/receivables, compensation and reimbursements. A zero-work fixture cannot verify closure of a financially active project.',
            'Project detail <strong>Project closeout → Prepare closeout draft</strong> is a package/document flow, separate from project status.',
            'On the project row expand <strong>Actions</strong>, read the status warning and fill the factual <strong>Reason</strong>. Click <strong>Begin close</strong>. Filter Status <strong>Closing</strong> and verify the saved project.',
            'When closure prerequisites are satisfied, fill Reason and <strong>Close project</strong>. Filter <strong>Closed</strong> and verify. New assignments are unavailable while Closing/Closed.',
            'For archive, fill Reason and <strong>Archive project</strong>. It disappears from the default active list. Select <strong>Include archived projects</strong> and Status <strong>Archived</strong> to find its preserved history.',
            'The Archived Actions menu offers <strong>Restore project</strong>. That control was inspected but not submitted. Do not infer reopening of Closed work, late entry permission or paid obligations from its presence.')
        +note('Browser passed Begin close → Closing → Close project → Closed → Archive → Archived for the separate supplier lab C-0050-P-050901, after cancelling future assignments. It had zero time, reports, expenses, invoices and economic contribution. Restore, closed-project late work and financial-project closure were not tested. Archiving is not payment.'))
    page('cost-reconciliation','Reconcile internal costing with compensation owed',
        '<p>The original BBS workbook uses independently dated internal hourly cost rules. Worker compensation is calculated separately from the compensation agreement. The application does not automatically replace an internal hourly estimate with daily/fixed compensation or force these totals to match.</p>'
        +table(['Same 42.5-hour scope','Original native workbook / conditional sensitivity'],[
            ['Customer charges','USD 4,672'],['Configured internal labor estimate','USD 1,520'],['Contractual worker compensation','USD 2,100: USD 580 above that labor estimate.'],['Original direct cost and contribution','USD 1,520 + 230 expenses = USD 1,750; contribution USD 2,922 / 62.54%.'],['Conditional replacement only','If labor basis is USD 2,100 instead of USD 1,520 and the same USD 230 expenses remain, direct cost = USD 2,330; contribution = USD 2,342 / 50.13%. Do not add compensation on top of the old labor estimate.'],
        ])
        +steps('Open <strong>Economic Review</strong> for the same project and 1–5 October dates. Compare Labor source <strong>Internal cost</strong> and <strong>Worker compensation</strong>, grouped by worker/date/category/rule.',
            'Open <strong>Commercial Configuration</strong> for the same project. Inspect dated <strong>Internal loaded cost</strong> and <strong>Worker compensation</strong> rules. Reconcile fixed USD 900 once-per-period allocation and the chief’s later USD 80 outside the opening settlement.',
            'Agree inclusive costing assumptions with the responsible finance/accounting person. If compensation should be included in loaded labor cost, this illustrative estimate is insufficient; employer taxes, benefits or overhead may add more.',
            'Use a supported new dated rule for approved future scope. Issued masters/finalized snapshots remain preserved; do not edit the attached workbook cells.')
        +note('The sensitivity calculation is not the application’s saved result, statutory profit or cash. USD 2,922 is configured contribution, not proof of actual employer labor cost. Source logic calculates directCost = laborCost + expenseCost, then contribution = revenue − directCost.'),toc=True)
    revise('spreadsheet-reconciliation')['body']=revise('spreadsheet-reconciliation')['body'].replace('USD 1,750 direct company cost;', 'USD 1,750 configured direct company costing estimate;').replace('This is an operational margin, not cash in the bank.', 'This is configured contribution, not cash or verified total employer cost. Reconcile the USD 580 labor-estimate/compensation gap in the following cost chapter.')
    revise('worker-payment-register-image',title='Initial unpaid baseline · actual-payment form')['body']=revise('worker-payment-register-image')['body'].replace('all demonstration settlements remain unpaid.', 'at this original baseline all three settlements are unpaid. The later isolated chief-payment sequence changes that copied obligation to fully paid.')
    revise('worker-payment-register-image')['wide']=True
    revise('lab-week-register-image')['wide']=True
    revise('worker-period-examples')['body']=revise('worker-period-examples')['body'].replace('All three show <strong>Actual paid USD 0</strong>', 'At this original pre-payment snapshot all three show <strong>Actual paid USD 0</strong>')
    page('private-documents','Documents · register, classify and recover a private file',
        route('Documents → Register a private artifact','/documents?lang=en')
        +steps('Select <strong>Project</strong> and <strong>Artifact type</strong>. Choose <strong>Document access</strong>: <strong>Project document</strong> or <strong>Finance, Owner and Auditor only</strong>. Confirm the intended audience.',
            'Choose <strong>Sensitivity</strong>: <strong>Internal</strong>, <strong>Sensitive</strong> or <strong>Customer private</strong>. Fill <strong>Description</strong>, attach <strong>File</strong> and click <strong>Upload and register hash</strong>. Sensitivity classifies the file; it does not publish a share link.',
            'Find the registered project/file, check its hash and scan/readiness state, then use the permitted private download. A listed filename does not prove that scanning or artifact generation succeeded.',
            'If upload fails, read the error and attach <strong>File</strong> again for retry. Register a corrected file as a new document; keep the original historical evidence.',
            'To retire an obsolete file, expand <strong>Archive</strong>, enter the required <strong>Archive reason</strong>, then <strong>Archive document</strong>. Archive retains the master and committed metadata with an archive timestamp; it is not deletion.',
            'Select language and customer-facing/internal audience separately when generating report outputs. Internal worker pay, loaded cost and contribution are unsuitable for an ordinary customer invoice delivery.')
        +note('Isolated browser tested a new synthetic PDF: Finance, Owner and Auditor only; Sensitive; uploaded/committed, Owner Download bytes/hash matched the stored master, assigned Worker received privacy-preserving HTTP 404, then Archive retained the master. The fixture’s optional scanner returned <strong>not_scanned</strong>, with no scan job: no antivirus/clean result is claimed. Inspect actual scan policy/status; upload or registration alone does not certify a scan. Failed scan/retry and corrected-file version behavior remain reference.'),toc=True)
    pair('lab-documents-image','Private document · exact classification and saved download controls',['lab-documents-upload-fields.png','lab-documents-saved-private-row.png'],'Isolated original BBS project: a conspicuously synthetic file with restricted finance audience and Sensitive classification. Owner download matched its registered hash; a Worker on this project was denied before archive. This optional-scan fixture was not_scanned, not antivirus-clean.')
    revise('owner-profile-and-help','Audit, notifications, security and Help · exact scope',
        steps('Use <strong>Audit</strong> to inspect preserved actions and follow their record context. The isolated lab observed skill.create, worker skill.set, planning.create/update/cancel and worker availability.create/update. Audit viewing does not edit history.',
            'Open Notifications and follow the relevant record link before acting. Marking a notification read manages attention; it is not source approval, payment or customer acceptance. The bounded test opened the inbox without marking items.',
            'In <strong>Profile → Account security → Passkeys</strong>, use <strong>Device name / Register passkey</strong>; an existing credential offers <strong>Revoke</strong>. Authenticator app offers <strong>Enable MFA / Verify MFA / Disable MFA</strong>. Keep setup URI and one-time recovery codes private. An enabled account can require MFA even when setup is optional.',
            'Security-control names are reference only: no production passkey, MFA or account preference was changed for a screenshot. Use your own account and the approved recovery process.',
            'Open <strong>Help → Contact support</strong> or email <strong>admin@j-aautomation.com</strong>. Include guide revision, URL/project/record ID, exact error, time and correlation ID. Ask explicitly for issuer-history review if the Owner is also the company administrator. Never send passwords, cookies, activation links or recovery codes.')
        +note('Help, Audit, Profile and Notifications routes rendered in the isolated browser. The role-assigned guide catalog was visible. Broad security, notification and history edge cases remain reference procedures. No support email was sent.'))
    revise('verification-scope','Validation matrix · completed, reference and blocked',table(['Task / evidence','Verified outcome and boundary'],[
        ['BBS sources and rate units','42.5 original actual hours; hourly/full-day/full-week source grouping and original USD 2,230 / 182 / 2,260 calculations checked.'],
        ['Invoice issue and integrity','Three final native training masters numbered through application issue, canonical downloads/annex streams/attachments unchanged. No real accountant approval asserted.'],
        ['Worker and customer ledgers','Chief simulated partial/reversal/full sequence net USD 400; expense reimbursement USD 180; BBS collections USD 682, receivable USD 3,990. Separate synthetic receipt/reversal and credit preserve original history.'],
        ['Onboarding, corrections and reports','Access/assignment; 9.5 h originals, corrected 7 h; reviews; Daily/Technical approval; customer v2/v3 Ready downloads; human technical UI and future-output mapping checked. Marked synthetic v2 acceptance/invalidation passed; no real signature or v3 acceptance.'],
        ['Planning, suppliers and lifecycle','Skills/plan/availability and zero actual hours verified; supplier/coordinator authorization, external profile and account-role/removal transitions verified. Only the empty fixture passed Closing → Closed → Archived; Restore not submitted.'],
        ['Email / weekly closure','Explicit consent, queue, repeat-event reuse and actual configured-service failure/retry tested. Weekly close and late source tested; no SMTP inbox delivery or late-source rewrite of issued master claimed.'],
        ['Accounting','Original BBS October scope remains blocked by archived issuer history. Separate synthetic October pack generated all five native formats, authenticated downloads matched masters before/after finalization, and review counts/reconciliation were zero. The earlier August snapshot retains its unresolved advisories.'],
        ['Reference calculations and controls','Overtime, percentage, minimum/cap/milestone/forecast examples and zero-hour layout-copy behavior are source-grounded. No universal contract/overlapping-settlement validation is inferred.'],
        ['Private documents and limits','Actual restricted upload/Owner download/Worker denial/archive retained native bytes. Fixture not_scanned: no antivirus pass. Audit/Help/Profile/Notifications routes inspected; security changes and broader document-recovery edge cases remain reference.'],
    ])+note('Read the following evidence history together with the task checklist. A pass covers the named action/environment/date scope; it is not a claim that every Owner permission, contract, exception or external service was tested.'))
    page('testing-history','Evidence history · keep snapshots and outcomes separate',
        table(['Capture phase','What it establishes'],[
            ['Original BBS pre-issue','42.5 approved actual hours, four purchases USD 230, customer charges USD 4,672. Three draft PDFs/zero issued and collected; three original compensation settlements unpaid. These remain historical screenshots/workbooks.'],
            ['Isolated BBS lifecycle','Copied original sources issued as three numbered native masters. Expense collected 100 + 82; mixed labor collected 500; chief simulated payment/reversal net 400; reimbursements 180. Canonical issued downloads match their stored bytes.'],
            ['Separate onboarding lab','New access/assignment, 8 + 1.5 originals then linked 6 + 1; reviews; Daily/Technical approval; v2 synthetic acceptance/invalidation, v3 refresh/approval/Ready download; planning/skills/availability; supplier/access/empty-project lifecycle; audit/nav observations.'],
            ['New Accounting demo','Separate synthetic C-0002-P-002 portfolio: collection/reversal, linked issued credit, explicit email consent/queue/failure/retry, weekly close/late source. August Accounting retains its disclosed advisories; October native Ready/review/final passed with zero review counts and verified cross-month evidence links. This is not a new state of the original BBS workbook.'],
            ['Reference procedures','Overtime/percentage/daily-minimum arithmetic, caps/milestones/forecast, zero-hour layout copy, supported foreign-currency escalation and security control descriptions are source-grounded; no additional browser pass is inferred.'],
        ])+note('Evidence packets are recorded under docs/evidence/bbs-owner-completion-20261005: owner, finance, secondary-owner, access-supplier, financial-completion and editorial. Their capture scope, hashes and observed outcomes are the audit trail. Read task chapters for exact boundaries; do not infer a real customer signature, SMTP delivery, accountant approval or bank transfer from synthetic training receipts.'),toc=True)
    page('owner-task-checklist','Owner completion checklist · verify the business result',
        table(['Task','Completion evidence'],[
            ['Access and setup','Own account/role, correct environment/project, active dated assignments/delegations; approved initial and later terms cover actual work dates.'],
            ['Work and correction','Actual source facts saved/submitted; operational and Finance review persisted; linked replacement active, original preserved, no duplicate eligible duration.'],
            ['Reports and acceptance','Daily/Technical reviewed; correct period audience/content/version; Ready PDF reviewed; genuine acceptance bound to that version when required.'],
            ['Billing and delivery','Intended source/period/issuer/tax/numbering; final assigned number and canonical Ready PDF; dispatch/email result recorded separately; issued correction preserves history.'],
            ['Collections and worker obligations','Actual receipt/payment evidence; posted and reversed events reconcile remaining balances; compensation and expense reimbursement handled separately.'],
            ['Exports and costing','Same project/date/currency scope; source totals reconcile; USD 580 illustrative labor/compensation gap explained; original XLSX retained privately.'],
            ['Closure and administration','Weekly prerequisites satisfied; project closure/archive only through supported controls; Accounting artifact readiness, reconciliation and finalization verified.'],
            ['Exceptions','Specific error and preserved scope understood; supported retry/escalation with record ID; no invented signature/approval/history or duplicate source.'],
        ])+note('A training completion proves the documented application transition for that scope. Real financial completion requires genuine business evidence. Broader reference procedures are not automatically browser-verified by checking this list.'),toc=True)

def order_course():
    # Explicit task order; numeric chapter prefixes no longer imply a conflicting course.
    groups = [
        ['cover','contents-1','contents-2','contents-3','contents-4','owner-first-access','before-practising','owner-navigation','owner-access-model','owner-team-onboarding','lab-team-access-image','lab-team-active-image'],
        ['bbs-inspect-or-create','chapter-1','project-prerequisites','chapter-2','client-fields','project-basics-image','project-fields','commercial-project','commercial-image','budget-fields','budget-image','creation-people','creation-assignment-image','creation-terms-image','lab-assignment-image','lab-assignment-result-image','bbs-initial-sheet','chapter-3','find-person-image','dated-terms','contract-decisions','chapter-4','issuer-setup-image','issuer-directories','chapter-5','person-5-rates','person-5-expenses','chapter-6','person-6-rates','person-6-expenses','chapter-7','person-7-rates','person-7-expenses','chapter-8','billing-unit-meaning','overtime-reference','worker-trigger-limits','alternative-contracts','chapter-9','assign-chief-image','suppliers-owner','supplier-tested-controls','supplier-example-image','supplier-access-lifecycle'],
        ['chapter-15','stream-prerequisites','stream-core-fields','stream-cadence-image','stream-delivery-fields','stream-delivery-image','cadence-options','chapter-19','planning-skills-availability','planning-owner-time','lab-week-image','lab-week-register-image','chapter-10','worker-time-image','chief-hours-image','chapter-12','expense-entry-fields','expense-source-image','expense-money-image','chief-receipt-image','foreign-currency-remedy'],
        ['operational-review','lab-review-active-image','lab-review-result-image','correction-states','correction-worked','lab-correction-form-image','lab-correction-saved-image','lab-correction-review-image','lab-direct-correction-submit-image','lab-direct-correction-result-image','lab-finance-active-image','lab-finance-reviewed-image','chapter-11','approved-time-image','chapter-13','approved-expense-image','finance-complete-image'],
        ['report-model','daily-report-procedure','lab-daily-form-image','lab-daily-review-image','technical-report-procedure','lab-technical-approval-image','period-report-procedure','lab-period-refresh-image','lab-customer-pdf-ready-image','signoff-evidence','lab-signoff-form-image','signoff-simulated-completion','lab-signoff-completed-image','lab-signoff-replacement-image'],
        ['chapter-16','invoice-prerequisites','invoice-wizard','invoice-project-image','invoice-period-image','labor-lines-image','chapter-17','expense-lines-image','chapter-18','mixed-lines-image','chapter-20','invoice-edit-fields','invoice-dates-image','pdf-button-image','chapter-22','final-numbering','lab-numbering-form-image','final-issue-procedure','lab-issued-ready-image','invoice-dispatch','lab-dispatch-image','issued-correction','lab-issued-adjustment-image'],
        ['collections-procedure','lab-collection-image','worker-schedules','worker-payment-prerequisites','worker-settlement-steps','worker-period-image','worker-period-examples','worker-planning-steps','worker-dates-image','worker-actual-payment','worker-payment-register-image','lab-initial-settlement-image','lab-partial-worker-payment-image','lab-payment-reversal-image','lab-payment-complete-image','lab-final-settlements-image','expense-reimbursement','lab-reimbursed-image','chapter-14','worker-pay-summary-image','worker-pay-activity-image'],
        ['economic-meaning','spreadsheet-exports','finance-export-button-image','spreadsheet-sheets','spreadsheet-reconciliation','cost-reconciliation','71-xlsx-summary-economics','72-xlsx-summary-cash','73-xlsx-labor-hours','74-xlsx-labor-economics','73b-xlsx-labor-hours','74b-xlsx-labor-economics','75-xlsx-expense-payers','76-xlsx-expense-recovery','77-xlsx-invoices','78-xlsx-invoice-expenses','79-xlsx-unbilled','79b-xlsx-unbilled','expense-workbook-steps','expense-export-button-image','80-xlsx-expense-register','82-xlsx-expense-reimbursement','81-xlsx-expense-totals','spreadsheet-verified-scope','after-lifecycle-workbook','83-xlsx-after-cash','84-xlsx-after-invoices','85-xlsx-after-reimbursements'],
        ['weekly-close-procedure','lab-weekly-close-image','owner-close-and-history','project-lifecycle-tested','accounting-pack','accounting-success','accounting-period-reconciliation','lab-accounting-ready-image','lab-accounting-review-image','lab-accounting-finalized-image','accounting-gap-remedy','lab-accounting-blocker-image','private-documents','lab-documents-image','owner-profile-and-help','ux-improvements','owner-task-checklist','verification-scope','testing-history','appendices'],
    ]
    by_key={p['key']:p for p in pages}
    ordered=[by_key[k] for g in groups for k in g if k in by_key]
    included={p['key'] for p in ordered}
    extras=[p for p in pages if p['key'] not in included and p['key']!='chapter-21']
    if extras: ordered[-1:-1]=extras
    assert len({p['key'] for p in ordered})==len(ordered)
    pages[:]=ordered
    preissue=set(k for g in groups[1:4] for k in g)
    preissue.update(k for k in by_key if re.match(r'^(7\d|8[012])(?:b)?-xlsx-',k))
    preissue.update(['worker-period-examples','worker-period-image','worker-dates-image','worker-payment-register-image','worker-pay-summary-image','worker-pay-activity-image','spreadsheet-reconciliation','cost-reconciliation','finance-export-button-image','expense-export-button-image'])
    preissue.update(k for k in by_key if k.startswith('chapter-') and k!='chapter-21')
    preissue.update(['invoice-prerequisites','invoice-wizard','invoice-project-image','invoice-period-image','labor-lines-image','expense-lines-image','mixed-lines-image','invoice-edit-fields','invoice-dates-image','pdf-button-image'])
    onboarding=set(k for k in by_key if k.startswith(('lab-owner','lab-team','lab-assignment','lab-week','lab-review','lab-correction','lab-direct','lab-finance','lab-daily','lab-period','lab-customer','lab-signoff','lab-technical')))
    onboarding.update(['planning-skills-availability','correction-worked','technical-report-procedure','signoff-simulated-completion','suppliers-owner','supplier-tested-controls','supplier-example-image','supplier-access-lifecycle','owner-close-and-history','project-lifecycle-tested'])
    for p in pages:
        p['title']=re.sub(r'^\d+\s*·\s*','',p['title'])
        k=p['key']
        if k in ['accounting-gap-remedy','lab-accounting-blocker-image']: label='Isolated BBS lifecycle · Historical coverage error'
        elif k.startswith('lab-accounting-') or k in ['accounting-success','accounting-period-reconciliation','invoice-dispatch','lab-dispatch-image','issued-correction','lab-issued-adjustment-image','lab-collection-image','weekly-close-procedure','lab-weekly-close-image']: label='New Accounting demo · Read-only demonstration'
        elif k in onboarding: label='Separate onboarding lab · Read-only demonstration'
        elif k in preissue: label='Original BBS pre-issue · Historical snapshot'
        elif k.startswith(('lab-payment','lab-partial','lab-initial','lab-final','lab-reimbursed','lab-issued','lab-dispatch','lab-collection','lab-numbering')) or k in ['after-lifecycle-workbook','83-xlsx-after-cash','84-xlsx-after-invoices','85-xlsx-after-reimbursements','final-issue-procedure','collections-procedure','expense-reimbursement','private-documents','lab-documents-image','appendices']: label='Isolated BBS lifecycle · Read-only demonstration'
        else: label='Reference procedure · Scope stated on this page'
        p['context']=label
