def insert_figure_after(target, key, title, filename, caption, wide=True):
    fig(key,title,filename,caption,wide=wide)
    added=pages.pop()
    position=next(i for i,p in enumerate(pages) if p['key']==target)
    pages.insert(position+1,added)

def build_evidence_chapters():
    insert_figure_after('owner-team-onboarding','lab-team-access-image','Owner · create local access before assignment','lab-owner-02-team-create-user.png','Isolated training browser: Set email and password and Create user access. This creates an account without sending an email; project assignment is a separate action.')
    insert_figure_after('lab-team-access-image','lab-team-active-image','Owner · new active training account, zero assignments','lab-owner-05-team-local-account-after.png','The BBS LAB account was created in isolation and initially had zero project assignments. Active access alone is not project participation.')
    insert_figure_after('lab-team-active-image','lab-assignment-image','Owner · assign the account to a dated project','lab-owner-06-project-assignment-before.png','Projects → More actions → Assign Worker: select project/person, start date and authorized finance/defaults; click Assign. The isolated onboarding lab is C-0050-P-20261006.',wide=False)
    insert_figure_after('lab-assignment-image','lab-assignment-result-image','Owner · account now has one saved assignment','lab-owner-07-project-assignment-after.png','After Assign, the newly created BBS LAB worker has one active assignment. Account and assignment steps were both saved and reopened.')
    insert_figure_after('planning-owner-time','lab-week-image','Owner · enter actual work in the weekly table','lab-owner-08-week-time-before.png','Isolated onboarding lab: week of 28 September, Friday 8 hours and Saturday 1.5 hours. Save daily drafts skips blank days; the saved result totals 9.5 hours.',wide=False)
    insert_figure_after('lab-week-image','lab-week-result-image','Owner · saved daily drafts, 9.5 hours','lab-owner-09-week-time-after.png','The browser saved and then submitted the selected worker’s week. These onboarding-lab rows are separate from the original 42.5-hour BBS invoice example.',wide=False)
    insert_figure_after('operational-review','lab-review-active-image','Active review · return eight hours with a reason','lab-owner-12-approval-return-before.png','Review actions → Required change → Needs changes. The reviewer enters why eight hours must become six. This is an actionable submitted record, before the final cleared queue.',wide=False)
    insert_figure_after('lab-review-active-image','lab-review-result-image','Returned source · saved Needs changes state','lab-owner-13-approval-return-after.png','The source is returned, with its factual correction reason retained. Returning work does not decide customer billing or reimbursement.')
    insert_figure_after('correction-worked','lab-correction-form-image','Returned source · six-hour owner correction','lab-owner-14-correction-six-hours-before.png','Create corrected draft: set Actual hours to 6, enter Correction reason, then Create owner override draft. A linked correction cannot be edited after creation; review before saving.',wide=False)
    insert_figure_after('lab-correction-form-image','lab-correction-saved-image','Linked correction · original eight hours preserved','lab-owner-15-correction-six-hours-draft.png','The isolated browser created the six-hour linked correction draft. The original eight-hour source remains part of traceable history.',wide=False)
    insert_figure_after('lab-correction-saved-image','lab-correction-review-image','Correction submitted · ready for review','lab-owner-17-correction-submitted-queue.png','After submission the linked correction appears in the approval flow. Check the resulting active source after operational and Finance review; do not submit a standalone duplicate.',wide=False)
    insert_figure_after('lab-correction-review-image','lab-direct-correction-submit-image','Linked correction · individual Submit control','lab-owner-27-owner-correction-direct-submit-before.png','Owner-authored unsubmitted correction details now expose Submit. The weekly bulk action excludes linked corrections; use this individual control or the Time register.',wide=False)
    insert_figure_after('lab-direct-correction-submit-image','lab-direct-correction-result-image','Linked correction · saved Submitted state','lab-owner-28-owner-correction-direct-submit-after.png','The second onboarding-lab correction changed 1.5 hours to 1 hour and submitted through its detail control. The original and replacement stay linked.',wide=False)
    insert_figure_after('lab-review-result-image','lab-finance-active-image','Finance review · six corrected hours and commercial treatment','lab-owner-29-six-hour-finance-review-before.png','After operational approval, select Billable or Non-billable and click Record Finance review. This actual active BBS LAB card demonstrates the step before the cleared queue.',wide=False)
    insert_figure_after('lab-finance-active-image','lab-finance-reviewed-image','Corrected time · Finance review saved Billable','lab-owner-30-six-hour-finance-reviewed.png','Record Finance review persisted Billable treatment for the operationally approved six-hour linked correction. The source remains linked to the preserved original.',wide=False)
    insert_figure_after('daily-report-procedure','lab-daily-form-image','Daily report · actual worker/date and completed work','lab-owner-33-daily-report-entry.png','New daily report: choose the dated assignment, worker and actual facts. Save daily report creates a draft; Submit starts its review.',wide=False)
    insert_figure_after('lab-daily-form-image','lab-daily-review-image','Submitted Daily report · active approval action','lab-owner-36-daily-report-approval-before.png','The isolated Owner reviews the submitted Daily report and approves its facts. One approved Daily report later appears in the onboarding-lab period record.',wide=False)
    insert_figure_after('period-report-procedure','lab-period-refresh-image','Refresh period records · customer-facing content choice','lab-owner-37-period-report-generator.png','Refresh period reports → Open period refresh: select project/date scope/language and Hours and activity summary. Refresh reports created customer/internal record snapshots. The customer report was subsequently approved, its English PDF generated and downloaded; genuine sign-off remains pending.',wide=False)
    insert_figure_after('period-report-procedure','lab-customer-pdf-ready-image','Approved customer period · English PDF Ready and Download','lab-owner-48-customer-report-native-pdf-ready.png','The isolated browser approved customer period version 2, generated its English artifact and downloaded the native Ready PDF. Other languages remain Not generated yet until explicitly requested.')
    insert_figure_after('signoff-evidence','lab-signoff-ready-image','Customer report · Ready for signature, acceptance pending','lab-owner-signoff-ready-summary.png','The approved customer-safe report is Ready for signature. This readiness is not proof that the customer signed; no signed copy or signer was fabricated.')
    insert_figure_after('lab-signoff-ready-image','lab-signoff-form-image','Exact version binding · signed-copy evidence form','lab-owner-signoff-evidence-form.png','The form binds the signed PDF to version 2 and its snapshot hash. Upload a genuine signed copy, enter actual signer/date and Record verified signed-copy evidence. The example fields remain empty; the suggested date is not signature evidence.',wide=False)
    page('technical-report-procedure','Technical / PLC report · tested review procedure',route('Reports → New technical report','/reports?view=technical&lang=en')+steps('Click <strong>New technical report</strong>. Select Project, Work date, System / machine and the entitled Worker when entering on their behalf.', 'Fill the actual problem, diagnosis, work/change, validation/result, production impact, risks and rollback detail. Attach genuine backup/change evidence when applicable; check the safety-related requirement.', 'Click <strong>Save PLC report</strong>. Reopen the saved draft, review the facts and click <strong>Submit for review</strong>.', 'Owner/PM opens <strong>Approvals → Reports</strong>, reviews the technical facts and clicks <strong>Approve report</strong>, or returns via Review actions with a reason.', 'If a customer report should include technical detail, refresh a new period version with <strong>Hours, activity and selected technical reports</strong>, then explicitly select the approved technical records. Do not assume they are added to an existing approved version.')+note('The browser example describes a simulated control bench. It did not modify a real PLC. Customer period v2 had already been prepared with hours/activity content before this technical approval; its selected snapshot remains unchanged.'),toc=True)
    insert_figure_after('technical-report-procedure','lab-technical-approval-image','Submitted technical report · Approve report action','lab-owner-45-technical-report-approval-before.png','The isolated simulated-bench technical report reached Submitted, then Approve report succeeded and the browser verified Approved status. It is not evidence of a real plant modification.')
    insert_figure_after('worker-actual-payment','lab-payment-reversal-image','Worker payment · retained payment and reversal','lab-finance-worker-payment-reversed.png','Isolated simulated ledger: the added USD 100 payment was reversed with its reason. Net chief paid returned from USD 300 to USD 200, leaving USD 200 owed. No bank transfer occurred.')
    insert_figure_after('lab-payment-reversal-image','lab-payment-complete-image','Worker payment · finalized obligation fully paid in training','lab-finance-worker-payment-complete.png','The training register then recorded the remaining USD 200. Net simulated payments equal the chief’s USD 400 finalized obligation, with USD 0 remaining. Original payment and reversal history are preserved.')
    insert_figure_after('worker-period-examples','lab-final-settlements-image','Compensation sources · corrected hours and retained project','lab-finance-settlements-cropped.png','Updated isolated register: Source shows 10 hrs, 13 hrs and 0 hrs; fixed-period USD 900 does not require a duration basis. Chief is USD 400 paid, zero remaining after the simulated payment sequence. Scroll horizontally for the full Timeline column.')
    insert_figure_after('expense-reimbursement','lab-reimbursed-image','Reimbursement results · three expenses, USD 180','lab-finance-reimbursements-cropped.png','The isolated simulation marks USD 20 parking, USD 100 hotel and USD 60 meal reimbursed, retaining Actual timestamps. This is worker reimbursement, separate from USD 182 customer recovery.')
    insert_figure_after('final-numbering','lab-numbering-form-image','Training numbering · synthetic approval timestamp','86-training-numbering-policy.png','Isolated training form only: Legal entity, Prefix, Digits, Effective from and Accountant approved at. The displayed timestamp is synthetic fixture data, not an accountant approving production. Click Save numbering policy only with genuine approval in the real system.')
    insert_figure_after('final-issue-procedure','lab-issued-ready-image','Final invoice · Ready download and lifecycle controls','lab-invoice-toolbar-ready.png','Latest built isolated candidate: PDF Ready, Download PDF and the separately preserved Paid lifecycle badge. This toolbar capture is cropped from the actual desktop browser screenshot. The canonical invoice master remains unchanged after payment or UI changes.',wide=True)
    page('after-lifecycle-workbook','After lifecycle XLSX · compare a second snapshot','<p>The third original XLSX was downloaded from project Billing after the isolated invoice/collection/payment/reimbursement exercises. It covers the same BBS project and 1–5 October scope, with the original 42.5 actual hours.</p>'+table(['Value','Meaning'],[['Issued invoices USD 4,672','USD 2,230 + 182 + 2,260 genuinely issued training invoice totals.'],['Collected USD 682','USD 500 mixed-labor partial receipt plus USD 100 + 82 expense receipts; simulated entries.'],['Receivable USD 3,990','USD 4,672 minus USD 682 posted collections.'],['Unbilled WIP USD 0','The worked sources are covered by issued training invoices.'],['Reimbursed USD 180','20 parking + 100 hotel + 60 shared meal.'],['Actual hours 42.5','The separate C-0050-P-20261006 onboarding-lab time is outside this workbook.']])+note('Keep the original pre-issue workbook for the starting state and this after-lifecycle workbook for the confirmed training state. Both are native downloads; cells were never altered to force matching totals. All three workbooks are embedded in the PDF and included beside the guide.'),toc=True)
    for item in json.loads((FIG/'workbook-previews.json').read_text())['views']:
        if 'after-lifecycle' in item['file']:
            fig(item['key'],item['title'],item['key']+'.png','Read-only landscape preview from the original after-lifecycle XLSX. Confirmed training invoice states and simulated collection/reimbursement entries; no bank transfer or customer email is asserted.',wide=True)
    page('accounting-gap-remedy','Accounting error · understand the retained dates',
        '<p>The isolated browser attempted <strong>Generate pack</strong> for <strong>1–5 October 2026</strong>. It returned <strong>ACCOUNTING_PACK_ISSUER_EFFECTIVE_DATE_GAP</strong>. The form still shows the selected dates and English language, so the Owner can investigate and retry the intended period without entering it again. <strong>Preserving the selection is successful form behavior; pack generation is blocked.</strong></p>'
        '<p>An Accounting Pack includes portfolio and historical currency/issuer records, rather than only the BBS USD invoice example. An archived issuer can still be included when historical sources refer to it. In this training clone, the blocking issuer <strong>QA-W48-EUR was already archived</strong>; archiving it again would not remove that history.</p>'
        +table(['Verified training history','Why the check fails or passes'],[
            ['QA-W48-EUR legal revision','Valid from 1 October until 5 October 2026, with the end exclusive. It therefore does not cover any time on 5 October.'],
            ['Selected pack period end','The coverage check uses 5 October 2026 at 23:59:59.999 UTC. QA-W48-EUR has no legal revision covering that instant.'],
            ['J&A USD issuer, JA-USA','Its revision starts 7 September 2026 with no end. It covers the selected period end and is not the cause of this error.'],
        ])
        +steps('Keep the intended period. Read the error and use <strong>Contact support</strong> to review the genuine issuer history and the historical sources that refer to it.',
            'Resolve only a verified historical-data issue through the supported process. Do not extend dates, invent a successor revision or purge sources merely to force generation.',
            'After that review resolves the coverage issue, retry the intended period, review Ready artifacts and finalize the reviewed version.')
        +note('Legal issuer revision coverage is separate from invoice frequency, worker payment frequency and accountant approval of invoice numbering. No Accounting Pack was generated or finalized by this blocked attempt, and no production issuer history was changed.'),toc=True)
    insert_figure_after('accounting-gap-remedy','lab-accounting-blocker-image','Accounting error: your selected period is preserved','lab-finance-accounting-result.png','The blocked form retains 1–5 October 2026 and English so the intended scope is available for investigation and retry. This confirms the form behavior; generation has failed because the archived training issuer QA-W48-EUR lacks a legal revision covering the period end. Contact support is offered. The J&A USD issuer is covered. No Accounting Pack artifact or finalization is claimed.',wide=False)
    page('ux-improvements','UX corrections and remaining operating limits',table(['Finding','Current behavior / operating guidance'],[
        ['Settlement returns to wrong project','Finalization/retry now preserves selected project, economic view and settlement source. Browser confirmed BBS heading remains selected.'],
        ['Approved minutes formatted as money','Source is duration: 600 minutes → 10 hours, 780 minutes → 13 hours. Percentage monetary bases retain currency. Finalized monetary amounts are separate.'],
        ['Initial creation crop hid controls','The budget screenshot now includes actual budgets and reporting switches. Review each applicable requirement before saving.'],
        ['Cleared review queue taught no action','New active approval/return/correction screenshots precede completion evidence.'],
        ['Owner correction detail had no Submit','An Owner-authored linked correction draft now has an individual Submit action. Weekly bulk submission excludes linked corrections.'],
        ['Ordinary reports showed correction withdrawal','Ordinary Daily/Technical drafts now show Submit for review and omit the unrelated Withdraw correction draft action.'],
        ['Issued PDF toolbar contrast / badge','Download controls now have readable contrasting labels; the Paid lifecycle badge is separately visible. Latest desktop/390px browser checks passed.'],
        ['Worker payment “frequency” ambiguity','No automatic per-worker payroll cadence exists. Select independent periods and expected dates manually.'],
        ['Accounting issuer date gap','Error retains selected scope and offers support; no self-service history bypass is claimed.'],
        ['Wide finance rows','Use landscape worksheet previews and horizontal table scrolling. Every original worksheet column remains available in attached XLSX.'],
    ]),toc=True)
    page('verification-scope','Verified scope · read this before copying an example',table(['Evidence','Outcome / limit'],[
        ['Original BBS commercial lab','35 initial + 7.5 later actual hours; hourly/day/week customer grouping; USD 2,230 / 182 / 2,260 examples retained.'],
        ['Independent worker schedule','Weekly opening, manual monthly and fourteen-day settlement periods and different expected dates persisted; no automated payroll calendar.'],
        ['Financial issue','Three genuine application-issued final training PDFs, native assigned numbers and totals; no draft watermark removal.'],
        ['Worker payment/reversal','Isolated additional USD 100, reversal, then remaining USD 200: chief net paid USD 400, remaining USD 0. Simulated entries only.'],
        ['Collections / expense reimbursement','Expense USD 182 collected as 100 + 82; portfolio training collection total USD 682, receivable USD 3,990. Parking/hotel/meal USD 180 marked reimbursed. Simulated entries only.'],
        ['Account / assignment / weekly entry','Local BBS LAB account active; independent saved assignment; two daily drafts totaling 9.5 hours, submitted.'],
        ['Returned correction','Eight-hour source returned with reason; linked six-hour owner correction created, submitted and operationally approved in isolated browser. Individual Submit also tested for the second 1.5→1-hour correction.'],
        ['Reporting and external processes','Daily and Technical draft/submission/approval, period refresh, customer report approval and Ready English PDF download passed in isolated browser. Sign-off form/version binding inspected; no genuine signature, email or bank transfer.'],
        ['Accounting','Browser generation blocked by issuer historical date coverage; normal Ready/finalize path described as reference, not a successful runtime result.'],
        ['Broader Owner workspaces','Planning/suppliers/lifecycle/history/Profile reference chapters explain purpose and steps; their entire edge-case surface was not exercised.'],
    ])+note('Use the evidence and checkpoints to assess your own contract/date scope. This guide is an operating reference and worked lab, not a claim that every Owner feature or every production financial operation has passed a universal novice test.'),toc=True)
