"""Native browser completion in a separate all-synthetic portfolio."""

def build_financial_completion():
    revise('invoice-dispatch','Dispatch · explicit email consent and failure recovery',
        route('Billing → Invoices → Manage → Send by email','/billing?view=invoices&lang=en')
        +steps('Open the issued invoice and review the canonical Ready PDF and intended recipient. Downloading a file alone does not deliver it.',
            'Expand <strong>Send by email</strong>. Fill the actual <strong>Invoice recipient email</strong>. In <strong>Send the invoice PDF to this address?</strong> choose <strong>Yes, send this email</strong>, then click <strong>Send by email</strong>. This is explicit delivery consent.',
            'Inspect the recorded email state. <strong>Queued is not sent</strong>; SMTP acceptance would still not prove inbox delivery. For <strong>Email delivery error; automatic retry pending</strong>, inspect the delivery configuration with the operator and the next scheduled retry.',
            'This panel has no manual <strong>Retry</strong> button: configured processing retries transient errors. Ask the operator to investigate terminal/uncertain failures. The tested same recipient/PDF/consent resubmission reused one event; the worker’s second attempt failed again with SMTP unconfigured.',
            'For completed delivery outside the app, retain genuine delivery evidence and use <strong>More actions → Mark sent</strong>. It records manual delivery only; it does not send an email. This control is reference, not a tested real delivery. Collection is separate after money is received.')
        +note('New Accounting demo environment, separate synthetic project C-0002-P-002. The browser queued one message to a reserved example.test training address. SMTP was disabled: the worker failed with JA_SMTP_URL is required, then actually retried and failed again. No customer email or inbox delivery occurred. The sequence proves consent, queue, deduplication and failure handling, not successful external mail transport.'))
    fig('lab-dispatch-image','Email delivery error · actual queued-event retry state','lab-email-failed-retry.png','New Accounting demo: the saved training recipient has Email delivery error; automatic retry pending. Blank/reset form fields do not erase the retained event. Configure the delivery service through the operator before expecting a successful retry.',wide=False)
    page('issued-correction','Issued correction · linked credit and void safeguards',
        route('Billing → Invoices → Manage → Collections and reversals / Create adjustment','/billing?view=invoices&lang=en')
        +steps('Open the original numbered invoice and its collection history. Keep its master, sources and original total preserved.',
            'For a mistaken receipt, expand <strong>Collections and reversals</strong>. Fill <strong>Reversal amount</strong>, <strong>Effective date</strong>, <strong>Reason code: Entry correction</strong> and the required factual reason. Click <strong>Reverse payment</strong>. Reverse the relevant receipt event; a credit note is not a payment reversal.',
            'For an authorized commercial change, expand <strong>Create adjustment</strong>: Credit, Debit or Correction, positive amount and required reason. Credit creates a linked negative draft. Review it, then <strong>Approve → Issue invoice</strong> with the report language and proper numbering policy. There is no direct issued-document Replace control.',
            'Review the new issued credit’s Ready PDF and link to the original. Use <strong>Review credit in ledger</strong> for the allocation/refund process. A credit balance owed to the customer is not a new customer collection.',
            'A void request is blocked while collections remain. Read the instruction and reverse only applicable receipts with genuine reasons before an authorized void. The lab separately created/issued an uncollected USD 10 Debit adjustment, then <strong>More actions → Void reason → Void</strong>. Its number/history/master remained; it was not deleted.')
        +table(['Separate synthetic example','Verified result'],[['Original DEMO-2026-00001','USD 79,800 master unchanged. USD 100 receipt minus USD 50 reversal = USD 50 net collected, USD 79,750 outstanding; void blocked.'],['Linked DEMO-2026-00002','USD −100 issued credit, native PDF Ready/downloaded. Original preserved; credit is not collection.'],['Separate DEMO-2026-00003','Uncollected USD 10 debit issued then voided with a reason; numbered native history retained.']])
        +note('New Accounting demo environment, C-0002-P-002, not any original BBS invoice. Receipt/reversal and credit are synthetic ledger demonstrations, not bank transfers or authority to credit a real customer.'),toc=True)
    fig('lab-issued-adjustment-image','Linked issued credit · Ready PDF and separate credit balance','lab-new-issued-credit-ready.png','New Accounting demo: issued credit DEMO-2026-00002, USD −100. Collected is USD 0 and credit balance USD 100. Review credit in ledger; do not record a customer payment against the credit merely to clear it.',wide=False)
    fig('lab-collection-image','Partial reversal · original receipt and retained reason','lab-new-collection-reversal.png','New Accounting demo: use the existing receipt’s reversal controls. The tested USD 100 receipt and USD 50 reversal remain separate append-only history, with USD 50 net collected.',wide=False)
    fig('lab-initial-settlement-image','Copied settlement start · USD 200 paid, USD 200 remaining','lab-initial-copied-settlement.png','Isolated BBS lifecycle: the copied USD 400 chief obligation already had a simulated USD 200 receipt before the additional-payment test. This differs from the earlier original unpaid baseline; technician 1/2 remain unpaid. The correct BBS project and duration sources stay selected.')
    fig('lab-partial-worker-payment-image','Additional partial payment · USD 300 paid, USD 100 remaining','lab-partial-worker-settlement.png','Isolated BBS lifecycle: Register actual payment added simulated USD 100 to the previous USD 200. Net paid is USD 300 of USD 400. The next screenshot reverses this added USD 100 before recording the remaining USD 200.')
    page('weekly-close-procedure','Weekly close · reviewed sources and a later arrival',
        route('Billing → Billing streams → Manage stream → Close sources','/billing?view=streams&lang=en')
        +steps('Select the intended Weekly stream and its full Monday–Sunday cadence week, not an arbitrary short range. In <strong>Close sources</strong>, fill <strong>Close period start</strong>, <strong>Close period end</strong> and <strong>Report language</strong>. Review readiness prerequisites.',
            'Click <strong>Close sources</strong>. Reopen the stream and period records. The separate synthetic 10–16 August close created the closed period and customer/internal report snapshots.',
            'If genuine late work arrives, enter, submit and review its actual facts through the normal source workflow. Inspect existing closed reports and issued reservations before attempting more billing.',
            'The lab then approved and Finance-reviewed a new 0.5-hour 13 August source. It remained unlocked, unbilled and outside the existing issued invoice. The same week’s Create invoice draft returned the existing numbered invoice unchanged.',
            'Review the contract before choosing a recovery route. This all-in fixed-price project’s separate Manual-stream test produced its full USD 79,800 contract fee, not an hourly charge for the late 30 minutes. The operator reviewed and <strong>Discard draft</strong> with a reason; it was never approved or issued.',
            'Ask responsible Finance/support for the permitted contract adjustment or billing route. Repeating Create invoice does not append late work to an immutable master; a new stream does not turn fixed-price terms into hourly terms.')
        +note('New Accounting demo, synthetic C-0002-P-002. Weekly close, late-source approval and discarded fixed-fee draft were tested. The late source remains unbilled. No self-service reopen/unlock or successful late-source invoice is claimed.'),toc=True)
    fig('lab-weekly-close-image','Weekly stream · Close sources for a chosen week','lab-new-weekly-close-controls.png','New Accounting demo: Close period start/end and Report language precede Close sources. The actual 10–16 August close succeeded; a later approved 30-minute source did not rewrite its existing numbered invoice.',wide=False)
    page('accounting-success','Accounting demo · reviewed October pack finalized',
        '<p>A separate all-synthetic Owner portfolio completed <strong>1–5 October 2026</strong>. The same dates refer to a different database/issuer history from the original BBS example; this does not repair its archived-issuer gap. These are native application Accounting outputs.</p>'
        +steps('Open <strong>Accounting → Generate monthly Accounting Pack</strong>, select the intended dates/language and click <strong>Generate pack</strong>. The browser observed Queued; the operator’s normal artifact worker processed the isolated jobs.',
            'Wait for <strong>PDF, XLSX, Invoice CSV, Expense CSV and JSON</strong> to show Ready. Download through each authenticated control. In this test all five returned HTTP 200 and matched the stored master hashes and byte lengths.',
            'Expand <strong>Review before finalizing</strong>. Inspect <strong>Pending records</strong>, <strong>Unclassified expenses</strong>, <strong>Missing documents</strong>, <strong>Reconciliation issues</strong> and <strong>Changes since generation</strong>. Follow each review link; reconcile amounts to the same scope.',
            'For a real pack, investigate advisories and decide with responsible finance/accounting whether the reviewed cut is fit for finalization. In this October fixture Pending, Unclassified expenses, Missing documents and Reconciliation issues were all <strong>0</strong>, with <strong>None detected</strong> changes.',
            'Click <strong>Finalize reviewed version</strong>. Reopen and verify <strong>final</strong>. All five native downloads before/after finalization returned HTTP 200 with identical stored hashes/lengths. Later source changes require a new reviewed version; finalization does not approve other periods’ pending work.')
        +note('The preceding August training snapshot had Pending 4, Unclassified 30 and Missing documents 30 despite Reconciliation issues 0. That historical incomplete snapshot remains preserved. The October zero counts concern October only; they do not resolve August omissions. Read the following reconciliation page before treating a period contribution as project profit.'),toc=True)
    page('accounting-period-reconciliation','Accounting period · invoices, cash and older work dates',
        '<p>Invoice amounts follow the issue-date period. Frozen older source links accompany the issued master as evidence even when their work dates are outside that period. Operational labor/expense costs remain in their own work/incurrence period; they are not moved to match the invoice.</p>'
        +table(['New Accounting demo, 1–5 October','Native verified result'],[
            ['Active invoices','Two: original USD 79,800 gross and linked USD −100 credit. The USD 10 debit was void by this cut and is excluded; its number/history/native master remain.'],
            ['Net invoiced before tax','USD 75,900'],['Tax / gross invoices','USD 3,800 / USD 79,700'],
            ['Net collected / receivable','USD 100 receipt − USD 50 reversal = USD 50; USD 79,700 − 50 = USD 79,650 outstanding.'],
            ['October operational cost','USD 0 in this fixture. August work costs remain in August.'],
            ['October contribution','USD 75,900 − USD 0 = USD 75,900. This period contribution is not the whole project’s profit; its August cost is outside this window.'],
            ['Historical evidence links','Seven source links and eight manifests retain their authoritative business dates, including August work and October adjustment evidence; 19 items reconcile. Do not change work dates to make the counts match.'],
        ])
        +steps('Compare invoice issue dates, receipt/reversal effective dates and operational work dates before comparing an Accounting Pack to a project export.',
            'A document voided by the selected cut is excluded from that cut. A document voided later can remain in an earlier historical cut; its master is preserved in either case.',
            'If the app reports a source/reconciliation mismatch, retain the period and contact support with the exact record/code. Do not purge old source links or rewrite an issued invoice to force generation.')
        +note('Cross-month and void-date handling were verified in the synthetic October browser replay and boundary tests. Tested boundaries use UTC; non-UTC near-midnight behavior is outside this bounded verification.'),toc=True)
    fig('lab-accounting-review-image','October Ready pack · review counts zero for this scope','lab-new-accounting-review.png','New Accounting demo, 1–5 October: PDF/XLSX/two CSVs/JSON Ready; Pending, Unclassified, Missing documents and Reconciliation issues all zero; no changes detected. The separate August snapshot’s advisories remain historical obligations.')
    fig('lab-accounting-finalized-image','October final version · five canonical downloads verified','lab-new-accounting-final.png','New Accounting demo: Finalize reviewed version saved final for 1–5 October. All five authenticated native downloads matched stored hashes/lengths before and after finalization. Original BBS issued masters and the archived-issuer coverage blocker are unchanged.')
