<script lang="ts">
  import { base } from '$app/paths';
  import { tick, untrack } from 'svelte';
  type Row = Record<string, unknown>;
  type SetupTemplate = {
    id: string;
    name: string;
    version: number;
    config: Record<string, unknown>;
  };

  let {
    projectId,
    currency,
    timezone,
    commercialModel,
    poCap,
    rules,
    legalEntities,
    taxProfiles,
    contacts,
    templates,
    people,
    version,
    rulesFingerprint,
    issuingPrerequisites,
    requestKey,
    canEdit,
    canEditProject,
    onEditProject,
    form,
    t,
  }: {
    projectId: string;
    currency: string;
    timezone: string;
    commercialModel: string;
    poCap: string;
    rules: Row[];
    legalEntities: Row[];
    taxProfiles: Row[];
    contacts: Row[];
    templates: SetupTemplate[];
    people: Array<{
      id: string;
      name: string;
      customerRate: string | null;
      customerRateAmount: string;
      payConfigured: boolean;
      payType: string;
      payAmount: string;
      percentageBasis: string;
      expenseConfigured: boolean;
      activeExpensePayers: string[];
      expensePayer: string;
      workerReimbursement: string;
      clientRecovery: string;
      markupPercent: string;
      assignmentId: string;
      termsEffectiveFrom: string;
      termsFingerprint: string;
      needsReview: boolean;
    }>;
    version: number;
    rulesFingerprint: string;
    issuingPrerequisites: string[];
    requestKey: string;
    canEdit: boolean;
    canEditProject: boolean;
    onEditProject: () => void;
    form?: unknown;
    t: (key: string) => string;
  } = $props();

  const entityChoices = $derived(
    legalEntities.filter((item) => String(item.currency) === currency),
  );
  const matchingTax = (entityId: string) =>
    taxProfiles.filter(
      (item) =>
        String(item.currency) === currency &&
        (item.legal_entity_id === null || String(item.legal_entity_id) === entityId),
    );
  type ActionFeedback = {
    action?: string;
    success?: boolean;
    message?: string;
    fields?: Record<string, string[]>;
    values?: Record<string, string>;
  };
  const feedback = $derived.by((): ActionFeedback | null => {
    if (!form || typeof form !== 'object' || !('action' in form)) return null;
    return form as ActionFeedback;
  });
  const setupFailure = $derived(
    feedback?.action === 'saveBillingSetup' && !feedback.success ? feedback : null,
  );
  const personFailure = $derived(
    (feedback?.action === 'savePersonTerms' || feedback?.action === 'savePeopleTerms') &&
      !feedback.success
      ? feedback
      : null,
  );
  const personAction = $derived(
    feedback?.action === 'savePersonTerms' || feedback?.action === 'savePeopleTerms',
  );
  const failedValues = $derived(setupFailure?.values ?? {});
  const personFailedValues = $derived(personFailure?.values ?? {});
  const failedBatchRows = $derived.by(() => {
    try {
      const rows = JSON.parse(personFailedValues.rows ?? '[]');
      return Array.isArray(rows) ? (rows as Array<Record<string, string>>) : [];
    } catch {
      return [] as Array<Record<string, string>>;
    }
  });
  const personFieldError = (workerId: string, name: string): string => {
    if (personFailedValues.workerId === workerId)
      return personFailure?.fields?.[name]?.join(', ') ?? '';
    const batchIndex = failedBatchRows.findIndex((row) => row.workerId === workerId);
    return batchIndex < 0
      ? ''
      : (personFailure?.fields?.[`${batchIndex}.${name}`]?.join(', ') ?? '');
  };
  const fieldError = (name: string): string => setupFailure?.fields?.[name]?.join(', ') ?? '';
  const errorId = (name: string): string => `billing-setup-${name}-error`;
  function failedStep(): number {
    const fields = Object.keys(setupFailure?.fields ?? {});
    if (fields.some((field) => ['mode', 'effectiveFrom'].includes(field))) return 1;
    if (fields.some((field) => ['selectedTemplateId'].includes(field))) return 1;
    if (fields.some((field) => ['templateName', 'saveAsTemplate'].includes(field))) return 4;
    if (
      fields.some((field) =>
        [
          'legalEntityId',
          'laborTaxProfileId',
          'expenseTaxProfileId',
          'cadenceType',
          'expenseCadenceType',
          'anchorDate',
          'expenseAnchorDate',
          'invoiceLayout',
          'groupingMode',
          'billingContactId',
          'recipientEmail',
          'paymentTermsDays',
          'autoGenerateDraft',
        ].includes(field),
      )
    )
      return 2;
    return 4;
  }

  // The parent keys this component by saved setup version, so this snapshot is
  // refreshed after each successful save while preserving in-progress edits.
  function initialValues() {
    const saved = (key: string, fallback: string): string =>
      typeof failedValues[key] === 'string' ? failedValues[key] : fallback;
    const active = rules
      .filter((rule) => Number(rule.enabled ?? 1) === 1)
      .sort(
        (a, b) =>
          String(b.effective_from).localeCompare(String(a.effective_from)) ||
          Number(b.version) - Number(a.version),
      );
    const labor = active.find((rule) => rule.stream_type === 'labor');
    const expense = active.find(
      (rule) =>
        rule.stream_type === 'expense' &&
        labor &&
        String(rule.effective_from) <= String(labor.effective_from) &&
        (!rule.effective_to || String(rule.effective_to) >= String(labor.effective_from)),
    );
    const firstEntityId = String(
      labor?.legal_entity_id ??
        legalEntities.find((item) => String(item.currency) === currency)?.id ??
        '',
    );
    return {
      mode: saved(
        'mode',
        !labor || Number(labor.include_expenses ?? 0) === 1 ? 'combined' : 'separate',
      ) as 'combined' | 'separate',
      effectiveFrom: saved(
        'effectiveFrom',
        String(labor?.effective_from ?? '') > projectDate()
          ? String(labor?.effective_from)
          : projectDate(),
      ),
      legalEntityId: saved('legalEntityId', firstEntityId),
      laborTaxProfileId: saved(
        'laborTaxProfileId',
        String(labor?.tax_profile_id ?? matchingTax(firstEntityId)[0]?.id ?? ''),
      ),
      expenseTaxProfileId: saved(
        'expenseTaxProfileId',
        String(
          expense?.tax_profile_id ??
            labor?.tax_profile_id ??
            matchingTax(firstEntityId)[0]?.id ??
            '',
        ),
      ),
      cadenceType: saved('cadenceType', String(labor?.cadence_type ?? 'monthly')),
      expenseCadenceType: saved(
        'expenseCadenceType',
        String(expense?.cadence_type ?? labor?.cadence_type ?? 'monthly'),
      ),
      anchorDate: saved('anchorDate', String(labor?.anchor_date ?? '')),
      expenseAnchorDate: saved('expenseAnchorDate', String(expense?.anchor_date ?? '')),
      invoiceLayout: saved('invoiceLayout', String(labor?.template_id ?? 'default')),
      groupingMode: saved('groupingMode', String(labor?.grouping_mode ?? 'by_worker')),
      billingContactId: saved('billingContactId', String(labor?.billing_contact_id ?? '')),
      recipientEmail: saved('recipientEmail', String(labor?.recipient_email ?? '')),
      paymentTermsDays: Number(saved('paymentTermsDays', String(labor?.payment_terms_days ?? 30))),
      autoGenerateDraft:
        saved(
          'autoGenerateDraft',
          Number(labor?.auto_generate_draft ?? 0) === 1 ? 'true' : 'false',
        ) === 'true',
    };
  }
  function projectDate(): string {
    const parts = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).formatToParts(new Date());
    const value = (kind: 'year' | 'month' | 'day') =>
      parts.find((part) => part.type === kind)?.value ?? '';
    return `${value('year')}-${value('month')}-${value('day')}`;
  }
  const initial = initialValues();
  // Initial form state is intentionally snapshotted; a successful save remounts
  // this component under the new setup version.
  const initialFailure = untrack(() => ({
    active: Boolean(setupFailure),
    personActive: Boolean(personAction),
    step: failedStep(),
    values: { ...failedValues },
  }));
  let step = $state(
    initialFailure.personActive ? 3 : initialFailure.active ? initialFailure.step : 1,
  );
  type PersonDraft = {
    effectiveFrom: string;
    customerHourlyRate: string;
    workerPayType: string;
    workerPayAmount: string;
    percentageBasis: string;
    expensePayer: string;
    workerReimbursement: string;
    clientRecovery: string;
    markupPercent: string;
  };
  const initialPersonDrafts = untrack(
    () =>
      Object.fromEntries(
        people.map((person) => {
          const failed =
            personFailedValues.workerId === person.id
              ? personFailedValues
              : (failedBatchRows.find((row) => row.workerId === person.id) ?? {});
          const value = (key: keyof PersonDraft, fallback: string) => failed[key] ?? fallback;
          return [
            person.id,
            {
              effectiveFrom: value('effectiveFrom', person.termsEffectiveFrom),
              customerHourlyRate: value('customerHourlyRate', person.customerRateAmount),
              workerPayType: value('workerPayType', person.payType),
              workerPayAmount: value('workerPayAmount', person.payAmount),
              percentageBasis: value('percentageBasis', person.percentageBasis),
              expensePayer: value('expensePayer', person.expensePayer),
              workerReimbursement: value('workerReimbursement', person.workerReimbursement),
              clientRecovery: value('clientRecovery', person.clientRecovery),
              markupPercent: value('markupPercent', person.markupPercent),
            } satisfies PersonDraft,
          ];
        }),
      ) as Record<string, PersonDraft>,
  );
  let personDrafts = $state(initialPersonDrafts);
  let personSubmitting = $state('');
  let bulkSourceId = $state(untrack(() => people[0]?.id ?? ''));
  let selectedPersonIds = $state<string[]>(
    untrack(() =>
      failedBatchRows
        .map((row) => row.workerId)
        .filter((id): id is string => typeof id === 'string' && id.length > 0),
    ),
  );
  let batchSubmitting = $state(false);
  let selectedTemplateId = $state(initialFailure.values.selectedTemplateId ?? '');
  let mode = $state<'combined' | 'separate'>(initial.mode);
  let effectiveFrom = $state(initial.effectiveFrom);
  let legalEntityId = $state(initial.legalEntityId);
  let laborTaxProfileId = $state(initial.laborTaxProfileId);
  let expenseTaxProfileId = $state(initial.expenseTaxProfileId);
  let cadenceType = $state(initial.cadenceType);
  let expenseCadenceType = $state(initial.expenseCadenceType);
  let anchorDate = $state(initial.anchorDate);
  let expenseAnchorDate = $state(initial.expenseAnchorDate);
  let invoiceLayout = $state(initial.invoiceLayout);
  let groupingMode = $state(initial.groupingMode);
  let billingContactId = $state(initial.billingContactId);
  let recipientEmail = $state(initial.recipientEmail);
  let paymentTermsDays = $state(initial.paymentTermsDays);
  let autoGenerateDraft = $state(initial.autoGenerateDraft);
  let saveAsTemplate = $state(initialFailure.values.saveAsTemplate === 'true');
  let templateName = $state(initialFailure.values.templateName ?? '');
  let submitted = $state(false);

  $effect(() => {
    if (setupFailure) submitted = false;
    if (personFailure) {
      personSubmitting = '';
      batchSubmitting = false;
    }
  });

  $effect(() => {
    if (!setupFailure?.fields) return;
    void tick().then(() => {
      const firstInvalid = document.querySelector<HTMLElement>(
        '.billing-setup [aria-invalid="true"]',
      );
      firstInvalid?.focus();
    });
  });

  function copyDraftToSelected(): void {
    const source = personDrafts[bulkSourceId];
    if (!source) return;
    for (const workerId of selectedPersonIds) {
      if (workerId === bulkSourceId || !personDrafts[workerId]) continue;
      personDrafts[workerId] = {
        ...source,
        effectiveFrom: personDrafts[workerId].effectiveFrom,
      };
    }
  }

  function personPayload(person: (typeof people)[number]) {
    const draft = personDrafts[person.id];
    if (!draft) return null;
    return {
      projectId,
      projectMemberId: person.assignmentId,
      workerId: person.id,
      expectedFingerprint: person.termsFingerprint,
      effectiveFrom: draft.effectiveFrom,
      customerHourlyRate: draft.customerHourlyRate,
      workerPayType: draft.workerPayType,
      workerPayAmount: draft.workerPayAmount,
      percentageBasis: draft.percentageBasis,
      expensePayer: draft.expensePayer,
      workerReimbursement: draft.workerReimbursement,
      clientRecovery: draft.clientRecovery,
      markupPercent: draft.clientRecovery === 'markup' ? draft.markupPercent : '',
    };
  }

  const availableTaxes = $derived(matchingTax(legalEntityId));
  const missingPeople = $derived(
    people.filter(
      (person) =>
        person.needsReview ||
        !person.customerRate ||
        !person.payConfigured ||
        !person.expenseConfigured,
    ),
  );
  const selectedTemplate = $derived(templates.find((entry) => entry.id === selectedTemplateId));
  const templateModified = $derived(
    Boolean(
      selectedTemplate &&
      [
        ['mode', mode],
        ['legalEntityId', legalEntityId],
        ['laborTaxProfileId', laborTaxProfileId],
        ...(mode === 'separate' ? [['expenseTaxProfileId', expenseTaxProfileId]] : []),
        ['cadenceType', cadenceType],
        ...(mode === 'separate' ? [['expenseCadenceType', expenseCadenceType]] : []),
        ['anchorDate', anchorDate],
        ...(mode === 'separate' ? [['expenseAnchorDate', expenseAnchorDate]] : []),
        ['invoiceLayout', invoiceLayout],
        ['groupingMode', groupingMode],
        ['paymentTermsDays', paymentTermsDays],
        ['autoGenerateDraft', autoGenerateDraft],
      ].some(([key, value]) => selectedTemplate.config[String(key)] !== value),
    ),
  );

  function applyTemplate(id: string): void {
    selectedTemplateId = id;
    const selected = templates.find((entry) => entry.id === id);
    if (!selected) return;
    const values = selected.config;
    mode = values.mode === 'separate' ? 'separate' : 'combined';
    const entity = String(values.legalEntityId ?? '');
    if (entityChoices.some((entry) => String(entry.id) === entity)) legalEntityId = entity;
    const laborTax = String(values.laborTaxProfileId ?? '');
    if (matchingTax(legalEntityId).some((entry) => String(entry.id) === laborTax))
      laborTaxProfileId = laborTax;
    const expenseTax = String(values.expenseTaxProfileId ?? '');
    if (matchingTax(legalEntityId).some((entry) => String(entry.id) === expenseTax))
      expenseTaxProfileId = expenseTax;
    cadenceType = String(values.cadenceType ?? cadenceType);
    expenseCadenceType = String(values.expenseCadenceType ?? expenseCadenceType);
    anchorDate = String(values.anchorDate ?? '');
    expenseAnchorDate = String(values.expenseAnchorDate ?? '');
    invoiceLayout = String(values.invoiceLayout ?? invoiceLayout);
    groupingMode = String(values.groupingMode ?? groupingMode);
    paymentTermsDays = Number(values.paymentTermsDays ?? paymentTermsDays);
    autoGenerateDraft = values.autoGenerateDraft === true;
  }

  function next(): void {
    if (step < 4) step += 1;
  }

  function previous(): void {
    if (step > 1) step -= 1;
  }
</script>

<section class="billing-setup" aria-label={t('Project billing setup')}>
  <div class="billing-setup__intro">
    <div>
      <h3>{t('Configure this project’s invoices')}</h3>
      <p>
        {t(
          'Choose how approved hours and recoverable expenses become customer invoices. Each person’s rates and expense agreement stay separate.',
        )}
      </p>
    </div>
    <span>{t('Step')} {step} / 4</span>
  </div>

  {#if version > 0}
    <div class:warning={issuingPrerequisites.length > 0} class="readiness-note" role="status">
      <strong>{t('Billing setup saved')}</strong>
      {#if issuingPrerequisites.length > 0}
        <p>{t('Invoice issuance still needs these prerequisites:')}</p>
        <ul>
          {#each [...new Set(issuingPrerequisites)] as issue}
            <li>
              {issue === 'canonical_legal_entity_revision_required'
                ? t('Assign an issuing legal entity revision to this project.')
                : issue === 'missing_accountant_approved_number_policy'
                  ? t('Approve an invoice numbering policy for the issuer.')
                  : issue === 'tax_profile_not_effective'
                    ? t('Choose a tax profile effective for this billing date.')
                    : t('Complete the project billing setup.')}
            </li>
          {/each}
        </ul>
        <a href={`${base}/app/finance?view=commercial&project=${encodeURIComponent(projectId)}`}
          >{t('Open finance configuration')}</a
        >
      {:else}
        <p>
          {t(
            'Issuing prerequisites are configured. Invoice readiness also checks approved sources and period rules.',
          )}
        </p>
      {/if}
    </div>
  {/if}

  {#if canEdit}
    {#if setupFailure}
      <div class="warning" role="alert">
        <strong>{t('Check billing setup fields')}</strong>
        {#if setupFailure.message}<p>{setupFailure.message}</p>{/if}
        {#if setupFailure.fields}
          <ul>
            {#each Object.entries(setupFailure.fields) as [field, messages]}<li>
                {t(field)}: {messages.join(', ')}
              </li>{/each}
          </ul>
        {/if}
      </div>
    {/if}
    <form method="POST" action="?/saveBillingSetup&tab=billing" onsubmit={() => (submitted = true)}>
      <input type="hidden" name="projectId" value={projectId} />
      <input type="hidden" name="expectedVersion" value={version} />
      <input type="hidden" name="expectedRulesFingerprint" value={rulesFingerprint} />
      <input type="hidden" name="requestKey" value={requestKey} />
      <input type="hidden" name="selectedTemplateId" value={selectedTemplateId} />
      <input type="hidden" name="mode" value={mode} />
      <input type="hidden" name="effectiveFrom" value={effectiveFrom} />
      <input type="hidden" name="legalEntityId" value={legalEntityId} />
      <input type="hidden" name="laborTaxProfileId" value={laborTaxProfileId} />
      <input type="hidden" name="expenseTaxProfileId" value={expenseTaxProfileId} />
      <input type="hidden" name="cadenceType" value={cadenceType} />
      <input type="hidden" name="expenseCadenceType" value={expenseCadenceType} />
      <input type="hidden" name="anchorDate" value={anchorDate} />
      <input type="hidden" name="expenseAnchorDate" value={expenseAnchorDate} />
      <input type="hidden" name="invoiceLayout" value={invoiceLayout} />
      <input type="hidden" name="groupingMode" value={groupingMode} />
      <input type="hidden" name="billingContactId" value={billingContactId} />
      <input type="hidden" name="recipientEmail" value={recipientEmail} />
      <input type="hidden" name="paymentTermsDays" value={paymentTermsDays} />
      <input type="hidden" name="autoGenerateDraft" value={autoGenerateDraft ? 'true' : 'false'} />
      <input type="hidden" name="saveAsTemplate" value={saveAsTemplate ? 'true' : 'false'} />
      <input type="hidden" name="templateName" value={templateName} />

      {#if step === 1}
        <fieldset>
          <legend>{t('1. Invoice arrangement')}</legend>
          <label
            >{t('Start from a saved template')}
            <select
              value={selectedTemplateId}
              onchange={(event) => applyTemplate(event.currentTarget.value)}
              aria-invalid={Boolean(fieldError('selectedTemplateId'))}
              aria-describedby={fieldError('selectedTemplateId')
                ? errorId('selectedTemplateId')
                : undefined}
            >
              <option value="">{t('Configure from scratch')}</option>
              {#each templates as template}
                <option value={template.id}>{template.name} · v{template.version}</option>
              {/each}
            </select>
          </label>
          {#if fieldError('selectedTemplateId')}<small
              id={errorId('selectedTemplateId')}
              class="warning">{fieldError('selectedTemplateId')}</small
            >{/if}
          <p class="hint">
            {t('A template fills defaults only. Review the project and each person before saving.')}
          </p>
          <p class="hint">
            {t('Current commercial model')}: <strong>{commercialModel}</strong> · {t(
              'Current PO cap',
            )}: <strong>{poCap}</strong>. {#if canEditProject}<button
                type="button"
                class="text-button"
                onclick={onEditProject}>{t('Edit project commercial model or cap')}</button
              >{/if}
          </p>
          <div class="choice-grid">
            <label class:selected={mode === 'combined'}>
              <input type="radio" value="combined" bind:group={mode} />
              <strong>{t('One invoice with two sections')}</strong>
              <small
                >{t(
                  'Approved labor and billable expenses appear on the same invoice, with separate section totals.',
                )}</small
              >
            </label>
            <label class:selected={mode === 'separate'}>
              <input type="radio" value="separate" bind:group={mode} />
              <strong>{t('Two separate invoices')}</strong>
              <small
                >{t(
                  'Labor and expenses use separate invoice drafts and may use different cadence and tax profiles.',
                )}</small
              >
            </label>
          </div>
          <label
            >{t('Configuration effective from')}
            <input
              type="date"
              bind:value={effectiveFrom}
              required
              aria-invalid={Boolean(fieldError('effectiveFrom'))}
              aria-describedby={fieldError('effectiveFrom') ? errorId('effectiveFrom') : undefined}
            />
          </label>
          {#if fieldError('effectiveFrom')}<small id={errorId('effectiveFrom')} class="warning"
              >{fieldError('effectiveFrom')}</small
            >{/if}
        </fieldset>
      {:else if step === 2}
        <fieldset>
          <legend>{t('2. Billing details')}</legend>
          <div class="field-grid">
            <label
              >{t('Issuing legal entity')}
              <select
                bind:value={legalEntityId}
                required
                aria-invalid={Boolean(fieldError('legalEntityId'))}
                aria-describedby={fieldError('legalEntityId')
                  ? errorId('legalEntityId')
                  : undefined}
                onchange={() => {
                  if (
                    !matchingTax(legalEntityId).some(
                      (item) => String(item.id) === laborTaxProfileId,
                    )
                  )
                    laborTaxProfileId = '';
                  if (
                    !matchingTax(legalEntityId).some(
                      (item) => String(item.id) === expenseTaxProfileId,
                    )
                  )
                    expenseTaxProfileId = '';
                }}
              >
                <option value="">{t('Select entity')}</option>
                {#each entityChoices as entity}<option value={entity.id}
                    >{entity.legal_name} ({entity.currency})</option
                  >{/each}
              </select>
            </label>
            {#if fieldError('legalEntityId')}<small id={errorId('legalEntityId')} class="warning"
                >{fieldError('legalEntityId')}</small
              >{/if}
            <label>{t('Project currency')}<input value={currency} readonly /></label>
            <label
              >{t('Labor tax profile')}
              <select
                aria-label={t('Labor tax profile')}
                bind:value={laborTaxProfileId}
                required
                aria-invalid={Boolean(fieldError('laborTaxProfileId'))}
                aria-describedby={fieldError('laborTaxProfileId')
                  ? errorId('laborTaxProfileId')
                  : undefined}
              >
                <option value="">{t('Select tax profile')}</option>
                {#each availableTaxes as tax}<option value={tax.id}>{tax.name}</option>{/each}
              </select>
            </label>
            {#if fieldError('laborTaxProfileId')}<small
                id={errorId('laborTaxProfileId')}
                class="warning">{fieldError('laborTaxProfileId')}</small
              >{/if}
            <label
              >{t('Labor billing cadence')}
              <select
                bind:value={cadenceType}
                aria-invalid={Boolean(fieldError('cadenceType'))}
                aria-describedby={fieldError('cadenceType') ? errorId('cadenceType') : undefined}
              >
                <option value="weekly">{t('Weekly')}</option><option value="every_14_days"
                  >{t('Every 14 days')}</option
                >
                <option value="semi_monthly">{t('Semi-monthly')}</option><option value="monthly"
                  >{t('Monthly')}</option
                >
                <option value="manual">{t('Manual')}</option>
              </select>
            </label>
            {#if fieldError('cadenceType')}<small id={errorId('cadenceType')} class="warning"
                >{fieldError('cadenceType')}</small
              >{/if}
            {#if cadenceType === 'every_14_days'}<label
                >{t('Labor cadence anchor date')}<input
                  type="date"
                  bind:value={anchorDate}
                  required
                  aria-invalid={Boolean(fieldError('anchorDate'))}
                  aria-describedby={fieldError('anchorDate') ? errorId('anchorDate') : undefined}
                /></label
              >{/if}
            {#if fieldError('anchorDate')}<small id={errorId('anchorDate')} class="warning"
                >{fieldError('anchorDate')}</small
              >{/if}
            {#if mode === 'separate'}
              <label
                >{t('Expense tax profile')}
                <select
                  aria-label={t('Expense tax profile')}
                  bind:value={expenseTaxProfileId}
                  required
                  aria-invalid={Boolean(fieldError('expenseTaxProfileId'))}
                  aria-describedby={fieldError('expenseTaxProfileId')
                    ? errorId('expenseTaxProfileId')
                    : undefined}
                >
                  <option value="">{t('Select tax profile')}</option>
                  {#each availableTaxes as tax}<option value={tax.id}>{tax.name}</option>{/each}
                </select>
              </label>
              {#if fieldError('expenseTaxProfileId')}<small
                  id={errorId('expenseTaxProfileId')}
                  class="warning">{fieldError('expenseTaxProfileId')}</small
                >{/if}
              <label
                >{t('Expense billing cadence')}
                <select
                  bind:value={expenseCadenceType}
                  aria-invalid={Boolean(fieldError('expenseCadenceType'))}
                  aria-describedby={fieldError('expenseCadenceType')
                    ? errorId('expenseCadenceType')
                    : undefined}
                >
                  <option value="weekly">{t('Weekly')}</option><option value="every_14_days"
                    >{t('Every 14 days')}</option
                  >
                  <option value="semi_monthly">{t('Semi-monthly')}</option><option value="monthly"
                    >{t('Monthly')}</option
                  >
                  <option value="manual">{t('Manual')}</option>
                </select>
              </label>
              {#if fieldError('expenseCadenceType')}<small
                  id={errorId('expenseCadenceType')}
                  class="warning">{fieldError('expenseCadenceType')}</small
                >{/if}
              {#if expenseCadenceType === 'every_14_days'}<label
                  >{t('Expense cadence anchor date')}<input
                    type="date"
                    bind:value={expenseAnchorDate}
                    required
                    aria-invalid={Boolean(fieldError('expenseAnchorDate'))}
                    aria-describedby={fieldError('expenseAnchorDate')
                      ? errorId('expenseAnchorDate')
                      : undefined}
                  /></label
                >{/if}
              {#if fieldError('expenseAnchorDate')}<small
                  id={errorId('expenseAnchorDate')}
                  class="warning">{fieldError('expenseAnchorDate')}</small
                >{/if}
            {/if}
            <label
              >{t('Invoice layout')}
              <select
                bind:value={invoiceLayout}
                aria-invalid={Boolean(fieldError('invoiceLayout'))}
                aria-describedby={fieldError('invoiceLayout')
                  ? errorId('invoiceLayout')
                  : undefined}
              >
                <option value="default">{t('Standard')}</option><option value="labor-detailed"
                  >{t('Detailed')}</option
                >
                <option value="labor-summary">{t('Summary')}</option>
              </select>
            </label>
            {#if fieldError('invoiceLayout')}<small id={errorId('invoiceLayout')} class="warning"
                >{fieldError('invoiceLayout')}</small
              >{/if}
            <label
              >{t('Line grouping')}
              <select
                bind:value={groupingMode}
                aria-invalid={Boolean(fieldError('groupingMode'))}
                aria-describedby={fieldError('groupingMode') ? errorId('groupingMode') : undefined}
              >
                <option value="by_worker">{t('By worker')}</option><option value="by_day"
                  >{t('By day')}</option
                >
                <option value="by_category">{t('By category')}</option><option value="detail"
                  >{t('Detailed')}</option
                >
                <option value="summary">{t('Summary')}</option>
              </select>
            </label>
            {#if fieldError('groupingMode')}<small id={errorId('groupingMode')} class="warning"
                >{fieldError('groupingMode')}</small
              >{/if}
            <label
              >{t('Billing contact')}
              <select
                bind:value={billingContactId}
                aria-invalid={Boolean(fieldError('billingContactId'))}
                aria-describedby={fieldError('billingContactId')
                  ? errorId('billingContactId')
                  : undefined}
              >
                <option value="">{t('Use client default')}</option>
                {#each contacts as contact}<option value={contact.id}>{contact.name}</option>{/each}
              </select>
            </label>
            {#if fieldError('billingContactId')}<small
                id={errorId('billingContactId')}
                class="warning">{fieldError('billingContactId')}</small
              >{/if}
            <label
              >{t('Recipient email')}
              <input
                type="email"
                bind:value={recipientEmail}
                autocomplete="email"
                aria-invalid={Boolean(fieldError('recipientEmail'))}
                aria-describedby={fieldError('recipientEmail')
                  ? errorId('recipientEmail')
                  : undefined}
              />
            </label>
            {#if fieldError('recipientEmail')}<small id={errorId('recipientEmail')} class="warning"
                >{fieldError('recipientEmail')}</small
              >{/if}
            <label
              >{t('Payment terms (days)')}
              <input
                type="number"
                min="0"
                max="365"
                step="1"
                bind:value={paymentTermsDays}
                required
                aria-invalid={Boolean(fieldError('paymentTermsDays'))}
                aria-describedby={fieldError('paymentTermsDays')
                  ? errorId('paymentTermsDays')
                  : undefined}
              />
            </label>
            {#if fieldError('paymentTermsDays')}<small
                id={errorId('paymentTermsDays')}
                class="warning">{fieldError('paymentTermsDays')}</small
              >{/if}
          </div>
          <label class="check"
            ><input type="checkbox" bind:checked={autoGenerateDraft} />{t(
              'Automatically prepare drafts for review',
            )}</label
          >
          <p class="hint">{t('Invoices are never issued or sent automatically.')}</p>
          {#if entityChoices.length === 0 || availableTaxes.length === 0}
            <p class="warning" role="alert">
              {t(
                'An active issuing entity and tax profile in the project currency are required before invoices can be configured.',
              )}
              <a
                href={`${base}/app/finance?view=commercial&project=${encodeURIComponent(projectId)}`}
                >{t('Configure legal entities and tax profiles')}</a
              >
            </p>
          {/if}
        </fieldset>
      {:else if step === 3}
        <fieldset>
          <legend>{t('3. Review each person')}</legend>
          <p>
            {t(
              'Set each assigned person’s customer charge, compensation and expense treatment here. Save each person before continuing.',
            )}
          </p>
          {#if personFailure}<div class="warning" role="alert">
              <strong>{t('Check person terms fields')}</strong>{#if personFailure.message}<p>
                  {personFailure.message}
                </p>{/if}
            </div>{/if}
          {#if canEdit && people.length > 1}
            <div class="bulk-defaults">
              <label
                >{t('Copy draft terms from')}
                <select bind:value={bulkSourceId}>
                  {#each people as person}<option value={person.id}>{person.name}</option>{/each}
                </select>
              </label>
              <button
                type="button"
                class="secondary-button"
                disabled={selectedPersonIds.length === 0}
                onclick={copyDraftToSelected}
              >
                {t('Apply to selected people')}
              </button>
              <button
                type="button"
                class="primary-button"
                disabled={selectedPersonIds.length === 0 || batchSubmitting}
                onclick={() => {
                  batchSubmitting = true;
                  (
                    document.getElementById('selected-person-terms') as HTMLFormElement
                  )?.requestSubmit();
                }}>{batchSubmitting ? t('Saving…') : t('Save selected people')}</button
              >
              <p class="hint">
                {t(
                  'This copies unsaved draft values only. Review selected people, then save them together or individually. Existing agreements are unchanged until saved.',
                )}
              </p>
            </div>
          {/if}
          <div class="people-list">
            {#each people as person}
              {@const draft = personDrafts[person.id]}
              {#if draft}
                <div class="person-terms">
                  <h4>{person.name}</h4>
                  {#if canEdit && people.length > 1}
                    <label class="bulk-select"
                      ><input
                        type="checkbox"
                        checked={selectedPersonIds.includes(person.id)}
                        onchange={(event) => {
                          selectedPersonIds = event.currentTarget.checked
                            ? [...selectedPersonIds, person.id]
                            : selectedPersonIds.filter((id) => id !== person.id);
                        }}
                      />{t('Apply draft defaults to this person')}</label
                    >
                  {/if}
                  <p class="hint">
                    {t('Current customer rate')}: {person.customerRate ?? t('Missing')} · {t(
                      'Worker pay',
                    )}: {person.payConfigured ? t('Configured') : t('Missing')} · {t(
                      'Expense policy',
                    )}: {person.expenseConfigured ? t('Configured') : t('Missing')}
                  </p>
                  {#if person.needsReview}<p class="warning">{t('Needs review')}</p>{/if}
                  {#if canEdit}
                    <div class="person-fields">
                      <label
                        >{t('Terms effective from')}<input
                          type="date"
                          bind:value={draft.effectiveFrom}
                          aria-invalid={Boolean(personFieldError(person.id, 'effectiveFrom'))}
                          required
                        /></label
                      >
                      <label
                        >{t('Customer hourly rate')} ({currency})<input
                          type="text"
                          inputmode="decimal"
                          bind:value={draft.customerHourlyRate}
                          aria-invalid={Boolean(personFieldError(person.id, 'customerHourlyRate'))}
                          required
                        /></label
                      >
                      <label
                        >{t('Worker compensation method')}<select bind:value={draft.workerPayType}>
                          <option value="Hourly">{t('Hourly')}</option><option value="Daily"
                            >{t('Daily')}</option
                          >
                          <option value="FixedPerBillingPeriod"
                            >{t('Fixed per billing period')}</option
                          >
                          <option value="FixedProjectAmount">{t('Fixed project amount')}</option>
                          <option value="PercentageOfEligibleClientLabor"
                            >{t('Percentage of eligible client labor')}</option
                          >
                        </select></label
                      >
                      <label
                        >{draft.workerPayType === 'PercentageOfEligibleClientLabor'
                          ? t('Worker compensation percentage')
                          : t('Worker compensation rate')}
                        {draft.workerPayType === 'PercentageOfEligibleClientLabor'
                          ? '(%)'
                          : `(${currency})`}<input
                          type="text"
                          inputmode="decimal"
                          bind:value={draft.workerPayAmount}
                          aria-invalid={Boolean(personFieldError(person.id, 'workerPayAmount'))}
                          required
                        /></label
                      >
                      {#if draft.workerPayType === 'PercentageOfEligibleClientLabor'}<label
                          >{t('Percentage basis')}<select bind:value={draft.percentageBasis}
                            ><option value="CLIENT_LABOR_BEFORE_TAX"
                              >{t('Client labor before tax')}</option
                            ><option value="CLIENT_LABOR_AFTER_APPROVED_DISCOUNT"
                              >{t('Client labor after approved discount')}</option
                            ><option value="ISSUED_ELIGIBLE_LABOR"
                              >{t('Issued eligible labor')}</option
                            ><option value="COLLECTED_ELIGIBLE_LABOR"
                              >{t('Collected eligible labor')}</option
                            ></select
                          ></label
                        >{/if}
                      <label
                        >{t('Expense payer')}<select
                          bind:value={draft.expensePayer}
                          onchange={() => {
                            if (draft.expensePayer !== 'worker') draft.workerReimbursement = 'none';
                            if (draft.expensePayer === 'client')
                              draft.clientRecovery = 'client_direct';
                            else if (draft.clientRecovery === 'client_direct')
                              draft.clientRecovery = 'at_cost';
                          }}
                          ><option value="worker">{t('Worker')}</option><option value="company_card"
                            >{t('Company card')}</option
                          ><option value="company_direct">{t('Company direct')}</option><option
                            value="client">{t('Client')}</option
                          ><option value="third_party">{t('Third party')}</option></select
                        ></label
                      >
                      <label
                        >{t('Reimburse worker')}<select
                          bind:value={draft.workerReimbursement}
                          disabled={draft.expensePayer !== 'worker'}
                          ><option value="at_cost">{t('At cost')}</option><option value="none"
                            >{t('No reimbursement')}</option
                          ></select
                        ></label
                      >
                      <label
                        >{t('Charge customer for expense')}<select
                          bind:value={draft.clientRecovery}
                          disabled={draft.expensePayer === 'client'}
                          ><option value="at_cost">{t('At cost')}</option><option value="markup"
                            >{t('Cost plus markup')}</option
                          ><option value="included">{t('Included in labor price')}</option><option
                            value="non_billable">{t('Do not charge customer')}</option
                          ><option value="client_direct">{t('Client pays directly')}</option
                          ></select
                        ></label
                      >
                      {#if draft.clientRecovery === 'markup'}<label
                          >{t('Expense markup percentage')}<input
                            type="text"
                            inputmode="decimal"
                            bind:value={draft.markupPercent}
                            aria-invalid={Boolean(personFieldError(person.id, 'markupPercent'))}
                            required
                          /></label
                        >{/if}
                    </div>
                    <p class="hint">
                      {t(
                        'Expense treatment applies to the selected payer only. Policies for other payers remain active.',
                      )}
                    </p>
                    {#if person.activeExpensePayers.filter((payer) => payer !== draft.expensePayer).length > 0}
                      <p class="warning">
                        {t('Other active expense payer policies')}: {person.activeExpensePayers
                          .filter((payer) => payer !== draft.expensePayer)
                          .join(', ')}. {t(
                          'To stop reimbursing worker-paid claims, select Worker and No reimbursement.',
                        )}
                      </p>
                    {/if}
                    <p class="hint">
                      {t(
                        'Existing terms on the same date are immutable. Choose a later effective date to change them.',
                      )}
                    </p>
                    {#if personFailure?.fields && (personFailedValues.workerId === person.id || failedBatchRows.some((row) => row.workerId === person.id))}
                      {@const batchIndex = failedBatchRows.findIndex(
                        (row) => row.workerId === person.id,
                      )}
                      <ul class="warning">
                        {#each Object.entries(personFailure.fields).filter(([field]) => personFailedValues.workerId === person.id || field.startsWith(`${batchIndex}.`)) as [field, messages]}
                          <li>{t(field.split('.').at(-1) ?? field)}: {messages.join(', ')}</li>
                        {/each}
                      </ul>
                    {/if}
                    <button
                      type="button"
                      class="secondary-button"
                      disabled={personSubmitting === person.id}
                      onclick={() => {
                        personSubmitting = person.id;
                        (
                          document.getElementById(`person-terms-${person.id}`) as HTMLFormElement
                        )?.requestSubmit();
                      }}
                      >{personSubmitting === person.id
                        ? t('Saving…')
                        : t('Save person terms')}</button
                    >
                  {/if}
                </div>
              {/if}
            {:else}<p class="warning">
                {t('No workers are assigned. Add people before issuing invoices.')}
              </p>{/each}
          </div>
          {#if missingPeople.length > 0}<p class="warning">
              {missingPeople.length}
              {t('person(s) still need commercial terms before their records can be billed.')}
            </p>{/if}
          <a href={`${base}/app/finance?view=commercial&project=${encodeURIComponent(projectId)}`}
            >{t('Advanced commercial rules')}</a
          >
        </fieldset>
      {:else}
        <fieldset>
          <legend>{t('4. Review and save')}</legend>
          <dl class="review">
            <div>
              <dt>{t('Invoice arrangement')}</dt>
              <dd>
                {mode === 'combined'
                  ? t('One invoice with two sections')
                  : t('Two separate invoices')}
              </dd>
            </div>
            <div>
              <dt>{t('Effective from')}</dt>
              <dd>{effectiveFrom}</dd>
            </div>
            <div>
              <dt>{t('Currency')}</dt>
              <dd>{currency}</dd>
            </div>
            <div>
              <dt>{t('Labor billing cadence')}</dt>
              <dd>{cadenceType}</dd>
            </div>
            {#if mode === 'separate'}<div>
                <dt>{t('Expense billing cadence')}</dt>
                <dd>{expenseCadenceType}</dd>
              </div>{/if}
            <div>
              <dt>{t('Invoice layout')}</dt>
              <dd>{invoiceLayout}</dd>
            </div>
            <div>
              <dt>{t('People needing terms')}</dt>
              <dd>{missingPeople.length}</dd>
            </div>
          </dl>
          {#if selectedTemplate}
            <p class="hint">
              {t('Selected template')}:
              <strong>{selectedTemplate.name} · v{selectedTemplate.version}</strong>. {templateModified
                ? t('Defaults were adjusted for this project; review the choices above.')
                : t('Template defaults are unchanged; per-person agreements remain independent.')}
            </p>
          {/if}
          <label class="check"
            ><input type="checkbox" bind:checked={saveAsTemplate} />{t(
              'Save these defaults as a reusable template',
            )}</label
          >
          {#if saveAsTemplate}<label
              >{t('Template name')}<input
                bind:value={templateName}
                maxlength="100"
                required
                aria-invalid={Boolean(fieldError('templateName'))}
                aria-describedby={fieldError('templateName') ? errorId('templateName') : undefined}
              /></label
            >{/if}
          {#if fieldError('templateName')}<small id={errorId('templateName')} class="warning"
              >{fieldError('templateName')}</small
            >{/if}
          <p class="hint">
            {t(
              'Saving changes future invoice preparation. Issued invoices keep their original totals and rules.',
            )}
          </p>
        </fieldset>
      {/if}
      <div class="actions">
        {#if step > 1}<button type="button" class="secondary-button" onclick={previous}
            >{t('Back')}</button
          >{/if}
        {#if step < 4}<button
            type="button"
            class="primary-button"
            onclick={next}
            disabled={step === 2 && (entityChoices.length === 0 || availableTaxes.length === 0)}
            >{t('Continue')}</button
          >
        {:else}<button type="submit" class="primary-button" disabled={submitted}
            >{submitted ? t('Saving…') : t('Save billing setup')}</button
          >{/if}
      </div>
    </form>
    {#each people as person}
      {@const draft = personDrafts[person.id]}
      {#if draft}
        <form
          id={`person-terms-${person.id}`}
          method="POST"
          action="?/savePersonTerms&tab=billing"
          class="hidden-person-form"
        >
          <input type="hidden" name="projectId" value={projectId} />
          <input type="hidden" name="projectMemberId" value={person.assignmentId} />
          <input type="hidden" name="workerId" value={person.id} />
          <input type="hidden" name="expectedFingerprint" value={person.termsFingerprint} />
          <input type="hidden" name="effectiveFrom" value={draft.effectiveFrom} />
          <input type="hidden" name="customerHourlyRate" value={draft.customerHourlyRate} />
          <input type="hidden" name="workerPayType" value={draft.workerPayType} />
          <input type="hidden" name="workerPayAmount" value={draft.workerPayAmount} />
          <input type="hidden" name="percentageBasis" value={draft.percentageBasis} />
          <input type="hidden" name="expensePayer" value={draft.expensePayer} />
          <input type="hidden" name="workerReimbursement" value={draft.workerReimbursement} />
          <input type="hidden" name="clientRecovery" value={draft.clientRecovery} />
          <input
            type="hidden"
            name="markupPercent"
            value={draft.clientRecovery === 'markup' ? draft.markupPercent : ''}
          />
        </form>
      {/if}
    {/each}
    <form
      id="selected-person-terms"
      method="POST"
      action="?/savePeopleTerms&tab=billing"
      class="hidden-person-form"
    >
      <input
        type="hidden"
        name="rows"
        value={JSON.stringify(
          people.filter((person) => selectedPersonIds.includes(person.id)).map(personPayload),
        )}
      />
    </form>
  {:else}
    <p>{t('Billing setup is read only for this role.')}</p>
  {/if}
</section>

<style>
  .billing-setup {
    border: 1px solid var(--ja-line, #e4e4e2);
    padding: clamp(1rem, 2vw, 1.5rem);
    background: white;
  }
  .billing-setup__intro {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    align-items: flex-start;
  }
  .billing-setup__intro h3 {
    margin: 0 0 0.35rem;
  }
  .billing-setup__intro p,
  .hint {
    color: var(--ja-steel, #686760);
    line-height: 1.45;
  }
  .billing-setup__intro > span {
    white-space: nowrap;
    font-weight: 750;
  }
  fieldset {
    display: grid;
    gap: 1rem;
    min-width: 0;
    margin: 1rem 0 0;
    padding: 0;
    border: 0;
  }
  legend {
    padding: 0;
    font-size: 1.08rem;
    font-weight: 800;
  }
  label {
    display: grid;
    gap: 0.35rem;
    font-weight: 700;
  }
  input,
  select {
    box-sizing: border-box;
    width: 100%;
    min-height: 2.75rem;
    border: 1px solid var(--ja-line, #bbb);
    border-radius: 0.4rem;
    padding: 0.6rem;
    background: white;
    color: inherit;
    font: inherit;
  }
  input:focus-visible,
  select:focus-visible,
  button:focus-visible,
  a:focus-visible {
    outline: 3px solid var(--ja-teal, #706e66);
    outline-offset: 2px;
  }
  .choice-grid,
  .field-grid,
  .person-fields {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 0.8rem;
  }
  .person-terms {
    border: 1px solid var(--ja-line, #ddd);
    border-radius: 0.5rem;
    padding: 1rem;
    min-width: 0;
  }
  .person-terms h4 {
    margin: 0;
  }
  .person-fields {
    margin: 0.8rem 0;
  }
  .hidden-person-form {
    display: none;
  }
  .choice-grid label {
    grid-template-columns: auto 1fr;
    align-content: start;
    border: 2px solid var(--ja-line, #ddd);
    border-radius: 0.5rem;
    padding: 1rem;
    cursor: pointer;
  }
  .choice-grid label.selected {
    border-color: var(--ja-teal, #706e66);
    background: #f6f7f5;
  }
  .choice-grid input {
    width: auto;
    min-height: auto;
    grid-row: 1 / span 2;
  }
  .choice-grid small {
    grid-column: 2;
    font-weight: 400;
    line-height: 1.45;
  }
  .check {
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }
  .check input {
    width: 1.2rem;
    min-height: 1.2rem;
  }
  .people-list {
    display: grid;
    gap: 0.45rem;
  }
  .people-list > div {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem 1rem;
    padding: 0.75rem;
    border: 1px solid var(--ja-line, #ddd);
  }
  .people-list > .person-terms {
    display: block;
  }
  .warning {
    padding: 0.7rem;
    background: #fff8e7;
    border-inline-start: 3px solid #b2771a;
  }
  .review {
    display: grid;
    gap: 0.4rem;
    margin: 0;
  }
  .review div {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    border-bottom: 1px solid var(--ja-line, #ddd);
    padding: 0.5rem 0;
  }
  .review dd {
    margin: 0;
    font-weight: 750;
    text-align: right;
  }
  .actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.6rem;
    padding-top: 1rem;
  }
  .actions button {
    min-height: 2.75rem;
    padding: 0.65rem 1rem;
    border-radius: 0.4rem;
    font: inherit;
    font-weight: 750;
    cursor: pointer;
  }
  .text-button {
    border: 0;
    background: transparent;
    color: var(--ja-teal, #706e66);
    text-decoration: underline;
    font: inherit;
    font-weight: 750;
    cursor: pointer;
  }
  .secondary-button {
    border: 1px solid var(--ja-line, #bbb);
    background: white;
  }
  .primary-button {
    border: 1px solid var(--ja-teal, #706e66);
    background: var(--ja-teal, #706e66);
    color: white;
  }
  @media (max-width: 640px) {
    .choice-grid,
    .field-grid,
    .person-fields {
      grid-template-columns: 1fr;
    }
    .billing-setup__intro {
      flex-direction: column;
    }
    .actions button {
      flex: 1;
    }
  }
</style>
