<script lang="ts">
  import type { PortalData, PortalRow } from '../portal-data';
  import type { ControlledValueDomain } from '../../i18n/controlled-values';

  let {
    base,
    data,
    availableProjects,
    online,
    queue,
    syncMessage,
    money,
    translate,
    controlledValue,
    canCreateProject = false,
    canCreateInvoiceDraft = false,
    invoiceDraftHref = null,
    canViewPendingReports = false,
  }: {
    base: string;
    data: Pick<PortalData, 'dashboard' | 'records'>;
    availableProjects: PortalRow[];
    online: boolean;
    queue: number;
    syncMessage: string;
    money: (minor: string | number | null | undefined, currency?: string) => string;
    translate: (value: string) => string;
    controlledValue: (domain: ControlledValueDomain, value: unknown) => string;
    canCreateProject?: boolean;
    canCreateInvoiceDraft?: boolean;
    invoiceDraftHref?: string | null;
    canViewPendingReports?: boolean;
  } = $props();

  const formatPlanningMinutes = (value: unknown): string | null => {
    const minutes = typeof value === 'number' ? value : Number(value);
    if (!Number.isFinite(minutes) || minutes <= 0) return null;

    const wholeMinutes = Math.floor(minutes);
    const hours = Math.floor(wholeMinutes / 60);
    const remainingMinutes = wholeMinutes % 60;
    if (hours === 0) return `${remainingMinutes} min`;
    if (remainingMinutes === 0) return `${hours} h`;
    return `${hours} h ${remainingMinutes} min`;
  };

  const planningReference = $derived(formatPlanningMinutes(data.records?.[0]?.planned_minutes));

  /**
   * Keep the dashboard invoice CTA on the already-authorized project target,
   * while carrying the user directly to its Billing workspace. The prop is
   * generated by the shell from the server-projected project list. URL's
   * searchParams.set replaces every previous tab value, so malformed or
   * duplicated tab parameters never leak into the destination; URL also keeps
   * unrelated parameters and the hash intact.
   */
  function withBillingTab(href: string): string {
    const absolute = /^(?:[a-z][a-z\d+.-]*:)?\/\//iu.test(href);
    const target = new URL(href, 'http://j-aautomation.local');
    target.searchParams.set('tab', 'billing');
    if (absolute) return target.toString();
    return `${target.pathname}${target.search}${target.hash}`;
  }
</script>

{#if data.dashboard}
  <div class="dashboard-hero">
    <div>
      <span class="portal-kicker">{translate('OPERATIONS CONTROL')}</span>
      <h2>{translate('Field operations overview')}</h2>
      <p>{translate('Current projects, field records, and billing readiness in one view.')}</p>
    </div>
    <a class="dashboard-project-count" href={`${base}/app/projects`}>
      <strong>{data.dashboard.activeProjects} {translate('active projects')}</strong>
    </a>
  </div>
  <nav class="quick-actions dashboard-quick-actions" aria-label={translate('Dashboard actions')}>
    {#if canCreateProject}
      <a href={`${base}/app/projects#new-project`}>{translate('New project')}</a>
    {/if}
    <a href={`${base}/app/time`}>{translate('Log actual time')}</a>
    <a href={`${base}/app/reports`}>{translate('Write field report')}</a>
    {#if canCreateInvoiceDraft && invoiceDraftHref}
      <a href={withBillingTab(invoiceDraftHref)} data-dashboard-invoice-draft
        >{translate('Create invoice draft')}</a
      >
    {/if}
    {#if canViewPendingReports}
      <a href={`${base}/app/approvals`}>{translate('View pending reports')}</a>
    {/if}
  </nav>
  <div class="finance-grid dashboard-metrics">
    <a class="metric" href={`${base}/app/time`}>
      <span>{translate('RECORDED HOURS')}</span><strong
        >{(data.dashboard.actualMinutes / 60).toFixed(1)}</strong
      >
      <p>{translate('Approved and submitted field time')}</p>
    </a>
    <a class="metric attention" href={`${base}/app/approvals`}>
      <span>{translate('PENDING REPORTS')}</span><strong>{data.dashboard.pendingReports}</strong>
      <p>{translate('Daily and PLC records awaiting review')}</p>
    </a>
    {#if data.dashboard.expenseMinor !== undefined && data.dashboard.currency}
      <a class="metric" href={`${base}/app/expenses`}>
        <span>{translate('PROJECT EXPENSES')}</span><strong
          >{money(data.dashboard.expenseMinor, data.dashboard.currency)}</strong
        >
        <p>{translate('All-in and reimbursable combined')}</p>
      </a>
    {/if}
    {#if data.dashboard.upcomingInvoiceMinor !== undefined && data.dashboard.currency}
      <a class="metric" href={`${base}/app/billing`}>
        <span>{translate('UPCOMING BILLING')}</span><strong
          >{money(data.dashboard.upcomingInvoiceMinor, data.dashboard.currency)}</strong
        >
        <p>{data.dashboard.upcomingInvoices ?? 0} {translate('draft invoice streams')}</p>
      </a>
    {/if}
  </div>
  <section class="record-list dashboard-projects">
    <div class="panel-title">
      <h2>{translate('Active project board')}</h2>
      <span>{availableProjects.length} {translate('records')}</span>
    </div>
    {#each availableProjects as project}<a
        class="project-board-row"
        href={`${base}/app/projects/${project.id}`}
        ><span><b>{project.project_number}</b><strong>{project.name}</strong></span><small
          >{controlledValue('status', project.status)} · {project.timezone}</small
        ><i>{translate('Open project')}</i></a
      >{/each}
  </section>
{:else}
  <div class="portal-grid">
    <section class="assignment">
      <span class="status-chip"><b></b>{translate('Today')}</span>
      {#if planningReference}
        <small class="assignment-planning-context"
          >{translate('Planned')}: {planningReference}</small
        >
      {/if}
      <div class="quick-actions">
        <a href={`${base}/app/time`}>{translate('Log actual time')}</a><a
          href={`${base}/app/reports`}>{translate('Write field report')}</a
        ><a href={`${base}/app/expenses`}>{translate('Add expense')}</a>
      </div>
      <h2>{data.records?.[0]?.project_name ?? translate('Field workspace')}</h2>
      <p>
        {data.records?.[0]
          ? `${data.records[0].site} · ${String(data.records[0].starts_at).slice(11, 16)}–${String(data.records[0].ends_at).slice(11, 16)}`
          : translate('No published assignment for today.')}
      </p>
    </section>
    <section class="sync-panel">
      <span class="portal-kicker">{translate('DEVICE STATUS')}</span><strong
        >{online ? translate('Connected to J&A') : translate('Working offline')}</strong
      >
      <p>
        {queue}
        {translate(
          queue === 1
            ? 'local mutation waiting to synchronize.'
            : 'local mutations waiting to synchronize.',
        )}
      </p>
      {#if syncMessage}<small>{translate(syncMessage)}</small>{/if}
    </section>
  </div>
{/if}
