import { translateControlledValue } from '$lib/i18n/controlled-values';
import type { PortalLocale } from '$lib/portal-i18n';

export const supplierCopy = {
  en: {
    title: 'Suppliers and technicians',
    back: 'Back to workspace',
    team: 'My supplier team',
    intro:
      'Register technicians and actual work for authorized installations. J&A reviews submitted hours.',
    restricted:
      'Operational access only. Payments, rates and financial reports are not available to these accounts.',
    owner: 'Owner administration',
    revoked: 'Revoked',
    provider: 'Supplier',
    createProvider: 'Add supplier',
    name: 'Name',
    account: 'Account',
    profile: 'Access profile',
    coordinator: 'Supplier coordinator',
    technician: 'External technician',
    standard: 'Standard account (restore normal permissions)',
    saveProfile: 'Save account access',
    grant: 'Authorize installation',
    project: 'Installation / project',
    from: 'From',
    to: 'To',
    starts: 'Starts on',
    ends: 'Ends on (optional)',
    revoke: 'Revoke access',
    grants: 'Installation authorizations',
    add: 'Add technician',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    company: 'Company (optional)',
    contactName: 'Contact name (optional)',
    address: 'Address (optional)',
    notes: 'Notes (optional)',
    personnel:
      'This creates a technician record without login credentials. Existing login accounts can be configured by the Owner.',
    assign: 'Assign existing technician',
    assigned: 'Technicians',
    time: 'Record team hours',
    worker: 'Technician',
    date: 'Work date',
    category: 'Category',
    work: 'Work',
    travel: 'Travel',
    minutes: 'Actual minutes',
    summary: 'Work performed',
    save: 'Save draft',
    submit: 'Submit to J&A',
    edit: 'Correct draft',
    correction: 'Create correction draft',
    reason: 'Reason for correction',
    state: 'State',
    superseded: 'Superseded — excluded from total',
    recordedBy: 'Recorded by',
    report: 'Operational report',
    download: 'Download CSV',
    print: 'Print / save PDF',
    apply: 'Apply filters',
    total: 'Total actual minutes',
    empty: 'No authorized installations or records for this selection.',
    saved: 'Changes saved.',
    failed: 'The change could not be saved. Check the values and your current authorization.',
    reportNote:
      'Operational work and approval status only. This report does not certify payment or customer acceptance.',
    noFinancial: 'No financial access',
    own: 'Own hours',
    reports: 'Own reports',
    select: 'Select',
  },
  es: {
    title: 'Proveedores y técnicos',
    back: 'Volver a la app',
    team: 'Equipo de mi proveedor',
    intro:
      'Registra técnicos y trabajo real en las instalaciones autorizadas. J&A revisa las horas enviadas.',
    restricted:
      'Acceso solo operativo. Estas cuentas no pueden consultar pagos, tarifas ni informes financieros.',
    owner: 'Administración del propietario',
    revoked: 'Revocado',
    provider: 'Proveedor',
    createProvider: 'Añadir proveedor',
    name: 'Nombre',
    account: 'Cuenta',
    profile: 'Perfil de acceso',
    coordinator: 'Responsable de proveedor',
    technician: 'Técnico externo',
    standard: 'Cuenta estándar (restaurar permisos habituales)',
    saveProfile: 'Guardar acceso de la cuenta',
    grant: 'Autorizar instalación',
    project: 'Instalación / proyecto',
    from: 'Desde',
    to: 'Hasta',
    starts: 'Fecha de inicio',
    ends: 'Fecha de fin (opcional)',
    revoke: 'Retirar acceso',
    grants: 'Instalaciones autorizadas',
    add: 'Añadir técnico',
    email: 'Correo (opcional)',
    phone: 'Teléfono (opcional)',
    company: 'Empresa (opcional)',
    contactName: 'Persona de contacto (opcional)',
    address: 'Dirección (opcional)',
    notes: 'Notas (opcional)',
    personnel:
      'Se crea una ficha de técnico sin credenciales de acceso. El propietario puede configurar cuentas de acceso ya existentes.',
    assign: 'Asignar técnico existente',
    assigned: 'Técnicos',
    time: 'Registrar horas del equipo',
    worker: 'Técnico',
    date: 'Fecha del trabajo',
    category: 'Categoría',
    work: 'Trabajo',
    travel: 'Viaje',
    minutes: 'Minutos reales',
    summary: 'Trabajo realizado',
    save: 'Guardar borrador',
    submit: 'Enviar a J&A',
    edit: 'Corregir borrador',
    correction: 'Crear borrador de corrección',
    reason: 'Motivo de la corrección',
    state: 'Estado',
    superseded: 'Sustituido — excluido del total',
    recordedBy: 'Registrado por',
    report: 'Informe operativo',
    download: 'Descargar CSV',
    print: 'Imprimir / guardar PDF',
    apply: 'Aplicar filtros',
    total: 'Total de minutos reales',
    empty: 'No hay instalaciones autorizadas o registros para esta selección.',
    saved: 'Cambios guardados.',
    failed: 'No se pudo guardar. Comprueba los valores y tu autorización actual.',
    reportNote:
      'Solo trabajo operativo y estado de aprobación. Este informe no acredita pagos ni aceptación del cliente.',
    noFinancial: 'Sin acceso financiero',
    own: 'Mis horas',
    reports: 'Mis informes',
    select: 'Seleccionar',
  },
  pt: {
    title: 'Fornecedores e técnicos',
    back: 'Voltar ao aplicativo',
    team: 'Equipe do meu fornecedor',
    intro:
      'Cadastre técnicos e trabalho real nas instalações autorizadas. A J&A revisa as horas enviadas.',
    restricted:
      'Acesso apenas operacional. Estas contas não podem consultar pagamentos, tarifas ou relatórios financeiros.',
    owner: 'Administração do proprietário',
    revoked: 'Revogado',
    provider: 'Fornecedor',
    createProvider: 'Adicionar fornecedor',
    name: 'Nome',
    account: 'Conta',
    profile: 'Perfil de acesso',
    coordinator: 'Responsável do fornecedor',
    technician: 'Técnico externo',
    standard: 'Conta padrão (restaurar permissões habituais)',
    saveProfile: 'Salvar acesso da conta',
    grant: 'Autorizar instalação',
    project: 'Instalação / projeto',
    from: 'De',
    to: 'Até',
    starts: 'Data de início',
    ends: 'Data de fim (opcional)',
    revoke: 'Revogar acesso',
    grants: 'Instalações autorizadas',
    add: 'Adicionar técnico',
    email: 'E-mail (opcional)',
    phone: 'Telefone (opcional)',
    company: 'Empresa (opcional)',
    contactName: 'Pessoa de contato (opcional)',
    address: 'Endereço (opcional)',
    notes: 'Notas (opcional)',
    personnel:
      'Cria um cadastro de técnico sem credenciais de acesso. O proprietário pode configurar contas de acesso já existentes.',
    assign: 'Atribuir técnico existente',
    assigned: 'Técnicos',
    time: 'Registrar horas da equipe',
    worker: 'Técnico',
    date: 'Data do trabalho',
    category: 'Categoria',
    work: 'Trabalho',
    travel: 'Viagem',
    minutes: 'Minutos reais',
    summary: 'Trabalho realizado',
    save: 'Salvar rascunho',
    submit: 'Enviar à J&A',
    edit: 'Corrigir rascunho',
    correction: 'Criar rascunho de correção',
    reason: 'Motivo da correção',
    state: 'Estado',
    superseded: 'Substituído — excluído do total',
    recordedBy: 'Registrado por',
    report: 'Relatório operacional',
    download: 'Baixar CSV',
    print: 'Imprimir / salvar PDF',
    apply: 'Aplicar filtros',
    total: 'Total de minutos reais',
    empty: 'Não há instalações autorizadas ou registros para esta seleção.',
    saved: 'Alterações salvas.',
    failed: 'Não foi possível salvar. Verifique os valores e sua autorização atual.',
    reportNote:
      'Somente trabalho operacional e estado de aprovação. Este relatório não comprova pagamento nem aceite do cliente.',
    noFinancial: 'Sem acesso financeiro',
    own: 'Minhas horas',
    reports: 'Meus relatórios',
    select: 'Selecionar',
  },
} as const;

export function supplierStateLabel(locale: PortalLocale, state: string): string {
  return state === 'revoked'
    ? supplierCopy[locale].revoked
    : translateControlledValue(locale, 'status', state);
}

export function supplierCategoryLabel(locale: PortalLocale, category: string): string {
  return category === 'work'
    ? supplierCopy[locale].work
    : translateControlledValue(locale, 'timeCategory', category);
}

export const supplierManagementCopy = {
  en: {
    directory: 'Directory',
    intro: 'Manage suppliers, technicians and installation access.',
    suppliers: 'Suppliers',
    search: 'Search directory',
    searchHint: 'Name, supplier or email',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    edit: 'Edit',
    remove: 'Remove',
    restore: 'Restore',
    cancel: 'Cancel',
    save: 'Save changes',
    confirm: 'I confirm this change',
    noMatches: 'No matching records. Change the search or status filter.',
    loginEmail: 'This email is used to sign in. Manage it from the account profile.',
    removeSupplierNote:
      'This supplier will be made inactive and its installation authorizations revoked. Existing hours and personnel history will be retained.',
    removeTechnicianNote:
      'This technician will be suspended and signed out. Existing hours and assignments will be retained.',
    restoreSupplierNote:
      'The supplier will become active again. Installation access must be authorized again.',
    restoreTechnicianNote:
      'The technician will become active again, with access through their existing valid assignments.',
    setup: 'Setup and access',
    personnel: 'Personnel',
    filters: 'Project and reporting period',
  },
  es: {
    directory: 'Directorio',
    intro: 'Gestiona proveedores, técnicos y accesos a las instalaciones.',
    suppliers: 'Proveedores',
    search: 'Buscar en el directorio',
    searchHint: 'Nombre, proveedor o correo',
    active: 'Activo',
    inactive: 'Inactivo',
    all: 'Todos',
    edit: 'Editar',
    remove: 'Dar de baja',
    restore: 'Restaurar',
    cancel: 'Cancelar',
    save: 'Guardar cambios',
    confirm: 'Confirmo este cambio',
    noMatches: 'No hay coincidencias. Cambia la búsqueda o el filtro de estado.',
    loginEmail: 'Este correo se usa para iniciar sesión. Se gestiona desde el perfil de la cuenta.',
    removeSupplierNote:
      'El proveedor quedará inactivo y se retirarán sus autorizaciones de instalación. Se conservará el historial de horas y personal.',
    removeTechnicianNote:
      'El técnico quedará suspendido y se cerrarán sus sesiones. Se conservarán sus horas y asignaciones.',
    restoreSupplierNote:
      'El proveedor volverá a estar activo. Será necesario autorizar de nuevo el acceso a las instalaciones.',
    restoreTechnicianNote:
      'El técnico volverá a estar activo, con acceso mediante sus asignaciones vigentes.',
    setup: 'Configuración y acceso',
    personnel: 'Personal',
    filters: 'Proyecto y periodo del informe',
  },
  pt: {
    directory: 'Diretório',
    intro: 'Gerencie fornecedores, técnicos e acessos às instalações.',
    suppliers: 'Fornecedores',
    search: 'Pesquisar diretório',
    searchHint: 'Nome, fornecedor ou e-mail',
    active: 'Ativo',
    inactive: 'Inativo',
    all: 'Todos',
    edit: 'Editar',
    remove: 'Desativar',
    restore: 'Restaurar',
    cancel: 'Cancelar',
    save: 'Salvar alterações',
    confirm: 'Confirmo esta alteração',
    noMatches: 'Nenhum registro encontrado. Altere a pesquisa ou o filtro de status.',
    loginEmail: 'Este e-mail é usado para entrar. Gerencie-o no perfil da conta.',
    removeSupplierNote:
      'O fornecedor será desativado e suas autorizações de instalação revogadas. O histórico de horas e pessoal será mantido.',
    removeTechnicianNote:
      'O técnico será suspenso e suas sessões encerradas. As horas e atribuições serão mantidas.',
    restoreSupplierNote:
      'O fornecedor ficará ativo novamente. O acesso às instalações deverá ser autorizado novamente.',
    restoreTechnicianNote:
      'O técnico ficará ativo novamente, com acesso pelas suas atribuições vigentes.',
    setup: 'Configuração e acesso',
    personnel: 'Pessoal',
    filters: 'Projeto e período do relatório',
  },
} as const;
