import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { projects } from './projects.ts';
import { lifecycle } from './shared.ts';

export const billingRules = sqliteTable('billing_rule', {
  id: text('id').primaryKey(),
  projectId: text('project_id')
    .notNull()
    .references(() => projects.id),
  legalEntityId: text('legal_entity_id'),
  streamType: text('stream_type').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  cadenceType: text('cadence_type').notNull(),
  anchorDate: text('anchor_date'),
  taxProfileId: text('tax_profile_id'),
  currency: text('currency').notNull(),
  autoGenerateDraft: integer('auto_generate_draft', { mode: 'boolean' }).notNull().default(false),
  autoIssue: integer('auto_issue', { mode: 'boolean' }).notNull().default(false),
  autoSend: integer('auto_send', { mode: 'boolean' }).notNull().default(false),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  groupingMode: text('grouping_mode'),
  templateId: text('template_id'),
  recipientEmail: text('recipient_email'),
  billingContactId: text('billing_contact_id'),
  paymentTermsDays: integer('payment_terms_days'),
  poNumberOverride: text('po_number_override'),
  semiMonthlyRule: text('semi_monthly_rule'),
  policyVersion: integer('policy_version'),
  fixedAmountMinor: integer('fixed_amount_minor'),
  includedMinutes: integer('included_minutes'),
  monthlyCutoffDay: integer('monthly_cutoff_day'),
  version: integer('version').notNull().default(1),
  ...lifecycle,
});

export const legalEntities = sqliteTable('legal_entity', {
  id: text('id').primaryKey(),
  code: text('code').notNull().unique(),
  legalName: text('legal_name').notNull(),
  currency: text('currency').notNull(),
  billingAddress: text('billing_address').notNull(),
  companyIdentifiers: text('company_identifiers').notNull(),
  version: integer('version').notNull().default(1),
  ...lifecycle,
});

export const invoiceNumberPolicies = sqliteTable('invoice_number_policy', {
  id: text('id').primaryKey(),
  legalEntityId: text('legal_entity_id').notNull(),
  prefix: text('prefix').notNull(),
  digits: integer('digits').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  accountantApprovedAt: text('accountant_approved_at'),
  version: integer('version').notNull().default(1),
  ...lifecycle,
});

export const taxProfiles = sqliteTable('tax_profile', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  currency: text('currency').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  version: integer('version').notNull().default(1),
  legalEntityId: text('legal_entity_id'),
  jurisdictionLabel: text('jurisdiction_label'),
  description: text('description'),
  status: text('status'),
});

export const taxComponents = sqliteTable('tax_component', {
  id: text('id').primaryKey(),
  taxProfileId: text('tax_profile_id').notNull(),
  name: text('name').notNull(),
  basisPoints: integer('basis_points').notNull(),
  calculationOrder: integer('calculation_order').notNull(),
  compound: integer('compound', { mode: 'boolean' }).notNull(),
  calculationType: text('calculation_type'),
  displayMode: text('display_mode'),
  basis: text('basis'),
});

export const billingPeriods = sqliteTable('billing_period', {
  id: text('id').primaryKey(),
  billingRuleId: text('billing_rule_id').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  state: text('state').notNull(),
  reasonsJson: text('reasons_json').notNull(),
  closedAt: text('closed_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull().default(1),
});

export const billingLocks = sqliteTable('billing_lock', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  streamType: text('stream_type').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  acquiredAt: text('acquired_at').notNull(),
});
