import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

export const localizedPdfVariants = sqliteTable(
  'localized_pdf_variant',
  {
    variantId: text('variant_id').primaryKey(),
    ownerType: text('owner_type').notNull(),
    ownerId: text('owner_id').notNull(),
    ownerRevisionId: text('owner_revision_id').notNull(),
    tenantId: text('tenant_id').notNull(),
    deploymentId: text('deployment_id').notNull(),
    locale: text('locale').notNull(),
    localeTag: text('locale_tag').notNull(),
    documentTag: text('document_tag').notNull(),
    templateVersion: text('template_version').notNull(),
    generationVersion: text('generation_version').notNull(),
    snapshotJson: text('snapshot_json').notNull(),
    snapshotHash: text('snapshot_hash').notNull(),
    snapshotHashKind: text('snapshot_hash_kind').notNull(),
    status: text('status').notNull(),
    currentAttemptNumber: integer('current_attempt_number').notNull().default(1),
    attemptNumber: integer('attempt_number').notNull().default(1),
    semanticFilename: text('semantic_filename').notNull(),
    mediaType: text('media_type'),
    byteLength: integer('byte_length'),
    contentSha256: text('content_sha256'),
    storageKey: text('storage_key').notNull(),
    rendererVersion: text('renderer_version'),
    readyAt: text('ready_at'),
    errorCode: text('error_code'),
    retryable: integer('retryable', { mode: 'boolean' }),
    integrityBlocked: integer('integrity_blocked', { mode: 'boolean' }).notNull().default(false),
    maxAttempts: integer('max_attempts').notNull().default(5),
    requestKey: text('request_key'),
    requestedBy: text('requested_by').notNull(),
    requestedAt: text('requested_at').notNull(),
    startedAt: text('started_at'),
    finishedAt: text('finished_at'),
    claimedJobId: text('claimed_job_id'),
    claimedJobRunId: text('claimed_job_run_id'),
    claimedLeaseFence: integer('claimed_lease_fence'),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('localized_pdf_variant_active_identity_uq').on(
      table.tenantId,
      table.deploymentId,
      table.ownerType,
      table.ownerId,
      table.locale,
      table.templateVersion,
      table.generationVersion,
      table.snapshotHash,
    ).where(sql`${table.status} IN ('queued','running','ready')`),
    index('localized_pdf_variant_owner_idx').on(
      table.tenantId,
      table.deploymentId,
      table.ownerType,
      table.ownerId,
      table.locale,
      table.status,
    ),
  ],
);

export const localizedPdfRetryDecisions = sqliteTable(
  'localized_pdf_retry_decision',
  {
    decisionId: text('decision_id').primaryKey(),
    variantId: text('variant_id').notNull(),
    priorAttemptNumber: integer('prior_attempt_number').notNull(),
    nextAttemptNumber: integer('next_attempt_number').notNull(),
    failureCode: text('failure_code').notNull(),
    failureClass: text('failure_class').notNull(),
    retryable: integer('retryable', { mode: 'boolean' }).notNull(),
    requestedBy: text('requested_by').notNull(),
    requestedAt: text('requested_at').notNull(),
    decisionHash: text('decision_hash').notNull(),
  },
  (table) => [
    uniqueIndex('localized_pdf_retry_decision_variant_uq').on(
      table.variantId,
      table.nextAttemptNumber,
    ),
    uniqueIndex('localized_pdf_retry_decision_hash_uq').on(table.decisionHash),
  ],
);

export const localizedPdfVariantAttempts = sqliteTable(
  'localized_pdf_variant_attempt',
  {
    attemptId: text('attempt_id').primaryKey(),
    variantId: text('variant_id').notNull(),
    attemptNumber: integer('attempt_number').notNull(),
    jobId: text('job_id'),
    jobRunId: text('job_run_id'),
    leaseFence: integer('lease_fence'),
    startedAt: text('started_at'),
    finishedAt: text('finished_at'),
    outcome: text('outcome'),
    failureClass: text('failure_class'),
    retryable: integer('retryable', { mode: 'boolean' }),
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    uniqueIndex('localized_pdf_variant_attempt_uq').on(table.variantId, table.attemptNumber),
  ],
);

export const localizedPdfIntegrityIncidents = sqliteTable(
  'localized_pdf_integrity_incident',
  {
    incidentId: text('incident_id').primaryKey(),
    variantId: text('variant_id').notNull(),
    ownerType: text('owner_type').notNull(),
    ownerId: text('owner_id').notNull(),
    ownerRevisionId: text('owner_revision_id').notNull(),
    locale: text('locale').notNull(),
    templateVersion: text('template_version').notNull(),
    generationVersion: text('generation_version').notNull(),
    attemptNumber: integer('attempt_number').notNull(),
    incidentKind: text('incident_kind').notNull(),
    expectedHash: text('expected_hash'),
    observedHash: text('observed_hash'),
    expectedLength: integer('expected_length'),
    observedLength: integer('observed_length'),
    storageKey: text('storage_key'),
    detectedAt: text('detected_at').notNull(),
    detectedBy: text('detected_by').notNull(),
    incidentHash: text('incident_hash').notNull(),
  },
  (table) => [uniqueIndex('localized_pdf_integrity_incident_hash_uq').on(table.incidentHash)],
);
