import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { lifecycle } from './shared.ts';

export const technicalReports = sqliteTable('technical_report', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  authorId: text('author_id').notNull(),
  systemName: text('system_name').notNull(),
  controller: text('controller'),
  changeSummary: text('change_summary').notNull(),
  safetyRelated: integer('safety_related', { mode: 'boolean' }).notNull(),
  validation: text('validation'),
  rollbackPlan: text('rollback_plan'),
  approvalState: text('approval_state').notNull(),
  ...lifecycle,
  plantSite: text('plant_site'),
  areaLine: text('area_line'),
  stationMachine: text('station_machine'),
  systemType: text('system_type'),
  plcPlatform: text('plc_platform'),
  hmiScada: text('hmi_scada'),
  robotPlatform: text('robot_platform'),
  driveMotion: text('drive_motion'),
  networkProtocol: text('network_protocol'),
  softwareVersion: text('software_version'),
  programReference: text('program_reference'),
  productionImpact: text('production_impact'),
  validationResult: text('validation_result'),
  openRisk: text('open_risk'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: text('reviewed_at'),
  reportDate: text('report_date'),
  reportDateProvenance: text('report_date_provenance'),
  version: integer('version').notNull().default(1),
});

export const technicalChanges = sqliteTable('technical_change', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  technicalReportId: text('technical_report_id'),
  authorId: text('author_id').notNull(),
  component: text('component').notNull(),
  originalBehavior: text('original_behavior'),
  rootCause: text('root_cause'),
  changeMade: text('change_made').notNull(),
  reason: text('reason'),
  safetyImpact: integer('safety_impact', { mode: 'boolean' }).notNull(),
  productionImpact: text('production_impact'),
  validation: text('validation'),
  validationResult: text('validation_result'),
  openRisk: text('open_risk'),
  rollbackInformation: text('rollback_information'),
  approvalState: text('approval_state').notNull(),
  version: integer('version').notNull().default(1),
  ...lifecycle,
});

export const projectCloseouts = sqliteTable('project_closeout', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull().unique(),
  state: text('state').notNull(),
  snapshotJson: text('snapshot_json').notNull(),
  documentManifestJson: text('document_manifest_json').notNull(),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  reopenedBy: text('reopened_by'),
  reopenedAt: text('reopened_at'),
  reopenReason: text('reopen_reason'),
});
