import { afterEach, describe, expect, it } from 'vitest';
import { newId } from '@ja/domain';
import {
  AccessDeniedError,
  ConflictError,
  ProjectBillingSetupRepository,
  ValidationError,
  type ProjectBillingSetupInput,
  type ProjectPersonTermsInput,
} from '@ja/database';
import { projectCalendarDate } from '../../packages/database/src/domains/billing/project-billing-setup-repository.ts';
import {
  closeB5LifecycleSecurityFixture,
  createB5LifecycleSecurityFixture,
  stepUpB5Principal,
  seedB5User,
  type B5LifecycleSecurityFixture,
} from '../fixtures/b5-lifecycle-security-fixture.js';

const opened: B5LifecycleSecurityFixture[] = [];
afterEach(() => {
  for (const fixture of opened.splice(0)) closeB5LifecycleSecurityFixture(fixture);
});

function setup() {
  const fixture = createB5LifecycleSecurityFixture();
  opened.push(fixture);
  const finance = stepUpB5Principal(fixture.sqlite, fixture.finance, 'billing-setup');
  const entity = fixture.repository.createLegalEntity(fixture.owner, {
    code: 'SETUP-TEST',
    legalName: 'Billing Setup Test SL',
    currency: 'EUR',
    billingAddress: 'Test Street 1, Madrid',
    companyIdentifiers: 'ES-BILL-SETUP',
  });
  const tax = fixture.repository.createTaxProfile(finance, {
    name: 'Setup zero tax',
    currency: 'EUR',
    effectiveFrom: '2026-01-01',
    components: [{ name: 'No tax', basisPoints: 0 }],
  });
  const service = new ProjectBillingSetupRepository(fixture.sqlite, fixture.repository);
  const input = (overrides: Partial<ProjectBillingSetupInput> = {}): ProjectBillingSetupInput => ({
    projectId: fixture.project.id,
    expectedVersion: 0,
    expectedRulesFingerprint: service.rulesFingerprint(finance, fixture.project.id),
    requestKey: newId(),
    mode: 'combined',
    effectiveFrom: '2026-08-01',
    legalEntityId: entity.id,
    laborTaxProfileId: tax.id,
    expenseTaxProfileId: tax.id,
    cadenceType: 'monthly',
    expenseCadenceType: 'monthly',
    invoiceLayout: 'default',
    groupingMode: 'by_worker',
    paymentTermsDays: 30,
    autoGenerateDraft: false,
    saveAsTemplate: false,
    ...overrides,
  });
  return { ...fixture, finance, entity, tax, service, input };
}

function dayOffset(days: number): string {
  const projectToday = projectCalendarDate('Europe/Madrid', new Date());
  return new Date(Date.parse(`${projectToday}T00:00:00.000Z`) + days * 86_400_000)
    .toISOString()
    .slice(0, 10);
}

describe('project-centered billing setup', () => {
  it('saves billing rules without a tax profile', () => {
    const value = setup();
    const result = value.service.save(
      value.finance,
      value.input({ laborTaxProfileId: '', expenseTaxProfileId: '' }),
    );
    expect(
      value.sqlite
        .prepare('SELECT tax_profile_id FROM billing_rule WHERE id=?')
        .get(result.laborRuleId),
    ).toEqual({ tax_profile_id: null });
    expect(
      value.service.issuingPrerequisites(
        value.finance,
        value.project.id,
        dayOffset(0),
        value.entity.id,
        [],
      ),
    ).not.toContain('missing_tax_profile');
  });
  it('provides the selected project client for billing contact scoping', () => {
    const value = setup();
    const ownContact = value.repository.createClientContact(value.owner, {
      clientId: value.client.id,
      name: 'Selected client billing',
      email: 'selected-client@example.test',
      isBillingContact: true,
    });
    const otherClient = value.repository.createClient(value.owner, {
      legalName: 'Other Client SL',
      displayName: 'Other Client',
      currency: 'EUR',
      timezone: 'Europe/Madrid',
      billingEmail: 'other-client@example.test',
      billingAddress: 'Other Street, Madrid',
      paymentTermsDays: 30,
    });
    value.repository.createClientContact(value.owner, {
      clientId: otherClient.id,
      name: 'Other client billing',
      email: 'other-contact@example.test',
      isBillingContact: true,
    });
    const project = value.repository
      .listFinanceProjects(value.finance)
      .find((row) => row.id === value.project.id);
    expect(project?.client_id).toBe(value.client.id);
    const contacts = value.repository.listAllClientContacts(value.finance);
    expect(
      contacts
        .filter((contact) => contact.client_id === project?.client_id)
        .map((contact) => contact.id),
    ).toContain(ownContact.id);
    expect(
      contacts
        .filter((contact) => contact.client_id === project?.client_id)
        .every((contact) => contact.client_id !== otherClient.id),
    ).toBe(true);
  });

  it('reports an off-cadence billing period once', () => {
    const value = setup();
    const rule = value.repository.createBillingRule(value.finance, {
      projectId: value.project.id,
      legalEntityId: value.entity.id,
      taxProfileId: value.tax.id,
      streamType: 'labor',
      cadenceType: 'monthly',
      currency: 'EUR',
      effectiveFrom: '2026-01-01',
    });
    const cutoffReasons = value.repository
      .billingReadiness(value.finance, rule.id, '2026-08-03', '2026-08-16')
      .reasons.filter((reason) => reason.code === 'period_cutoff_mismatch');
    expect(cutoffReasons).toEqual([{ code: 'period_cutoff_mismatch' }]);
  });

  it('uses the project civil date near UTC midnight', () => {
    const instant = new Date('2026-09-23T23:30:00.000Z');
    expect(projectCalendarDate('Europe/Madrid', instant)).toBe('2026-09-24');
    expect(projectCalendarDate('America/New_York', instant)).toBe('2026-09-23');
  });

  it('does not save a project with no active issuing entity or tax profile', () => {
    const fixture = createB5LifecycleSecurityFixture();
    opened.push(fixture);
    const finance = stepUpB5Principal(fixture.sqlite, fixture.finance, 'billing-setup-empty');
    const service = new ProjectBillingSetupRepository(fixture.sqlite, fixture.repository);
    expect(
      fixture.repository.listLegalEntities(finance).filter((entity) => entity.currency === 'EUR'),
    ).toEqual([]);
    expect(fixture.repository.listTaxProfiles(finance)).toEqual([]);
    expect(service.listTemplates(finance, 'EUR')).toEqual([]);
    expect(() =>
      service.save(finance, {
        projectId: fixture.project.id,
        expectedVersion: 0,
        expectedRulesFingerprint: service.rulesFingerprint(finance, fixture.project.id),
        requestKey: newId(),
        mode: 'combined',
        effectiveFrom: '2026-08-01',
        legalEntityId: newId(),
        laborTaxProfileId: newId(),
        expenseTaxProfileId: newId(),
        cadenceType: 'monthly',
        expenseCadenceType: 'monthly',
        invoiceLayout: 'default',
        groupingMode: 'by_worker',
        paymentTermsDays: 30,
        autoGenerateDraft: false,
        saveAsTemplate: false,
      }),
    ).toThrow(ValidationError);
    expect(service.currentVersion(finance, fixture.project.id)).toBe(0);
  });

  it('saves one invoice with two sections and replays the request without duplicate rules', () => {
    const value = setup();
    const command = value.input({
      saveAsTemplate: true,
      templateName: 'Standard T&E',
      expenseTaxProfileId: '',
    });
    const first = value.service.save(value.finance, command);
    const replay = value.service.save(value.finance, command);
    expect(replay).toEqual(first);
    expect(first.expenseRuleId).toBeNull();
    expect(
      value.sqlite
        .prepare('SELECT stream_type,include_expenses FROM billing_rule WHERE project_id=?')
        .all(value.project.id),
    ).toEqual([{ stream_type: 'labor', include_expenses: 1 }]);
    expect(value.service.listTemplates(value.finance, 'EUR')).toEqual([
      expect.objectContaining({ name: 'Standard T&E', version: 1 }),
    ]);
    expect(value.service.currentVersion(value.finance, value.project.id)).toBe(1);
    expect(() => value.service.save(value.finance, { ...command, paymentTermsDays: 45 })).toThrow(
      ConflictError,
    );
  });

  it('rejects a stale wizard after the advanced billing rule changed', () => {
    const value = setup();
    const first = value.service.save(value.finance, value.input());
    const stale = value.input({ expectedVersion: 1, effectiveFrom: dayOffset(1) });
    value.repository.updateBillingRule(value.finance, first.laborRuleId, {
      recipientEmail: 'billing-new@example.test',
    });
    expect(() => value.service.save(value.finance, stale)).toThrow(/changed outside this setup/i);
    expect(value.service.currentVersion(value.finance, value.project.id)).toBe(1);
    expect(
      value.sqlite
        .prepare('SELECT recipient_email FROM billing_rule WHERE id=?')
        .get(first.laborRuleId),
    ).toEqual({ recipient_email: 'billing-new@example.test' });
  });

  it('shows canonical issuer, numbering and tax-date prerequisites without claiming issuance is ready', () => {
    const value = setup();
    const futureTax = value.repository.createTaxProfile(value.finance, {
      name: 'Future tax',
      currency: 'EUR',
      effectiveFrom: dayOffset(30),
      components: [{ name: 'Zero', basisPoints: 0 }],
    });
    value.service.save(value.finance, value.input({ laborTaxProfileId: futureTax.id }));
    expect(
      value.service.issuingPrerequisites(
        value.finance,
        value.project.id,
        dayOffset(0),
        value.entity.id,
        [futureTax.id],
      ),
    ).toEqual(
      expect.arrayContaining([
        'canonical_legal_entity_revision_required',
        'missing_accountant_approved_number_policy',
        'tax_profile_not_effective',
      ]),
    );
  });

  it('denies worker and project-manager finance access while an auditor can only read', () => {
    const value = setup();
    seedB5User(value.sqlite, 'b5-auditor-setup', 'auditor_read_only');
    const auditor = value.repository.principalFor('b5-auditor-setup');
    for (const principal of [value.worker, value.manager]) {
      expect(() => value.service.listTemplates(principal, 'EUR')).toThrow(AccessDeniedError);
      expect(() => value.service.peopleReview(principal, value.project.id, dayOffset(0))).toThrow(
        AccessDeniedError,
      );
      expect(() => value.service.rulesFingerprint(principal, value.project.id)).toThrow(
        AccessDeniedError,
      );
    }
    expect(value.service.listTemplates(auditor, 'EUR')).toEqual([]);
    expect(value.service.rulesFingerprint(auditor, value.project.id)).toMatch(/^[0-9a-f]{64}$/);
    expect(() => value.service.save(auditor, value.input())).toThrow(AccessDeniedError);
  });

  it('switches combined to separate and back using effective rules without overlaps', () => {
    const value = setup();
    const initial = value.service.save(value.finance, value.input());
    const separate = value.service.save(
      value.finance,
      value.input({
        expectedVersion: 1,
        effectiveFrom: dayOffset(1),
        mode: 'separate',
        expenseCadenceType: 'weekly',
      }),
    );
    expect(separate.expenseRuleId).toBeTruthy();
    expect(
      value.sqlite
        .prepare('SELECT effective_to FROM billing_rule WHERE id=?')
        .get(initial.laborRuleId),
    ).toEqual({ effective_to: dayOffset(0) });
    const combined = value.service.save(
      value.finance,
      value.input({
        expectedVersion: 2,
        effectiveFrom: dayOffset(2),
        mode: 'combined',
      }),
    );
    expect(combined.expenseRuleId).toBeNull();
    expect(
      value.sqlite
        .prepare('SELECT effective_to FROM billing_rule WHERE id=?')
        .get(separate.expenseRuleId),
    ).toEqual({ effective_to: dayOffset(1) });
    const rows = value.sqlite
      .prepare(
        'SELECT stream_type,include_expenses,effective_from,effective_to FROM billing_rule WHERE project_id=? ORDER BY stream_type,effective_from',
      )
      .all(value.project.id) as Array<{
      stream_type: string;
      include_expenses: number;
      effective_from: string;
      effective_to: string | null;
    }>;
    for (const stream of ['labor', 'expense']) {
      const streamRows = rows.filter((row) => row.stream_type === stream);
      for (let index = 1; index < streamRows.length; index += 1)
        expect(streamRows[index - 1]!.effective_to! < streamRows[index]!.effective_from).toBe(true);
    }
    expect(
      rows.filter((row) => row.stream_type === 'labor').map((row) => row.include_expenses),
    ).toEqual([1, 0, 1]);
  });

  it('blocks a change that overlaps an existing billing period and rolls back both streams', () => {
    const value = setup();
    const initial = value.service.save(value.finance, value.input());
    const now = new Date().toISOString();
    value.sqlite
      .prepare(
        `INSERT INTO billing_period(id,billing_rule_id,period_start,period_end,state,reasons_json,created_at,updated_at)
       VALUES(?,?,?,?,?,?,?,?)`,
      )
      .run(newId(), initial.laborRuleId, dayOffset(0), dayOffset(7), 'ready', '[]', now, now);
    expect(() =>
      value.service.save(
        value.finance,
        value.input({
          expectedVersion: 1,
          effectiveFrom: dayOffset(1),
          mode: 'separate',
        }),
      ),
    ).toThrow(ConflictError);
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM billing_rule WHERE project_id=?')
        .get(value.project.id),
    ).toEqual({ count: 1 });
    expect(value.service.currentVersion(value.finance, value.project.id)).toBe(1);
  });

  it('rejects incompatible legal entity and tax selections on a same-date correction', () => {
    const value = setup();
    value.service.save(value.finance, value.input({ effectiveFrom: dayOffset(0) }));
    const otherTax = value.repository.createTaxProfile(value.finance, {
      name: 'USD tax',
      currency: 'USD',
      effectiveFrom: '2026-01-01',
      components: [{ name: 'Zero', basisPoints: 0 }],
    });
    expect(() =>
      value.service.save(
        value.finance,
        value.input({
          expectedVersion: 1,
          effectiveFrom: dayOffset(0),
          laborTaxProfileId: otherTax.id,
        }),
      ),
    ).toThrow(ValidationError);
    expect(value.service.currentVersion(value.finance, value.project.id)).toBe(1);
  });

  it('lets an initial project setup cover approved older work only without overlapping billing history', () => {
    const value = setup();
    expect(
      value.service.save(value.finance, value.input({ effectiveFrom: '2026-01-01' })).version,
    ).toBe(1);
    expect(() =>
      value.service.save(
        value.finance,
        value.input({
          expectedVersion: 1,
          effectiveFrom: '2026-01-01',
        }),
      ),
    ).toThrow(ConflictError);
  });

  it('keeps an ambiguous worker assignment visible as needing review', () => {
    const value = setup();
    value.repository.assignWorker(value.owner, {
      projectId: value.project.id,
      workerId: value.worker.userId,
      startsOn: '2026-02-01',
    });
    expect(value.service.peopleReview(value.finance, value.project.id, '2026-08-15')).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: value.worker.userId, needsReview: true }),
      ]),
    );
  });

  it('includes future project members and saves selected people in one rollback-safe batch', () => {
    const value = setup();
    const futureWorkerId = 'future-terms-worker';
    seedB5User(value.sqlite, futureWorkerId, 'worker');
    const futureDate = dayOffset(5);
    value.repository.assignWorker(value.owner, {
      projectId: value.project.id,
      workerId: futureWorkerId,
      startsOn: futureDate,
    });
    const people = value.service.peopleReview(value.finance, value.project.id, dayOffset(0));
    expect(people).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: futureWorkerId, termsEffectiveFrom: futureDate }),
      ]),
    );
    const terms = (
      person: (typeof people)[number],
      effectiveFrom: string,
    ): ProjectPersonTermsInput => ({
      projectId: value.project.id,
      projectMemberId: person.assignmentId,
      workerId: person.id,
      expectedFingerprint: person.termsFingerprint,
      effectiveFrom,
      customerHourlyRate: person.id === futureWorkerId ? '70' : '55',
      workerPayType: 'Hourly',
      workerPayAmount: '30',
      percentageBasis: 'CLIENT_LABOR_BEFORE_TAX',
      expensePayer: 'worker',
      workerReimbursement: 'at_cost',
      clientRecovery: 'at_cost',
      markupPercent: '',
    });
    const first = people.find((person) => person.id === value.worker.userId)!;
    const second = people.find((person) => person.id === futureWorkerId)!;
    const commands = [terms(first, dayOffset(1)), terms(second, futureDate)];
    expect(() => value.service.savePeopleTerms(value.worker, commands)).toThrow(AccessDeniedError);
    expect(() => value.service.savePeopleTerms(value.manager, commands)).toThrow(AccessDeniedError);
    expect(() =>
      value.service.savePeopleTerms(value.finance, [
        commands[0]!,
        {
          ...commands[1]!,
          clientRecovery: 'client_direct',
        },
      ]),
    ).toThrow();
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM client_labor_rate WHERE project_id=?')
        .get(value.project.id),
    ).toEqual({ count: 0 });
    expect(value.service.savePeopleTerms(value.finance, commands)).toEqual({ saved: 2 });
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM client_labor_rate WHERE project_id=?')
        .get(value.project.id),
    ).toEqual({ count: 2 });
  });

  it('saves per-person customer, pay and expense terms atomically and shows them after reload', () => {
    const value = setup();
    const assignment = value.sqlite
      .prepare('SELECT id FROM project_member WHERE project_id=? AND user_id=?')
      .get(value.project.id, value.worker.userId) as { id: string };
    const command: ProjectPersonTermsInput = {
      projectId: value.project.id,
      projectMemberId: assignment.id,
      workerId: value.worker.userId,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      effectiveFrom: dayOffset(1),
      customerHourlyRate: '55.00',
      workerPayType: 'Hourly',
      workerPayAmount: '30.00',
      percentageBasis: 'CLIENT_LABOR_BEFORE_TAX',
      expensePayer: 'worker',
      workerReimbursement: 'at_cost',
      clientRecovery: 'at_cost',
      markupPercent: '',
    };
    expect(value.service.savePersonTerms(value.finance, command)).toEqual({ changed: true });
    const rows = value.service.peopleReview(value.finance, value.project.id, dayOffset(1));
    expect(rows).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: value.worker.userId,
          customerRateAmount: '55.00',
          payType: 'Hourly',
          payAmount: '30.00',
          expensePayer: 'worker',
          workerReimbursement: 'at_cost',
          clientRecovery: 'at_cost',
        }),
      ]),
    );
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM assignment_rate_override WHERE project_member_id=?')
        .get(assignment.id),
    ).toEqual({ count: 1 });
    expect(() => value.service.savePersonTerms(value.finance, command)).toThrow(ConflictError);
    const changed = {
      ...command,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      effectiveFrom: dayOffset(2),
      customerHourlyRate: '70.00',
      workerPayType: 'Daily' as const,
      workerPayAmount: '220.00',
    };
    expect(value.service.savePersonTerms(value.finance, changed)).toEqual({ changed: true });
    expect(value.service.peopleReview(value.finance, value.project.id, dayOffset(2))).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: value.worker.userId,
          customerRateAmount: '70.00',
          payType: 'Daily',
          payAmount: '220.00',
        }),
      ]),
    );
  });

  it('rolls back person rates when expense terms fail and denies other roles', () => {
    const value = setup();
    const assignment = value.sqlite
      .prepare('SELECT id FROM project_member WHERE project_id=? AND user_id=?')
      .get(value.project.id, value.worker.userId) as { id: string };
    const command: ProjectPersonTermsInput = {
      projectId: value.project.id,
      projectMemberId: assignment.id,
      workerId: value.worker.userId,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      effectiveFrom: dayOffset(1),
      customerHourlyRate: '55',
      workerPayType: 'Hourly',
      workerPayAmount: '30',
      percentageBasis: 'CLIENT_LABOR_BEFORE_TAX',
      expensePayer: 'client',
      workerReimbursement: 'at_cost',
      clientRecovery: 'client_direct',
      markupPercent: '',
    };
    expect(() => value.service.savePersonTerms(value.finance, command)).toThrow(ValidationError);
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM client_labor_rate WHERE project_id=? AND worker_id=?')
        .get(value.project.id, value.worker.userId),
    ).toEqual({ count: 0 });
    expect(
      value.sqlite
        .prepare('SELECT COUNT(*) count FROM compensation_rule WHERE project_id=? AND worker_id=?')
        .get(value.project.id, value.worker.userId),
    ).toEqual({ count: 0 });
    for (const principal of [value.worker, value.manager])
      expect(() => value.service.savePersonTerms(principal, command)).toThrow(AccessDeniedError);
  });

  it('keeps fixed and percentage pay methods explicit and other payer policies visible', () => {
    const value = setup();
    const assignment = value.sqlite
      .prepare('SELECT id FROM project_member WHERE project_id=? AND user_id=?')
      .get(value.project.id, value.worker.userId) as { id: string };
    const base: ProjectPersonTermsInput = {
      projectId: value.project.id,
      projectMemberId: assignment.id,
      workerId: value.worker.userId,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      effectiveFrom: dayOffset(1),
      customerHourlyRate: '55',
      workerPayType: 'FixedPerBillingPeriod',
      workerPayAmount: '1000',
      percentageBasis: 'CLIENT_LABOR_BEFORE_TAX',
      expensePayer: 'worker',
      workerReimbursement: 'at_cost',
      clientRecovery: 'at_cost',
      markupPercent: '',
    };
    value.service.savePersonTerms(value.finance, base);
    expect(value.service.peopleReview(value.finance, value.project.id, dayOffset(1))).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: value.worker.userId,
          payType: 'FixedPerBillingPeriod',
          payAmount: '1000.00',
        }),
      ]),
    );
    const sameDay = {
      ...base,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      workerPayAmount: '1100',
    };
    expect(() => value.service.savePersonTerms(value.finance, sameDay)).toThrow(
      /later effective date/i,
    );
    value.service.savePersonTerms(value.finance, {
      ...base,
      expectedFingerprint: value.service.personTermsFingerprint(
        value.finance,
        value.project.id,
        value.worker.userId,
      ),
      effectiveFrom: dayOffset(2),
      workerPayType: 'PercentageOfEligibleClientLabor',
      workerPayAmount: '12.50',
      expensePayer: 'company_card',
      workerReimbursement: 'none',
      clientRecovery: 'included',
    });
    expect(value.service.peopleReview(value.finance, value.project.id, dayOffset(2))).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: value.worker.userId,
          payType: 'PercentageOfEligibleClientLabor',
          payAmount: '12.50',
          activeExpensePayers: ['company_card', 'worker'],
        }),
      ]),
    );
  });
});
