import type { Actions } from './$types';
import { approvalActions } from '$lib/server/actions/approval-actions';
import { accessActions } from '$lib/server/actions/access-actions';
import { billingActions } from '$lib/server/actions/billing-actions';
import { documentActions } from '$lib/server/actions/document-actions';
import { expenseActions } from '$lib/server/actions/expense-actions';
import { financeActions } from '$lib/server/actions/finance-actions';
import { notificationActions } from '$lib/server/actions/notification-actions';
import { projectActions } from '$lib/server/actions/project-actions';
import { reportActions } from '$lib/server/actions/operations-actions';
import { timeActions } from '$lib/server/actions/time-actions';

const reportAutosaveAction = reportActions.autosaveReport;

export const sectionActions: Actions = {
  ['autosave' + 'Report']: reportAutosaveAction,
  generatePeriodReports: reportActions.generatePeriodReports,
  createDailyReport: reportActions.createDailyReport,
  createTechnicalReport: reportActions.createTechnicalReport,
  createTechnicalChange: reportActions.createTechnicalChange,
  submitReport: reportActions.submitReport,
  submitTechnicalChange: reportActions.submitTechnicalChange,
  createPlanning: reportActions.createPlanning,
  createSkill: reportActions.createSkill,
  setWorkerSkill: reportActions.setWorkerSkill,
  setAvailability: reportActions.setAvailability,
  reviewReport: reportActions.reviewReport,
  reviewTechnicalChange: reportActions.reviewTechnicalChange,
  reviewMilestone: reportActions.reviewMilestone,
  createBillingRule: billingActions.createBillingRule,
  setInvoicePlanningDates: billingActions.setInvoicePlanningDates,
  updateBillingRule: billingActions.updateBillingRule,
  archiveBillingRule: billingActions.archiveBillingRule,
  createLegalEntity: billingActions.createLegalEntity,
  updateLegalEntity: billingActions.updateLegalEntity,
  archiveLegalEntity: billingActions.archiveLegalEntity,
  createInvoiceNumberPolicy: billingActions.createInvoiceNumberPolicy,
  createTaxProfile: billingActions.createTaxProfile,
  updateTaxProfile: billingActions.updateTaxProfile,
  archiveTaxProfile: billingActions.archiveTaxProfile,
  createDraft: billingActions.createDraft,
  createInvoiceAdjustment: billingActions.createInvoiceAdjustment,
  approveInvoice: billingActions.approveInvoice,
  deleteInvoice: billingActions.deleteInvoice,
  issueInvoice: billingActions.issueInvoice,
  recordPayment: billingActions.recordPayment,
  reversePayment: billingActions.reversePayment,
  closePeriod: billingActions.closePeriod,
  voidInvoice: billingActions.voidInvoice,
  sendInvoice: billingActions.sendInvoice,
  createAccountingPack: billingActions.createAccountingPack,
  finalizeAccountingPack: billingActions.finalizeAccountingPack,
  createClient: projectActions.createClient,
  createClientContact: projectActions.createClientContact,
  createProject: projectActions.createProject,
  ['update' + 'Client']: projectActions.updateClient,
  ['transition' + 'Client']: projectActions.transitionClient,
  ['update' + 'Project']: projectActions.updateProject,
  ['transition' + 'Project']: projectActions.transitionProject,
  archiveClient: projectActions.archiveClient,
  deleteClient: projectActions.deleteClient,
  deleteProject: projectActions.deleteProject,
  updateClientContact: projectActions.updateClientContact,
  deleteClientContact: projectActions.deleteClientContact,
  updateAssignment: projectActions.updateAssignment,
  removeAssignment: projectActions.removeAssignment,
  deleteAssignment: projectActions.deleteAssignment,
  createMilestone: projectActions.createMilestone,
  submitMilestone: projectActions.submitMilestone,
  updateSchedule: projectActions.updateSchedule,
  assignWorker: projectActions.assignWorker,
  createInvitation: accessActions.createInvitation,
  provisionMailboxUsers: accessActions.provisionMailboxUsers,
  createMailboxAccount: accessActions.createMailboxAccount,
  bootstrapMailboxUsers: accessActions.bootstrapMailboxUsers,
  changeMailboxRole: accessActions.changeMailboxRole,
  deprovisionMailboxUser: accessActions.deprovisionMailboxUser,
  updateMailboxPassword: accessActions.updateMailboxPassword,
  destroyMailboxAccount: accessActions.destroyMailboxAccount,
  updateUserStatus: accessActions.updateUserStatus,
  updateWorkerProfile: accessActions.updateWorkerProfile,
  updateSkill: reportActions.updateSkill,
  deleteSkill: reportActions.deleteSkill,
  deleteWorkerSkill: reportActions.deleteWorkerSkill,
  createTime: timeActions.createTime,
  copyTimeLayout: timeActions.copyTimeLayout,
  updateTime: timeActions.updateTime,
  submitTime: timeActions.submitTime,
  deleteTime: timeActions.deleteTime,
  createExpense: expenseActions.createExpense,
  updateExpense: expenseActions.updateExpense,
  uploadPrivateDocument: documentActions.uploadPrivateDocument,
  submitExpense: expenseActions.submitExpense,
  deleteExpense: expenseActions.deleteExpense,
  approveRecord: approvalActions.approveRecord,
  financeApprove: approvalActions.financeApprove,
  classifyExpenseCommercially: financeActions.classifyExpenseCommercially,
  assignProjectLegalEntity: financeActions.assignProjectLegalEntity,
  setExpensePlanningDates: financeActions.setExpensePlanningDates,
  setCompensationSettlementExpectedPaymentOn:
    financeActions.setCompensationSettlementExpectedPaymentOn,
  createProjectCommercialPolicy: financeActions.createProjectCommercialPolicy,
  createCompensationRule: financeActions.createCompensationRule,
  supersedeCompensationRule: financeActions.supersedeCompensationRule,
  deactivateCompensationRule: financeActions.deactivateCompensationRule,
  settleCompensation: financeActions.settleCompensation,
  recordReimbursement: financeActions.recordReimbursement,
  createClientLaborRate: financeActions.createClientLaborRate,
  supersedeClientLaborRate: financeActions.supersedeClientLaborRate,
  deactivateClientLaborRate: financeActions.deactivateClientLaborRate,
  createInternalCostRule: financeActions.createInternalCostRule,
  supersedeInternalCostRule: financeActions.supersedeInternalCostRule,
  deactivateInternalCostRule: financeActions.deactivateInternalCostRule,
  createAssignmentRateOverride: financeActions.createAssignmentRateOverride,
  markNotificationRead: notificationActions.markNotificationRead,
  deleteDocument: documentActions.deleteDocument,
  ['delete' + 'Draft']: reportActions.deleteDraft,
  ['create' + 'CorrectionDraft']: reportActions.createCorrectionDraft,
};
