export const cashCopy = {
  en: {
    title: 'Cash calendar',
    back: 'Back to Finance',
    explanation:
      'Obligations and expected movements, grouped by project issuing entity and currency. This is not a bank balance. Expected dates and actual recorded transactions are separate; no opening cash or exchange-rate conversion is assumed.',
    pending:
      'Finalized compensation without transfer evidence needs confirmation. These amounts are shown separately and excluded from expected and actual totals. They are not asserted to be paid or unpaid.',
    from: 'From',
    to: 'To',
    project: 'Project',
    all: 'All projects',
    group: 'Group by',
    week: 'Week',
    month: 'Month',
    apply: 'Apply filters',
    undated: 'Date not recorded',
    unknownEntity: 'Issuing entity needs review',
    expectedIn: 'Expected receipts',
    expectedOut: 'Expected payments',
    expectedNet: 'Net expected movements',
    actualNet: 'Net recorded movements',
    unconfirmed: 'Payment confirmation needed',
    sources: 'Source records',
    none: 'No movements match these filters.',
    due: 'Invoice due date',
    expected: 'Expected date',
    actual: 'Recorded transaction date',
    amount: 'Amount',
    reference: 'Reference / source state',
    open: 'Open source',
    unknownDateNote:
      'Records without dates remain visible in a separate group, including when date filters are applied.',
    customer_receipt: 'Customer receipt',
    receipt_reversal: 'Receipt reversal',
    worker_compensation: 'Worker compensation',
    worker_reimbursement: 'Worker reimbursement',
    expectedBasis: 'Expected',
    actualBasis: 'Recorded',
    needs_confirmation: 'Needs confirmation',
  },
  es: {
    title: 'Calendario de caja',
    back: 'Volver a Finanzas',
    explanation:
      'Obligaciones y movimientos previstos, agrupados por entidad emisora del proyecto y moneda. No es un saldo bancario. Las fechas previstas y las transacciones registradas están separadas; no se supone saldo inicial ni conversión de moneda.',
    pending:
      'La compensación finalizada sin evidencia de transferencia necesita confirmación. Estos importes se muestran separados y no entran en los totales previstos ni registrados. No se consideran pagados ni impagados.',
    from: 'Desde',
    to: 'Hasta',
    project: 'Proyecto',
    all: 'Todos los proyectos',
    group: 'Agrupar por',
    week: 'Semana',
    month: 'Mes',
    apply: 'Aplicar filtros',
    undated: 'Fecha no registrada',
    unknownEntity: 'Revisar entidad emisora',
    expectedIn: 'Cobros previstos',
    expectedOut: 'Pagos previstos',
    expectedNet: 'Movimientos previstos netos',
    actualNet: 'Movimientos registrados netos',
    unconfirmed: 'Confirmación de pago pendiente',
    sources: 'Registros de origen',
    none: 'No hay movimientos con estos filtros.',
    due: 'Vencimiento de factura',
    expected: 'Fecha prevista',
    actual: 'Fecha de transacción registrada',
    amount: 'Importe',
    reference: 'Referencia / estado de origen',
    open: 'Abrir origen',
    unknownDateNote:
      'Los registros sin fecha permanecen visibles en un grupo separado, incluso al filtrar por fechas.',
    customer_receipt: 'Cobro del cliente',
    receipt_reversal: 'Reversión de cobro',
    worker_compensation: 'Compensación del trabajador',
    worker_reimbursement: 'Reembolso al trabajador',
    expectedBasis: 'Previsto',
    actualBasis: 'Registrado',
    needs_confirmation: 'Necesita confirmación',
  },
  pt: {
    title: 'Calendário de caixa',
    back: 'Voltar a Finanças',
    explanation:
      'Obrigações e movimentos previstos, agrupados pela entidade emissora do projeto e moeda. Não é um saldo bancário. Datas previstas e transações registradas ficam separadas; não se presume saldo inicial nem conversão de moeda.',
    pending:
      'Remuneração finalizada sem evidência de transferência precisa de confirmação. Esses valores aparecem separados e não entram nos totais previstos ou registrados. Não são considerados pagos nem em aberto.',
    from: 'Desde',
    to: 'Até',
    project: 'Projeto',
    all: 'Todos os projetos',
    group: 'Agrupar por',
    week: 'Semana',
    month: 'Mês',
    apply: 'Aplicar filtros',
    undated: 'Data não registrada',
    unknownEntity: 'Revisar entidade emissora',
    expectedIn: 'Recebimentos previstos',
    expectedOut: 'Pagamentos previstos',
    expectedNet: 'Movimentos previstos líquidos',
    actualNet: 'Movimentos registrados líquidos',
    unconfirmed: 'Confirmação de pagamento pendente',
    sources: 'Registros de origem',
    none: 'Nenhum movimento corresponde aos filtros.',
    due: 'Vencimento da fatura',
    expected: 'Data prevista',
    actual: 'Data da transação registrada',
    amount: 'Valor',
    reference: 'Referência / estado de origem',
    open: 'Abrir origem',
    unknownDateNote:
      'Registros sem data permanecem visíveis em um grupo separado, inclusive ao filtrar por datas.',
    customer_receipt: 'Recebimento do cliente',
    receipt_reversal: 'Estorno de recebimento',
    worker_compensation: 'Remuneração do colaborador',
    worker_reimbursement: 'Reembolso ao colaborador',
    expectedBasis: 'Previsto',
    actualBasis: 'Registrado',
    needs_confirmation: 'Precisa de confirmação',
  },
};
