export const copy = {
  en: {
    title: 'Commercial agreement and example',
    back: 'Back to commercial setup',
    project: 'Project',
    select: 'Select a project',
    view: 'View agreement',
    summary: 'Recorded project configuration',
    pricing: 'Labour pricing',
    hourly: 'Hourly labour',
    fixed: 'Fixed engagement (existing all-in)',
    allInHourly: 'Hourly labour with selected expenses included (all-in)',
    currency: 'Currency',
    reference: 'Reference day (hours)',
    minimum: 'Customer minimum (hours)',
    sample: 'Single-worker calculation example',
    scope:
      'These editable sample values are not project rates or saved configuration. The example covers one worker, one workday, hourly compensation and a loaded cost that already includes pay. Travel, percentage pay, caps, taxes and mixed-rate minimums need the project’s effective rules; review them in commercial setup.',
    work: 'Actual work (hours)',
    sell: 'Customer hourly rate',
    pay: 'Worker hourly pay',
    cost: 'Loaded hourly cost (including pay)',
    expenses: 'Expense responsibility',
    included: 'Included in hourly price',
    recoverable: 'Recovered from customer at cost',
    direct: 'Customer paid directly',
    expenseAmount: 'Expense amount',
    payer: 'Worker advanced this expense',
    yes: 'Yes',
    no: 'No',
    fixedPrice: 'Fixed labour price',
    overtime: 'Optional overtime',
    threshold: 'Starts after work hours (blank = off)',
    sellMultiplier: 'Customer total multiplier',
    payMultiplier: 'Worker total multiplier',
    costMultiplier: 'Loaded-cost total multiplier',
    multiplierNote: '1.6× means a total rate of 160% of the base hourly rate.',
    periods: 'Upcoming billing periods',
    cadence: 'Cadence for this example',
    weekly: 'Weekly',
    fortnight: 'Every 14 days (anchored)',
    twice: 'Twice monthly (1–15 / 16–end)',
    monthly: 'Monthly',
    custom: 'Custom / manual',
    date: 'Example date',
    anchor: '14-day anchor',
    calculate: 'Calculate example',
    invalid:
      'Review the entered values. Use valid dates and non-negative amounts, hours that resolve to whole minutes, a positive overtime threshold or leave it blank, and multipliers up to 10. Customer-direct expenses cannot also be advanced by the worker.',
    result: 'Example result — before tax',
    actual: 'Actual hours',
    regular: 'Regular work hours',
    overtimeHours: 'Overtime work hours',
    adjustment: 'Additional minimum billable hours',
    laborRevenue: 'Customer labour',
    expenseRevenue: 'Customer expense recovery',
    totalRevenue: 'Revenue candidate',
    workerPay: 'Worker compensation',
    laborCost: 'Loaded labour cost',
    expenseCost: 'J&A expense cost',
    totalCost: 'Direct project cost',
    contribution: 'Direct contribution',
    reimbursement: 'Worker reimbursement obligation',
    resultNote:
      'Actual hours stay unchanged. Reference hours do not create work. Reimbursement and compensation are separate obligations; these example amounts do not record payment.',
    streams: 'Recorded billing streams',
    policies: 'Effective commercial policy history',
    from: 'From',
    to: 'To',
    signoff: 'Customer sign-off required',
    travel: 'Travel billable to customer',
    enabled: 'Overtime enabled',
    none: 'Not configured',
    expenseNote:
      'All-in does not automatically mean fixed price. Hourly labour can include selected expenses while worker reimbursement and J&A cost remain separate. A fixed engagement exists only when a fixed labour price is explicitly configured.',
  },
  es: {
    title: 'Acuerdo comercial y ejemplo',
    back: 'Volver a configuración comercial',
    project: 'Proyecto',
    select: 'Seleccionar proyecto',
    view: 'Ver acuerdo',
    summary: 'Configuración registrada del proyecto',
    pricing: 'Precio de labor',
    hourly: 'Labor por horas',
    fixed: 'Importe fijo (all-in existente)',
    allInHourly: 'Labor por horas con gastos seleccionados incluidos (all-in)',
    currency: 'Moneda',
    reference: 'Jornada de referencia (horas)',
    minimum: 'Mínimo al cliente (horas)',
    sample: 'Ejemplo de cálculo de un trabajador',
    scope:
      'Estos valores de ejemplo son editables y no son tarifas del proyecto ni configuración guardada. El ejemplo cubre un trabajador, una jornada, compensación horaria y un coste cargado que ya incluye la compensación. Viajes, porcentajes, límites, impuestos y mínimos con tarifas mixtas requieren las reglas vigentes del proyecto; revíselas en configuración comercial.',
    work: 'Trabajo real (horas)',
    sell: 'Tarifa horaria al cliente',
    pay: 'Compensación horaria del trabajador',
    cost: 'Coste horario cargado (incluye compensación)',
    expenses: 'Responsabilidad de gastos',
    included: 'Incluidos en el precio horario',
    recoverable: 'Repercutidos al cliente a coste',
    direct: 'Pagados directamente por el cliente',
    expenseAmount: 'Importe del gasto',
    payer: 'El trabajador adelantó este gasto',
    yes: 'Sí',
    no: 'No',
    fixedPrice: 'Precio fijo de labor',
    overtime: 'Horas extra opcionales',
    threshold: 'Después de estas horas (vacío = desactivado)',
    sellMultiplier: 'Multiplicador total al cliente',
    payMultiplier: 'Multiplicador total del trabajador',
    costMultiplier: 'Multiplicador total del coste',
    multiplierNote: '1,6× significa una tarifa total del 160% de la tarifa base.',
    periods: 'Próximos periodos de facturación',
    cadence: 'Frecuencia del ejemplo',
    weekly: 'Semanal',
    fortnight: 'Cada 14 días (con fecha de anclaje)',
    twice: 'Dos veces al mes (1–15 / 16–fin)',
    monthly: 'Mensual',
    custom: 'Personalizado / manual',
    date: 'Fecha del ejemplo',
    anchor: 'Anclaje de 14 días',
    calculate: 'Calcular ejemplo',
    invalid:
      'Revise los valores. Use fechas válidas, importes no negativos, horas equivalentes a minutos enteros, umbral positivo o vacío y multiplicadores hasta 10. Un gasto pagado por el cliente no puede estar adelantado por el trabajador.',
    result: 'Resultado del ejemplo — antes de impuestos',
    actual: 'Horas reales',
    regular: 'Horas regulares',
    overtimeHours: 'Horas extra',
    adjustment: 'Horas adicionales por mínimo facturable',
    laborRevenue: 'Labor al cliente',
    expenseRevenue: 'Recuperación de gastos del cliente',
    totalRevenue: 'Ingreso candidato',
    workerPay: 'Compensación del trabajador',
    laborCost: 'Coste cargado de labor',
    expenseCost: 'Coste de gastos J&A',
    totalCost: 'Coste directo del proyecto',
    contribution: 'Contribución directa',
    reimbursement: 'Obligación de reembolso al trabajador',
    resultNote:
      'Las horas reales no cambian. La referencia no crea trabajo. Reembolso y compensación son obligaciones separadas; estos importes de ejemplo no registran pagos.',
    streams: 'Flujos de facturación registrados',
    policies: 'Histórico de políticas comerciales vigentes',
    from: 'Desde',
    to: 'Hasta',
    signoff: 'Conformidad del cliente requerida',
    travel: 'Viaje facturable al cliente',
    enabled: 'Horas extra activadas',
    none: 'Sin configurar',
    expenseNote:
      'All-in no significa automáticamente precio fijo. La labor por horas puede incluir determinados gastos mientras el reembolso al trabajador y el coste de J&A siguen separados. Sólo existe importe fijo cuando se configura expresamente un precio fijo de labor.',
  },
  pt: {
    title: 'Acordo comercial e exemplo',
    back: 'Voltar à configuração comercial',
    project: 'Projeto',
    select: 'Selecionar projeto',
    view: 'Ver acordo',
    summary: 'Configuração registrada do projeto',
    pricing: 'Preço de mão de obra',
    hourly: 'Mão de obra por hora',
    fixed: 'Valor fixo (all-in existente)',
    allInHourly: 'Mão de obra por hora com despesas selecionadas incluídas (all-in)',
    currency: 'Moeda',
    reference: 'Jornada de referência (horas)',
    minimum: 'Mínimo ao cliente (horas)',
    sample: 'Exemplo de cálculo de um colaborador',
    scope:
      'Estes valores editáveis são exemplos, não tarifas do projeto ou configuração salva. O exemplo cobre um colaborador, um dia, remuneração por hora e custo carregado que já inclui a remuneração. Viagens, percentuais, limites, impostos e mínimos com tarifas mistas exigem as regras vigentes do projeto; confira a configuração comercial.',
    work: 'Trabalho real (horas)',
    sell: 'Tarifa por hora ao cliente',
    pay: 'Remuneração por hora do colaborador',
    cost: 'Custo horário carregado (inclui remuneração)',
    expenses: 'Responsabilidade pelas despesas',
    included: 'Incluídas no preço por hora',
    recoverable: 'Repassadas ao cliente pelo custo',
    direct: 'Pagas diretamente pelo cliente',
    expenseAmount: 'Valor da despesa',
    payer: 'O colaborador adiantou esta despesa',
    yes: 'Sim',
    no: 'Não',
    fixedPrice: 'Preço fixo de mão de obra',
    overtime: 'Horas extras opcionais',
    threshold: 'Após estas horas (vazio = desativado)',
    sellMultiplier: 'Multiplicador total ao cliente',
    payMultiplier: 'Multiplicador total do colaborador',
    costMultiplier: 'Multiplicador total do custo',
    multiplierNote: '1,6× significa uma tarifa total de 160% da tarifa base.',
    periods: 'Próximos períodos de faturamento',
    cadence: 'Frequência do exemplo',
    weekly: 'Semanal',
    fortnight: 'A cada 14 dias (com data-âncora)',
    twice: 'Duas vezes por mês (1–15 / 16–fim)',
    monthly: 'Mensal',
    custom: 'Personalizado / manual',
    date: 'Data do exemplo',
    anchor: 'Âncora de 14 dias',
    calculate: 'Calcular exemplo',
    invalid:
      'Revise os valores. Use datas válidas, valores não negativos, horas equivalentes a minutos inteiros, limite positivo ou vazio e multiplicadores até 10. Uma despesa paga pelo cliente não pode ter sido adiantada pelo colaborador.',
    result: 'Resultado do exemplo — antes de impostos',
    actual: 'Horas reais',
    regular: 'Horas regulares',
    overtimeHours: 'Horas extras',
    adjustment: 'Horas adicionais por mínimo faturável',
    laborRevenue: 'Mão de obra ao cliente',
    expenseRevenue: 'Recuperação de despesas do cliente',
    totalRevenue: 'Receita candidata',
    workerPay: 'Remuneração do colaborador',
    laborCost: 'Custo carregado de mão de obra',
    expenseCost: 'Custo de despesas J&A',
    totalCost: 'Custo direto do projeto',
    contribution: 'Contribuição direta',
    reimbursement: 'Obrigação de reembolso ao colaborador',
    resultNote:
      'As horas reais não mudam. A referência não cria trabalho. Reembolso e remuneração são obrigações separadas; estes valores de exemplo não registram pagamentos.',
    streams: 'Fluxos de faturamento registrados',
    policies: 'Histórico de políticas comerciais vigentes',
    from: 'Desde',
    to: 'Até',
    signoff: 'Aceite do cliente obrigatório',
    travel: 'Viagem faturável ao cliente',
    enabled: 'Horas extras ativadas',
    none: 'Não configurado',
    expenseNote:
      'All-in não significa automaticamente preço fixo. A mão de obra por hora pode incluir determinadas despesas, enquanto o reembolso ao colaborador e o custo da J&A continuam separados. Só existe valor fixo quando um preço fixo de mão de obra é configurado explicitamente.',
  },
};
