import type {
  AccountingPackSourceSnapshot,
  InvoiceCollectionLedgerRow,
  ReportLocale,
  WorkerStatementSnapshot,
} from '@ja/reporting';
import type {
  InvoiceTemplateId,
  InvoiceTemplateSnapshot,
} from '../packages/invoice-templates/src/index.ts';

export const exampleLocales = ['en', 'es', 'pt'] as const satisfies readonly ReportLocale[];
export const examplePeriod = { start: '2026-09-01', end: '2026-09-30' } as const;

export const exampleIdentity = {
  issuer: {
    legalName: 'EXAMPLE — NOT PAYABLE — Example Automation Ltd',
    billingAddress: '100 Example Way, Sample City, TX 00000',
    email: 'billing@example.invalid',
    taxId: 'EXAMPLE-NOT-PAYABLE',
  },
  client: {
    legalName: 'EXAMPLE — Example Manufacturing Ltd',
    billingAddress: '200 Fictional Avenue, Sample City, TX 00000',
    email: 'accounts@example.invalid',
  },
  project: {
    id: 'example-project-001',
    number: 'EXAMPLE-P-001',
    name: 'EXAMPLE — Packaging Cell Commissioning',
    clientName: 'Example Manufacturing Ltd',
    poNumber: 'EXAMPLE-NOT-PAYABLE',
    currency: 'USD',
  },
  workers: {
    alex: { id: 'example-worker-alex', name: 'Alex Rivera', email: 'alex.rivera@example.invalid' },
    marina: {
      id: 'example-worker-marina',
      name: 'Marina Costa',
      email: 'marina.costa@example.invalid',
    },
  },
} as const;

export const exampleActivities = [
  {
    id: 'example-time-001',
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    date: '2026-09-08',
    worker: exampleIdentity.workers.alex.name,
    category: 'work',
    activitySummary: 'EXAMPLE — commissioned conveyor interlocks and verified safe stops',
    startTime: '08:00',
    endTime: '16:30',
    breakMinutes: 30,
    actualMinutes: 480,
    minutes: 480,
    approvalState: 'approved',
  },
  {
    id: 'example-time-002',
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    date: '2026-09-09',
    worker: exampleIdentity.workers.marina.name,
    category: 'travel',
    activitySummary: 'EXAMPLE — field validation, operator handover and return travel',
    startTime: '07:30',
    endTime: '15:30',
    breakMinutes: 30,
    actualMinutes: 450,
    minutes: 450,
    approvalState: 'approved',
  },
] as const;

export const exampleExpenses = [
  {
    id: 'example-expense-001',
    date: '2026-09-08',
    spentOn: '2026-09-08',
    spent_on: '2026-09-08',
    client_name: exampleIdentity.client.legalName,
    project: `${exampleIdentity.project.number} · ${exampleIdentity.project.name}`,
    projectNumber: exampleIdentity.project.number,
    project_number: exampleIdentity.project.number,
    project_name: exampleIdentity.project.name,
    worker: exampleIdentity.workers.alex.name,
    workerName: exampleIdentity.workers.alex.name,
    worker_name: exampleIdentity.workers.alex.name,
    vendor: 'EXAMPLE Hotel — NOT PAYABLE',
    category: 'hotel',
    description: 'EXAMPLE lodging receipt',
    currency: 'USD',
    amountMinor: '12400',
    amount_minor: '12400',
    grossMinor: '12400',
    taxMinor: '0',
    who_paid: 'worker',
    approval_state: 'approved',
    reimbursement_state: 'approved',
    billable: true,
  },
  {
    id: 'example-expense-002',
    date: '2026-09-09',
    spentOn: '2026-09-09',
    spent_on: '2026-09-09',
    client_name: exampleIdentity.client.legalName,
    project: `${exampleIdentity.project.number} · ${exampleIdentity.project.name}`,
    projectNumber: exampleIdentity.project.number,
    project_number: exampleIdentity.project.number,
    project_name: exampleIdentity.project.name,
    worker: exampleIdentity.workers.marina.name,
    workerName: exampleIdentity.workers.marina.name,
    worker_name: exampleIdentity.workers.marina.name,
    vendor: 'EXAMPLE Transit — NOT PAYABLE',
    category: 'travel',
    description: 'EXAMPLE local transport receipt',
    currency: 'USD',
    amountMinor: '8600',
    amount_minor: '8600',
    grossMinor: '8600',
    taxMinor: '0',
    who_paid: 'worker',
    approval_state: 'approved',
    reimbursement_state: 'scheduled',
    billable: true,
  },
] as const;

const invoiceAmounts: Record<InvoiceTemplateId, string> = {
  'labor-detailed': '193750',
  'labor-summary': '193750',
  'expenses-detailed': '21000',
  'fixed-milestone': '500000',
  'credit-adjustment': '-12500',
};

export function exampleInvoiceSnapshot(
  templateId: InvoiceTemplateId,
  locale: ReportLocale,
): InvoiceTemplateSnapshot {
  const common = {
    template: { id: templateId, version: 1 },
    number: `EXAMPLE-${templateId.toUpperCase()}-001`,
    purchaseNo: 'EXAMPLE-NOT-PAYABLE',
    issueDate: '2026-09-30',
    dueDate: '2026-10-30',
    locale,
    legalEntity: exampleIdentity.issuer,
    client: exampleIdentity.client,
    project: exampleIdentity.project,
    calculation: {
      currency: 'USD',
      subtotalMinor: invoiceAmounts[templateId],
      taxMinor: '0',
      totalMinor: invoiceAmounts[templateId],
    },
  } as const;
  const linesByTemplate: Record<InvoiceTemplateId, readonly Record<string, unknown>[]> = {
    'labor-detailed': exampleActivities.map((activity) => ({
      description: activity.activitySummary,
      worker: activity.worker,
      date: activity.date,
      start_time: activity.startTime,
      end_time: activity.endTime,
      break_minutes: activity.breakMinutes,
      actual_minutes: activity.actualMinutes,
      quantity: activity.actualMinutes / 60,
      unit_price_minor: '12500',
      subtotal_minor: activity.actualMinutes === 480 ? '100000' : '93750',
      amount_minor: activity.actualMinutes === 480 ? '100000' : '93750',
    })),
    'labor-summary': [
      {
        description: 'EXAMPLE — September commissioning labor summary',
        quantity: 15.5,
        unit_price_minor: '12500',
        subtotal_minor: '193750',
        amount_minor: '193750',
      },
    ],
    'expenses-detailed': exampleExpenses.map((expense) => ({
      description: expense.description,
      vendor: expense.vendor,
      date: expense.spentOn,
      category: expense.category,
      quantity: 1,
      unit_price_minor: expense.amountMinor,
      subtotal_minor: expense.amountMinor,
      amount_minor: expense.amountMinor,
    })),
    'fixed-milestone': [
      {
        description: 'EXAMPLE — Packaging cell commissioning milestone',
        milestone: 'EXAMPLE-M1 — accepted for demonstration only',
        quantity: 1,
        unit_price_minor: '500000',
        subtotal_minor: '500000',
        amount_minor: '500000',
      },
    ],
    'credit-adjustment': [
      {
        description: 'EXAMPLE credit — commissioning allowance, NOT PAYABLE',
        original_invoice: 'EXAMPLE-LABOR-DETAILED-001',
        quantity: 1,
        unit_price_minor: '-12500',
        subtotal_minor: '-12500',
        amount_minor: '-12500',
      },
    ],
  };
  return { ...common, lines: linesByTemplate[templateId] } as InvoiceTemplateSnapshot;
}

export const exampleCustomerPeriod = {
  project: exampleIdentity.project,
  periodStart: examplePeriod.start,
  periodEnd: examplePeriod.end,
  audience: 'customer' as const,
  currency: 'USD',
  commercialSummary: {
    currency: 'USD',
    actualMinutes: 930,
    approvedMinutes: 930,
    billableMinutes: 930,
  },
  dailyReports: [
    {
      work_date: '2026-09-08',
      worker_name: 'Alex Rivera',
      summary: exampleActivities[0].activitySummary,
      approval_state: 'approved',
    },
    {
      work_date: '2026-09-09',
      worker_name: 'Marina Costa',
      summary: exampleActivities[1].activitySummary,
      approval_state: 'approved',
    },
  ],
  technicalReports: [
    {
      report_date: '2026-09-09',
      worker_name: 'Marina Costa',
      change_summary: 'EXAMPLE — adjusted photoeye debounce and validated ten cycles',
      approval_state: 'approved',
    },
  ],
  technicalChanges: [
    {
      created_at: '2026-09-09',
      change_made: 'EXAMPLE — photoeye debounce 40 ms to 80 ms',
      approval_state: 'approved',
    },
  ],
  timeSummary: exampleActivities,
  sourceCounts: { dailyReports: 2, technicalReports: 1, technicalChanges: 1, timeEntries: 2 },
};

export const exampleInternalPeriod = {
  ...exampleCustomerPeriod,
  audience: 'internal' as const,
  commercialSummary: {
    currency: 'USD',
    actualMinutes: 930,
    approvedMinutes: 930,
    billableMinutes: 930,
    candidateSubtotalMinor: '214750',
    operationalRevenueCandidateMinor: '214750',
    invoicedNetMinor: '214750',
    paidMinor: '171000',
    receivableMinor: '43750',
  },
  financialSummary: {
    currency: 'USD',
    approvedCostMinor: '98500',
    contributionMarginMinor: '116250',
    contributionMarginBps: 5413,
  },
  commercialCalculation: [
    { type: 'labor', basis: 'approved actual intervals', minutes: 930, amountMinor: '193750' },
    { type: 'expenses', basis: 'approved example expenses', amountMinor: '21000' },
  ],
};

export const exampleDailyReport = {
  id: 'example-daily-001',
  project: exampleIdentity.project,
  date: '2026-09-08',
  workerName: exampleIdentity.workers.alex.name,
  workerEmail: exampleIdentity.workers.alex.email,
  summary: 'EXAMPLE — Completed conveyor interlock commissioning and safe-stop verification.',
  safetyRelated: true,
  approvalState: 'approved',
  completedWork: 'EXAMPLE — Verified twelve I/O points and ten controlled stop cycles.',
  blockers: 'None in this fictional example.',
  nextSteps: 'EXAMPLE — operator handover and monitoring.',
};

export const exampleTechnicalReport = {
  id: 'example-technical-001',
  project: exampleIdentity.project,
  date: '2026-09-09',
  workerName: exampleIdentity.workers.marina.name,
  workerEmail: exampleIdentity.workers.marina.email,
  systemName: 'EXAMPLE — Packaging Cell PLC',
  plantSite: 'EXAMPLE Manufacturing Site',
  areaLine: 'EXAMPLE Packaging Line 1',
  stationMachine: 'EXAMPLE Case Packer',
  systemType: 'PLC and safety controller',
  plcPlatform: 'EXAMPLE controller — training data',
  controller: 'EXAMPLE-CPU-001',
  hmiScada: 'EXAMPLE-HMI-001',
  networkProtocol: 'Industrial Ethernet — EXAMPLE',
  softwareVersion: 'EXAMPLE v1.0',
  programReference: 'EXAMPLE_P001_REV_02_NOT_FOR_USE',
  problemSymptom: 'EXAMPLE photoeye chatter caused an intermittent carton-present alarm.',
  diagnosisRootCause: 'EXAMPLE input debounce was shorter than the simulated sensor transition.',
  changePerformed: 'EXAMPLE debounce changed from 40 ms to 80 ms.',
  productionImpact: 'No production impact; fictional test mode only.',
  validation: 'EXAMPLE — ten consecutive simulated cartons passed.',
  validationResult: 'Pass for documentation example only.',
  openRisk: 'None; this is synthetic and must not be used for field work.',
  rollbackPlan: 'Restore EXAMPLE_P001_REV_01_NOT_FOR_USE.',
  safetyRelated: false,
  approvalState: 'approved',
  technicalChanges: [
    {
      created_at: '2026-09-09',
      component: 'EXAMPLE photoeye input',
      change_made: 'Debounce 40 ms → 80 ms',
      approval_state: 'approved',
    },
  ],
};

export function exampleWorkerStatement(locale: ReportLocale): WorkerStatementSnapshot {
  return {
    locale,
    worker: exampleIdentity.workers.alex,
    periodStart: examplePeriod.start,
    periodEnd: examplePeriod.end,
    currency: 'USD',
    approvedMinutes: 480,
    pendingMinutes: 0,
    estimatedApprovedMinor: '40000',
    estimatedPendingMinor: '0',
    approvedReimbursementMinor: '12400',
    pendingReimbursementMinor: '0',
    missingCompensationRules: 0,
    activities: [exampleActivities[0]],
    settlements: [
      {
        id: 'example-settlement-001',
        projectNumber: exampleIdentity.project.number,
        projectName: exampleIdentity.project.name,
        periodStart: examplePeriod.start,
        periodEnd: examplePeriod.end,
        amountMinor: '40000',
        currency: 'USD',
        state: 'final',
        paymentState: 'paid',
        paidAmountMinor: '40000',
        remainingAmountMinor: '0',
        actualPaymentOn: '2026-10-05',
        settledAt: '2026-10-05T12:00:00.000Z',
      },
    ],
    expenses: [
      {
        id: exampleExpenses[0].id,
        projectNumber: exampleIdentity.project.number,
        spentOn: exampleExpenses[0].spentOn,
        vendor: exampleExpenses[0].vendor,
        category: exampleExpenses[0].category,
        reimbursementAmountMinor: exampleExpenses[0].amountMinor,
        currency: 'USD',
        approvalState: 'approved',
        reimbursementState: 'approved',
        reimbursedAt: '2026-10-05T12:00:00.000Z',
      },
    ],
  };
}

export const exampleAccountingPack: AccountingPackSourceSnapshot = {
  periodStart: examplePeriod.start,
  periodEnd: examplePeriod.end,
  currency: 'USD',
  invoiceRegister: [
    {
      invoiceNumber: 'EXAMPLE-LABOR-001',
      client: exampleIdentity.client.legalName,
      project: exampleIdentity.project.name,
      projectNumber: exampleIdentity.project.number,
      stream: 'labor',
      servicePeriod: '2026-09-01 → 2026-09-30',
      issueDate: '2026-09-30',
      dueDate: '2026-10-30',
      subtotalMinor: '193750',
      taxMinor: '0',
      totalMinor: '193750',
      grossMinor: '193750',
      currency: 'USD',
    },
    {
      invoiceNumber: 'EXAMPLE-EXPENSE-001',
      client: exampleIdentity.client.legalName,
      project: exampleIdentity.project.name,
      projectNumber: exampleIdentity.project.number,
      stream: 'expense',
      servicePeriod: '2026-09-01 → 2026-09-30',
      issueDate: '2026-09-30',
      dueDate: '2026-10-30',
      subtotalMinor: '21000',
      taxMinor: '0',
      totalMinor: '21000',
      grossMinor: '21000',
      currency: 'USD',
    },
    {
      invoiceNumber: 'EXAMPLE-MILESTONE-001',
      client: exampleIdentity.client.legalName,
      project: exampleIdentity.project.name,
      projectNumber: exampleIdentity.project.number,
      stream: 'milestone',
      servicePeriod: '2026-09-01 → 2026-09-30',
      issueDate: '2026-09-30',
      dueDate: '2026-10-30',
      subtotalMinor: '500000',
      taxMinor: '0',
      totalMinor: '500000',
      grossMinor: '500000',
      currency: 'USD',
    },
    {
      invoiceNumber: 'EXAMPLE-CREDIT-001',
      client: exampleIdentity.client.legalName,
      project: exampleIdentity.project.name,
      projectNumber: exampleIdentity.project.number,
      stream: 'credit',
      servicePeriod: '2026-09-01 → 2026-09-30',
      issueDate: '2026-09-30',
      dueDate: '2026-09-30',
      subtotalMinor: '-12500',
      taxMinor: '0',
      totalMinor: '-12500',
      grossMinor: '-12500',
      currency: 'USD',
    },
  ],
  collections: [
    {
      invoiceNumber: 'EXAMPLE-LABOR-001',
      receivedAt: '2026-10-10',
      client: exampleIdentity.client.legalName,
      currency: 'USD',
      amountMinor: '150000',
      paymentMethod: 'example_wire',
      reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
    },
    {
      invoiceNumber: 'EXAMPLE-EXPENSE-001',
      receivedAt: '2026-10-10',
      client: exampleIdentity.client.legalName,
      currency: 'USD',
      amountMinor: '21000',
      paymentMethod: 'example_wire',
      reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
    },
    {
      invoiceNumber: 'EXAMPLE-MILESTONE-001',
      receivedAt: '2026-10-15',
      client: exampleIdentity.client.legalName,
      currency: 'USD',
      amountMinor: '250000',
      paymentMethod: 'example_wire',
      reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
    },
  ],
  workerCosts: [
    {
      worker: 'Alex Rivera',
      project: exampleIdentity.project.number,
      actualApprovedMinutes: 480,
      approvedCompensationMinor: '40000',
      currency: 'USD',
    },
    {
      worker: 'Marina Costa',
      project: exampleIdentity.project.number,
      actualApprovedMinutes: 450,
      approvedCompensationMinor: '37500',
      currency: 'USD',
    },
  ],
  expenseRegister: exampleExpenses,
  totals: {
    currency: 'USD',
    laborInvoicedMinor: '193750',
    expenseInvoicedMinor: '21000',
    milestoneOtherInvoicedMinor: '500000',
    creditsMinor: '-12500',
    totalInvoicedMinor: '702250',
    taxInvoicedMinor: '0',
    grossInvoicedMinor: '702250',
    collectedMinor: '421000',
    outstandingMinor: '281250',
    workerCompensationMinor: '77500',
    internalLaborCostMinor: '77500',
    travelCostMinor: '21000',
    directCostMinor: '98500',
    contributionMinor: '603750',
  },
  totalsByCurrency: [
    {
      currency: 'USD',
      totalInvoicedMinor: '702250',
      collectedMinor: '421000',
      outstandingMinor: '281250',
      directCostMinor: '98500',
      contributionMinor: '603750',
    },
  ],
};

export const exampleProjectFinance = {
  project: {
    project_number: exampleIdentity.project.number,
    project_name: exampleIdentity.project.name,
    client_number: 'EXAMPLE-C-001',
    client_name: exampleIdentity.client.legalName,
    currency: 'USD',
    period_start: examplePeriod.start,
    period_end: examplePeriod.end,
  },
  financial: {
    currency: 'USD',
    candidateSubtotalMinor: '702250',
    invoicedNetMinor: '702250',
    paidMinor: '421000',
    receivableMinor: '281250',
    approvedCostMinor: '98500',
    contributionMarginMinor: '603750',
    contributionMarginBps: 8597,
    alerts: [],
    reasons: [],
  },
  timeEconomics: exampleActivities.map((activity, index) => ({
    worker: activity.worker,
    date: activity.date,
    category: activity.category,
    actualMinutes: activity.actualMinutes,
    billableMinutes: activity.actualMinutes,
    clientRevenueExactMinor: index === 0 ? '100000' : '93750',
    internalCostExactMinor: index === 0 ? '40000' : '37500',
    workerCompensationExactMinor: index === 0 ? '40000' : '37500',
    billability: 'billable',
    approval: 'approved',
    billingStatus: 'invoiced',
    invoiceId: 'EXAMPLE-LABOR-001',
    startTime: activity.startTime,
    endTime: activity.endTime,
    breakMinutes: activity.breakMinutes,
  })),
  expenseEconomics: exampleExpenses.map((expense) => ({
    worker: expense.worker,
    date: expense.spentOn,
    category: expense.category,
    paidBy: 'worker',
    treatment: 'reimbursable',
    costExactMinor: expense.amountMinor,
    revenueExactMinor: expense.amountMinor,
    approval: 'approved',
    financeApproval: 'approved',
    projection: 'reimbursable',
  })),
  invoices: exampleAccountingPack.invoiceRegister,
  milestones: [
    {
      name: 'EXAMPLE commissioning milestone',
      due_on: '2026-09-30',
      approval_state: 'approved',
      amount_minor: '500000',
      currency: 'USD',
    },
  ],
};

export const exampleLedgerRows: readonly InvoiceCollectionLedgerRow[] = [
  {
    invoiceId: 'example-invoice-labor',
    invoiceNumber: 'EXAMPLE-LABOR-001',
    clientNumber: 'EXAMPLE-C-001',
    clientName: exampleIdentity.client.legalName,
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    issueDate: '2026-09-30',
    dueDate: '2026-10-30',
    currency: 'USD',
    subtotalMinor: '193750',
    taxMinor: '0',
    totalMinor: '193750',
    grossPaymentsMinor: '150000',
    paymentReversalsMinor: '0',
    netCollectedMinor: '150000',
    collectedMinor: '150000',
    outstandingMinor: '43750',
    directCostKnownMinor: '77500',
    directCostMinor: '77500',
    directCostComplete: true,
    directCostMissingSourceIds: [],
    contributionMinor: '116250',
    contributionMarginBps: '6000',
    paymentStatus: 'partially_paid',
    billingStatus: 'issued',
    payments: [
      {
        id: 'example-payment-001',
        amountMinor: '150000',
        receivedAt: '2026-10-10',
        reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
      },
    ],
    paymentReversals: [],
    projectId: exampleIdentity.project.id,
    clientId: 'example-client-001',
    expectedCollectionDate: '2026-10-30',
  },
  {
    invoiceId: 'example-invoice-expense',
    invoiceNumber: 'EXAMPLE-EXPENSE-001',
    clientNumber: 'EXAMPLE-C-001',
    clientName: exampleIdentity.client.legalName,
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    issueDate: '2026-09-30',
    dueDate: '2026-10-30',
    currency: 'USD',
    subtotalMinor: '21000',
    taxMinor: '0',
    totalMinor: '21000',
    grossPaymentsMinor: '21000',
    paymentReversalsMinor: '0',
    netCollectedMinor: '21000',
    collectedMinor: '21000',
    outstandingMinor: '0',
    directCostKnownMinor: '21000',
    directCostMinor: '21000',
    directCostComplete: true,
    directCostMissingSourceIds: [],
    contributionMinor: '0',
    contributionMarginBps: '0',
    paymentStatus: 'paid',
    billingStatus: 'issued',
    payments: [
      {
        id: 'example-payment-002',
        amountMinor: '21000',
        receivedAt: '2026-10-10',
        reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
      },
    ],
    paymentReversals: [],
    projectId: exampleIdentity.project.id,
    clientId: 'example-client-001',
    expectedCollectionDate: '2026-10-30',
  },
  {
    invoiceId: 'example-invoice-milestone',
    invoiceNumber: 'EXAMPLE-MILESTONE-001',
    clientNumber: 'EXAMPLE-C-001',
    clientName: exampleIdentity.client.legalName,
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    issueDate: '2026-09-30',
    dueDate: '2026-10-15',
    currency: 'USD',
    subtotalMinor: '500000',
    taxMinor: '0',
    totalMinor: '500000',
    grossPaymentsMinor: '250000',
    paymentReversalsMinor: '0',
    netCollectedMinor: '250000',
    collectedMinor: '250000',
    outstandingMinor: '250000',
    directCostKnownMinor: '0',
    directCostMinor: '0',
    directCostComplete: true,
    directCostMissingSourceIds: [],
    contributionMinor: '500000',
    contributionMarginBps: '10000',
    paymentStatus: 'partially_paid',
    billingStatus: 'issued',
    payments: [
      {
        id: 'example-payment-003',
        amountMinor: '250000',
        receivedAt: '2026-10-15',
        reference: 'EXAMPLE-NOT-A-BANK-REFERENCE',
      },
    ],
    paymentReversals: [],
    projectId: exampleIdentity.project.id,
    clientId: 'example-client-001',
    expectedCollectionDate: '2026-10-15',
  },
  {
    invoiceId: 'example-invoice-credit',
    invoiceNumber: 'EXAMPLE-CREDIT-001',
    clientNumber: 'EXAMPLE-C-001',
    clientName: exampleIdentity.client.legalName,
    projectNumber: exampleIdentity.project.number,
    projectName: exampleIdentity.project.name,
    issueDate: '2026-09-30',
    dueDate: '2026-09-30',
    currency: 'USD',
    subtotalMinor: '-12500',
    taxMinor: '0',
    totalMinor: '-12500',
    grossPaymentsMinor: '0',
    paymentReversalsMinor: '0',
    netCollectedMinor: '0',
    collectedMinor: '0',
    outstandingMinor: '-12500',
    directCostKnownMinor: '0',
    directCostMinor: '0',
    directCostComplete: true,
    directCostMissingSourceIds: [],
    contributionMinor: '-12500',
    contributionMarginBps: '10000',
    paymentStatus: 'credit',
    billingStatus: 'credit',
    payments: [],
    paymentReversals: [],
    projectId: exampleIdentity.project.id,
    clientId: 'example-client-001',
  },
];

export const exampleSupplierRows = [
  {
    project: exampleIdentity.project.name,
    worker: exampleIdentity.workers.alex.name,
    date: '2026-09-08',
    category: 'work',
    startTime: '08:00',
    endTime: '16:30',
    breakMinutes: 30,
    minutes: 480,
    summary: exampleActivities[0].activitySummary,
    state: 'approved',
    recordedBy: 'Example Supplier Coordinator',
  },
  {
    project: exampleIdentity.project.name,
    worker: exampleIdentity.workers.marina.name,
    date: '2026-09-09',
    category: 'travel',
    startTime: '07:30',
    endTime: '15:30',
    breakMinutes: 30,
    minutes: 450,
    summary: exampleActivities[1].activitySummary,
    state: 'submitted',
    recordedBy: 'Example Supplier Coordinator',
  },
] as const;

export const fixtureReconciliation = {
  approvedMinutes: 930,
  workerCompensationMinor: '77500',
  expenseMinor: '21000',
  invoicedMinor: '702250',
  collectedMinor: '421000',
  outstandingMinor: '281250',
  directCostMinor: '98500',
  contributionMinor: '603750',
} as const;
