import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const lifecycle = {
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
};

export const schemaMigrations = sqliteTable('schema_migration', {
  version: integer('version').primaryKey(),
  appliedAt: text('applied_at').notNull(),
});

export const users = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
  image: text('image'),
  role: text('role').notNull().default('worker'),
  status: text('status').notNull().default('invited'),
  mfaEnrolled: integer('mfa_enrolled', { mode: 'boolean' }).notNull().default(false),
  mfaRequired: integer('mfa_required', { mode: 'boolean' }).notNull().default(false),
  twoFactorEnabled: integer('two_factor_enabled', { mode: 'boolean' }).notNull().default(false),
  offboardedAt: text('offboarded_at'),
  lastStepUpAt: text('last_step_up_at'),
  ...lifecycle,
});

export const sessions = sqliteTable(
  'session',
  {
    id: text('id').primaryKey(),
    token: text('token').notNull().unique(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: text('expires_at').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    stepUpAt: text('step_up_at'),
  },
  (table) => [index('session_user_idx').on(table.userId)],
);

export const invitations = sqliteTable('invitation', {
  id: text('id').primaryKey(),
  email: text('email').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  role: text('role').notNull(),
  invitedBy: text('invited_by')
    .notNull()
    .references(() => users.id),
  expiresAt: text('expires_at').notNull(),
  usedAt: text('used_at'),
  createdAt: text('created_at').notNull(),
});

export const clients = sqliteTable('client', {
  id: text('id').primaryKey(),
  clientNumber: text('client_number').notNull().unique(),
  legalName: text('legal_name').notNull(),
  displayName: text('display_name').notNull(),
  status: text('status').notNull(),
  currency: text('currency').notNull(),
  timezone: text('timezone').notNull(),
  billingEmail: text('billing_email'),
  paymentTermsDays: integer('payment_terms_days'),
  notes: text('notes'),
  ...lifecycle,
});

export const projects = sqliteTable(
  'project',
  {
    id: text('id').primaryKey(),
    projectNumber: text('project_number').notNull().unique(),
    clientId: text('client_id')
      .notNull()
      .references(() => clients.id),
    name: text('name').notNull(),
    timezone: text('timezone').notNull(),
    currency: text('currency').notNull(),
    status: text('status').notNull(),
    billingModel: text('billing_model').notNull(),
    description: text('description'),
    siteName: text('site_name'),
    country: text('country'),
    projectManagerId: text('project_manager_id'),
    expectedMinutesPerDay: integer('expected_minutes_per_day'),
    clientDailyMinimumMinutes: integer('client_daily_minimum_minutes'),
    revenueBudgetMinor: integer('revenue_budget_minor'),
    poCapMinor: integer('po_cap_minor'),
    laborBudgetMinutes: integer('labor_budget_minutes'),
    travelBudgetMinor: integer('travel_budget_minor'),
    poNumber: text('po_number'),
    dailyReportRequired: integer('daily_report_required', { mode: 'boolean' }),
    technicalReportingRequired: integer('technical_reporting_required', { mode: 'boolean' }),
    budgetMinor: integer('budget_minor'),
    plannedMinutes: integer('planned_minutes'),
    projectAlias: text('project_alias'),
    startDate: text('start_date'),
    plannedEndDate: text('planned_end_date'),
    actualEndDate: text('actual_end_date'),
    contractNumber: text('contract_number'),
    budgetType: text('budget_type'),
    otherCostBudgetMinor: integer('other_cost_budget_minor'),
    weeklyCloseEnabled: integer('weekly_close_enabled', { mode: 'boolean' }),
    notes: text('notes'),
    expectedScheduleId: text('expected_schedule_id'),
    fixedPriceMinor: integer('fixed_price_minor'),
    ...lifecycle,
  },
  (table) => [index('project_client_idx').on(table.clientId)],
);

export const projectMembers = sqliteTable(
  'project_member',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    assignmentRole: text('assignment_role').notNull(),
    startsOn: text('starts_on').notNull(),
    endsOn: text('ends_on'),
    plannedMinutes: integer('planned_minutes'),
    canSubmitTechnicalReport: integer('can_submit_technical_report', { mode: 'boolean' }),
    canReview: integer('can_review', { mode: 'boolean' }),
    status: text('status'),
    roleOnProject: text('role_on_project'),
    expectedMinutesPerDay: integer('expected_minutes_per_day'),
    workdayMask: text('workday_mask'),
    workerCompensationRuleId: text('worker_compensation_rule_id'),
    internalCostRuleId: text('internal_cost_rule_id'),
    clientBillRuleId: text('client_bill_rule_id'),
    ...lifecycle,
  },
  (table) => [
    uniqueIndex('project_member_unique').on(table.projectId, table.userId, table.startsOn),
  ],
);

export const timeEntries = sqliteTable(
  'time_entry',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id),
    workerId: text('worker_id')
      .notNull()
      .references(() => users.id),
    workDate: text('work_date').notNull(),
    category: text('category').notNull(),
    minutes: integer('minutes').notNull(),
    approvalState: text('approval_state').notNull().default('draft'),
    billabilityState: text('billability_state').notNull().default('pending'),
    invoiceId: text('invoice_id'),
    projectTimezone: text('project_timezone'),
    activitySummary: text('activity_summary'),
    submittedAt: text('submitted_at'),
    approvedBy: text('approved_by'),
    approvedAt: text('approved_at'),
    financeApprovedBy: text('finance_approved_by'),
    financeApprovedAt: text('finance_approved_at'),
    startTime: text('start_time'),
    endTime: text('end_time'),
    activityCode: text('activity_code'),
    breakMinutes: integer('break_minutes'),
    site: text('site'),
    billableMinutes: integer('billable_minutes'),
    clientRateMinor: integer('client_rate_minor'),
    compensationAmountMinor: integer('compensation_amount_minor'),
    internalCostMinor: integer('internal_cost_minor'),
    billingStatus: text('billing_status'),
    lockedAt: text('locked_at'),
    lockedBy: text('locked_by'),
    billingLockId: text('billing_lock_id'),
    ...lifecycle,
  },
  (table) => [
    index('time_project_period_idx').on(table.projectId, table.workDate),
    index('time_worker_period_idx').on(table.workerId, table.workDate),
  ],
);

export const expenses = sqliteTable(
  'expense',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id),
    workerId: text('worker_id')
      .notNull()
      .references(() => users.id),
    spentOn: text('spent_on').notNull(),
    category: text('category').notNull(),
    currency: text('currency').notNull(),
    amountMinor: integer('amount_minor').notNull(),
    clientTreatment: text('client_treatment').notNull(),
    approvalState: text('approval_state').notNull().default('draft'),
    invoiceId: text('invoice_id'),
    vendor: text('vendor'),
    description: text('description'),
    whoPaid: text('who_paid'),
    receiptDocumentId: text('receipt_document_id'),
    receiptRequired: integer('receipt_required', { mode: 'boolean' }),
    reimbursementState: text('reimbursement_state'),
    submittedAt: text('submitted_at'),
    approvedBy: text('approved_by'),
    approvedAt: text('approved_at'),
    financeApprovedBy: text('finance_approved_by'),
    financeApprovedAt: text('finance_approved_at'),
    taxAmountMinor: integer('tax_amount_minor'),
    paymentMethod: text('payment_method'),
    markupBps: integer('markup_bps'),
    projectCurrencyAmountMinor: integer('project_currency_amount_minor'),
    billingTreatment: text('billing_treatment'),
    billingState: text('billing_state'),
    billingAmountMinor: integer('billing_amount_minor'),
    billingLockId: text('billing_lock_id'),
    reimbursementAmountMinor: integer('reimbursement_amount_minor'),
    reimbursedAt: text('reimbursed_at'),
    reimbursementReference: text('reimbursement_reference'),
    fxRateBps: integer('fx_rate_bps'),
    ...lifecycle,
  },
  (table) => [index('expense_project_period_idx').on(table.projectId, table.spentOn)],
);

export const invoices = sqliteTable(
  'invoice',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id')
      .notNull()
      .references(() => projects.id),
    invoiceNumber: text('invoice_number').unique(),
    streamType: text('stream_type').notNull(),
    state: text('state').notNull().default('draft'),
    currency: text('currency').notNull(),
    subtotalMinor: integer('subtotal_minor').notNull().default(0),
    taxMinor: integer('tax_minor').notNull().default(0),
    totalMinor: integer('total_minor').notNull().default(0),
    issuedAt: text('issued_at'),
    snapshotJson: text('snapshot_json'),
    billingRuleId: text('billing_rule_id'),
    periodStart: text('period_start'),
    periodEnd: text('period_end'),
    dueAt: text('due_at'),
    calculationHash: text('calculation_hash'),
    sentAt: text('sent_at'),
    pdfStatus: text('pdf_status'),
    pdfStorageKey: text('pdf_storage_key'),
    pdfSha256: text('pdf_sha256'),
    pdfGeneratedAt: text('pdf_generated_at'),
    sourceLockAt: text('source_lock_at'),
    voidedAt: text('voided_at'),
    pdfByteLength: integer('pdf_byte_length'),
    ...lifecycle,
  },
  (table) => [
    index('invoice_project_idx').on(table.projectId),
    uniqueIndex('invoice_number_unique').on(table.invoiceNumber),
  ],
);

export const billingRules = sqliteTable('billing_rule', {
  id: text('id').primaryKey(),
  projectId: text('project_id')
    .notNull()
    .references(() => projects.id),
  legalEntityId: text('legal_entity_id'),
  streamType: text('stream_type').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  cadenceType: text('cadence_type').notNull(),
  anchorDate: text('anchor_date'),
  taxProfileId: text('tax_profile_id'),
  currency: text('currency').notNull(),
  autoGenerateDraft: integer('auto_generate_draft', { mode: 'boolean' }).notNull().default(false),
  autoIssue: integer('auto_issue', { mode: 'boolean' }).notNull().default(false),
  autoSend: integer('auto_send', { mode: 'boolean' }).notNull().default(false),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  groupingMode: text('grouping_mode'),
  templateId: text('template_id'),
  recipientEmail: text('recipient_email'),
  billingContactId: text('billing_contact_id'),
  paymentTermsDays: integer('payment_terms_days'),
  poNumberOverride: text('po_number_override'),
  semiMonthlyRule: text('semi_monthly_rule'),
  policyVersion: integer('policy_version'),
  fixedAmountMinor: integer('fixed_amount_minor'),
  includedMinutes: integer('included_minutes'),
  monthlyCutoffDay: integer('monthly_cutoff_day'),
  ...lifecycle,
});

export const documents = sqliteTable(
  'document',
  {
    id: text('id').primaryKey(),
    projectId: text('project_id').references(() => projects.id),
    ownerId: text('owner_id')
      .notNull()
      .references(() => users.id),
    sha256: text('sha256').notNull(),
    mediaType: text('media_type').notNull(),
    byteLength: integer('byte_length').notNull(),
    state: text('state').notNull(),
    storageKey: text('storage_key').notNull(),
    originalFilename: text('original_filename'),
    description: text('description'),
    sensitive: integer('sensitive', { mode: 'boolean' }),
    artifactType: text('artifact_type'),
    softwareVersion: text('software_version'),
    supersedesId: text('supersedes_id'),
    approvedAt: text('approved_at'),
    approvedBy: text('approved_by'),
    sensitivity: text('sensitivity'),
    safeFilename: text('safe_filename'),
    scanStatus: text('scan_status'),
    scannedAt: text('scanned_at'),
    scanProvider: text('scan_provider'),
    artifactMetadataJson: text('artifact_metadata_json'),
    ...lifecycle,
  },
  (table) => [
    index('document_project_idx').on(table.projectId),
    uniqueIndex('document_content_idx').on(table.sha256, table.byteLength),
  ],
);

export const auditEvents = sqliteTable('audit_event', {
  id: text('id').primaryKey(),
  actorId: text('actor_id'),
  action: text('action').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  occurredAt: text('occurred_at').notNull(),
  detailsJson: text('details_json').notNull(),
  projectId: text('project_id').references(() => projects.id),
  beforeJson: text('before_json'),
  afterJson: text('after_json'),
  reason: text('reason'),
  correlationId: text('correlation_id'),
  metadataJson: text('metadata_json'),
});

export const jobs = sqliteTable('job', {
  id: text('id').primaryKey(),
  kind: text('kind').notNull(),
  idempotencyKey: text('idempotency_key').notNull().unique(),
  state: text('state').notNull(),
  runAfter: text('run_after').notNull(),
  leaseUntil: text('lease_until'),
  attempts: integer('attempts').notNull().default(0),
  payloadJson: text('payload_json').notNull(),
  ...lifecycle,
});

export const publicInquiries = sqliteTable('public_inquiry', {
  id: text('id').primaryKey(),
  kind: text('kind').notNull(),
  payloadJson: text('payload_json').notNull(),
  sourceHash: text('source_hash').notNull(),
  createdAt: text('created_at').notNull(),
  deliveredAt: text('delivered_at'),
});

export const outboxEvents = sqliteTable('outbox_event', {
  id: text('id').primaryKey(),
  topic: text('topic').notNull(),
  aggregateId: text('aggregate_id').notNull(),
  idempotencyKey: text('idempotency_key').notNull().unique(),
  payloadJson: text('payload_json').notNull(),
  availableAt: text('available_at').notNull(),
  attempts: integer('attempts').notNull().default(0),
  deliveredAt: text('delivered_at'),
  leaseUntil: text('lease_until'),
  lastError: text('last_error'),
  failedAt: text('failed_at'),
  createdAt: text('created_at').notNull(),
});

// The tables below are intentionally declared alongside the operational
// tables rather than hidden in generated output. This keeps Drizzle's model
// aligned with reviewed migrations 0001–0017 and makes schema review useful.
export const accounts = sqliteTable('account', {
  id: text('id').primaryKey(),
  issuer: text('issuer').notNull().default('local:credential'),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: text('access_token_expires_at'),
  refreshTokenExpiresAt: text('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const verifications = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: text('expires_at').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const passkeys = sqliteTable('passkey', {
  id: text('id').primaryKey(),
  name: text('name'),
  publicKey: text('public_key').notNull(),
  userId: text('user_id').notNull(),
  credentialId: text('credential_id').notNull().unique(),
  counter: integer('counter').notNull(),
  deviceType: text('device_type').notNull(),
  backedUp: integer('backed_up', { mode: 'boolean' }).notNull(),
  transports: text('transports'),
  createdAt: text('created_at').notNull(),
});
export const twoFactors = sqliteTable('two_factor', {
  id: text('id').primaryKey(),
  secret: text('secret').notNull(),
  backupCodes: text('backup_codes').notNull(),
  userId: text('user_id').notNull().unique(),
  verified: integer('verified', { mode: 'boolean' }).notNull().default(false),
  failedVerificationCount: integer('failed_verification_count').notNull().default(0),
  lockedUntil: text('locked_until'),
});
export const numberSequences = sqliteTable('number_sequence', {
  scope: text('scope').notNull(),
  scopeId: text('scope_id').notNull(),
  nextValue: integer('next_value').notNull(),
  version: integer('version').notNull().default(1),
});
export const skills = sqliteTable('skill', {
  id: text('id').primaryKey(),
  code: text('code').notNull().unique(),
  name: text('name').notNull(),
  createdAt: text('created_at').notNull(),
});
export const workerSkills = sqliteTable('worker_skill', {
  workerId: text('worker_id').notNull(),
  skillId: text('skill_id').notNull(),
  proficiency: integer('proficiency').notNull(),
  verifiedAt: text('verified_at'),
});
export const schedules = sqliteTable('schedule', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  timezone: text('timezone').notNull(),
  mondayMinutes: integer('monday_minutes').notNull(),
  tuesdayMinutes: integer('tuesday_minutes').notNull(),
  wednesdayMinutes: integer('wednesday_minutes').notNull(),
  thursdayMinutes: integer('thursday_minutes').notNull(),
  fridayMinutes: integer('friday_minutes').notNull(),
  saturdayMinutes: integer('saturday_minutes').notNull(),
  sundayMinutes: integer('sunday_minutes').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  version: integer('version').notNull().default(1),
});
export const planningAssignments = sqliteTable('planning_assignment', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  workerId: text('worker_id').notNull(),
  startsAt: text('starts_at').notNull(),
  endsAt: text('ends_at').notNull(),
  plannedMinutes: integer('planned_minutes').notNull(),
  status: text('status'),
  site: text('site'),
  requiredSkill: text('required_skill'),
  plannedCostMinor: integer('planned_cost_minor'),
  createdBy: text('created_by'),
  ...lifecycle,
});
export const dailyReports = sqliteTable('daily_report', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  workerId: text('worker_id').notNull(),
  workDate: text('work_date').notNull(),
  summary: text('summary').notNull(),
  safetyNotes: text('safety_notes'),
  approvalState: text('approval_state').notNull(),
  ...lifecycle,
  siteShift: text('site_shift'),
  tasksCompleted: text('tasks_completed'),
  problemsFound: text('problems_found'),
  correctiveActions: text('corrective_actions'),
  clientDecisions: text('client_decisions'),
  downtimeMinutes: integer('downtime_minutes'),
  standbyReason: text('standby_reason'),
  blockers: text('blockers'),
  openItems: text('open_items'),
  nextDayPlan: text('next_day_plan'),
  safetyRelated: integer('safety_related', { mode: 'boolean' }),
  customerContact: text('customer_contact'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: text('reviewed_at'),
});
export const technicalReports = sqliteTable('technical_report', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  authorId: text('author_id').notNull(),
  systemName: text('system_name').notNull(),
  controller: text('controller'),
  changeSummary: text('change_summary').notNull(),
  safetyRelated: integer('safety_related', { mode: 'boolean' }).notNull(),
  validation: text('validation'),
  rollbackPlan: text('rollback_plan'),
  approvalState: text('approval_state').notNull(),
  ...lifecycle,
  plantSite: text('plant_site'),
  areaLine: text('area_line'),
  stationMachine: text('station_machine'),
  systemType: text('system_type'),
  plcPlatform: text('plc_platform'),
  hmiScada: text('hmi_scada'),
  robotPlatform: text('robot_platform'),
  driveMotion: text('drive_motion'),
  networkProtocol: text('network_protocol'),
  softwareVersion: text('software_version'),
  programReference: text('program_reference'),
  productionImpact: text('production_impact'),
  validationResult: text('validation_result'),
  openRisk: text('open_risk'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: text('reviewed_at'),
});
export const technicalChanges = sqliteTable('technical_change', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  technicalReportId: text('technical_report_id'),
  authorId: text('author_id').notNull(),
  component: text('component').notNull(),
  originalBehavior: text('original_behavior'),
  rootCause: text('root_cause'),
  changeMade: text('change_made').notNull(),
  reason: text('reason'),
  safetyImpact: integer('safety_impact', { mode: 'boolean' }).notNull(),
  productionImpact: text('production_impact'),
  validation: text('validation'),
  validationResult: text('validation_result'),
  openRisk: text('open_risk'),
  rollbackInformation: text('rollback_information'),
  approvalState: text('approval_state').notNull(),
  ...lifecycle,
});
export const clientContacts = sqliteTable('client_contact', {
  id: text('id').primaryKey(),
  clientId: text('client_id').notNull(),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  role: text('role'),
  isBillingContact: integer('is_billing_contact', { mode: 'boolean' }),
  isPrimary: integer('is_primary', { mode: 'boolean' }),
  ...lifecycle,
});
export const clientLaborRates = sqliteTable('client_labor_rate', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  workerId: text('worker_id'),
  category: text('category'),
  currency: text('currency').notNull(),
  hourlyRateMinor: integer('hourly_rate_minor').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  ...lifecycle,
  rateBasis: text('rate_basis'),
  overtimeMethod: text('overtime_method'),
  overtimeMultiplierBps: integer('overtime_multiplier_bps'),
  overtimeRateMinor: integer('overtime_rate_minor'),
  eligibleForPercentage: integer('eligible_for_percentage', { mode: 'boolean' }),
  notes: text('notes'),
});
export const internalCostRules = sqliteTable('internal_cost_rule', {
  id: text('id').primaryKey(),
  workerId: text('worker_id').notNull(),
  projectId: text('project_id'),
  currency: text('currency').notNull(),
  hourlyRateMinor: integer('hourly_rate_minor').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  ...lifecycle,
  overtimeMethod: text('overtime_method'),
  overtimeMultiplierBps: integer('overtime_multiplier_bps'),
  overtimeRateMinor: integer('overtime_rate_minor'),
  costMethod: text('cost_method'),
  notes: text('notes'),
});
export const compensationRules = sqliteTable('compensation_rule', {
  id: text('id').primaryKey(),
  workerId: text('worker_id').notNull(),
  projectId: text('project_id'),
  currency: text('currency').notNull(),
  rateMinor: integer('rate_minor').notNull(),
  rateBasis: text('rate_basis').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  ...lifecycle,
  dailyGuaranteeMinutes: integer('daily_guarantee_minutes'),
  workerVisible: integer('worker_visible', { mode: 'boolean' }),
  ruleType: text('rule_type'),
  percentageBps: integer('percentage_bps'),
  percentageBasis: text('percentage_basis'),
  settlementTrigger: text('settlement_trigger'),
  overtimeMethod: text('overtime_method'),
  overtimeMultiplierBps: integer('overtime_multiplier_bps'),
  overtimeRateMinor: integer('overtime_rate_minor'),
  weekendMethod: text('weekend_method'),
  travelMethod: text('travel_method'),
  standbyMethod: text('standby_method'),
  fixedPeriodMinor: integer('fixed_period_minor'),
  fixedProjectMinor: integer('fixed_project_minor'),
  notes: text('notes'),
});
export const compensationSettlements = sqliteTable('compensation_settlement', {
  id: text('id').primaryKey(),
  workerId: text('worker_id').notNull(),
  projectId: text('project_id').notNull(),
  compensationRuleId: text('compensation_rule_id').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  sourceBasis: text('source_basis').notNull(),
  sourceAmountMinor: integer('source_amount_minor').notNull(),
  percentageBps: integer('percentage_bps'),
  amountMinor: integer('amount_minor').notNull(),
  currency: text('currency').notNull(),
  state: text('state').notNull(),
  settledAt: text('settled_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const assignmentRateOverrides = sqliteTable('assignment_rate_override', {
  id: text('id').primaryKey(),
  projectMemberId: text('project_member_id').notNull(),
  timeCategory: text('time_category'),
  activityCode: text('activity_code'),
  compensationRuleId: text('compensation_rule_id'),
  internalCostRuleId: text('internal_cost_rule_id'),
  clientLaborRateId: text('client_labor_rate_id'),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  priority: integer('priority').notNull(),
  ...lifecycle,
});
export const legalEntities = sqliteTable('legal_entity', {
  id: text('id').primaryKey(),
  code: text('code').notNull().unique(),
  legalName: text('legal_name').notNull(),
  currency: text('currency').notNull(),
  billingAddress: text('billing_address').notNull(),
  companyIdentifiers: text('company_identifiers').notNull(),
  ...lifecycle,
});
export const invoiceNumberPolicies = sqliteTable('invoice_number_policy', {
  id: text('id').primaryKey(),
  legalEntityId: text('legal_entity_id').notNull(),
  prefix: text('prefix').notNull(),
  digits: integer('digits').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  accountantApprovedAt: text('accountant_approved_at'),
  ...lifecycle,
});
export const taxProfiles = sqliteTable('tax_profile', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  currency: text('currency').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  version: integer('version').notNull().default(1),
  legalEntityId: text('legal_entity_id'),
  jurisdictionLabel: text('jurisdiction_label'),
  description: text('description'),
  status: text('status'),
});
export const taxComponents = sqliteTable('tax_component', {
  id: text('id').primaryKey(),
  taxProfileId: text('tax_profile_id').notNull(),
  name: text('name').notNull(),
  basisPoints: integer('basis_points').notNull(),
  calculationOrder: integer('calculation_order').notNull(),
  compound: integer('compound', { mode: 'boolean' }).notNull(),
  calculationType: text('calculation_type'),
  displayMode: text('display_mode'),
  basis: text('basis'),
});
export const billingPeriods = sqliteTable('billing_period', {
  id: text('id').primaryKey(),
  billingRuleId: text('billing_rule_id').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  state: text('state').notNull(),
  reasonsJson: text('reasons_json').notNull(),
  closedAt: text('closed_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull().default(1),
});
export const billingLocks = sqliteTable('billing_lock', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  streamType: text('stream_type').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  acquiredAt: text('acquired_at').notNull(),
});
export const invoiceLines = sqliteTable('invoice_line', {
  id: text('id').primaryKey(),
  invoiceId: text('invoice_id').notNull(),
  description: text('description').notNull(),
  quantityNumerator: integer('quantity_numerator').notNull(),
  quantityDenominator: integer('quantity_denominator').notNull(),
  unitPriceMinor: integer('unit_price_minor').notNull(),
  subtotalMinor: integer('subtotal_minor').notNull(),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  snapshotJson: text('snapshot_json').notNull(),
  taxMinor: integer('tax_minor'),
  groupingKey: text('grouping_key'),
});
export const invoiceSources = sqliteTable('invoice_source', {
  invoiceId: text('invoice_id').notNull(),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  sourceVersion: integer('source_version').notNull(),
  lockedAt: text('locked_at'),
});
export const payments = sqliteTable('payment', {
  id: text('id').primaryKey(),
  invoiceId: text('invoice_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  currency: text('currency').notNull(),
  receivedAt: text('received_at').notNull(),
  reference: text('reference'),
  createdAt: text('created_at').notNull(),
  idempotencyKey: text('idempotency_key'),
});
export const invoiceEvents = sqliteTable('invoice_event', {
  id: text('id').primaryKey(),
  invoiceId: text('invoice_id').notNull(),
  eventType: text('event_type').notNull(),
  amountMinor: integer('amount_minor'),
  reason: text('reason').notNull(),
  actorId: text('actor_id').notNull(),
  occurredAt: text('occurred_at').notNull(),
  idempotencyKey: text('idempotency_key').notNull().unique(),
});
export const invoiceAdjustments = sqliteTable('invoice_adjustment', {
  id: text('id').primaryKey(),
  originalInvoiceId: text('original_invoice_id').notNull(),
  adjustmentInvoiceId: text('adjustment_invoice_id').notNull().unique(),
  adjustmentType: text('adjustment_type').notNull(),
  reason: text('reason').notNull(),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull(),
});
export const projectMilestones = sqliteTable('project_milestone', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  amountMinor: integer('amount_minor').notNull(),
  currency: text('currency').notNull(),
  dueOn: text('due_on'),
  approvalState: text('approval_state').notNull(),
  approvedBy: text('approved_by'),
  approvedAt: text('approved_at'),
  invoiceId: text('invoice_id'),
  ...lifecycle,
});
export const financeSnapshots = sqliteTable('finance_snapshot', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  asOf: text('as_of').notNull(),
  costMinor: integer('cost_minor').notNull(),
  revenueMinor: integer('revenue_minor').notNull(),
  contributionMarginMinor: integer('contribution_margin_minor').notNull(),
  etcMinor: integer('etc_minor').notNull(),
  eacMinor: integer('eac_minor').notNull(),
  inputHash: text('input_hash').notNull(),
  createdAt: text('created_at').notNull(),
});
export const jobRuns = sqliteTable('job_run', {
  id: text('id').primaryKey(),
  jobId: text('job_id').notNull(),
  startedAt: text('started_at').notNull(),
  finishedAt: text('finished_at'),
  outcome: text('outcome'),
  errorCode: text('error_code'),
});
export const approvalEvents = sqliteTable('approval_event', {
  id: text('id').primaryKey(),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  fromState: text('from_state').notNull(),
  toState: text('to_state').notNull(),
  actorId: text('actor_id').notNull(),
  reason: text('reason'),
  occurredAt: text('occurred_at').notNull(),
});
export const notifications = sqliteTable('notification', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull(),
  kind: text('kind').notNull(),
  subjectId: text('subject_id').notNull(),
  readAt: text('read_at'),
  createdAt: text('created_at').notNull(),
});
export const documentAccessEvents = sqliteTable('document_access_event', {
  id: text('id').primaryKey(),
  documentId: text('document_id').notNull(),
  userId: text('user_id').notNull(),
  action: text('action').notNull(),
  occurredAt: text('occurred_at').notNull(),
});
export const periodReports = sqliteTable('period_report', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  audience: text('audience').notNull(),
  reportType: text('report_type').notNull(),
  state: text('state').notNull(),
  snapshotJson: text('snapshot_json').notNull(),
  pdfStorageKey: text('pdf_storage_key'),
  pdfSha256: text('pdf_sha256'),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  pdfByteLength: integer('pdf_byte_length'),
});
export const reportSources = sqliteTable('report_source', {
  reportId: text('report_id').notNull(),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
});
export const reportTimeLinks = sqliteTable('report_time_link', {
  reportType: text('report_type').notNull(),
  reportId: text('report_id').notNull(),
  timeEntryId: text('time_entry_id').notNull(),
});
export const projectCloseouts = sqliteTable('project_closeout', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull().unique(),
  state: text('state').notNull(),
  snapshotJson: text('snapshot_json').notNull(),
  documentManifestJson: text('document_manifest_json').notNull(),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  reopenedBy: text('reopened_by'),
  reopenedAt: text('reopened_at'),
  reopenReason: text('reopen_reason'),
});
export const accountingPeriods = sqliteTable('accounting_period', {
  id: text('id').primaryKey(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  legalEntityId: text('legal_entity_id'),
  state: text('state').notNull(),
  closedAt: text('closed_at'),
  closedBy: text('closed_by'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const accountingPackRuns = sqliteTable('accounting_pack_run', {
  id: text('id').primaryKey(),
  periodStart: text('period_start').notNull(),
  periodEnd: text('period_end').notNull(),
  legalEntityId: text('legal_entity_id'),
  state: text('state').notNull(),
  snapshotJson: text('snapshot_json').notNull(),
  reconciliationJson: text('reconciliation_json').notNull(),
  generatedBy: text('generated_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const accountingPackExports = sqliteTable('accounting_pack_export', {
  id: text('id').primaryKey(),
  packRunId: text('pack_run_id').notNull(),
  exportType: text('export_type').notNull(),
  storageKey: text('storage_key').notNull(),
  sha256: text('sha256').notNull(),
  byteLength: integer('byte_length').notNull(),
  createdAt: text('created_at').notNull(),
});
export const offlineMutations = sqliteTable('offline_mutation', {
  mutationId: text('mutation_id').primaryKey(),
  userId: text('user_id').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  baseVersion: integer('base_version').notNull(),
  payloadJson: text('payload_json').notNull(),
  attachmentIdsJson: text('attachment_ids_json').notNull(),
  state: text('state').notNull(),
  resultJson: text('result_json').notNull(),
  createdAt: text('created_at').notNull(),
  processedAt: text('processed_at').notNull(),
});
export const scheduledJobs = sqliteTable('scheduled_job', {
  id: text('id').primaryKey(),
  kind: text('kind').notNull().unique(),
  cronExpression: text('cron_expression').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull(),
  payloadJson: text('payload_json').notNull(),
  updatedAt: text('updated_at').notNull(),
});
export const rateLimitBuckets = sqliteTable('rate_limit_bucket', {
  bucketKey: text('bucket_key').primaryKey(),
  windowStartedAt: text('window_started_at').notNull(),
  requestCount: integer('request_count').notNull(),
});
export const mutationReceipts = sqliteTable('mutation_receipt', {
  mutationId: text('mutation_id').primaryKey(),
  userId: text('user_id').notNull(),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  resultJson: text('result_json').notNull(),
  createdAt: text('created_at').notNull(),
});
export const workerAvailability = sqliteTable('worker_availability', {
  id: text('id').primaryKey(),
  workerId: text('worker_id').notNull(),
  startsAt: text('starts_at').notNull(),
  endsAt: text('ends_at').notNull(),
  availability: text('availability').notNull(),
  note: text('note'),
  ...lifecycle,
});
