import {
  accountingPackPeriodSchema,
  billingCloseSchema,
  billingRuleInputSchema,
  invoiceAdjustmentSchema,
  invoiceIdSchema,
  invoiceNumberPolicyInputSchema,
  invoicePeriodSchema,
  legalEntityInputSchema,
  paymentInputSchema,
  sendInvoiceSchema,
  taxProfileInputSchema,
  voidInvoiceSchema,
} from '@ja/schemas';
import { fail } from '@sveltejs/kit';
import { actionFailure, openPortalRepository } from '$lib/server/portal-repository';
import { runArtifactJobs } from '$lib/server/artifact-jobs';
import {
  decimalToMinor,
  formObject,
  normalizeLocalDateTime,
  type PortalActionEvent,
} from '$lib/server/action-utils';

export const billingActions = {
  createBillingRule: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const object = await formObject(request);
    object.autoGenerateDraft = object.autoGenerateDraft === 'on';
    const parsed = billingRuleInputSchema.safeParse(object);
    if (!parsed.success)
      return fail(400, {
        success: false,
        message: 'Invalid billing stream',
        fields: parsed.error.flatten().fieldErrors,
      });
    const context = openPortalRepository(locals);
    try {
      context.repository.createBillingRule(context.principal, parsed.data);
      return { success: true, message: 'Billing stream saved' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createLegalEntity: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = legalEntityInputSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return fail(400, {
        success: false,
        message: 'Check legal entity fields',
        fields: parsed.error.flatten().fieldErrors,
      });
    const context = openPortalRepository(locals);
    try {
      context.repository.createLegalEntity(context.principal, parsed.data);
      return { success: true, message: 'Legal entity saved' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createInvoiceNumberPolicy: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const object = await formObject(request);
    object.accountantApprovedAt = normalizeLocalDateTime(object.accountantApprovedAt);
    const parsed = invoiceNumberPolicyInputSchema.safeParse(object);
    if (!parsed.success)
      return fail(400, {
        success: false,
        message: 'Check invoice-number policy fields',
        fields: parsed.error.flatten().fieldErrors,
      });
    const context = openPortalRepository(locals);
    try {
      context.repository.createInvoiceNumberPolicy(context.principal, parsed.data);
      return { success: true, message: 'Invoice-number policy saved' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createTaxProfile: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const object = await formObject(request);
    object.componentCompound = object.componentCompound === 'on';
    const parsed = taxProfileInputSchema.safeParse(object);
    if (!parsed.success)
      return fail(400, {
        success: false,
        message: 'Check tax profile fields',
        fields: parsed.error.flatten().fieldErrors,
      });
    const context = openPortalRepository(locals);
    try {
      context.repository.createTaxProfile(context.principal, {
        legalEntityId: parsed.data.legalEntityId || undefined,
        name: parsed.data.name,
        currency: parsed.data.currency,
        effectiveFrom: parsed.data.effectiveFrom,
        components: [
          {
            name: parsed.data.componentName,
            basisPoints: parsed.data.componentBasisPoints,
            compound: parsed.data.componentCompound,
          },
        ],
      });
      return { success: true, message: 'Tax profile saved' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createDraft: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = invoicePeriodSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid billing period' });
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.createInvoiceDraft(
        context.principal,
        parsed.data.billingRuleId,
        parsed.data.periodStart,
        parsed.data.periodEnd,
      );
      return {
        success: true,
        message: result.created ? 'Invoice draft created' : 'Existing draft returned',
      };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createInvoiceAdjustment: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = invoiceAdjustmentSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return fail(400, { success: false, message: 'Invalid invoice adjustment' });
    const context = openPortalRepository(locals);
    try {
      context.repository.createInvoiceAdjustment(context.principal, parsed.data);
      return { success: true, message: 'Adjustment draft created' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  approveInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = invoiceIdSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid invoice' });
    const context = openPortalRepository(locals);
    try {
      context.repository.approveInvoiceDraft(context.principal, parsed.data.invoiceId);
      return { success: true, message: 'Invoice approved' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  issueInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = invoiceIdSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid invoice' });
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.issueInvoice(context.principal, parsed.data.invoiceId);
      return { success: true, message: `Issued ${result.invoiceNumber}` };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  recordPayment: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const object = await formObject(request);
    object.amountMinor = decimalToMinor(object.amount);
    if (typeof object.receivedOn === 'string')
      object.receivedAt = `${object.receivedOn}T12:00:00.000Z`;
    const parsed = paymentInputSchema.safeParse(object);
    if (!parsed.success)
      return fail(400, {
        success: false,
        message: 'Invalid payment',
        fields: parsed.error.flatten().fieldErrors,
      });
    const context = openPortalRepository(locals);
    try {
      context.v3.recordPayment(context.principal, parsed.data);
      return { success: true, message: 'Payment recorded' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  closePeriod: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = billingCloseSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid billing period' });
    const context = openPortalRepository(locals);
    try {
      const result = context.v3.closeBillingPeriod(
        context.principal,
        parsed.data.billingRuleId,
        parsed.data.periodStart,
        parsed.data.periodEnd,
      );
      if (!result.closed)
        return fail(409, {
          success: false,
          message: 'Period is incomplete',
          reasons: result.reasons,
        });
      return { success: true, message: 'Billing period closed and sources locked' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  voidInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = voidInvoiceSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid void request' });
    const context = openPortalRepository(locals);
    try {
      context.v3.voidInvoice(
        context.principal,
        parsed.data.invoiceId,
        parsed.data.reason,
        parsed.data.idempotencyKey,
      );
      return { success: true, message: 'Invoice voided with audit trail' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  sendInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = sendInvoiceSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid send request' });
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.sendInvoice(
        context.principal,
        parsed.data.invoiceId,
        parsed.data.idempotencyKey,
      );
      return {
        success: true,
        message: result.sent ? 'Invoice marked sent' : 'Invoice was already sent',
      };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createAccountingPack: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'accounting')
      return fail(404, { success: false, message: 'Wrong section' });
    const parsed = accountingPackPeriodSchema.safeParse(await formObject(request));
    if (!parsed.success) return fail(400, { success: false, message: 'Invalid accounting period' });
    const context = openPortalRepository(locals);
    try {
      const pack = context.v3.createAccountingPack(
        context.principal,
        parsed.data.periodStart,
        parsed.data.periodEnd,
      );
      return { success: true, message: `Accounting Pack ${pack.id.slice(0, 8)} is ready` };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  finalizeAccountingPack: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'accounting')
      return fail(404, { success: false, message: 'Wrong section' });
    const object = await formObject(request);
    const packId = typeof object.packId === 'string' ? object.packId : '';
    const context = openPortalRepository(locals);
    try {
      context.v3.markAccountingPackFinal(context.principal, packId);
      return { success: true, message: 'Accounting Pack marked final' };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  runJobs: async ({ locals, params }: PortalActionEvent) => {
    if (params.section !== 'accounting' && params.section !== 'billing')
      return fail(404, { success: false, message: 'Wrong section' });
    const context = openPortalRepository(locals);
    try {
      if (context.principal.role !== 'owner_admin' && context.principal.role !== 'finance_admin')
        return fail(403, { success: false, message: 'Finance role required' });
      context.v3.scheduleCoreJobs();
      const result = runArtifactJobs(context);
      return { success: true, message: `Jobs processed: ${result.processed}` };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
};
