import {
  accountingPackPeriodSchema,
  billingCloseSchema,
  billingRuleInputSchema,
  invoiceAdjustmentSchema,
  invoiceIdSchema,
  invoiceNumberPolicyInputSchema,
  invoicePeriodSchema,
  legalEntityInputSchema,
  paymentInputSchema,
  paymentReversalInputSchema,
  sendInvoiceSchema,
  taxProfileInputSchema,
  voidInvoiceSchema,
} from '@ja/schemas';
import { openPortalRepository } from '$lib/server/portal-repository';
import {
  actionFail,
  actionFailure,
  actionSuccess,
  type ActionMessageKey,
} from './action-message';
import {
  decimalToMinor,
  formObject,
  normalizeLocalDateTime,
  type PortalActionEvent,
} from '$lib/server/action-utils';

type AccountingPackStatusRecord = Readonly<{
  id?: unknown;
  state?: unknown;
  exportStatuses?: unknown;
}>;

const accountingPackStatusRank: Record<string, number> = {
  failed: 4,
  running: 3,
  processing: 3,
  queued: 2,
  pending: 2,
  ready: 1,
  final: 1,
};

/**
 * Build the user-facing result from the target pack, not from global durable-job counters.
 * A finance page can have unrelated jobs in flight, so scheduler counters are not evidence
 * about this specific Accounting Pack.
 */
export function accountingPackActionMessage(
  pack: AccountingPackStatusRecord | undefined,
  fallbackId: string,
): string {
  const shortId = (String(pack?.id ?? fallbackId).slice(0, 8) || 'unknown').trim();
  const statuses =
    pack?.exportStatuses && typeof pack.exportStatuses === 'object'
      ? Object.values(pack.exportStatuses as Record<string, unknown>).map((value) =>
          String(value).toLowerCase(),
        )
      : [];
  const state = String(pack?.state ?? '').toLowerCase();
  const targetStatus =
    statuses.length > 0
      ? statuses.reduce(
          (current, candidate) =>
            !current ||
            (accountingPackStatusRank[candidate] ?? 2) > (accountingPackStatusRank[current] ?? 2)
              ? candidate
              : current,
          '',
        )
      : state;

  if (targetStatus === 'failed')
    return `Accounting Pack ${shortId} failed; one or more artifacts need retry`;
  if (targetStatus === 'running' || targetStatus === 'processing')
    return `Accounting Pack ${shortId} processing`;
  if (targetStatus === 'queued' || targetStatus === 'pending')
    return `Accounting Pack ${shortId} queued`;
  if (targetStatus === 'ready' || targetStatus === 'final')
    return `Accounting Pack ${shortId} ready`;

  // A newly-created pack should never be described as generated when its job status is not
  // observable yet. Queueing is the safest truthful state until the target can be refreshed.
  return `Accounting Pack ${shortId} queued`;
}

export function accountingPackActionFeedback(
  pack: AccountingPackStatusRecord | undefined,
  fallbackId: string,
): Readonly<{
  messageKey: ActionMessageKey;
  messageParams: Readonly<{ packId: string }>;
  legacyMessage: string;
}> {
  const legacyMessage = accountingPackActionMessage(pack, fallbackId);
  const shortId = (String(pack?.id ?? fallbackId).slice(0, 8) || 'unknown').trim();
  const status = legacyMessage.match(/\b(failed|processing|queued|ready)\b/i)?.[1]?.toLowerCase() ?? 'queued';
  return {
    messageKey: `action.billing.accountingPack.${status}`,
    messageParams: { packId: shortId },
    legacyMessage,
  };
}

export const billingActions = {
  createBillingRule: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    object.autoGenerateDraft = object.autoGenerateDraft === 'on';
    const parsed = billingRuleInputSchema.safeParse(object);
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.billingStream',
        {},
        'Invalid billing stream',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      context.repository.createBillingRule(context.principal, parsed.data);
      return actionSuccess('action.billing.streamSaved', {}, 'Billing stream saved');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createLegalEntity: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = legalEntityInputSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.legalEntityFields',
        {},
        'Check legal entity fields',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      context.repository.createLegalEntity(context.principal, parsed.data);
      return actionSuccess('action.billing.legalEntitySaved', {}, 'Legal entity saved');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createInvoiceNumberPolicy: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    object.accountantApprovedAt = normalizeLocalDateTime(object.accountantApprovedAt);
    const parsed = invoiceNumberPolicyInputSchema.safeParse(object);
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.invoiceNumberPolicyFields',
        {},
        'Check invoice-number policy fields',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      context.repository.createInvoiceNumberPolicy(context.principal, parsed.data);
      return actionSuccess(
        'action.billing.invoiceNumberPolicySaved',
        {},
        'Invoice-number policy saved',
      );
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createTaxProfile: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    object.componentCompound = object.componentCompound === 'on';
    const parsed = taxProfileInputSchema.safeParse(object);
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.taxProfileFields',
        {},
        'Check tax profile fields',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      context.repository.createTaxProfile(context.principal, {
        name: parsed.data.name,
        legalEntityId: parsed.data.legalEntityId || undefined,
        effectiveFrom: parsed.data.effectiveFrom,
        currency: parsed.data.currency,
        components: [
          {
            name: parsed.data.componentName,
            basisPoints: parsed.data.componentBasisPoints,
            compound: parsed.data.componentCompound,
          },
        ],
      });
      return actionSuccess('action.billing.taxProfileSaved', {}, 'Tax profile saved');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  updateBillingRule: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('billingRuleId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.billingRuleIdRequired', {}, 'Billing Rule ID required');

    const input: Record<string, unknown> = {};
    if (formData.has('templateId')) input.templateId = formData.get('templateId')?.toString();
    if (formData.has('recipientEmail'))
      input.recipientEmail = formData.get('recipientEmail')?.toString();
    if (formData.has('paymentTermsDays'))
      input.paymentTermsDays = Number(formData.get('paymentTermsDays'));
    if (formData.has('poNumberOverride'))
      input.poNumberOverride = formData.get('poNumberOverride')?.toString();
    if (formData.has('groupingMode')) input.groupingMode = formData.get('groupingMode')?.toString();
    if (formData.has('includedMinutes'))
      input.includedMinutes = Number(formData.get('includedMinutes'));
    if (formData.has('autoGenerateDraft'))
      input.autoGenerateDraft = formData.get('autoGenerateDraft')?.toString() === 'on';
    if (formData.has('autoIssue')) input.autoIssue = formData.get('autoIssue')?.toString() === 'on';
    if (formData.has('autoSend')) input.autoSend = formData.get('autoSend')?.toString() === 'on';

    const fixedAmountMinorRaw = formData.get('fixedAmountMinor')?.toString();
    if (fixedAmountMinorRaw) {
      const value = fixedAmountMinorRaw.trim();
      try {
        // The field is named in minor units, but accepting an explicitly
        // decimal value keeps the form ergonomic. Both branches are exact;
        // no binary floating-point conversion is involved.
        input.fixedAmountMinor = /^\d+$/.test(value)
          ? BigInt(value)
          : (() => {
              const minor = decimalToMinor(value);
              if (!minor) throw new Error('Invalid fixed amount');
              return BigInt(minor);
            })();
      } catch {
        return actionFail(
          400,
          'action.validation.fixedAmount',
          {},
          'Fixed amount must be a non-negative exact amount',
        );
      }
    }

    const context = openPortalRepository(locals);
    try {
      context.repository.updateBillingRule(context.principal, id, input);
      return actionSuccess('action.billing.ruleUpdated', {}, 'Billing rule updated');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  archiveBillingRule: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('billingRuleId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.billingRuleIdRequired', {}, 'Billing Rule ID required');
    const context = openPortalRepository(locals);
    try {
      context.repository.archiveBillingRule(context.principal, id);
      return actionSuccess('action.billing.ruleArchived', {}, 'Billing rule archived');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  updateLegalEntity: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('legalEntityId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.legalEntityIdRequired', {}, 'Legal Entity ID required');

    const input: Record<string, unknown> = {};
    if (formData.has('legalName')) input.legalName = formData.get('legalName')?.toString();
    if (formData.has('currency')) input.currency = formData.get('currency')?.toString();
    if (formData.has('billingAddress'))
      input.billingAddress = formData.get('billingAddress')?.toString();
    if (formData.has('companyIdentifiers'))
      input.companyIdentifiers = formData.get('companyIdentifiers')?.toString();

    const context = openPortalRepository(locals);
    try {
      context.repository.updateLegalEntity(context.principal, id, input);
      return actionSuccess('action.billing.legalEntityUpdated', {}, 'Legal entity updated');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  archiveLegalEntity: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('legalEntityId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.legalEntityIdRequired', {}, 'Legal Entity ID required');
    const context = openPortalRepository(locals);
    try {
      context.repository.archiveLegalEntity(context.principal, id);
      return actionSuccess('action.billing.legalEntityArchived', {}, 'Legal entity archived');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  updateTaxProfile: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('taxProfileId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.taxProfileIdRequired', {}, 'Tax Profile ID required');

    const input: Record<string, unknown> = {};
    if (formData.has('name')) input.name = formData.get('name')?.toString();

    const context = openPortalRepository(locals);
    try {
      context.repository.updateTaxProfile(context.principal, id, input);
      return actionSuccess('action.billing.taxProfileUpdated', {}, 'Tax profile updated');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  archiveTaxProfile: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const formData = await request.formData();
    const id = formData.get('taxProfileId')?.toString();
    if (!id)
      return actionFail(400, 'action.validation.taxProfileIdRequired', {}, 'Tax Profile ID required');
    const context = openPortalRepository(locals);
    try {
      context.repository.archiveTaxProfile(context.principal, id);
      return actionSuccess('action.billing.taxProfileArchived', {}, 'Tax profile archived');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createDraft: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = invoicePeriodSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.billingPeriod', {}, 'Invalid billing period');
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.createInvoiceDraft(
        context.principal,
        parsed.data.billingRuleId,
        parsed.data.periodStart,
        parsed.data.periodEnd,
      );
      return actionSuccess(
        result.created ? 'action.billing.invoiceDraftCreated' : 'action.billing.invoiceDraftExisting',
        {},
        result.created ? 'Invoice draft created' : 'Existing draft returned',
      );
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createInvoiceAdjustment: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = invoiceAdjustmentSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoiceAdjustment', {}, 'Invalid invoice adjustment');
    const context = openPortalRepository(locals);
    try {
      context.repository.createInvoiceAdjustment(context.principal, parsed.data);
      return actionSuccess('action.billing.invoiceAdjustmentCreated', {}, 'Adjustment draft created');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  approveInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = invoiceIdSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoice', {}, 'Invalid invoice');
    const context = openPortalRepository(locals);
    try {
      context.repository.approveInvoiceDraft(context.principal, parsed.data.invoiceId);
      return actionSuccess('action.billing.invoiceApproved', {}, 'Invoice approved');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  deleteInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = invoiceIdSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoice', {}, 'Invalid invoice');
    const context = openPortalRepository(locals);
    try {
      context.repository.deleteInvoice(context.principal, parsed.data.invoiceId);
      return actionSuccess('action.billing.invoiceDeleted', {}, 'Invoice deleted');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  issueInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = invoiceIdSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoice', {}, 'Invalid invoice');
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.issueInvoice(
        context.principal,
        parsed.data.invoiceId,
        parsed.data.reportLocale,
      );
      return actionSuccess(
        'action.billing.invoiceIssued',
        { invoiceNumber: result.invoiceNumber },
        `Issued ${result.invoiceNumber}`,
      );
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  recordPayment: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    object.amountMinor = decimalToMinor(object.amount);
    if (typeof object.receivedOn === 'string')
      object.receivedAt = `${object.receivedOn}T12:00:00.000Z`;
    const parsed = paymentInputSchema.safeParse(object);
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.payment',
        {},
        'Invalid payment',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      context.v3.recordPayment(context.principal, parsed.data);
      return actionSuccess('action.billing.paymentRecorded', {}, 'Payment recorded');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  reversePayment: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    object.amountMinor = decimalToMinor(object.amount);
    if (typeof object.effectiveOn === 'string')
      object.effectiveAt = `${object.effectiveOn}T12:00:00.000Z`;
    const parsed = paymentReversalInputSchema.safeParse(object);
    if (!parsed.success)
      return actionFail(
        400,
        'action.validation.paymentReversal',
        {},
        'Invalid payment reversal',
        { fields: parsed.error.flatten().fieldErrors },
      );
    const context = openPortalRepository(locals);
    try {
      // v3 owns finance authorization, step-up enforcement, immutable reversal
      // history, remaining-balance checks, and idempotent retries.
      context.v3.reversePayment(context.principal, {
        paymentId: parsed.data.paymentId,
        amountMinor: parsed.data.amountMinor,
        effectiveAt: `${parsed.data.effectiveOn}T12:00:00.000Z`,
        reasonCode: parsed.data.reasonCode,
        reason: parsed.data.reason,
        idempotencyKey: parsed.data.idempotencyKey,
      });
      return actionSuccess('action.billing.paymentReversed', {}, 'Payment reversal recorded');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  closePeriod: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = billingCloseSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.billingPeriod', {}, 'Invalid billing period');
    const context = openPortalRepository(locals);
    try {
      const result = context.v3.closeBillingPeriod(
        context.principal,
        parsed.data.billingRuleId,
        parsed.data.periodStart,
        parsed.data.periodEnd,
        parsed.data.reportLocale,
      );
      if (!result.closed)
        return actionFail(409, 'action.conflict.billingPeriodIncomplete', {}, 'Period is incomplete', {
          reasons: result.reasons,
        });
      return actionSuccess(
        'action.billing.periodClosed',
        {},
        'Billing period closed and sources locked',
      );
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  voidInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = voidInvoiceSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoiceVoid', {}, 'Invalid void request');
    const context = openPortalRepository(locals);
    try {
      context.v3.voidInvoice(
        context.principal,
        parsed.data.invoiceId,
        parsed.data.reason,
        parsed.data.idempotencyKey,
      );
      return actionSuccess('action.billing.invoiceVoided', {}, 'Invoice voided with audit trail');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  sendInvoice: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'billing')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = sendInvoiceSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.invoiceSend', {}, 'Invalid send request');
    const context = openPortalRepository(locals);
    try {
      const result = context.repository.sendInvoice(
        context.principal,
        parsed.data.invoiceId,
        parsed.data.idempotencyKey,
      );
      return actionSuccess(
        result.sent ? 'action.billing.invoiceSent' : 'action.billing.invoiceAlreadySent',
        {},
        result.sent ? 'Invoice marked sent' : 'Invoice was already sent',
      );
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  createAccountingPack: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'accounting')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const parsed = accountingPackPeriodSchema.safeParse(await formObject(request));
    if (!parsed.success)
      return actionFail(400, 'action.validation.accountingPeriod', {}, 'Invalid accounting period');
    const context = openPortalRepository(locals);
    try {
      const pack = context.v3.createAccountingPack(
        context.principal,
        parsed.data.periodStart,
        parsed.data.periodEnd,
        parsed.data.reportLocale,
      );
      const refreshedPack = context.v3
        .listAccountingPacks(context.principal)
        .find((candidate) => candidate.id === pack.id);
      const feedback = accountingPackActionFeedback(refreshedPack ?? pack, pack.id);
      return {
        ...actionSuccess(feedback.messageKey, feedback.messageParams, feedback.legacyMessage),
        packId: pack.id,
        packState: refreshedPack?.state ?? pack.state,
        exportStatuses: refreshedPack?.exportStatuses ?? {},
      };
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
  finalizeAccountingPack: async ({ locals, request, params }: PortalActionEvent) => {
    if (params.section !== 'accounting')
      return actionFail(404, 'action.navigation.wrongSection', {}, 'Wrong section');
    const object = await formObject(request);
    const packId = typeof object.packId === 'string' ? object.packId : '';
    const context = openPortalRepository(locals);
    try {
      context.v3.markAccountingPackFinal(context.principal, packId);
      return actionSuccess('action.billing.accountingPackFinalized', {}, 'Accounting Pack marked final');
    } catch (error) {
      return actionFailure(error);
    } finally {
      context.sqlite.close();
    }
  },
};
